### ISSUE TITLE
Address Syntax Highlighting in the Readme

### ISSUE THREAD

**Issue by colincornaby** [Microsoft/WinObjC#10]
I noticed there is a syntax highlighting plugin, but as someone who's more familiar with Xcode, I haven't been able to get it working. Online I read double clicking it should work, but I'm getting no response in VS2015 when I do that.

**Comment by joewood** [comment]
Looks like the plugin needs to be upgraded. I'm currently using VS Code, which does basic syntax coloring [https://code.visualstudio.com/Docs/languages](code.visualstudio.com/Docs/languages).

**Comment by jmsaunders-ms** [comment]
This should be fixed. Please reopen if still a problem.
