### ISSUE TITLE
UIImages do not load on non retina devices

### ISSUE THREAD

**Issue by pittmab** [Microsoft/WinObjC#1003]
On a non retina device, the UIImage code fails to load png images.

**Comment by mnithish** [comment]
@pittmab Is there any warning/error in the Visual Studio output Window when this happens? Also can you share with the code snippet that fails for you?

**Comment by pittmab** [comment]
Is there a way to start the app and force it to be non-retina via a simulator?  We are trying to find a non retina device to set this up on again.  Basically, the images did not load when going down the non retina code path.  @mnithish Can you load images on a non-retina device?

**Comment by mnithish** [comment]
@pittmab let me check with the emulator team if such a capability is supported.
On your second question I will defer it to @davelamb

**Comment by ArnOmsft** [comment]
Addressed via #1004

**Comment by jaredhms** [comment]
We successfully load UIImages on both regular and high-DPI devices (aka Retina), so it's unclear what's failing here.  Can you provide a concise repro of the issue?

**Comment by ArnOmsft** [comment]
Closing this. Please reopen that issue or create a new one when you have a repro. Thank you.
