### ISSUE TITLE
UILabel wrong default background

### ISSUE THREAD

**Issue by ad1Dima** [Microsoft/WinObjC#1015]
Most UIViews in iOS has clearColor (transparent) background. UILabel has transparent background too. However This bridge UILabel has white background by default https://github.com/Microsoft/WinObjC/blob/develop/Frameworks/UIKit/UILabel.mm#L195

**Comment by ArnOmsft** [comment]
Thank you for the feedback. We'll address this when we will migrate the UILabel implementation to be backed by XAML which should happen sometimes in the coming months.

**Comment by ad1Dima** [comment]
It seems, like you'd fixed it.

**Comment by ad1Dima** [comment]
@ArnOmsft @rajsesh-msft should I close it?

**Comment by tadam-msft** [comment]
Please close the issue if it’s fixed.
