### ISSUE TITLE
Re-enable CTFont CaseInsensitive test

### ISSUE THREAD

**Issue by mnithish** [Microsoft/WinObjC#1020]
Because DWrite is case sensitive, this test had to be disabled after the move from FreeType.

Investigate how the reference platform handles this and provide similar support on top of DWrite (as possible)

**Comment by ms-jihua** [comment]
Correction - I introduced this test _while_ doing the DWrite implementation, while checking for edge cases, and confirmed that the reference platform does ignore case.
