### ISSUE TITLE
Support CTFontManagerRegisterFontsForURL and CTFontManagerRegisterGraphicsFont with DWrite

### ISSUE THREAD

**Issue by mnithish** [Microsoft/WinObjC#1022]
This is a regression after our move to DWrite. Investigate on how to support this API
- [ ] Interoperable CTFontManagerRegisterFontsForURL
- [ ] Interoperable CTFontManagerRegisterGraphicsFont

**Comment by rajsesh-msft** [comment]
This causes clipping issue with internal test app.
