### ISSUE TITLE
Pure C Dependences from XCodeProject

### ISSUE THREAD

**Issue by agustingandara** [Microsoft/WinObjC#103]
I had problems trying to vsimport my XCodeProject with sqlite3 dependence.

**Comment by asimonov-msft** [comment]
@agustingandara Could you please be more specific about the issue/errors you ran into?

**Comment by agustingandara** [comment]
C:\Users\agustingandara\Documents\repo\essen\essen_app>vsimporter
[W] Ignoring "CatalogoLibs" target with unsupported product type "com.apple.product-type.framework".
[W] Failed to process PBXTargetDependency (C34FB1731AE04BFB00618DB5) for "Essen AR" target. Unable to create dependency target in "Essen" project.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "Essen AR" target.
[W] Ignoring "CatalogoLibs" target with unsupported product type "com.apple.product-type.framework".
[W] Failed to process PBXTargetDependency (C38D73D31AE16FFF00DA1BAC) for "Essen UY" target. Unable to create dependency target in "Essen" project.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "Essen UY" target.
[W] Ignoring "CatalogoLibs" target with unsupported product type "com.apple.product-type.framework".
[W] Failed to process PBXTargetDependency (C38D74481AE1765A00DA1BAC) for "Essen BO" target. Unable to create dependency target in "Essen" project.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "Essen BO" target.
[W] Ignoring "CatalogoLibs" target with unsupported product type "com.apple.product-type.framework".
[W] Failed to process PBXTargetDependency (C3D006851AE6BCFE007C7101) for "Essen LA" target. Unable to create dependency target in "Essen" project.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "Essen LA" target.
[W] Ignoring "CatalogoLibs" target with unsupported product type "com.apple.product-type.framework".
Generated C:\Users\agustingandara\Documents\repo\essen\essen_app\Essen.vsimporter\Essen AR-WinStore10\Essen AR.vcxproj
Generated C:\Users\agustingandara\Documents\repo\essen\essen_app\Essen.vsimporter\Essen BO-WinStore10\Essen BO.vcxproj
Generated C:\Users\agustingandara\Documents\repo\essen\essen_app\Essen.vsimporter\Essen LA-WinStore10\Essen LA.vcxproj
Generated C:\Users\agustingandara\Documents\repo\essen\essen_app\Essen.vsimporter\Essen UY-WinStore10\Essen UY.vcxproj
Generated C:\Users\agustingandara\Documents\repo\essen\essen_app\Essen.vsimporter\Essen-Headers-WinStore10\Essen-Headers.vcxitems
Generated C:\Users\agustingandara\Documents\repo\essen\essen_app\Essen-WinStore10.sln

**Comment by agustingandara** [comment]
@asimonov-msft @s5msft What about importing the NuGet Package of the same sqlite3 project?

**Comment by agustingandara** [comment]
I added the same NuGet Package of sqlite3 project, download and add headers to my project. Problem seem to be solved. 
BUT! I had to raise another issue: fatal error LNK1181 #104 

1>------ Build started: Project: Essen AR, Configuration: Debug Win32 ------
 1>LINK : fatal error LNK1181: cannot open input file 'CoreData.lib'
 ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
 ========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

I had to
