### ISSUE TITLE
Performance issues with CoreText using DWrite

### ISSUE THREAD

**Issue by aballway** [Microsoft/WinObjC#1038]
Drawing is much slower using DWrite, especially with larger font sizes.  This can be seen on the Alignment test in CTCatalog, where drawing is much less smooth when changing font sizes.

**Comment by DHowett-MSFT** [comment]
This may be mollified slightly by a CoreGraphics retargting to D2D, as in #1028.

**Comment by mnithish** [comment]
Yes, with D2D this should definitely go away but we know why it is bad today and how it can be improved - #1037

**Comment by mnithish** [comment]
Verified this is indeed due to #1037. Closing this as a dupe
