### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'CoreData.lib'

### ISSUE THREAD

**Issue by agustingandara** [Microsoft/WinObjC#104]
1>------ Build started: Project: Essen AR, Configuration: Debug Win32 ------
1>LINK : fatal error LNK1181: cannot open input file 'CoreData.lib'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by s5msft** [comment]
CoreData isn't implemented right now.

**Comment by agustingandara** [comment]
So, still waiting
