### ISSUE TITLE
Cortana sample doesn't launch on phone through voice

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#1050]
1.  Install the cortana sample app on a RS2 phone.
2.  Attempt to launch the phone via cortana voice or text command.

RESULT:
The app doesn't launch.  Instead, a web search is performed.

**Comment by aballway** [comment]
Can you confirm that the CortanaSampleCommands.xml file has been added to the Visual Studio project?

**Comment by rajsesh-msft** [comment]
Looking at the sample [here](https://github.com/Microsoft/WinObjC-Samples/tree/master/Scenarios/Cortana/CortanaSample), it seems to be there.  Also, this only seems to be an issue on phone.

**Comment by aballway** [comment]
The file is there but it need to be manually added to the project.

> A sample VCD XML file is included in the CortanaSample Xcode project directory. After running vsimporter, you'll need to add the VCD XML file reference to your Visual Studio project manually.

> In the Visual Studio menu bar choose Project > Add Existing Item. Add the VCD XML file (CortanaSampleCommands.xml) located in the original Xcode project directory.

I'm not sure why it would only cause an issue on phone though, possibly due to file copying or permissions.  If this isn't the cause I'll take a closer look.
