### ISSUE TITLE
UIKIT_EXPORT_CLASS macro missing for some UI classes

### ISSUE THREAD

**Issue by antoine-haas** [Microsoft/WinObjC#1053]
The UIKIT_EXPORT_CLASS macro is missing for some UI classes like UIMenuController and UIMenuItem.

**Comment by memontic-ms** [comment]
It is also missing for UIRefreshControl.

**Comment by antoine-haas** [comment]
Hey @LenoreMarlow,

Have you thought about submitting a pull request for this issue, since you fixed it on your end? We would be glad to merge your contribution and make it available to the community!

**Comment by LenoreMarlow** [comment]
UIKIT_EXPORT_CLASS added to 2 files UIMenuItem.h and UIMenuController.h.  
File location ..\winobjc\include\UIKit

[UIKIT_EXPORT_CLASS Fix for UIMenu classes.zip](https://github.com/Microsoft/WinObjC/files/522061/UIKIT_EXPORT_CLASS.Fix.for.UIMenu.classes.zip)

**Comment by ArnOmsft** [comment]
Thanks for this. Could you submit a pull request for these changes? We'll review it and approve it.
Thanks!
