### ISSUE TITLE
Remove the workorund in CGContextCairo::CGContextDrawGlyphRun to not divide the verticalScalingFactor and height by the device scaling factor once we move CG to use DIPs after moving to D2D

### ISSUE THREAD

**Issue by mnithish** [Microsoft/WinObjC#1057]
Today CG talks in Pixels but all Windows interfaces understand only DIPs. The current code is a workaround is to revert the device scaling factor before rendering with D2D for DWrite so that test rendering works on phone but this is wrong and will cause text rendering to PDF or printer to not work at all

**Comment by rajsesh-msft** [comment]
This is addressed with #1171
