### ISSUE TITLE
NSDecimalNumber - add a few extra interesting test cases

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#1062]
Code Review is ballooning so cutting this off into a separate issue:
* [ ] Test for operations that ought to return NSCalculationOverflow
* [ ] Test for operations where a loss of precision is incurred

**Comment by msft-Jeyaram** [comment]
this will be inline with #1052

**Comment by msft-Jeyaram** [comment]
Also the correct behavior can be fully tested when rounding is implemented.

**Comment by msft-Jeyaram** [comment]
removing for triage

**Comment by rajsesh-msft** [comment]
Use #1052 to cover this.
