### ISSUE TITLE
Add support for the float complex type

### ISSUE THREAD

**Issue by antoine-haas** [Microsoft/WinObjC#1063]
Files using the float complex type do not compile using the bridge.

**Comment by antoine-haas** [comment]
Trying to compile the following code snippet causes the compiler error below. The code is part of CorePlot's [CPTNumericData.m](https://github.com/core-plot/core-plot/blob/77f2e154a7c6ff3beb210e1c77495cee8e0b01c9/framework/Source/CPTNumericData.m) file.

```Objective-C
case CPTComplexFloatingPointDataType:
                switch ( self.sampleBytes ) {
                    case sizeof(float complex):
                        result = @( crealf(*(const float complex *)[self samplePointer:sample]) );
                        break;

                    case sizeof(double complex):
                        result = @( creal(*(const double complex *)[self samplePointer:sample]) );
                        break;
                }
                break;
```
Error: C-style cast from 'const void * _Nullable' to 'const float' is not allowed

**Comment by DHowett-MSFT** [comment]
This should work with `_Complex`.
