### ISSUE TITLE
How can I consume a .a-file

### ISSUE THREAD

**Issue by GitMarJansen** [Microsoft/WinObjC#1076]
I am trying to convert a project where a static library is used (an .a-file). In my linker input, I have a .lib reference to that library. When compiling, the linker complains 'cannot open input file '.....lib'. How can I get this to work?

Sorry for the cryptic description... I am no iOS developer :) so I am having a hard time understanding how this works in iOS....

**Comment by rajsesh-msft** [comment]
static libraries built for iOS/Mac aren't usable on windows, so you will have to recompile the code for the static library using winobjc.  This is of course assuming that you have the source code for that library.  What library are you using?

**Comment by rajsesh-msft** [comment]
Closing this issue as the original question is answered.
