### ISSUE TITLE
Certain Projected Apis with containers use wrong type for contained item

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#1091]
Example:
@interface WAAFileActivatedEventArgs : 
 ...
@property (readonly) NSArray\* /\* RTObject<WSIStorageItem>\* */ files; 
 ...
@end

should return an object that conforms to protocol WSIStorageItem but just returns a plain RTObject.

**Comment by mukhole** [comment]
The workaround we have is good enough, closing this.
