### ISSUE TITLE
UIScrollView - add the ability to hide scroll bars

### ISSUE THREAD

**Issue by pittmab** [Microsoft/WinObjC#1095]
It would be good to be able to hide the appearance of scroll bars in UIScrollView.  Or by default have them be not visible.

**Comment by ArnOmsft** [comment]
We'll address this in the coming months but this is not high-priority for now.

**Comment by ArnOmsft** [comment]
Thanks for the feedback. We checked and confirmed it's already possible to call UIScrollview or its subclass using set ShowsHorizontalScrollIndicator:NO or set ShowsVerticalScrollIndicator:NO or using property syntax access to hide horizontal/vertical scrollindicator.
Let us know if you're running into any issues using this.
