### ISSUE TITLE
Rename Xib2Nib to ibtool

### ISSUE THREAD

**Issue by jakepetroules** [Microsoft/WinObjC#11]
And make the command line arguments the same as the real ibtool.

**Comment by jmsaunders-ms** [comment]
We can probably make the flags the same but I have reservations about renaming it to ibtool.

Is there a compelling reason to do this? This should run transparently to the user as part of the build system so its name shouldn't matter.

Artem should have the final say on this.

**Comment by jakepetroules** [comment]
> Is there a compelling reason to do this?

Transparency with existing build tools using WinObjC in a cross compiler environment.

Why require a special case? In other words, is there a compelling reason NOT to do this?

**Comment by antoine-haas** [comment]
We're not currently planning to rename the tool since we think it already runs transparently enough.
