### ISSUE TITLE
Coding style is either completely missing, highly unconventional or just plain inconsistent

### ISSUE THREAD

**Issue by H2CO3** [Microsoft/WinObjC#110]
A lot of code completely lacks all coding conventions. Spacing and indentation is inconsistent, oftentimes both with other parts of this same repository and by the long-established style used by Apple, e.g. method definitions need not be indented.

https://github.com/Microsoft/WinObjC/blob/1243e498779fa29d1baed7298d03be59c1ab8cfc/Frameworks/CoreFoundation/CFDictionary.mm#L216-L245

Here, for example, the indentation is so horribly wrong that it makes my eyes bleed.

**Comment by lhoward** [comment]
Suggest (if licensing permits) the Apportable Foundation implementation be consulted, it has correct layering WRT CoreFoundation and is also for the most part much more pleasant to read.

**Comment by vmagaziy** [comment]
According to @s5msft they have a special tool for checking the code style which is to about to be uncovered to the rest of the world -- check this out #70.

**Comment by vmagaziy** [comment]
This is also related to #54.

**Comment by alexzielenski** [comment]
Someone forgot to reindent after a copy & paste
