### ISSUE TITLE
Add back in OBJCUWP_IN_BUILD or OBJCUWP_INCLUDE_ONLY guard to #pragma includes for projections

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#1101]
this guard was removed because it was thought to be superfluous in CR. Turns out I'm not as crazy as I thought and did have a good reason for it. When a different Projections binary is being built and including a .h, it will try to link against that Projections binary that may not be built yet. This is normally handled via a ProjectReference but these references are the minset of actual deps and headers can be included for other, non dep forming, reasons. Currently the build simply works by happenstance as it is referencing the checked in binaries from prebuilts but if anyone needs to change the layout / structure of modules again it will explode spectacularly.

**Comment by rajsesh-msft** [comment]
may want to look at this with the work #2687

**Comment by DHowett-MSFT** [comment]
Closing; @mukhole told me that this is "No longer needed, the dependency is taken care of at project level."
