### ISSUE TITLE
NSThread unsafe casts and other issues

### ISSUE THREAD

**Issue by lhoward** [Microsoft/WinObjC#111]
pthread_setspecific(tlsNSThread, (void *) (DWORD) pParam->threadObj);

casts threadObj, which is a pointer type, to a DWORD and then to a pointer. Is this 64-bit clean?

Also:

* code duplicated between initializers which should be factored out
* use of the word "foo" as a variable name evinces questionable coding style
* stack size should have a #defined constant or at least explanation in comment
* native Windows thread API should possibly be used instead of pthread wrappers

**Comment by rajsesh-msft** [comment]
Available in release 0.1.0.151222
