### ISSUE TITLE
KeychainItemWrapper: SecItemCopyMatching() false positives?

### ISSUE THREAD

**Issue by v-brflem** [Microsoft/WinObjC#1114]
There appears to be some issue with the SecItem APIs for WinObjC.  I have written a sample project that writes and retrieves authentication information to/from a keychain that appears to work on an actual iOS device, however it does not appear to work properly on WinObjC.

Source: https://www.dropbox.com/s/dx8ln2n0ndqjkcc/KeychainItemWrapperTest.zip?dl=0

Details: looking at -(void)writeToKeychain, the code checks whether an existing item is found in the keychain.  If it exists, update the item, if not, then add the item to the keychain.  The issue appears to be that the function SecItemCopyMatching() reports that there is no error, even if there has been no previous entry.  Then the following call to SecItemUpdate() returns -25300 (errSecItemNotFound).  So the issue appears that the API (SecItemCopyMatching) is returning a false positive.  This is the best understanding I could come up with.

NOTE: I also noticed that TARGET_IPHONE_SIMULATOR is defined while debugging.  If this expected behaviour?

v-brflem

**Comment by rajsesh-msft** [comment]
@v-brflem on TARGET_IPHONE_SIMULATOR - it was indeed a bug due to a hack from the past.  It has since been fixed by 90200b997fc131ce7450b39b2bd2cd3e512797e0  and should be available in next release.

**Comment by v-brflem** [comment]
@rajsesh-msft excellent, thanks for the update.  If I build the latest repro, will it have the fix you mentioned or should I wait for the next update?

**Comment by rajsesh-msft** [comment]
@v-brflem You can try our develop branch, but it is not fully tested.  That said, only the TARGET_IPHONE_SIMULATOR issue is fixed.  We still have to look into the issue you reported with SecItemCopyMatching.

**Comment by andrejo-msft** [comment]
@v-brflem You can build out the develop branch as an SDK to test out the TARGET_IPHONE_SIMULATOR fix by following the directions here:
https://github.com/Microsoft/WinObjC/wiki/Building-From-Source

As @rajsesh-msft points out, SecItemCopyMatching still needs to be investigated, so this issue should not be closed.

**Comment by bbowman** [comment]
@v-brflem I've looked into the sample you provided and the key (pun sort of intended) difference is that you are calling SecItemCopyMatching with a key that we don't support (can't store). As you can see at https://github.com/Microsoft/WinObjC/blob/develop/Frameworks/Security/GenericPasswordItemHandler.mm#L308 we have a large table of handlers for different properties and there is no comparator for kSecAttrGeneric which means that on the query side I have no way to know if the supplied value matches or not. I try to be more receptive than overly restrictive as many attributes are unfortunately not supported and I don't want to return 0 items for basically any query. You may be thinking that the obvious fix at this point is to simply add support for the kSecAttrGeneric key, but unfortunately, the backing store used https://msdn.microsoft.com/en-us/library/windows/apps/windows.security.credentials.passwordcredential.aspx only supports a very few items. We have already engaged with the team that owns those APIs to enhance them and I will pass along your feedback. Until then you can workaround this in your code by querying off of one of the few things we do support like Account, username, or Service.
