### ISSUE TITLE
OAuthConsumer crashes (NSMakeCollectable)

### ISSUE THREAD

**Issue by v-brflem** [Microsoft/WinObjC#1119]
When using OAuthConsumer to request a token, the code crashes when NSMakeCollectable is called internally.  I do not understand why this function causes a crash, as I have gone over it numerous times.

The offending code (found in OAMutableURLRequest.m): 
- (void)_generateNonce {
  CFUUIDRef theUUID = CFUUIDCreate(NULL);
  CFStringRef string = CFUUIDCreateString(NULL, theUUID);
  
  [NSMakeCollectable(theUUID) autorelease];
  if (nonce) {
      CFRelease(nonce);
  }
  nonce = (NSString *)string;
  }

Source: https://www.dropbox.com/s/0kcl6qrdyu1283q/OAuthVimeoTest.zip?dl=0

**Comment by rajsesh-msft** [comment]
@v-brflem Do you have a call stack?

**Comment by bbowman** [comment]
I looked at the dropbox repro and it looked like you are trying to create a subview off of the main thread. Fixing that I don't see the repro for the bug mentioned here. I am closing this unless you can provide a more detailed repro with call stack etc. Thanks!
