### ISSUE TITLE
Xib2Nib issue - Getting blank black screen

### ISSUE THREAD

**Issue by smity-optimus** [Microsoft/WinObjC#112]
I am trying to convert a very basic iOS application to Windows 10 application. I tried to build this using local machine but it was showing an error related to "Xib2Nib.exe", saying it was unable to convert LaunchScreen.xib (error exit code 255). So I removed the LaunchScreen.xib file from my project. Now there is just a Main.storyboard file for UI and I am NOT using AutoLayout in this.

I again tried to build the application and I was able to build it successfully, but the application is just showing the navigation title and a blank black screen.

Can anyone help me in this?

**Comment by s5msft** [comment]
xib2nib is still under development, as is storyboard support. Stay tuned.

**Comment by SquaredTiki** [comment]
See #27 also

**Comment by Ramu-msft** [comment]
Storyboard support has been added and more enhancements were made to xib2nib tool. Please test with latest version of the SDK

**Comment by antoine-haas** [comment]
Please re-test your app with the latest release of the SDK, which should have fixed this.
