### ISSUE TITLE
Internal test app has winobjc references in xcodeprojects

### ISSUE THREAD

**Issue by BIDSG** [Microsoft/WinObjC#1121]
Internal test app has winobjc references in xcodeprojects.

**Comment by andrejo-msft** [comment]
@rajsesh-msft, do you know which app this is with regard to?

**Comment by rajsesh-msft** [comment]
@andrejo-msft unfortunately, i don't remember any context around this issue.  We should close this out.

**Comment by andrejo-msft** [comment]
Closing. @BIDSG - please let us know whether this should be reopened. We're uncertain of the problem.
