### ISSUE TITLE
Unable to push changes after merge

### ISSUE THREAD

**Issue by RG-J** [Microsoft/WinObjC#1136]
After doing the recent merge, I am starting to get the following error:

Git LFS: (0 of 3683 files, 507 skipped) 0 B / 1.17 GB, 544.86 MB skipped                                                                                                  Trying to push "bin/objc2winmd.exe" with OID dbb9d6203b56a8a4791a7676b279985157f19b032f200607595ee7d30046d409.
Not found in C:\{USER_PATH}\WinObjC\.git\lfs\objects\db\b9.
error: failed to push some refs to 'git@github.com:RG-J/WinObjC.git'

I have done git lfs pull after the merge.

**Comment by rajsesh-msft** [comment]
You could try git lfs fetch and if that doesnt work, try git lfs fetch --all as a final measure.

**Comment by rajsesh-msft** [comment]
Please let me know if you are still running into this.  git push --no-verify has worked for some as well (thanks @DHowett-MSFT for the tip).

**Comment by RG-J** [comment]
got a fix, Thanks.
