### ISSUE TITLE
Large project crashes in libobjc2

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1141]
Dear WinObjC Engineers,

I made a test project with about 300 files (Obj-C Object Classes) in it and it compiled, linked and ran fine.

Then I added more files for a total of well over 1000 files (Class definitions) and it compiled and linked. When I ran it, it crashed with the output "Debug Error!". It did so before getting to the main() entry point in the test application execution, which means that it is bombing in the libobjc2 loading of all the classes (or so it appears).

The call stack and output is attached.

Windows 10 is updated, Visual Studio 2015 Update 3 is being used and a WinObjC build from about 3 weeks ago is being used. I'll try it again on the next full build release of WinObjC (that would be release 42), but in the meantime ... any hints on how to proceed (maybe you can make something of the hex call stack without a PDB file)?

Sincerely,

Ed

[callstack1.txt](https://github.com/Microsoft/WinObjC/files/527579/callstack1.txt)

**Comment by edvv** [comment]
Update: I think I figured it out. I think it was the way non-ddlexport classes were used; and not necessarily the number of classes.

**Comment by rajsesh-msft** [comment]
@edvv the libobjc2 symbols should be picked up by visual studio if you selected "Microsoft Symbol Servers" in the debug symbols option.  When you say you have figured it out, does it mean you have fixed the crash, or do you know what scenario caused the crash?  Thanks in advance!

**Comment by edvv** [comment]
The crash scenario identification is being narrowed down (by process of elimination) and I think I may have a small example project demonstrating it by next week. If it gets that far then I'll post the project.

**Comment by edvv** [comment]
So far, the crash was resolved to this bug:

in the file objc_2stage_init.cpp
function __objc_resolve_compiled_modules()
call to __objc_resolve_module(*i);

prints this to the system console:

Error: Class MyClass has an unexpected ivar myIvar with a negative offset of -2!

and then the app crashes.

When the type of myIvar is changed from unsigned char to unsigned then the program runs.

There seems to be something wrong with the objc runtime when computing ivar offsets.

__objc_resolve_module on github and google search gives only one hit, so I don't know what it is doing.

Also, see the related samples app issue: https://github.com/Microsoft/WinObjC/issues/1203

I think this is a bug deep in libobjc2.

Sincerely,

Ed

**Comment by edvv** [comment]
@rajsesh-msft I put a small example project demonstating the crash at the issue https://github.com/Microsoft/WinObjC/issues/1208

Sincerely,

Ed

**Comment by DHowett-MSFT** [comment]
THis was resolved to the same cause as #1208, right? If so, we can close it and track status there.

**Comment by edvv** [comment]
@DHowett-MSFT You are right, so I closed this issue in preference to #1208.
