### ISSUE TITLE
CGD2D - _CGPathFitRect and CTFramesetterCreateFrame Broken

### ISSUE THREAD

**Issue by MSFTFox** [Microsoft/WinObjC#1143]
As a part of the work with CGPath some functions have broken since they try to access information inside of the CGPath which is being removed. These functions should be re-enabled or replaced as a part of the CGPath work.

**Comment by rajsesh-msft** [comment]
The feature should work, we need tests for this.

**Comment by rajsesh-msft** [comment]
@aballway you already have this covered in your pull request?

**Comment by aballway** [comment]
Yes, _CGPathFitRect is removed in #1398
