### ISSUE TITLE
C1001 - An internal error has occurred in the compiler

### ISSUE THREAD

**Issue by MyCADDev** [Microsoft/WinObjC#1155]
Hi,
I'm getting this compile error when I compile this code.

Is there any workaround or fix available? I'm using the latest release of WinObjC (0.2.160927) and Visual Studio 2015 Update 3.

See image attached.

![image](https://cloud.githubusercontent.com/assets/883028/19402732/b02e49be-9230-11e6-98c6-bedf2b0b374b.png)

**Comment by MyCADDev** [comment]
Here is another instance of "An internal error has occurred in the compiler"

![image](https://cloud.githubusercontent.com/assets/883028/19406233/581c0e08-9250-11e6-9c64-5c3312894114.png)

**Comment by MyCADDev** [comment]
I want to give some context to what we are trying to do. We want to share non-UI code written in Java between Android, iOS and Windows using J2ObjC and WinObjC. 

J2ObjC has become very stable and everything works in XCode.

We are trying to compile the generated Objective-C (generated using J2ObjC) in Windows using the WinObjC bridge.

Several compiler errors got fixed in WinObjC 0.2.160927. These are the last two which are remaining in our code.

Thanks in advance. WinObjC is a very promising project!!

**Comment by zakirt-msft** [comment]
Thank you for raising this issue. We are following up with the compiler team (who is separate from this team) and will get back to you with an update soon.

**Comment by antoine-haas** [comment]
@MyCADDev, can you share repro code for this errors? It's hard to investigate this further without more details.

**Comment by MyCADDev** [comment]
OK @antoine-haas I will make a small application with this error.
It will take me a few days. Thanks for your support.

**Comment by weswmsft** [comment]
Is this still an issue? Do you have a repro for us?

**Comment by weswmsft** [comment]
If this still persists please reopen the issue.
