### ISSUE TITLE
Expected ":" when build

### ISSUE THREAD

**Issue by jcamachov** [Microsoft/WinObjC#1157]
Hi,

I have this error "Expected ":"" when I want to build the solution... 

![image](https://cloud.githubusercontent.com/assets/1019773/19417086/b1489772-93a3-11e6-9e74-826da454cde2.png)

Somebody has the solution for this issue?

Thanks in advance

**Comment by ad1Dima** [comment]
@jcamachov Can you show us line 63 in this file?

**Comment by rajsesh-msft** [comment]
@jcamachov could you please provide the build log by following these steps in our [FAQ](https://github.com/Microsoft/WinObjC/wiki/FAQ#how-do-i-get-my-project-log-file-to-help-determining-the-cause-of-an-issue)?  Thanks in advance!

**Comment by jcamachov** [comment]
@rajsesh-msft This is the log:

 pch.cpp
  App.xaml.cpp
  XamlTypeInfo.Impl.g.cpp
  ConsumeRuntimeComponent.cpp
  objc_2stage_init.cpp
  Note: Setting MaxClangProcesses to 1 because Modules are enabled.
  ..\..\Maristas\Clases\WebServices\TouchXML\CXMLDocument.m
C:\Users\Javier\Desktop\Desarrollo\Maristas_iOs_Source\Maristas\Clases\WebServices\Soap/SoapArray.h(63,100): error : expected ':'

**Comment by jcamachov** [comment]
I updated Visual Studio to "Update 3" from "Update 2" and these issue is out of the error list. Now, I have a new Issue when I building the project.

"Clang fronted command due to signal (use -v to see invocation)"

**Comment by jcamachov** [comment]
I updated Visual Studio to "Update 3" and the same issue persist... 

Anybody knows what is the problem?... I tried to compile several of my iOs projects and I can't be able to run on visual studio anyone with Windows Bridge for iOs. I hope the bridge go forward in order to compile the first one project and offer all my projects to windows mobile platform too.

**Comment by antoine-haas** [comment]
@jcamachov, what you pasted above seems to be the contents of the Output window rather than the full build log. Please follow the steps in our [FAQ](https://github.com/Microsoft/WinObjC/wiki/FAQ#how-do-i-get-my-project-log-file-to-help-determining-the-cause-of-an-issue) to get the log so we can further investigate the issue.

**Comment by weswmsft** [comment]
Is this still an issue? If so please provide the logs & source code.

**Comment by weswmsft** [comment]
If this issue persists please re-open and add the necessary info that was requested
