### ISSUE TITLE
Why not use the GNUstep Objective-C runtime?

### ISSUE THREAD

**Issue by davidchisnall** [Microsoft/WinObjC#116]
The [GNUstep Objective-C runtime](https://github.com/gnustep/libobjc2) is MIT licensed (unlike the ObjFW runtime, that was used as a base for the WinObjC implementation and is under a more restrictive license) and fixed issues like #92 years ago.  It currently supports a superset of the functionality of Apple's Objective-C language and is used in deployment on millions of Android devices already.  It's actively maintained (I'm currently working on a new ABI that would clean up a number of legacy issues, for example) and we would happily work with Microsoft to improve Windows support.

**Comment by lhoward** [comment]
Or Apple's runtime, although it does require the dynamic loader to be able to notify the runtime when new images are loaded (not sure if this is possible on Windows). I'm less concerned with libobjcrt per se as the quality of the CoreFoundation and Foundation implementations. I would humbly suggest ripping out the existing one and replacing them with the Apple/Apportable CoreFoundation/Foudnation (respectively).

**Comment by nicholasgerard-msft** [comment]
In this week's release of the bridge we've officially made the move to the GNUstep Objective-C 2.0 runtime. Thanks for the suggestion, and please let us know about any issues you find with the new runtime here on Github!
