### ISSUE TITLE
StackOverflow is not a tech support

### ISSUE THREAD

**Issue by cubuspl42** [Microsoft/WinObjC#117]
[Why can't I ask customer service-related questions?](http://meta.stackoverflow.com/a/255746)

> If you have any questions, we're listening and will do our best to help. Just go to http://stackoverflow.com/ and tag your questions with WinObjC

It should be clearly stated that only *some* questions can be asked on StackOverflow. For example, I could ask "Do you have any plans to implement [insert some unimplemented API name]?", which might be a good question, but not a question allowed on StackOverflow.

**Comment by nicholasgerard-msft** [comment]
Thanks for pointing this out. Github is now our primary means of communication with the community and contributors. Please file issues for any bugs you encounter or questions you have.
