### ISSUE TITLE
vsimporter is not able to handle a complex xcode project like react-native SampleApp

### ISSUE THREAD

**Issue by volkrass** [Microsoft/WinObjC#118]
I did following: 

C:\Users\Projects\react-native\Examples\SampleApp\iOS>..\..\..\..\bin\vsimporter.exe

Output is this:

[W] Ignoring unsupported PBXShellScriptBuildPhase in "React" target.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "React" target.
[W] Ignoring unsupported PBXShellScriptBuildPhase in "React" target.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "RCTActionSheet" target.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "RCTGeolocation" target.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "RCTImage" target.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "RCTLinking" target.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "RCTNetwork" target.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "RCTSettings" target.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "RCTText" target.
[W] Ignoring unsupported PBXCopyFilesBuildPhase in "RCTVibration" target.
[W] Ignoring "SampleAppTests" target with unsupported product type "com.apple.product-type.bundle.unit-test".
Generated C:\Users\Projects\react-native\Examples\SampleApp\iOS\SampleApp.vsimporter\SampleApp-Headers-WinStore10\SampleApp-Headers.vcxitems
Generated C:\Users\Projects\react-native\Examples\SampleApp\iOS\SampleApp.vsimporter\SampleApp-WinStore10\SampleApp.vcxproj
Generated C:\Users\Projects\react-native\Libraries\ActionSheetIOS\RCTActionSheet.vsimporter\RCTActionSheet-Headers-WinStore10\RCTActionSheet-Headers.vcxitems
Generated C:\Users\Projects\react-native\Libraries\ActionSheetIOS\RCTActionSheet.vsimporter\RCTActionSheet-WinStore10\RCTActionSheet.vcxproj
Generated C:\Users\Projects\react-native\Libraries\Geolocation\RCTGeolocation.vsimporter\RCTGeolocation-Headers-WinStore10\RCTGeolocation-Headers.vcxitems
Generated C:\Users\Projects\react-native\Libraries\Geolocation\RCTGeolocation.vsimporter\RCTGeolocation-WinStore10\RCTGeolocation.vcxproj
Generated C:\Users\Projects\react-native\Libraries\Image\RCTImage.vsimporter\RCTImage-Headers-WinStore10\RCTImage-Headers.vcxitems
Generated C:\Users\Projects\react-native\Libraries\Image\RCTImage.vsimporter\RCTImage-WinStore10\RCTImage.vcxproj
Generated C:\Users\Projects\react-native\Libraries\LinkingIOS\RCTLinking.vsimporter\RCTLinking-Headers-WinStore10\RCTLinking-Headers.vcxitems
Generated C:\Users\Projects\react-native\Libraries\LinkingIOS\RCTLinking.vsimporter\RCTLinking-WinStore10\RCTLinking.vcxproj
Generated C:\Users\Projects\react-native\Libraries\Network\RCTNetwork.vsimporter\RCTNetwork-Headers-WinStore10\RCTNetwork-Headers.vcxitems
Generated C:\Users\Projects\react-native\Libraries\Network\RCTNetwork.vsimporter\RCTNetwork-WinStore10\RCTNetwork.vcxproj
Generated C:\Users\Projects\react-native\Libraries\Settings\RCTSettings.vsimporter\RCTSettings-Headers-WinStore10\RCTSettings-Headers.vcxitems
Generated C:\Users\Projects\react-native\Libraries\Settings\RCTSettings.vsimporter\RCTSettings-WinStore10\RCTSettings.vcxproj
Generated C:\Users\Projects\react-native\Libraries\Text\RCTText.vsimporter\RCTText-Headers-WinStore10\RCTText-Headers.vcxitems
Generated C:\Users\Projects\react-native\Libraries\Text\RCTText.vsimporter\RCTText-WinStore10\RCTText.vcxproj
Generated C:\Users\Projects\react-native\Libraries\Vibration\RCTVibration.vsimporter\RCTVibration-Headers-WinStore10\RCTVibration-Headers.vcxitems
Generated C:\Users\Projects\react-native\Libraries\Vibration\RCTVibration.vsimporter\RCTVibration-WinStore10\RCTVibration.vcxproj
Generated C:\Users\Projects\react-native\Libraries\WebSocket\RCTWebSocket.vsimporter\RCTWebSocket-Headers-WinStore10\RCTWebSocket-Headers.vcxitems
Generated C:\Users\Projects\react-native\Libraries\WebSocket\RCTWebSocket.vsimporter\RCTWebSocket-WinStore10\RCTWebSocket.vcxproj
Generated C:\Users\Projects\react-native\React\React.vsimporter\React-Headers-WinStore10\React-Headers.vcxitems
Generated C:\Users\Projects\react-native\React\React.vsimporter\React-WinStore10\React.vcxproj
Generated C:\Users\Projects\react-native\Examples\SampleApp\iOS\SampleApp-WinStore10.sln

Any thoughts how to deal with PBXShellScriptBuildPhase & PBXCopyFilesBuildPhase ?

I can't compile the project afterwards, because few *.tlh files are not available.

**Comment by asimonov-msft** [comment]
@volkrass The .tlh errors come from IntelliSense because it doesn't yet understand Objective C. These errors should not cause compilation problems. Could you please be more specific about the errors you're seeing in the Visual Studio build log?

In regards to PBXShellScriptBuildPhase and PBXCopyFilesBuildPhase - while they are used quite commonly, they rarely affect the actual complication and linking stages. Unfortunately, if they are actually required for compilation, there is no easy way to transfer them to Visual Studio. PBXCopyFilesBuildPhase  would have to become a custom msbuild target that copies the files using the [Copy Task](https://msdn.microsoft.com/en-us/library/3e54c37h.aspx). PBXShellScriptBuildPhase would also have to become a custom msbuild target, with the script being converted to something that can run on Windows.

**Comment by volkrass** [comment]
@asimonov-msft Sorry for my misinterpretation of the .tlh files. I got it, they have no impact on compiler or linker errors. It seems to be that through the vsimporter tasks either the header files are not in the correct place or the paths for header files are not imported correctly. In my case RCTBridge.h hasn't found. Might be I have to add some folders to "include path" to fix it.

**Comment by asimonov-msft** [comment]
@volkrass I've taken a brief look at the React-native sample project. It uses recursive search paths (e.g. "$(SRCROOT)/../../../React/**") which is related to issue #62. This is likely why the RCTBridge.h header is not found.
Unfortunately, the change that adds support for this feature has not yet made it to the pre-build SDK. However, the updated msvc/ClangCompileTask.dll can be downloaded from github directly, if you wish to try it.

**Comment by technotrance** [comment]
Yes and patented by microsoft to mcps go have a look

**Comment by technotrance** [comment]
You need a connector piece of java and inter Link it  beginning with a single drawer and loop Your programme out her in a winzip file video and audio and then convert to an applicationable format that suites you for Your programme and keep ir in the repository cbined for others to use This is how git hub its a seperate Server where you edite a code in java Your programme

**Comment by volkrass** [comment]
@asimonov-msft Thanks for your advice. It solved my issue with RTCBridge.h. There are still few issues with header files. CoreLocation/CLError.h seems to be that is not part of WinObjC project.  Is there any plan to support JavaScriptCore? I have seen MapKit is on your roadmap. I try to create a build without the missing components anyway.

**Comment by DeChrist** [comment]
@volkrass You may want to use this tool to detect the currently missing components:
https://github.com/fdierick/WinObjC-Check

**Comment by joewood** [comment]
Hi @volkrass, I was trying to port React Native too. The main two missing components were MapKit and JavaScriptCore (which is a bit fundamental to RN!). I hit a few other issues with missing macros and attributes. I removed MapKit from the build to get a compile and stubbed in the JSCore headers - just to fix the compile. I was planning on wrapping up the Chakra engine for JSCore. See #44, #63, #72, #73.

**Comment by volkrass** [comment]
@joewood  You are absolutly right, JavaScriptCore is fundamental for RN.
Regarding missing macros and attributes will it be fixed by WinObjC Project? 
Let me know if I can help you in anyway.

**Comment by antoine-haas** [comment]
JavaScriptCore and MapKit require a considerable amount of work and are not in our immediate roadmap (see [our roadmap](https://github.com/Microsoft/WinObjC/wiki/Roadmap) in the wiki), but they may be included in future releases.

**Comment by volkrass** [comment]
It looks like we can close this ticket for now, because there is a way to to get ReactNative running on Windows 10. https://github.com/ReactWindows/react-native

**Comment by antoine-haas** [comment]
Closing as per above comment.
