### ISSUE TITLE
Provide a CONTRIBUTING.md

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/WinObjC#119]
It's useful for users to know

1. What the etiquette/expectations are for taking on bugs.
2. What the coding guidelines are (I know, #54 tracks this).
3. How to write tests.
    * Current documentation says writing unit tests are encouraged, but doesn't tell me how to write one.
4. How to run tests.
5. What the etiquette/expectations are for submitting fixes.

Additionally, you may want to consider suggesting certain workflows for digging into your codebase (i.e. what editor do you guys use, what do users need to have set up to contribute, etc.). Given that the codebase is a little unconventional compared to most projects, I'd say this would be very helpful.

For an example, see [our CONTRIBUTING.md](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md). While it's not necessarily perfect, it helps give users some idea of the general workflow.

**Comment by s5msft** [comment]
@DanielRosenwasser this is great feedback, and contribution guidelines are high on our "todo list".

But to answer your specific question around tests, the framework (still being built and populated) lives here:
https://github.com/Microsoft/WinObjC/tree/master/tests/cmdline

**Comment by DanielRosenwasser** [comment]
I have a CONTRIBUTING.md almost done, though I can't seem to get tests to run. I've rebooted after installing

* Visual Studio 2015 with
    * Visual C++
    * Universal Windows App Development Tools (all)
    * Windows 8.1 and Windows Phone 8.0/8.1 Tools (all)

However, if I try running `buildall.bat` from the , I get

```
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 8/29/2015 12:16:05 AM.
The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft
\.NetNative\Microsoft.Net.CoreRuntime.targets (68,11)" does not exist in the project, and will be ignored.
The target "_GeneratePrisForPortableLibraries" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\M
icrosoft\.NetNative\Microsoft.Net.CoreRuntime.targets (177,11)" does not exist in the project, and will be ignored.
The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft
\.NetNative\Microsoft.NetNative.targets (126,11)" does not exist in the project, and will be ignored.
The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft
\.NetNative\Microsoft.NetNative.targets (174,11)" does not exist in the project, and will be ignored.
The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Micros
oft\NuGet\Microsoft.NuGet.targets (149,61)" does not exist in the project, and will be ignored.
Project "C:\Users\drosen\WinObjC\tests\cmdline\cmdline.vcxproj.template" on node 1 (default targets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [C:\Users\drosen\WinObjC\tests\cmdline\cmdline.vcxproj.templat
e]
Done Building Project "C:\Users\drosen\WinObjC\tests\cmdline\cmdline.vcxproj.template" (default targets) -- FAILED.


Build FAILED.

"C:\Users\drosen\WinObjC\tests\cmdline\cmdline.vcxproj.template" (default target) (1) ->
(PlatformPrepareForBuild target) ->

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build
 tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 b
uild tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-c
lick the solution, and then selecting "Retarget solution". [C:\Users\drosen\WinObjC\tests\cmdline\cmdline.vcxproj.template]

    0 Warning(s)
    1 Error(s)
```

If I try copying the `cmdline.vcxproj.template` to ` cmdline.vcxproj` and running `msbuild` (or having VS2015 import/update it), then I get the following:

```
Build FAILED.

"C:\Users\drosen\WinObjC\tests\cmdline\cmdline.vcxproj" (default target) (1) ->
(Link target) ->
  LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\Users\drosen\WinObjC\tests\cmdline\cmdline.vcxproj]

    0 Warning(s)
    1 Error(s)
```

And if I try to retarget the SDK version to 10.0.10240.0, then I get


Severity | Code | Description | Project | File | Line
-----------|----------|----------------|-------------|---------|----------
Error | LNK2019 | unresolved external symbol _main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ) | cmdline | C:\Users\drosen\WinObjC\tests\cmdline\msvcrtd.lib(exe_main.obj) | 1

**Comment by nicholasgerard-msft** [comment]
We've now published coding guidelines and standards as part of our wiki. Please see [How to Contribute](https://github.com/Microsoft/WinObjC/wiki/How-to-Contribute) for more details.
