### ISSUE TITLE
quite a few unimplemented stub methods

### ISSUE THREAD

**Issue by spalda2** [Microsoft/WinObjC#1196]
Warning		'tag' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\elements\categories\UIViewController-Additions.m	222	
Warning		'setScrollIndicatorInsets:' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\ccal\ASIHTTPRequest\ASIAuthenticationDialog.m	127	
Warning		'setAutocapitalizationType:' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\ccal\ASIHTTPRequest\ASIAuthenticationDialog.m	447	
Warning		'tintColor' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\MHEditViewController.m	127	
Warning		'setNetworkActivityIndicatorVisible:' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\ccal\ASIHTTPRequest\ASIHTTPRequest.m	4765	
Warning		'setNetworkActivityIndicatorVisible:' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\ccal\ASIHTTPRequest\ASIHTTPRequest.m	4772	
Warning		'attributedText' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\ccal\MHMultipleCursorAdaptor.m	498	
Warning		'networkActivityIndicatorVisible' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\ccal\MHHttpClient.m	110	
Warning		'networkActivityIndicatorVisible' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\ccal\MHHttpClient.m	116	
Warning		'transactionReceipt' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\sal\MHStoreController.m	258	
Warning		'transactionIdentifier' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\sal\MHStoreController.m	259	
Warning		'payment' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\sal\MHStoreController.m	268	
Warning		'productIdentifier' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\sal\MHStoreController.m	268	
Warning		'transactions' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\sal\MHStoreController.m	419	
Warning		'delegate' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\sal\MHStoreController.m	482	
Warning		'products' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\sal\MHStoreController.m	508	
Warning		'invalidProductIdentifiers' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	
Warning		'transactionState' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	
Warning		'error' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\sal\MHStoreController.m	676	
Warning		'originalTransaction' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\sal\MHStoreController.m	762	
Warning		'transactionReceipt' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\sal\MHStoreController.m	762	
Warning		'transactionDate' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	
Warning		'alertViewStyle' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\MHDialogs.m	394	
Warning		'autocapitalizationType' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\MHDialogs.m	405	
Warning		'scrollIndicatorInsets' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\MHLoginViewActivity.m	426	
Warning		'setScrollIndicatorInsets:' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\MHLoginViewActivity.m	433	
Warning		'scrollIndicatorInsets' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\MHLoginViewActivity.m	447	
Warning		'setScrollsToTop:' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\MHGalleryGridViewActivity.m	500	
Warning		'isTranslucent' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\MHTranslucentNavBarController.m	19	
Warning		'statusBarStyle' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\MHTranslucentNavBarController.m	20	
Warning		'setTranslucent:' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\MHTranslucentNavBarController.m	23	
Warning		'setTranslucent:' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\MHTranslucentNavBarController.m	35	
Warning		'showsTouchWhenHighlighted' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\binders\MHBookCell.m	455	
Warning		'allowsSelectionDuringEditing' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\binders\MHListViewUIbinder.m	231	
Warning		'setSearchBarStyle:' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\binders\MHRemoteBooksListUIbinder.m	340	
Warning		'setSpellCheckingType:' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\binders\MHRemoteBooksListUIbinder.m	353	
Warning		'baselineAdjustment' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\binders\MHListCell.m	63	
Warning		'editing' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\binders\MHListCell.m	136	
Warning		'segmentedControlStyle' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\binders\MHSearchViewUIbinder.m	696	
Warning		'setModalTransitionStyle:' is deprecated: property not yet implemented [-Wdeprecated-declarations]	mhLib	C:\workspace\Windows\drcompanion-Windows-iOS\mhLib\src\uial\binders\MHWebViewControllerBinder.m	341

**Comment by rajsesh-msft** [comment]
@spalda2 yes, the bridge is work in progress, and not all methods/classes are fully implemented.  The idea of the stubs though is to let you build and run your app.  In a lot of cases the stubs will work just fine.  If there are specific items that you need you could open issues for them.  Please see our wiki for more details on the stub macros.

https://github.com/Microsoft/WinObjC/wiki/FAQ#whats-the-deal-with-all-of-these-stubs

**Comment by spalda2** [comment]
Well, yes..I read all of that:)
But I don't use methods just so that they keep returning the same value and do nothing or close to nothing...
If i'm to write an issue for every single method it'll be a lots of issues:)
And try i can start implementing these stubs but not sure if it's not gonna take me more time then simply convert the whole lot into css/js and run in on own webkit port on all platforms then...
Because if you want this to take off then it simply MUST have the basic functionality for a simple app to run and set UI and then people start contributing.
And setting a tag on a view or handling products and payments or having attributed text is such a basic functionality.
E.g. one can live without animation with spring attenuation but not without the above.

**Comment by antoine-haas** [comment]
@spalda2, as you pointed out, there are methods that one can and cannot live without, which is why we suggest filing separate issues so we can independently prioritize them. We recommend that you file specific issues for at least the missing methods that are completely blocking you and the ones that you plan to implement yourself (let us know in the comments of the issue if that's the case). That way, we'll be able to prioritize your main blockers against all feature requests with the former and avoid working on issues that you are already working on with the latter.

**Comment by spalda2** [comment]
Ok, i'll supply a list ordered by importance as per my subjective needs....

**Comment by ArnOmsft** [comment]
Thank you for the feedback. Also, if you'd like to evaluate the compatibility of your app with the Bridge in its current state, you can use our app analysis tool: https://developer.microsoft.com/en-us/windows/bridges/ios/app-analyzer-tool.

**Comment by spalda2** [comment]
With all due respect the whole point of winobjc bridge is to BE compatible with the iOS app and NOT the other way around, as you suggesting. As i said earlier: there is is fine border, work effort-wise, at least for me, between using this bridge and resorting to have own webkit port for all platforms having my app running as CSS/JS/HTLM.
Anyway I think it's sensible from me supply a priority list, however in the meantime i posted another issue whereby the app doesn't even start which is far more important then this. So once the app at least starts i can post the priority list
