### ISSUE TITLE
initializing static const using objective c calls crashes app

### ISSUE THREAD

**Issue by spalda2** [Microsoft/WinObjC#1198]
const CGFloat kMHConstants_TableViewLeftPadding = (kRUNNING_IPAD ? 11.0f : 0.0f);
where 
#define kRUNNING_IPAD (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)
static inline UIUserInterfaceIdiom UI_USER_INTERFACE_IDIOM() {
    return ([[UIDevice currentDevice] respondsToSelector:@selector(userInterfaceIdiom)] ?
            [[UIDevice currentDevice] userInterfaceIdiom] :
            UIUserInterfaceIdiomPhone);
}
crashes at the bold line with access violation NULL pointer
- (UIUserInterfaceIdiom)userInterfaceIdiom {
    **if (!GetCACompositor()->isTablet()) {**
        return UIUserInterfaceIdiomPhone;
    } else {
        return UIUserInterfaceIdiomPad;
    }
}
seems like not a proper objc runtime initialisation.....

**Comment by rajsesh-msft** [comment]
This is the same issue as #598.  Unfortunately, COM is not initialized when setting up statics.

**Comment by rajsesh-msft** [comment]
@spalda2 this would require you to workaround in your code.

**Comment by spalda2** [comment]
Ah, sorry, overlooked that. It’s quite easy to work around it though…

P
