### ISSUE TITLE
No such interface supported

### ISSUE THREAD

**Issue by spalda2** [Microsoft/WinObjC#1209]
The application doesn't even start (debug builds for all libs and the app):
<img width="621" alt="screen shot 2016-10-22 at 15 27 54" src="https://cloud.githubusercontent.com/assets/976172/19619628/5ba6eb5c-986c-11e6-8f75-c7ee9a4862fb.png">
Stack trace:
    KernelBase.dll!776c3e28()   Unknown
    [Frames below may be incorrect and/or missing, no symbols loaded for KernelBase.dll]  
    [External Code] 

>   UIKIT.DLL!XamlCompositor::Controls::CALayerXaml::CreateLayer() Line 1100    C++
>     UIKIT.DLL!DisplayNode::DisplayNode() Line 238   C++
>     UIKIT.DLL!DisplayNodeXaml::DisplayNodeXaml() Line 941   Objective-C++
>     UIKIT.DLL!CAXamlCompositor::CreateDisplayNode() Line 1287   Objective-C++
>     QUARTZCORE.DLL!CAPrivateInfo::CAPrivateInfo(CALayer \* self) Line 310    Objective-C++
>     QUARTZCORE.DLL!-[CALayer init](CALayer * self, objc_selector * _cmd) Line 377   Objective-C++
>     FOUNDATION.DLL!+[NSObject new](id * self, objc_selector * _cmd) Line 70 Objective-C++
>     UIKIT.DLL!-[UIView _initPriv](UIView * self, objc_selector * _cmd) Line 650 Objective-C++
>     UIKIT.DLL!__24+[UIView allocWithZone:]_block_invoke(void \* .block_descriptor) Line 733  Objective-C++
>     UIKIT.DLL!RunSynchronouslyOnMainThread(...) Line 137    Objective-C++
>     UIKIT.DLL!+[UIView allocWithZone:](objc_class * self, objc_selector * _cmd, id * zone) Line 732 Objective-C++
>     UIKIT.DLL!+[UIImageView allocWithZone:](objc_class * self, objc_selector * _cmd, id * zone) Line 43 Objective-C++
>     FOUNDATION.DLL!+[NSObject alloc](id * self, objc_selector * _cmd) Line 77   Objective-C++
>     UIKIT.DLL!-[UIApplication init](UIApplication * self, objc_selector * _cmd) Line 925    Objective-C++
>     FOUNDATION.DLL!+[NSObject new](id * self, objc_selector * _cmd) Line 70 Objective-C++
>     UIKIT.DLL!UIApplicationMainInit(id \* principalClassName, id \* delegateClassName, unsigned int defaultOrientation, int activationType, objc_object \* activationArg) Line 151 Objective-C++
>     UIKIT.DLL!ApplicationMainStart(const char \* principalName, const char \* delegateName, float windowWidth, float windowHeight, ActivationType activationType, IInspectable \* activationArg) Line 146  Objective-C++
>     UIKIT.DLL!RunApplicationMain(Platform::String ^ principalClassName, Platform::String ^ delegateClassName, float windowWidth, float windowHeight, ActivationType activationType, Platform::Object ^ activationArg) Line 68   C++
>     UIKIT.DLL!DoApplicationLaunch(ActivationType activationType, Platform::Object ^ activationArg) Line 271 C++
>     UIKIT.DLL!_ApplicationLaunch(ActivationType activationType, Platform::Object ^ activationArg) Line 287  C++
>     UIKIT.DLL!UIApplicationLaunched(Windows::ApplicationModel::Activation::LaunchActivatedEventArgs ^ args) Line 186    C++
>     [External Code] 

It seems it has a problem with loading xib/nib files

**Comment by jaredhms** [comment]
Can you please try this on the latest master or develop branches?   Apologies for the delayed response; we were in the process of a large refactor across UIKit/CoreAnimation/XamlCompositor.  

If you can still reproduce the issue, please provide a new call stack, as well as more details on the OS version that you're running.

**Comment by ArnOmsft** [comment]
@spalda2, did you have the chance to try this with the latest master branch?
Please provide a new call stack if you can reproduce this.
Thanks.

**Comment by spalda2** [comment]
Hi,
   Sorry I got delayed on my trip. I have replied by mail to the previous comment, but not sure if you got it. I was on a trip with no access to my other pc wehere i have it all set up. I was to return on the 11th but got delayed. Will return on the 14th and then i'll test it.
Thanks

**Comment by spalda2** [comment]
I tested it now and it seems to be passing that point...getting another failure though shortly after as per new issue raised.

**Comment by jaredhms** [comment]
Thanks for the confirmation; we'll go ahead and close this out.  Feel free to reopen if you hit it again.
