### ISSUE TITLE
Tooling Questions

### ISSUE THREAD

**Issue by wjk** [Microsoft/WinObjC#121]
I have a few questions regarding the WinObjC project in general and its closed-source compiler in particular. Is it possible for this compiler be used to compile Objective-C code that does _not_ necessarily target the UWP? (I don't care about the libraries or the runtime, just the compiler.) This would be a big help for me in some of my desktop projects.

Also, is it possible to integrate the compiler into a third-party IDE which I am thinking of writing? If so, how would be the best way to do this? I find that the appeal of WinObjC is greatly reduced when I realize that currently I must use Microsoft's IMO sub-par tooling, so I have decided to create my own. Thanks!

**Comment by jakepetroules** [comment]
> closed-source compiler

The compiler is Clang/LLVM, which is Open Source software.

> Is it possible for this compiler be used to compile Objective-C code that does not necessarily target the UWP? (I don't care about the libraries or the runtime, just the compiler.)

Yes (see above).
