### ISSUE TITLE
Setting MaxClangProcesses to 1

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1210]
MaxClangProcesses is overridden to 1 and compiles use about 20-30% of the cores - which means that compile times are lengthy. Can the restriction be relaxed (e.g.: honor the -1)?

**Comment by pradipd** [comment]
Are you using clang modules?

**Comment by edvv** [comment]
I am not explicitly using Clang modules, but if Islandwood uses them (or vsimporter.exe sets the solution to use them) then I am implicitly using Clang modules. vsimporter.exe sets the solution property Maximum Clang processes to -1 (auto), but when the compiler runs it logs MaxClangProcesses as having a value of 1.

**Comment by bbowman** [comment]
Given other issues you've filed, I would try turning off clang modules in your solution. I t should fix the include weirdness and the max processors. @mukhole should know more.

**Comment by edvv** [comment]
With Clang > General > Enable C and Objective-C Modules set to Yes, the compile produced no errors and the solution ran. With that same flag set to No the compile produced 25 errors, such as:

`use of undeclared identifier 'UIPasteboard'`

With that flag set to No, the compile used 100% of the CPU most of the time, and the compile was much faster, but the solution would not run because of the errors.

**Comment by bbowman** [comment]
Do you have a small repro of this? Sounds like with Modules set to NO there may be a bug but it would be good to get a minimal repro to be sure.

**Comment by edvv** [comment]
No repro yet. If I'm able to get one then I'll post it.

**Comment by memontic-ms** [comment]
Cannot repro, closing. @edvv let us know if you run into this issue in the future.
