### ISSUE TITLE
Clean builds of some projects fail if whole solution isn't built (FunctionalTests.vcxproj as an example)

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#1213]
Develop builds of FunctionalTests.vcxproj try to link against all frameworks (default imports from sbclang stuff) but the build dependencies aren't actually there. This suggests that this system of just dumping everything in is not sufficient and error prone. Either FunctionalTests should depend on a fully built sdk and be moved to samples / somewhere else or it should correctly describe its build deps and not be built as an "sdk consumer" since it is in the build that builds the sdk so everything may not be built by the time its needed ...

**Comment by rajsesh-msft** [comment]
@bbowman why can't we add the explicit dependencies on the "dll" projects which the functional tests use?

**Comment by bbowman** [comment]
@rajsesh-msft that is exactly what we are already doing but its the ones it *doesn't* use that can be problematic. The linker still looks for all of the import libs added and only discards them if they don't provide any needed unresolved external symbols. This means *all* libraries in the sdk consumer build props (all our frameworks) must exist so that lib can be found and found to be useless.

**Comment by bbowman** [comment]
packaging fixed this I believe. FunctionalTests no longer inherit a huge linker line with all the libraries on it. This only happens when consuming packages which by definition all the binaries would be in the package.
