### ISSUE TITLE
Font display name and PostScript name issue

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#1221]
Hi, this is related to my issue: https://github.com/Microsoft/WinObjC/issues/1029

I have tested with CT-DW branch and didn’t work. It must be because the SDK does not support kCTFont**DisplayName**Attribute yet.

As I have described in the issue, a font file has different names – real full name and PostScript name. Some of the font file have same name for both but there are many files that shows different names for these. If you look at Typography Insight app and see the list of the fonts in Type Inspector menu, there will be many fonts that are displayed as Segoe UI as fallback since it couldn’t recognize the font name with PostScript name.

As you can see in these pages, kCTFontNameAttribute is PostScript name.
https://developer.apple.com/reference/coretext/kctfontnameattribute

Some of the examples are (typically no space between the words)
ITCAvantGardeStd-MdCn
ITCAvantGardeStd-XLtObl
ITCAvantGardeStd-BkObl
ITCAvantGardeStd-Md
ITCAvantGardeStd-MdObl

kCTFontDisplayNameAttribute is full real name. 
https://developer.apple.com/reference/coretext/kctfontdisplaynameattribute?language=objc 

Same example in DisplayName will be:
ITC Avant Garde Standard Medium Condensed
ITC Avant Garde Standard Extra Large Oblique
ITC Avant Garde Standard Black Oblique
ITC Avant Garde Standard Medium
ITC Avant Garde Standard Medium Oblique

Family name is just a single representative name for the groups of the different styles in a single font.
Family name for the sample would be just:
ITC Avant Garde Standard

Conclusion:
If SDK does not implement kCTFontDisplayNameAttribute, apps that use multiple custom fonts or system fonts will not be able to display many fonts. It will be just shown as default fallback Segoe UI.

**Comment by rajsesh-msft** [comment]
In the CT-DW branch, we support display name if it is specified as the kCTFontName attribute.  Clearly there are some gaps here, we need to address that.
