### ISSUE TITLE
[UIViewController presentedViewController] will return wrong view controller

### ISSUE THREAD

**Issue by memontic-ms** [Microsoft/WinObjC#1233]
Current Implementation: will return the view controller that presented it, the view controller that presented its parent, or nil.

Might just be a spelling mistake between presentingViewController and presentedViewController, but its ancestor view controllers also need to be checked.

**Comment by oliversa-msft** [comment]
Looks like a copy-paste bug. A reasonable person would assume the presentedVC property would return the _presentedVC controller.
