### ISSUE TITLE
No visible @interface for 'UITableViewController' declares the selector 'initWithCoder'

### ISSUE THREAD

**Issue by yw346090249** [Microsoft/WinObjC#124]
My code goes like that,
(id)initWithCoder:(NSCoder *)aDecoder
{
        if ((self = [super initWithCoder:aDecoder]))
        {
            [self loadChecklists];
        }
        return self;
}

Before the loadChecklists function, I would check the initWithCoder function of the super class. This works well in Xcoder however there is an error after I changed the Objective-C project into Windows 10 app and built the project. 
The error said "No visible @interface for 'UITableViewController' declares the selector 'initWithCoder' " and I wonder why it happened and is there any way I can fix that？

**Comment by asimonov-msft** [comment]
@yw346090249 8c89205e5f50748436ea39fdf2291884f68978d2 should hopefully fix this issue.
