### ISSUE TITLE
Draw CGPaths

### ISSUE THREAD

**Issue by MSFTFox** [Microsoft/WinObjC#1267]
Implement the drawing functionality for CGPaths. This is done via CGContextAddPath and CGContextStrokePath. Implement any missing CGContextPath APIs.

**Comment by DHowett-MSFT** [comment]
This is also partly covered by #1238.

**Comment by DHowett-MSFT** [comment]
Of note: The path will be stored transformed (!), and must be detransformed before draw lest we double transform it.
