### ISSUE TITLE
Proxy implementation of appearance doesn't work

### ISSUE THREAD

**Issue by volkrass** [Microsoft/WinObjC#127]
Unfortunately I can't compile a Project which includes following line:

[UINavigationBar appearance].tintColor = [UIColor whiteColor];

I got following error: 
"error : property 'tintColor' not found on object of type 'id'"

**Comment by wjk** [comment]
Have you tried this?

    [[UINavigationBar appearance] setTintColor:[UIColor whiteColor]];

You could also try casting the result of `[UINavigationBar appearance]` to type `UINavigationBar *`.

**Comment by volkrass** [comment]
@wjk Thanks for your support, works perfect.

**Comment by wjk** [comment]
I would say no, as Xcode's compiler has the exact same problem with dot-notation access to properties on type `id`.

**Comment by volkrass** [comment]
@wjk Ok I'm going to close my ticket, your hint has worked for me.

**Comment by bmedinab** [comment]
Hey guys, whenever I do 

```objc
[[UINavigationBar appearance] setTintColor:[UIColor whiteColor]];
```

I get the next Exception 
<pre>
Plaform::NotImplemented Exception ^.
Selector +[appearenceWhenContainedIn:forUIClass] is not implemented for class UIApperanceSetter on object 0x1754840!
</pre>

Any help will be welcome, also is there a way to change the blue color of the nav bar?
