### ISSUE TITLE
XamlTypeInfo.g.cpp errors when building C++ UWP app that uses WinObjC

### ISSUE THREAD

**Issue by Alovchin91** [Microsoft/WinObjC#128]
I'm trying to make use of WinObjC in a regular C++ UWP app. I created a blank UWP app, added WinObjC build customization (as described in Wiki), and then added two files: Class1.h and Class1.mm.

Class1.h:
```cpp
class Class1
{
public:
    void ThrowIslandwood();
};
```

Class1.mm:
```objc
#import "Class1.h"
#import <Foundation/Foundation.h>

void Class1::ThrowIslandwood()
{
    @throw [NSException exceptionWithName:@"Class1Exception" reason:@"You called it!" userInfo:nil];
}
```

The Class1.mm file builds fine, but then the build crashes with the following errors:

```
1>c:\objcwinrt\app1\generated files\xamltypeinfo.g.cpp(276): error C3083: 'System': the symbol to the left of a '::' must be a type
1>c:\objcwinrt\app1\generated files\xamltypeinfo.g.cpp(276): error C2039: 'Void': is not a member of '`global namespace''
1>c:\objcwinrt\app1\generated files\xamltypeinfo.g.cpp(276): error C2065: 'Void': undeclared identifier
1>c:\objcwinrt\app1\generated files\xamltypeinfo.g.cpp(276): error C2146: syntax error: missing ')' before identifier 'value'
```

Is there anything that can be done to fix this? Thanks.

**Comment by Alovchin91** [comment]
The problem solved. In project properties, I had to set *Islandwood > Composition > Composite layers as* setting to *SwapChainPanel*.

**Comment by Alovchin91** [comment]
Ah great. With the release [0.1.0.150903](../releases/tag/0.1.0.150903) there is no more _Composite layers as_ setting in the project properties! You can still add `<WSCompositor>SwapChain</WSCompositor>` to your project and it will ~~blend~~ build, but c'mon, it's not a solution anymore!

**Comment by jmsaunders-ms** [comment]
https://github.com/Microsoft/WinObjC/commit/0b4ec86d54a92dcb520f502f624386274ae9dfc4 should fix your issue (excuse the improper labeling....).

**Comment by Alovchin91** [comment]
@jmsaunders-ms Yep, this fixed it. Thanks!
