### ISSUE TITLE
Re-introduce text shadow

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#1288]
This has regressed since CT-DW merge

**Comment by rajsesh-msft** [comment]
This should work with CGD2D?

**Comment by DHowett-MSFT** [comment]
Correct!

**Comment by DHowett-MSFT** [comment]
This works properly in CGD2D right now, as of the #1239 + #1729 double-tap combo. We can close it since it's solidified in CGD2D, right?

**Comment by rajsesh-msft** [comment]
@DHowett-MSFT Yes, we can! Thanks for confirming this!
