### ISSUE TITLE
CFNetwork Library is missing

### ISSUE THREAD

**Issue by volkrass** [Microsoft/WinObjC#129]
I see that CFNetwork is part of CoreFoundation. But after importing my xcode project with vsimporter, it seems to be that the importer is not aware that CFNetwork is not a standalone lib anymore. I got LNK1181 cannot open Input file 'CFNetwork.lib'. Not a big deal to fix. But not sure if it should be considered somehow from vsimporter or it is one step of tasks I have todo manually afterwards.

**Comment by nicholasgerard-msft** [comment]
@volkrass This issue should be fixed with newer versions of the bridge. Could you please check with [the latest release](https://github.com/Microsoft/WinObjC/releases) and close the issue if it is resolved?

**Comment by volkrass** [comment]
@nicholasgerard-msft, sure I will do.

**Comment by nicholasgerard-msft** [comment]
Closing this for now – please open a new issue if your problem persists in the latest release of the bridge.
