### ISSUE TITLE
UIImage::applicationImageNamed:(NSString*)pathAddr Broken

### ISSUE THREAD

**Issue by MSFTFox** [Microsoft/WinObjC#1292]
UIImage is using a bad initialization pattern for this method. It attempts to call alloc/init and if that fails, will call init again on the alloc'd object.

UIImage* ret = [UIImage alloc];
    UIImage* found = [ret initWithContentsOfFile:pathAddr];

    if (found == nil) {
    ...
    found = [ret initWithData:fileData scale:scale];

This is obviously a bad pattern and was only working due to a design flaw in initWithContentsOfFile that was fixed with a change by @bbowman.

**Comment by msft-Jeyaram** [comment]
Thanks for the filing Hank.
I was just hitting this and debugging it.

**Comment by msft-Jeyaram** [comment]
This is not blocking develop.
Only blocking CGD2D branch, fix in the works.

**Comment by msft-Jeyaram** [comment]
Verifying fix for this.

The proper fix will come with the total removal of the old backing and migration to new design.
