### ISSUE TITLE
Linker error unresolved external symbol _NSFontAttributeName

### ISSUE THREAD

**Issue by volkrass** [Microsoft/WinObjC#130]
Can't compile my project because of few linker errors. _NSFontAttributeName is one of the missing symbols but it is part of the Foundation here:(https://github.com/Microsoft/WinObjC/blob/master/include/Foundation/NSAttributedString.h) 
Are there just only the declarations implemented?

**Comment by Ramu-msft** [comment]
The fix should be available in the recent release.

**Comment by volkrass** [comment]
@Ramu-msft Great to see that.
