### ISSUE TITLE
Issue with removeLastObject in NSMutableArray

### ISSUE THREAD

**Issue by zakirt-msft** [Microsoft/WinObjC#1308]
NSMutableArray *array = [[NSMutableArray alloc] init];
[array removeLastObject];
NSInteger count = [array count]; //count - will be -1, but should be 0.

// [array removeLastObject] should not effect on array, if it’s empty

As per the above code, and the implementation of removeLastObject in NSCFArray.mm, it seems that there may be an implementation issue with CFArrayRemoveValueAtIndex.

**Comment by bbowman** [comment]
@param idx The index from which to remove the value. If the index is
		outside the index space of the array (0 to N-1 inclusive,
		where N is the count of the array before the operation), the
		behavior is undefined.

Sounds like we should do a parameter check before calling into CF there.

**Comment by rajsesh-msft** [comment]
Also other methods that use CF.  The compat tests *should* catch these issues, assuming the tests exist.
