### ISSUE TITLE
Orientation issue

### ISSUE THREAD

**Issue by hervevi** [Microsoft/WinObjC#131]
Hello,

I've converted a Landscape application and it is running perfectly, except that the whole UI is rotated by 90°.

Any help/fix would be appreciated.

Regards,
Herve

**Comment by bdrlamb-ms** [comment]
You can manually set/override the application startup orientation using the display settings override callback that's issued to +[UIApplication setStartupDisplayMode:] - set "mode.presentationTransform = UIInterfaceOrientationLandscapeLeft"

See "WOCDisplayMode" in /include/UIKit/UIApplication.h and "setStartupDisplayMode:" in /samples/WOCCatalog/AppDelegate.m for an example.

**Comment by Alx06** [comment]
I tried everything in this setStartupDisplayMode method, but nothing works at all.
In certain cases it's even worst as I got a blank screen!!!
I can provide my project if you need it.

I added this code to my AppDelegate:

@implementation UIApplication(UIApplicationInitialStartupMode)
+(void) setStartupDisplayMode: (WOCDisplayMode *) mode {
    mode.autoMagnification = TRUE;
    mode.sizeUIWindowToFit = TRUE;
    mode.fixedWidth = 0;
    mode.fixedHeight = 0;
    mode.magnification = 1.0;
}
@end

And what I got was a blank screen.

I added

mode.presentationTransform = UIInterfaceOrientationLandscapeLeft;

=> same result (blank screen)

So I commented out these 2 lines:
    // mode.fixedWidth = 0;
    // mode.fixedHeight = 0;
And I got my app visible, but still rotated at 180 degrees.

So I tried with

mode.presentationTransform = UIInterfaceOrientationLandscapeRight;

and it worked!!!
