### ISSUE TITLE
Open GL Extensions function glMapBufferRangeEXT

### ISSUE THREAD

**Issue by zakirt-msft** [Microsoft/WinObjC#1314]
Looking for more robust support in OpenGL Extensions, specific to function glMapBufferRangeEXT.

Errors (LNK2019 unresolved external symbol) occur when trying to use OpenGL ES function glMapBufferRangeEXT (see OpenGLES/ES2/glext.h). GL_GLEXT_PROTOTYPES is defined but it does not seem to make any difference. 

Repro by trying to write and build the following in OpenGLES20Controller.m in WOCCatalog sample app:
glMapBufferRangeEXT(GL_ARRAY_BUFFER, 0, 4, GL_MAP_READ_BIT_EXT)

**Comment by rajsesh-msft** [comment]
@zakirt-msft we don't have any extensions support except glTexStorage2DEXT which just happens to work with Angle.  it is simple enough add a pass through API along the lines of glTexStorage2DEXT which will unblock you.  If this is blocking you, we would appreciate a pull request.

**Comment by sakrist** [comment]
Please check my pull request. `glMapBufferRangeEXT` function works as expect on many devices.

**Comment by sakrist** [comment]
I think this can be closed.
