### ISSUE TITLE
Ensure error handling in CoreGraphics and attendant frameworks happens at API boundaries

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#1323]
* All internal methods should be able to report failure without aborting, whether through an `HRESULT` return or a `nullptr` return.
* All external API surface methods should be able to fail *where possible*.
  * Some frameworks do not provide for errors to be returned. The reference platform has been observed calling `abort()`.
  * If there is an opportunity for a failure return, it should be taken. API functions that can return newly-created resources are safe to return nothing and emit a trace error.

**Comment by rajsesh-msft** [comment]
We have normalized the design on this, so we can close this now.
