### ISSUE TITLE
Code bring up is done

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1326]
Dear WinObjC Engineers,

Instead of a bug issue, I thought you might like to see some success (something fun) at: [Graph IDE on Windows](http://www.vvi.com/windowsbridgeforios/index.html).

Sincerely,

Ed

**Comment by rajsesh-msft** [comment]
@edvv This is great, thanks for sharing! Are you planning to publish the app in Windows store?

**Comment by kellymor** [comment]
Great looking project.  Thanks for sharing your success with the Windows Bridge for iOS.

**Comment by edvv** [comment]
@rajsesh-msft Thank you for your team's great work bringing the bridge up to speed. I am planning to publish to the Windows store; hopefully early next year, maybe as soon as January 2017. That is based upon estimates on the bridge's state and also a lot of production testing that needs to be done. I am sure you are aware that a timeline can slip here and there :-) and January may be too optimistic and it may slip to Q1 or even Q2. So far, based upon the current bridge performance, I am very optimistic.

**Comment by antoine-haas** [comment]
@edvv, this is awesome!

**Comment by ashvarma** [comment]
@edvv, This is awesome. Thanks for sharing! Really appreciate the feedback as well - so please keep it coming.

**Comment by rajsesh-msft** [comment]
Closing this issue out, thanks again for all the feedback.
