### ISSUE TITLE
Enable developers to easily get started with WinObjC without an existing xcode project to import

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#1340]
The current documentation and flows all presuppose that a developer has existing iOS code that they want to port to Windows. This is likely true for a large number of potential consumers but sort of pigeonholes the role of the project in an undesirable way. There is no reason that ObjectiveC can't become more of a "first class" citizen / language on Windows where developers could just choose to write with it from the get go. 

It would be super swell for IDE integration, etc. to just present ObjC as a new project type and allow developers to start fresh or import existing xcode proejcts.

**Comment by rajsesh-msft** [comment]
This is a good suggestion - this doesn't fit into our current plans - which is to provide a bridge to windows for iOS developers porting their existing code - so closing this for now.
