### ISSUE TITLE
Antialias for images, curves and fonts

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1349]
Dear WinObjC Engineers:

I notice that compositing for UIImage is not re-sampled in a interpolative way (misnomer: antialiased). This is an integral feature for displaying a high resolution image on different DPI devices (normal and retina) instead of using the `@2x , @3x`, etc. method. I have the following requests:

- CGContextSetShouldAntialias() be implemented.

- UIImage apply a resampling filter better than the current one.

- Antialiased fonts.

Sincerely,

Ed

Reference:

void CGContextSetShouldAntialias(CGContextRef ctx, bool shouldAntialias) {
    UNIMPLEMENTED();
    ctx->Backing()->CGContextSetShouldAntialias(shouldAntialias);
}

**Comment by edvv** [comment]
Perhaps this is all referenced in issue https://github.com/Microsoft/WinObjC/issues/1177 . If it is then please feel free to close this issue.

**Comment by rajsesh-msft** [comment]
This is likely not covered by #1177, adding this to the backlog.

**Comment by rajsesh-msft** [comment]
CGContextSetShouldAntialias(), etc is different from UIImage resampling, it would be best to break these asks.  We can use this to cover anti-alias.

**Comment by DHowett-MSFT** [comment]
The work backing this is tracked by #1391. Image interpolation is in CGD2D as of #1557, and will merge into develop when CGD2D does.
