### ISSUE TITLE
Windows Runtime component fails to load because of ConsumeRuntimeComponent.cpp

### ISSUE THREAD

**Issue by Alovchin91** [Microsoft/WinObjC#136]
I have a test Windows Runtime component that consists of two classes. One class is a plain C++ class that has implementation in .mm file, and this implementation uses Objective-C. Another class is a Windows Runtime class that wraps up the C++ class.

The component builds successfully; I then use this component in a C# Universal app project. When I try to create Windows Runtime class, I get a `System.IO.FileLoadException` with HRESULT of **0x8007045A** (_"A dynamic link library (DLL) initialization routine failed."_)

I found out that the cause is in the **ConsumeRuntimeComponent.cpp** file that is being added by Islandwood's targets. Specifically, the problem is in the following line presented in commit 8ac4e7209eec646cf9d298108b8694965fcb6f9f:

```cpp
#pragma comment(linker, "/INCLUDE:___refMTAThread")
```

If I comment this line out, the Windows Runtime component is being loaded and the class is constructed successfully.

Is there anything that can be done about this? Thanks!

**Comment by rajsesh-msft** [comment]
This should be fixed now.
