### ISSUE TITLE
[NSURL initFileURLWithPath:] performs blocking access to filesystem

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#1362]
When creating an NSURL instance via `[NSURL initFileURLWithPath:]` the filesystem is accessed during the init method when it calls `_stringLooksLikeOrIsPathToDirectory()`. This causes the method to block and has a big performance impact when you are creating a collection of NSURL instances.

Ideally the filesystem should not be accessed during the init process and only methods like `[NSURL checkResourceIsReachableAndReturnError:]` should do this.

**Comment by rajsesh-msft** [comment]
also URLByAppendingPathComponent.

**Comment by ms-jihua** [comment]
Hi @rupertdaniel , this is unfortunately part of the API contract of initFileURLWithPath: (https://developer.apple.com/reference/foundation/nsurl/1410828-fileurlwithpath?language=objc). While we could defer this process until a getter is used, as you recommend, doing so is fairly non-trivial, prone to error, and would place a burden of knowledge on developers who make future changes to the class's getters. As such, we'd like to avoid making such a change at this time.

If you're in a position where you can make certain assumptions about the URLs you're consuming, could you try initFileURLWithPath:isDirectory:NO, instead? Internal testing shows good performance improvements from this (cuts time nearly in half). Thanks!

**Comment by rupertdaniel** [comment]
Ahh thanks @ms-jihua for looking into this. I will give that suggestion try!
