### ISSUE TITLE
[CGD2D] CGPath's default fill mode is Alternate (EO), but CG should default to Winding.

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#1375]
Current fix: "convert" all D2D Geometries to the appropriate fill mode, even if they are already compliant.

Suggested fix: Enlighten CGPath as to its fill mode and provide a CGPath internal function for obtaining a geometry in a different fill mode.

**Comment by rajsesh-msft** [comment]
Per offline discussion with Hank, this requires more work.  Moving to 1701.

**Comment by DHowett-MSFT** [comment]
This is a relatively minor optimization, it doesn't need the CGD2D-Blocker label.

**Comment by rajsesh-msft** [comment]
@DHowett-MSFT thanks!
