### ISSUE TITLE
BOOL has 4 bytes instead of 1.

### ISSUE THREAD

**Issue by sakrist** [Microsoft/WinObjC#1383]
Original version of `BOOL` is typedef as `signed char`, but in WinObjC `int`.

Is it bug or was made for a reason? 

Here is source [objc.h](https://opensource.apple.com/source/objc4/objc4-706/runtime/objc.h.auto.html)

**Comment by DHowett-MSFT** [comment]
Since we have to interoperate with **windows.h** consumers, we must share its definition of `BOOL` (née `int`); otherwise, translation units built with one set of headers would be ABI-incompatible with ones built from a different set of headers.
