### ISSUE TITLE
[CGD2D] Draw primitives with Porter-Duff blend modes

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#1389]
Direct2D supports a subset of CG's blend modes as direct composition modes, and a subset of CG's porter-duff blend modes with its blend effect.

The blend effect, however, requires a full target readback and recompose.

The scope of this issue is to support only the basic non-blend-effect composition modes for 1611.

```
kCGBlendModeNormal = kCGBlendModeSourceOver
kCGBlendModeSourceOver
kCGBlendModeDestinationOver
kCGBlendModeSourceIn
kCGBlendModeDestinationIn
kCGBlendModeSourceOut
kCGBlendModeDestinationOut
kCGBlendModeSourceAtop
kCGBlendModeDestinationAtop
kCGBlendModeXOR
kCGBlendModePlusLighter
kCGBlendModeCopy
kCGBlendModePlusDarker // Not supported
```

**Comment by rajsesh-msft** [comment]
Still have some open issues here that need to be sorted out.  May not be required for merge back to develop.
