### ISSUE TITLE
Support CGContextSetRenderingIntent.  (Draw images with the context-wide rendering intent)

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#1390]
This will require the use of D2D1's [Color Management effect](https://msdn.microsoft.com/en-us/library/windows/desktop/hh706318(v=vs.85).aspx).

[D2D1_COLORMANAGEMENT_RENDERING_INTENT](https://msdn.microsoft.com/en-us/library/windows/desktop/dn934228(v=vs.85).aspx)

**Not supported on `develop`**.

**Comment by rajsesh-msft** [comment]
Not in plan for the near future as this doesn't seem to be widely used.
