### ISSUE TITLE
not compatible with other redstones 

### ISSUE THREAD

**Issue by ali1997** [Microsoft/WinObjC#1432]

**Comment by rajsesh-msft** [comment]
@ali1997 please provide more details on what issue you are running into.

**Comment by rajsesh-msft** [comment]
closing the issue as there is not enough information.

**Comment by ali1997** [comment]
i have technical preview . and sdk is technical preview . hope to be compatible with other verisons

**Comment by ali1997** [comment]
i didnt know why it is says when i try to convert it is says you should install sdk for create uwp apps but it is already installed !
