### ISSUE TITLE
Sytem UIButton does not update when being pressed

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#1442]
Phone: Lumia 640 device (14393 build)
Master commit: https://github.com/Microsoft/WinObjC/commit/2e0afafbf36d23b1cee7bd09f1dc8cf230c5c8a1

Build/run WoCCatalog in Debug.
Go to ButtonsViewController.
Press Simple Button.

Expected: Simple Button makes some sort of visible change when pressed.
Actual: No visible change when pressed.

Image Button does change when pressed.

**Comment by ArnOmsft** [comment]
The default behavior of system type UIButton where the button is being dimmed when pressed is currently not supported by the bridge. So the same code will show the button's appearance changing when run on iOS but the button's appearance is not changing when being run on Windows.

**Comment by ArnOmsft** [comment]
We'll fix this bug by updating the app to show a change in visual state of the button when being pressed but we'll track the work required to support the default behavior of system button separately.

**Comment by jaredhms** [comment]
ButtonsViewController has been removed from WoCCatalog, so closing this out since we'll track proper default button behavior separately.

**Comment by tadam-msft** [comment]
Decided this should track button task of adding default pressed behavior.
