### ISSUE TITLE
WOCCatalog [ARM]: Display mode switches move outside their ovals when turned on.

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#1443]
Phone: Lumia 640 device (14393 build)
Master commit: https://github.com/Microsoft/WinObjC/commit/2e0afafbf36d23b1cee7bd09f1dc8cf230c5c8a1

Build/run WoCCatalog in Debug or Release.
Bring up Display Mode.
Flick a switch to the on position.

Expected: switch turns to a color, circle moves to the right.
Actual: switch turns to a color, circle moves to the right, colored oval moves past the confines of the control for a split second.

**Comment by oliversa-msft** [comment]
This issue existed prior to the composition refactor. We also noticed that it's intermittent - sometimes the gap when changing the UISwitch from off to on is noticeably, other times you'll won't see any gap at all.

**Comment by ArnOmsft** [comment]
UISwitch is currently not a control backed by its XAML equivalent (ToggleSwitch), we'll make sure to address this issue when we migrate UISwitch to XAML.
