### ISSUE TITLE
WOCCatalog [ARM]: Accelerate 1 takes several seconds to refresh.

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#1444]
Phone: Lumia 640 device (14393 build)
Master commit: https://github.com/Microsoft/WinObjC/commit/2e0afafbf36d23b1cee7bd09f1dc8cf230c5c8a1

Build/run WoCCatalog in Debug or Release.
Go to Accelerate 1.
Move the value of RGB, etc to a different value.

Expected: the color values update on the mountain.
Actual: the color values update after about 3-5 seconds.

Is this expected behavior?

**Comment by rajsesh-msft** [comment]
Its usually not a good idea to measure perf on debug build.  Does this repro on retail?

**Comment by andrejo-msft** [comment]
It does indeed. I'll update the name of the issue to reflect it.

**Comment by rajsesh-msft** [comment]
@andrejo-msft I compared to last release of this.  When you change the slider, the entire image has to be processed.  on ARM, we don't use any ARM optimization to speed this up (of x86, we have the optimized code).  So this is performing as expected and is not a regression.  I'll close this issue as such.
