### ISSUE TITLE
Canabalt [ARM]: app crashes when button is pressed on Main Menu

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#1445]
Phone: Lumia 640 device (14393 build)
Master commit: https://github.com/Microsoft/WinObjC/commit/2e0afafbf36d23b1cee7bd09f1dc8cf230c5c8a1

Build Canabalt from open source codebase.
Install on Windows Phone via the bridge.
Run the app (debug/release).

Expected: App runs, shows buttons after splash screen appears.
Actual: App runs, shows buttons after splash screen appears and orientation is changed. Buttons are empty, pressing a button crashes app.

**Comment by DHowett-MSFT** [comment]
The crash is due to a stack smash introduced [here](https://github.com/Microsoft/WinObjC/pull/1175/files#diff-504dcaf5c62df21ac9083e5c3ae517c1R203); instead of reading into `outBufferData` we are reading into the pointer to `outBufferData` and its following parameters.

@bbowman

**Comment by DHowett-MSFT** [comment]
The missing button text is due to #924.

**Comment by ashvarma** [comment]
Repurposing this issue to track only the crash. 

We will use #924 to track the text missing on button.
