### ISSUE TITLE
iLabyrinth [ARM]: Back button does not function until a change in alignment.

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#1446]
Phone: Lumia 640 device (14393 build)
Master commit: https://github.com/Microsoft/WinObjC/commit/2e0afafbf36d23b1cee7bd09f1dc8cf230c5c8a1

Build iLabyrinth from codebase.
Deploy to Phone device over bridge.
Run app in portrait mode. (debug mode)

Press Play.
Notice the alignment of level selection. Move to landscape to see everything.

**Expected:**
Virtual buttons change alignment. Level select screen changes.

**Actual:**
Virtual buttons change alignment. Level select screen does not.

Press Back Button.

**Expected:**
Go back to the previous app.

**Actual:**
No response until I change orientation and press it again.

Note that the app crashes afterward and must be restarted.

**Comment by ArnOmsft** [comment]
I cannot repro this one with a 950. We agreed with Drew we'll try to repro again with the next build and close it if we can't.

**Comment by andrejo-msft** [comment]
As part of our monthly release process, we perform some manual tests with a variety of devices. This particular issue has been difficult to reproduce with anything other than an older model Windows Phone device.

**Comment by ArnOmsft** [comment]
I just tried to repro with the latest build and I could not. Let me know if you can, if not we'll close this one.
Thanks.

**Comment by tadam-msft** [comment]
No Repro
