### ISSUE TITLE
IslandwoodNews [ARM]: app crashes on launch

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#1447]
Phone: Lumia 640 device (14393 build)
Master commit: https://github.com/Microsoft/WinObjC/commit/2e0afafbf36d23b1cee7bd09f1dc8cf230c5c8a1

Build IslandwoodNews app from MSFT source (IW News is an internal testing tool for WinObjC).
Deploy to phone (release)

Expected: app launches
Actual: app crashes

**Comment by jaredhms** [comment]
Fixed with #1534.
