### ISSUE TITLE
WOCCatalog [x86] ButtonsViewController - single button do not change appearance when pressed

### ISSUE THREAD

**Issue by MichelLopez** [Microsoft/WinObjC#1452]
Desktop running 14975
Run the app (debug/release)

Expected: ButtonsViewController - The 2 buttons should be visible, clickable and their appearance should changed when pressed
Actual: The single button do not change appearance when pressed

**Comment by ArnOmsft** [comment]
This is a known issue on the app itself which we won't fix. the button below it properly configured and works as expected.
