### ISSUE TITLE
[CGD2D] CGImage.mm:580 causes over-release of COM object

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#1453]
The `.Get()` [here](https://github.com/Microsoft/WinObjC/pull/1414/commits/9fe3638ca7157d72d9063fb4f65e7503d624aa72#diff-16e01a72b686518a7ed4ff3668919f2bR580) does not store a +1 reference into the destination but the destination ([here](https://github.com/Microsoft/WinObjC/pull/1414/commits/9fe3638ca7157d72d9063fb4f65e7503d624aa72#diff-71f2997808c3d09d7d9ae3411de51489R1794)) is a ComPtr and will release it.

The preferred method for getting a +1 reference from a ComPtr **a** into an out pointer **b** is `a.CopyTo(b)`.

**Comment by msft-Jeyaram** [comment]
Thanks on the fix.

**Comment by msft-Jeyaram** [comment]
I'm going to do a bit more diligence on the take in ownership by IWICSource for CGImage struct.

**Comment by DHowett-MSFT** [comment]
@msft-Jeyaram I fixed this in a branch because I thought it was the cause of my over-release.
It wasn't.
