### ISSUE TITLE
Autolayout related memory leaks

### ISSUE THREAD

**Issue by ehren** [Microsoft/WinObjC#1463]
The heap profiler shows this allocation stack associated with a large number of leaks:

![screen shot 2016-11-28 at 8 50 59 am](https://cloud.githubusercontent.com/assets/252343/20671179/4db5fca4-b54a-11e6-8270-97d38db3c416.png)

^^ above shows session with heap snapshots taken on the main menu of the WOCCatalog app (snapshot taken every time a view controller is loaded and unloaded; WOCCatalog needs patch from #1462). There's about a 400KB leak, not entirely autolayout related; leak is worse without fix in #1461.

**Comment by jaredhms** [comment]
Thanks for finding this and for tracking down the root cause.
