### ISSUE TITLE
Popover related touch/view-hierarchy problem

### ISSUE THREAD

**Issue by ehren** [Microsoft/WinObjC#1479]
(this is not an urgent issue for me as there's a workaround noted below and my app development is currently against a stable branch)

Some of the recent view/layer work has broken popover dismisses (via touch on a clear overlay view outside the bounds of the popover content view controller). 

Steps to reproduce:

1) Open WOCCatalog app
2) Enable tablet mode in display mode view controller, press back
3) Load Controls View Controller
4) Touch a popover button
5) Dismiss popover via touch outside the popover content

Expected:
The popover is dismissed

Actual:
The touch passes through to the table below; popover is not dismissed

I've been able to bisect the commits and I believe the problem was introduced by ec804795a924609eb975a6518475a6371c871b14

The last good version (where popover is dismissed) is b52a219eba2093a3c273ecee10e0a81242072979

The relevant WYPopoverController code is here:
https://github.com/Microsoft/WinObjC/blob/812d6636036a8d2eaeaaf7b92aa0c7b76252e190/Frameworks/UIKit/WYPopoverController.m#L1937

```
        overlayView = [[WYPopoverOverlayView alloc] initWithFrame:inView.window.bounds];
        overlayView.autoresizesSubviews = NO;
        overlayView.isAccessibilityElement = YES;
        overlayView.accessibilityTraits = UIAccessibilityTraitNone;
        overlayView.delegate = self;
        overlayView.passthroughViews = passthroughViews;
        
        backgroundView = [[WYPopoverBackgroundView alloc] initWithContentSize:contentViewSize];
        backgroundView.appearing = YES;
        backgroundView.isAccessibilityElement = YES;
        backgroundView.accessibilityTraits = UIAccessibilityTraitNone;
        
        backgroundView.delegate = self;
        backgroundView.hidden = YES;
        
        [inView.window addSubview:backgroundView];
        [inView.window insertSubview:overlayView belowSubview:backgroundView];
```

Something is going wrong with `overlayView` here.

A few other notes:

- This problem can be bypassed by selecting the legacy hit test operation mode.
- However I don't believe this is a "legacy hit test" issue - though overlayView does implement hitTest it doesn't request to participate in hit testing outside it's bounds.
- I suspect something is funny with the view hierarchy at the point the background and overlay views are added to the window of the inView (which corresponds to the UIPopoverPresentationController sourceView)
- I have not yet attempted to dump a description of the view hierarchy at the time the above code is executed. This could be enlightening.

**Comment by ehren** [comment]
I found an additional view in my app that needs legacy hit testing enabled against the latest revisions. It's a UITableViewCell (no popovers involved). Will post if I find out more.

**Comment by jaredhms** [comment]
Thanks, @ehren - I'm hoping to take a look this week.  I think it's a bit odd that you need to use legacy hit testing though; are there any tweaks to setUserInteractionEnabled(true/false) that alleviate the issue?    If you inspect the UIElements in the live UIElement tree viewer in the VS debugger, and look for 'isHitTestVisible', you may find that toggling that value will fix the issue.  Any more details you can provide would be helpful.

**Comment by ehren** [comment]
@jaredhms toggling isHitTestVisible in the tree viewer fixed the issue for the UITableView cell (this view does have a few disabled UIImageViews as subviews - may be related - will look further). Haven't tested if this is the case for ```overlayView``` yet.

**Comment by jaredhms** [comment]
Thanks, @ehren.  We internally map the setUserInteractionEnabled(true/false) values to Xaml isHitTestable values, so you should be able to fine-tune your subviews via setUserInteractionEnabled to get this to work reliably in your app.  

Any more details you can provide would be helpful though (another self-contained repro, etc.).  It's possible that we're not setting a userInteractionEnabled value correctly somewhere, but it's also possible that this is by design, and we may always require a bit more fine-tuning of hit testability on our platform.

**Comment by ehren** [comment]
@jaredhms I'm going to try recursively applying setUserInteractionEnabled for that problematic cell mentioned above (I'm also debugging a possibly unrelated issue where a control seems to require a long press? don't have details yet).

No rush in any case - this particular issue really isn't a blocker.

fyi, I was able to modify WOCCatalog to highlight some interesting issues (one of them reproduces the WYPopoverController overlay problem)

```
diff --git a/samples/WOCCatalog/WOCCatalog/ControlsViewController.m b/samples/WOCCatalog/WOCCatalog/ControlsViewController.m
index 8dc431f..a1bfc11 100644
--- a/samples/WOCCatalog/WOCCatalog/ControlsViewController.m
+++ b/samples/WOCCatalog/WOCCatalog/ControlsViewController.m
@@ -66,6 +66,11 @@ static const int MULTIPLEPRESENTDISMISS_ROW = 5;
     [self.rightPopoverButton setFrame:CGRectMake(self.view.bounds.size.width - originOffset - buttonWidth, originOffset, buttonWidth, buttonHeight)];
     [self.rightPopoverButton addTarget:self action:@selector(pressedPopoverButton:) forControlEvents:UIControlEventTouchUpInside];
     [self.view addSubview:self.rightPopoverButton];
+
+    // this blocks touches
+    UIView *blah = [[UIView alloc] initWithFrame:self.view.bounds];
+    blah.alpha = 0.0;
+    [self.view addSubview:blah];
 }
 
 - (void)viewDidDisappear:(BOOL)animated {
diff --git a/samples/WOCCatalog/WOCCatalog/MenuTableViewController.m b/samples/WOCCatalog/WOCCatalog/MenuTableViewController.m
index 988c857..8d56ce2 100644
--- a/samples/WOCCatalog/WOCCatalog/MenuTableViewController.m
+++ b/samples/WOCCatalog/WOCCatalog/MenuTableViewController.m
@@ -39,6 +39,18 @@ static NSString* viewTitleKeyName = @"ViewName";
     [self.menuItems addObject:[NSDictionary dictionaryWithObjectsAndKeys:title, viewTitleKeyName, controllerClass, controllerKeyName, nil]];
 }
 - (void)viewDidLoad {
+    // this doesn't even show up (same issue as WYPopoverController _overlayView)
+    UIView* red = [[UIView alloc] initWithFrame:self.view.bounds];
+    red.backgroundColor = [UIColor redColor];
+    red.alpha = 0.5;
+    [self.view.window addSubview:red];
+
+    // this shows up but touches on menu table aren't blocked
+    UIView* green = [[UIView alloc] initWithFrame:self.view.bounds];
+    green.backgroundColor = [UIColor greenColor];
+    green.alpha = 0.5; // none of these alpha values matter for these tests
+    [self.view addSubview:green];
+
     [super viewDidLoad];
 }
```

It's weird that the same code in the pushed view controller blocks touches while in the root touches aren't blocked (and adding directly to the window reproduces the WYPopover issue).

**Comment by jaredhms** [comment]
Thanks for the added details.  FYI that I'll be out for the holidays, so we likely won't be able to investigate futher until early 2017.  Please let us know if this becomes a blocking issue though.

**Comment by ehren** [comment]
@jaredhms no prob, thanks for the assistance (with the autolayout stuff too!). I may file a few more bugs before going on break but my current app dev isn't blocked.

**Comment by ehren** [comment]
Note: I mentioned above some other problems with UITableViewCells and other misc views behaving strangely or not responding to touches. These issues have all been fixed against the latest develop (that contains the #1685 pull).

**Comment by jaredhms** [comment]
Awesome - thanks for letting us know.
