### ISSUE TITLE
Missing crucial UICollectionView methods

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#148]
Missing the following:

indexPathForCell:
setCollectionViewLayout: animated:
@property backgroundView
@property visibleCells

**Comment by Ramu-msft** [comment]
UICollectionView enhancements are available in 0.1 Preview (December 3, 2015) release.

**Comment by Ramu-msft** [comment]
UICollectionView enhancements are available in&nbsp;0.1 Preview (December 3, 2015) release.
