### ISSUE TITLE
WoCCatalog: Display Mode: text fields are partially obscured

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#1484]
Phone: Lumia 640 device (14393 build)
Master commit: https://github.com/Microsoft/WinObjC/commit/3a18ee2fba446ed209055348dd74f8ddc102ad94

Build/run WoCCatalog in Debug or Release.
Bring up Display Mode.
Go to Fixed Width and text fields below.

Expected: number values are visible
Actual: number values are partially obscured

This looks like a WoCCatalog problem, looking at the code for the Display Mode. Looks like a change was made recently to make text fields more readable, but the specific text fields in question were given a static height.

Not a regression from the previous master commit.

**Comment by andrejo-msft** [comment]
Also of note; it seems that you can scroll the numbers around in the box with your finger; is that expected?

**Comment by tadam-msft** [comment]
Need to determine if this was a regression

**Comment by tadam-msft** [comment]
Fixed
