### ISSUE TITLE
WoCCatalog [ARM|RELEASE]: PageView: flickers in pageview

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#1488]
Phone: Lumia 640 device (14393 build)
Master commit: 3a18ee2
Build/run WoCCatalog in Release.
Bring up PageView.

Click on arrows.

Expected: transition of PageView is fluid
Actual: transition of PageView from one page to another flickers significantly on the first three loads, then becomes less pronounced (but visible) in subsequent transitions.

**Comment by bebauer-msft** [comment]
Found an additional issue that may result from this flickering. 

If you tap pages fast enough and happen to tap during transition (in the flickery part), you will end up losing one of the pages and making the paging completely broken.

**Comment by andrejo-msft** [comment]
Closing this issue, as work on it is being tracked by issue #1537.
