### ISSUE TITLE
UILabel: [UILabel adjustTextLayerSize] does more work than necessary

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#1497]
We should apply most of the properties to the _textBlock as they're set (within setText, setFont, etc.) rather than doing it within adjustTextLayerSize (which is called quite frequently by most of UILabel's setters).

**Comment by yiyang-msft** [comment]
adjustTextLayerSize is being renamed as _updateXamlElement

**Comment by jaredhms** [comment]
And now _updateXamlElement is being renamed to _updateXamlElementWithAdjustedFont.  Maybe we should fix this bug as part of the rename.

**Comment by jaredhms** [comment]
Not sure what the correct fix is here, but doing minimal work in _updateXamlElementWithAdjustedFont is the goal.

**Comment by yiyang-msft** [comment]
_updateXamlElementWithAdjustedFont is break out to smaller functions and setting correponding properties only calls into corresponding smaller functions. e.g., setTextColor only setting color and only calls setNeedsDisplay.

**Comment by yiyang-msft** [comment]
fixed with 6fcf514c273d32104026c0a973a10ca84d36a5f3
