### ISSUE TITLE
UILabel: [UILabel lineBreakMode] is not honored/applied to the backing _textBlock

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#1498]
We're not currently mapping _lineBreakMode to textWrapping/textTrimming/linestackingstrategy properties on the Xaml _textBlock, but we should be.  This work may be gated on the addition of line break support to our CoreText implementation.  

Note: We're currently always setting _textBlock's lineStackingStrategy to BlockLineHeight, because that's how it was originally written, but we should revisit that to see when that value is correct/necessary (vs. sticking with the default, etc.).

Here's a snippet of code that was in the compositor refactor, but was stripped out due to app compat issues (probably due to the fact that CT didn't yet support it for size calculations).

    switch (_lineBreakMode) {
        case UILineBreakModeWordWrap:
            [_textBlock setTextWrapping:WXTextWrappingWrapWholeWords];
            break;

        case UILineBreakModeCharacterWrap:
            [_textBlock setTextWrapping:WXTextWrappingWrap];
            break;

        case UILineBreakModeClip:
            [_textBlock setTextWrapping:WXTextWrappingNoWrap];
            [_textBlock setTextTrimming:WXTextTrimmingClip];
            break;

        case UILineBreakModeHeadTruncation:
            // GAP: currently textblock don't support UILineBreakModeHeadTruncation
            UNIMPLEMENTED_WITH_MSG("UILineBreakModeHeadTruncation unsupported");
            break;

        case UILineBreakModeMiddleTruncation:
            // GAP currently textblock don't support UILineBreakModeMiddleTruncation
            UNIMPLEMENTED_WITH_MSG("UILineBreakModeMiddleTruncation unsupported");
            break;

        case UILineBreakModeTailTruncation:
            [_textBlock setTextWrapping:WXTextWrappingNoWrap];
            [_textBlock setTextTrimming:WXTextTrimmingCharacterEllipsis];
            break;
    }

**Comment by yiyang-msft** [comment]
fixed.
