### ISSUE TITLE
source.extension.vsixmanifest should support Visual Studio 2015

### ISSUE THREAD

**Issue by reghrafa** [Microsoft/WinObjC#15]
The objc-syntax-highlighting Extension currently only supports VS 12. It should also support higher versions.

**Comment by KyleMcNutt** [comment]
+1

**Comment by reghrafa** [comment]
As a workaround you can still manipulate the vsixmanifest inside the extension and add VS 2015^^
  <Installation>
    <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[12.0]" />
    <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[14.0]" />
  </Installation>

**Comment by davelamb** [comment]
The vsix found in WinObjC/bin (not in the SDK zip) has been updated to work with 2015. Give it a try, and let us know if you have any more problems.
