### ISSUE TITLE
Text draw speed regression

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1500]
Dear WinObjC Engineers,

From release 41 to 42 there is a regression in text drawing speed. Release 41 is about 10 to 100 times faster than 42. It is a very significant effect. Release 41 text draw speed was similar to an iPad, while Release 42 is an order of magnitude or two slower.

See also https://github.com/Microsoft/WinObjC/issues/1374

Sincerely,

Ed

**Comment by rajsesh-msft** [comment]
@edvv could you please explain what text draw API you are seeing regression in? What formatting you are using and the contents?

**Comment by edvv** [comment]
@rajsesh-msft The API is that of the project at this URL:

https://github.com/Microsoft/WinObjC/issues/1335

Where [aString drawAtPoint:aPoint withAttributes:stringAttributes]; is called tens to hundreds of times for tables formatted as shown at this URL:

http://www.vvidget.org/manuals/GraphIDE/Controls/Tables/index.html

and while scrolling. It is noticeable by a user while scrolling, but is not particular to this situation.

Sincerely,

Ed

**Comment by edvv** [comment]
This problem persists with release 43.

**Comment by antoine-haas** [comment]
Thanks for trying it out with the new release @edvv. This should be fixed with the December release as part of #1374.

**Comment by rajsesh-msft** [comment]
@eddv, thanks for reporting this.  We had seen the regression internally as well. We will use #1374 for tracking perf issues.  We will likely have to address these over a couple of iterations.  For example, #1490 is also hit quite a bit in this code path.

**Comment by rajsesh-msft** [comment]
#1374 won't fix all issues afterall, so we will keep this active for now.

**Comment by rajsesh-msft** [comment]
Issue #1620 will improve the performance.  We will re-evaluate perf after that work and iterate.
