### ISSUE TITLE
Text clipping path regression

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1501]
Dear WinObjC Engineers,

From release 41 to 42 there is a regression in text clipping path. Release 41 properly truncated text at the clipping path boundary while release 42 text does not clip at the clipping path.

Sincerely,

Ed

**Comment by edvv** [comment]
This problem persists with release 43.

**Comment by DHowett-MSFT** [comment]
Hi @edvv! Thanks for the report.

Just to make sure, you're talking about the combination of `CGContext(EO)?Clip` and the CT+CG glyph/frame/line drawing APIs, correct?

If so, we're mirroring most of the Cairo context's state into the text renderer and we appear to have missed the clipping/masking parameters.

**Comment by edvv** [comment]
@DHowett-MSFT That is correct.

**Comment by ArnOmsft** [comment]
@edvv, fixing this requires the work we're doing to implement CoreGraphics on D2D (cf. the CGD2D branch) to be merged to master. We're planning to merge at the end of January (that's our 1701 sprint) so the fix for this specific issue will come in February (our 1702 sprint).

**Comment by edvv** [comment]
@ArnOmsft That sounds very sensible. Thank you for the consideration.

**Comment by DHowett-MSFT** [comment]
This is fixed in develop with the merge of #1892.

**Comment by edvv** [comment]
@DHowett-MSFT I am very excited to try this out in the next release. Thank you for the note and fix.
