### ISSUE TITLE
CoreText: AV in WoCCatalog text display sample when quickly scrolling around

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#1508]
I hit this AV when going into the Text Display sample in WoCCatalog and quickly scrolling up/down.

00 0311ee28 6a60a8cc 0x0
01 0311ee28 6a61defa DWrite!FontCollectionBuilder::AddFontFiles+0xbc onecoreuap\windows\core\text\font\fontcollectionbuilder.cpp @ 56]
02 0311eed8 6a6240c6 DWrite!FontCollectionConstructionTask::AddElementData+0xea onecoreuap\windows\core\text\fontcache\elements\fontcollectionelement.cpp @ 148]
03 0311ef48 6a6230e2 DWrite!CacheWriter::AddElement+0x4e onecoreuap\windows\core\text\fontcache\logic\cachewriter.cpp @ 605]
04 0311efb8 6a5d04d4 DWrite!IBaseCacheContextImpl::AddElementInternal+0x42 onecoreuap\windows\core\text\fontcache\logic\ibasecachecontext.cpp @ 37]
05 (Inline) -------- DWrite!ClientSideCacheContext::AddElementInternal+0x4 onecoreuap\windows\core\text\fontcache\logic\fontcachecontext.cpp @ 237]
06 0311f000 6a62373e DWrite!DWriteFactory::AddElement+0x14 onecoreuap\windows\core\text\apiimpl\dwritefactory.cpp @ 325]
07 0311f030 6a57e24a DWrite!ElementTaskList::ExecuteTask+0x36 onecoreuap\windows\core\text\fontcache\logic\elementtasklist.cpp @ 208]
08 (Inline) -------- DWrite!ElementTaskList::GetElementData+0xa6 onecoreuap\windows\core\text\fontcache\logic\elementtasklist.cpp @ 163]
09 0311f070 6a60bc46 DWrite!IBaseCacheContextImpl::GetElementData+0xba onecoreuap\windows\core\text\fontcache\logic\ibasecachecontext.cpp @ 23]
0a 0311f0a0 6a5cea6e DWrite!FontCollection::FontCollection+0x5a onecoreuap\windows\core\text\font\fontcollection.cpp @ 24]
0b (Inline) -------- DWrite!DWriteFontCollection::{ctor}+0x10 onecoreuap\windows\core\text\apiimpl\dwritefontcollection.cpp @ 24]
0c 0311f100 6a5d08fc DWrite!ComObject<DWriteFontCollection,DeleteOnZeroReference>::ComObject<DWriteFontCollection,DeleteOnZeroReference><DWriteFactory * const,FontCollectionElementKey *>+0x2a onecoreuap\windows\core\text\common\comhelpers.h @ 75]
0d 0311f130 65774878 DWrite!DWriteFactory::CreateCustomFontCollection+0x8c onecoreuap\windows\core\text\apiimpl\dwritefactory.cpp @ 520]
0e 0311f1c0 657746f0 CoreGraphics!__DWriteUpdateUserCreatedFontCollection<std::_Mem_fn<void (__cdecl DWriteFontCollectionLoader::*)(__CFArray const *,__CFArray const * *)> >+0x184 d:\build\agent9\_work\2\s\frameworks\coregraphics\dwritewrapper.mm @ 831]
0f 0311f238 66467b66 CoreGraphics!_DWriteRegisterFontsWithDatas+0x1c d:\build\agent9\_work\2\s\frameworks\coregraphics\dwritewrapper.mm @ 843]
*** WARNING: Unable to verify checksum for CoreText.dll
10 0311f248 66467a72 CoreText!__CTFontManagerUpdateWithFonts<long (__cdecl*)(__CFArray const *,__CFArray const * *)>+0xb2 d:\build\agent9\_work\2\s\frameworks\coretext\ctfontmanager.mm @ 67]
11 0311f290 664679ee CoreText!CTFontManagerRegisterFontsForURLs+0x1a d:\build\agent9\_work\2\s\frameworks\coretext\ctfontmanager.mm @ 119]
12 0311f2a0 66467994 CoreText!__CTFontManagerUpdateWithFont<bool (__cdecl*)(__CFArray const *,unsigned int,__CFArray const * *)>+0x56 d:\build\agent9\_work\2\s\frameworks\coretext\ctfontmanager.mm @ 45]
13 0311f2e8 0030f23c CoreText!CTFontManagerRegisterFontsForURL+0x18 d:\build\agent9\_work\2\s\frameworks\coretext\ctfontmanager.mm @ 103]
*** WARNING: Unable to verify checksum for WOCCatalog.exe
14 0311f2f8 0030ee98 WOCCatalog!-[TextDrawer testCTFontManagerRegisterFontsForURL:]+0xa4 d:\build\agent9\_work\2\s\unzippedsdk\samples\woccatalog\woccatalog\textdisplayviewcontroller.m @ 483]
15 0311f368 63297522 WOCCatalog!-[TextDrawer drawRect:]+0xac d:\build\agent9\_work\2\s\unzippedsdk\samples\woccatalog\woccatalog\textdisplayviewcontroller.m @ 414]
*** WARNING: Unable to verify checksum for UIKit.dll
16 0311f388 655f5f86 UIKit!-[UIView drawLayer:inContext:]+0x32 d:\build\agent9\_work\2\s\frameworks\uikit\uiview.mm @ 2233]
*** WARNING: Unable to verify checksum for QuartzCore.dll
17 0311f398 655f9230 QuartzCore!-[CALayer display]+0x436 d:\build\agent9\_work\2\s\frameworks\quartzcore\calayer.mm @ 540]
18 0311f3d0 655fa77e QuartzCore!-[CALayer _getDisplayTexture]+0x20 d:\build\agent9\_work\2\s\frameworks\quartzcore\calayer.mm @ 1821]
19 0311f3e8 655fa6fe QuartzCore!DoDisplayList+0x62 d:\build\agent9\_work\2\s\frameworks\quartzcore\calayer.mm @ 212]
1a 0311f430 698c2f3a QuartzCore!__26-[CALayer _displayChanged]_block_invoke+0x4e d:\build\agent9\_work\2\s\frameworks\quartzcore\calayer.mm @ 2236]
*** WARNING: Unable to verify checksum for libdispatch.dll
1b 0311f440 698c3cf4 libdispatch!_dispatch_call_block_and_release+0xe z:\winobjc\deps\3rdparty\libdispatch\src\queue.c @ 125]
1c 0311f450 698c3ba6 libdispatch!_dispatch_queue_drain+0x114 z:\winobjc\deps\3rdparty\libdispatch\src\queue.c @ 1548]
1d 0311f490 698c77d4 libdispatch!_dispatch_queue_serial_drain_till_empty+0x2a z:\winobjc\deps\3rdparty\libdispatch\src\queue.c @ 1407]
1e 0311f4b0 647ad2bc libdispatch!_dispatch_manual_queue_drain+0x1c z:\winobjc\deps\3rdparty\libdispatch\src\interop.c @ 108]
*** WARNING: Unable to verify checksum for Foundation.dll
1f 0311f4c0 6480a030 Foundation!-[NSRunLoop(Internal) _processMainRunLoop:]+0xac d:\build\agent9\_work\2\s\frameworks\foundation\nsrunloop.mm @ 536]
20 0311f4e0 6480abb8 Foundation!_ProcessMainRunLoop+0x50 d:\build\agent9\_work\2\s\frameworks\foundation\maindispatcher.mm @ 71]
21 0311f500 6baf3662 Foundation! ?? :: ?? ::Invoke+0xc c:\program files (x86)\windows kits\10\include\10.0.10586.0\winrt\wrl\event.h @ 240]
22 0311f508 6baf4b42 Windows_UI!Windows::UI::Core::CDispatcher::ProcessInvokeItem+0x726 onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 1175]
23 0311f588 6baf2d38 Windows_UI!Windows::UI::Core::CDispatcher::ProcessMessage+0x19a onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 331]
24 0311f5e8 6baf4960 Windows_UI!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal+0x74 onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 1784]
25 0311f678 5d235bac Windows_UI!Windows::UI::Core::CDispatcher::ProcessEvents+0x60 onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 562]
26 0311f6e0 5d235b60 Windows_UI_Xaml!CJupiterWindow::RunCoreWindowMessageLoop+0x40 onecoreuap\windows\dxaml\xcp\dxaml\lib\jupiterwindow.cpp @ 1181]
27 0311f700 5d235a30 Windows_UI_Xaml!CJupiterControl::RunMessageLoop+0x20 onecoreuap\windows\dxaml\xcp\dxaml\lib\jupitercontrol.cpp @ 876]
28 0311f730 75eda9ce Windows_UI_Xaml!DirectUI::DXamlCore::RunMessageLoop+0x20 onecoreuap\windows\dxaml\xcp\dxaml\lib\dxamlcore.cpp @ 2000]
29 0311f760 75eecd0e twinapi_appcore!Windows::ApplicationModel::Core::CoreApplicationView::Run+0x2e onecoreuap\shell\coreapplication\application\lib\coreapplicationview.cpp @ 1679]
2a 0311f770 77907be0 twinapi_appcore!<lambda_98eebfccee4f02b8eb3df4102b567a22>::operator()+0xb6 onecoreuap\shell\coreapplication\application\lib\coreapplicationview.cpp @ 1124]
2b 0311f7b0 77e809e2 shcore!_WrapperThreadProc+0x1b0 onecoreuap\shell\shcore\libs\thread\thread.cpp @ 321]
2c 0311f840 00000000 ntdll!RtlUserThreadStart+0x22 minkernel\ntdll\rtlstrt.c @ 996]
0:004> .frame 1

**Comment by jaredhms** [comment]
This was on the following WOCCatalog build: github\develop\Release\20161201.2\drop\apps\arm\WOCCatalog_1.0.0.0_ARM_Test

I grabbed a full heap memory dump; let me know if you want to take a look at it.

**Comment by DHowett-MSFT** [comment]
@aballway will definitely have more insight here.

**Comment by aballway** [comment]
I'm unable to repro on current develop.  This was likely fixed in #1504 when @ms-jihua refactored the font registration code.

**Comment by rajsesh-msft** [comment]
closing per comment from @aballway
