### ISSUE TITLE
CoreAnimationTests failing on develop daily build - 20161209.1

### ISSUE THREAD

**Issue by ashvarma** [Microsoft/WinObjC#1526]
Debug build: 
Desktop: CoreAnimationTests::CALayerAppearance_OpacityChanged
Phone: CoreAnimationTests::CALayerAppearance_OpacityChanged

Release build: 
Desktop: CoreAnimationTests::CALayerAppearance_BackgroundColorChanged and some cleanup tests
Phone: -

**Comment by oliversa-msft** [comment]
Commit 537410eb2c1a10c7 pushed to develop.
