### ISSUE TITLE
Exception when trying to create instance of WGIBitmapTypedValue

### ISSUE THREAD

**Issue by jboich** [Microsoft/WinObjC#1531]
Hello.

The following code snippets cause exception

```
WSFPhotoOrientation photoOrientation = WSFPhotoOrientationRotate90;
WGIBitmapTypedValue* bitmapTypedValue = [WGIBitmapTypedValue make:[NSString stringWithFormat:@"%d", photoOrientation] type:WFPropertyTypeInt32];
```

```
WSFPhotoOrientation photoOrientation = WSFPhotoOrientationRotate90;
WGIBitmapTypedValue* bitmapTypedValue = [WGIBitmapTypedValue make:[NSNumber numberWithInt:photoOrientation ] type:WFPropertyTypeInt32];
```

What is the proper way to create instance of **WGIBitmapTypedValue**  using method
`+ (WGIBitmapTypedValue*)make:(RTObject*)value type:(WFPropertyType)type`  ?

Also, I'm not sure if the following will work
```
 WGIBitmapPropertySet* properties = [WGIBitmapPropertySet make];
[properties setObject:bitmapTypedValue forKey:@"System.Photo.Orientation"];
```

The code I wrote above is required to port Camera Capture from this example: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CameraAdvancedCapture

Thank you in advance.
Kind regards,
Julia

**Comment by mukhole** [comment]
@jboich ,
The first argument to 'make' is an RTObject, https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.imaging.bitmaptypedvalue.bitmaptypedvalue.aspx will tell you that this is System.Object or a PropertyValue.
The way you create an RTObject from value types is by creating an instance of WFPropertyValue.
So the below code is what you need:
#import <UWP/WindowsFoundation.h>
#import <UWP/WindowsGraphicsImaging.h>
RTObject* rtObj = [WFPropertyValue createInt32:WSFPhotoOrientationRotate90];
WGIBitmapTypedValue* bitmapTypedValue = [WGIBitmapTypedValue make:rtObj type:WFPropertyTypeInt32];

Let me know if you still have any problem using it.

**Comment by jboich** [comment]
Hello, @mukhole . This works. Thank you!

**Comment by rajsesh-msft** [comment]
Closing since this appears to be resolved.
