### ISSUE TITLE
Xib2Nib: Support the new XCode8 XIB format so that controls layout placement is preserved (compatibility support only)

### ISSUE THREAD

**Issue by ArnOmsft** [Microsoft/WinObjC#1536]
If you upgrade to XCode 8 and open a storyboard/XIB, you will be formed to choose an initial design view. This forced dialog will change the underlying markup to your XIB or storyboard. As a result <rect> attributes may be changed to <frame frameInset> which is not handled correctly by Xib2Nib. We should see if we can handle this change in the format without much effort.

Repro steps:
- Install XCode8 on OSX
- Open up XAMLCatalog.xcodeproj under XCode
- Open up the XAMLCatalog.storyboard file
- You will be asked to choose an initial design view (iPhone SE, iPhone 6, etc.)
- Once you make a selection, XAMLCatalog.storyboard markup will be changed and the Xib2Nib conversion at build time will not render the controls correctly

**Comment by oliversa-msft** [comment]
This seems like a bug in XCode8.0, just found out that the <frame frameInset> tag is no longer present when I use XCode8.2.1. This means Xib2Nib will parse the <rect> tag correctly in both XIB and storyboard files. I believe it might have been fixed in XCode8.1 as part of Apple bug  28221021.

**Comment by oliversa-msft** [comment]
Arnaud, this is now a doc bug to alert developers to upgrade to the latest XCode.

**Comment by ArnOmsft** [comment]
Thanks! I updated the wiki page about using VSImporter [here](https://github.com/Microsoft/WinObjC/wiki/Using-vsimporter) to mention this and recommend to upgrade to the latest version of Xcode.
