### ISSUE TITLE
How to implement Microsoft Ads?

### ISSUE THREAD

**Issue by shenzyapp** [Microsoft/WinObjC#1538]
Hello
I have successfully converted my iOS-cocos2d game to UWP, but  I don't know how to implement Microsoft Ads? Both the WinObjC team and the MS UWP team told me that they didn't have any solution.
My converted project is repo-ed here: https://t.co/tpDyGw72o6
Can somebody help me to solve this issue?
Thank you.
Shenzyapp

**Comment by antoine-haas** [comment]
Hello @shenzyapp,
WinObjC does not support ads yet via Objective-C projections. If you really need ads, you could try to add C++ files to your project and create an ad control in them that you would cast as an IInspectable* and then repass it to Objective-C as an RTObject*, but that is far from trivial and I cannot guarantee it would work.

**Comment by shenzyapp** [comment]
Hi @antoine-haas 
Many thanks to your info. Do you know if WinObjC will enable ads feature?
Thank you.

**Comment by Romascu** [comment]
Any news on this? Thanks.

**Comment by shenzyapp** [comment]
Hi
Not at all.

@iPhone

**Comment by weswmsft** [comment]
See https://github.com/Microsoft/WinObjC/issues/2126. This is coming very soon.
