### ISSUE TITLE
NSFileCreationDate not declared

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#154]
NSFileCreationDate (property for dictionary return of  NSFileManager attributesOfItemAtPath) not found

**Comment by codinggooner** [comment]
I have the same queation, SOS!

**Comment by rajsesh-msft** [comment]
This is coming soon.

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by vertostudio3d** [comment]
WE GET IT!  a fix is available!  : p

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by jasssonpet** [comment]
One more time to be sure :)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by vertostudio3d** [comment]
<img width="143" alt="screen shot 2015-11-18 at 11 14 40 am" src="https://cloud.githubusercontent.com/assets/15823269/11251362/c628c5f0-8de5-11e5-9580-15ab139cef67.png">

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in&nbsp;0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
The tool we use to communicate with GitHub started malfunctioning which resulted in multiple updates, I apologize for the inconvenience.
