### ISSUE TITLE
CGGradient should use CPPBased implementation 

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#1541]

**Comment by rajsesh-msft** [comment]
@msft-Jeyaram since we are implementing CGGradient now, why not do it right?  why separate this out?

**Comment by rajsesh-msft** [comment]
Synced up offline with @msft-Jeyaram, don't want to block the implementation of gradient.

**Comment by msft-Jeyaram** [comment]
as per offline, I'm planning to do it this iteration but would like it keep it as separate PR for now (since it's independent)
