### ISSUE TITLE
NSURL * does not toll-free-bridge properly to CFURLRef

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#155]
The following code compiles (as it should) in XCode

NSURL *imageFileURL = [NSURL fileURLWithPath:fileToAdd];
CGImageSourceRef imageSource = CGImageSourceCreateWithURL((CFURLRef)imageFileURL, NULL);

but not with clang/cl2

**Comment by rajsesh-msft** [comment]
This should all work as expected, as NSURL has been properly bridged for a while now. Please let us know if you run into issues.
