### ISSUE TITLE
WoCCatalog [ARM|Release] Status text in Foundation Test -> URL Session overlaps and is unreadable

### ISSUE THREAD

**Issue by bebauer-msft** [Microsoft/WinObjC#1559]
WoCCatalog [ARM|Release] 
Phone: Lumia 950 device (14995 build)
Master commit: 4804ed9

Build/run WOCCatalog in Release.
Tap "Foundation Tests -> URL Session"
Tap "Data" button.

Expected:
Status text appears at bottom of the screen and is easily read.

Actual:
Status text overlaps on three lines making it impossible to read.
![wp_ss_20161215_0002](https://cloud.githubusercontent.com/assets/24572685/21247346/a27a2ed0-c2e3-11e6-9d9e-081bf949e172.png)

**Comment by rajsesh-msft** [comment]
#1557, this test wont pass fit and finish issues.
