### ISSUE TITLE
WoCCatalog [ARM|Release] Buttons in CoreMotion are sporadically not properly displaying text 

### ISSUE THREAD

**Issue by bebauer-msft** [Microsoft/WinObjC#1560]
Phone: Lumia 950 device (14995 build)
Master commit: 4804ed9

Build/run WOCCatalog in Release.
Tap "CoreMotion"

Expected:
Two buttons should appear next to Accelerometer, Gyrometer, and Magnetometer titles with the text "with Handler" and "without Handler"

Actual:
The buttons appear, however they contain no text. Behavior is sporadic with app launch, as there have been a few instances where the text has appeared.

![wp_ss_20161215_0003](https://cloud.githubusercontent.com/assets/24572685/21247503/acf2d028-c2e4-11e6-816f-c4106bfb7986.png)

**Comment by tadam-msft** [comment]
This issue no longer reproes, tested with 20170228.1 Master build.
