### ISSUE TITLE
Typing mid-string in a UIKit/XAML text field forces cursor to end of string

### ISSUE THREAD

**Issue by bebauer-msft** [Microsoft/WinObjC#1561]
_Edited by @DHowett-MSFT._

There may be a regression in UITextField/UITextView's caret handling. It appears that moving the caret mid-string and typing a character (or deleting a character) causes the caret to move to the end of the text field.

This is reproduceable in CTCatalog, CGCatalog, WOCCatalog, and any application with an unadorned text field.

**Comment by rajsesh-msft** [comment]
#1577

**Comment by DHowett-MSFT** [comment]
Reopening as per discussion with @rajsesh-msft; issue has been repurposed to track UI bug.

**Comment by rajsesh-msft** [comment]
Thanks @DHowett-MSFT

**Comment by edvv** [comment]
@bebauer-msft Please also see: https://github.com/Microsoft/WinObjC/issues/1609 using release 0.2.161130. You stated: "There may be a regression in []UITextView's caret handling". If editing of a UITextView instance is in the works then that would be very timely.

**Comment by yiyang-msft** [comment]
fixed.
