### ISSUE TITLE
WoCCatalog [ARM|Release] Tapping outside of the URL text box in Foundation Tests - URL Session does not dismiss the keyboard

### ISSUE THREAD

**Issue by bebauer-msft** [Microsoft/WinObjC#1562]
Phone: Lumia 950 device (14995 build)
Master commit: 4804ed9

Build/run WOCCatalog in Release.
Tap "Foundation Test -> URL Session"
Tap anywhere in the URL text box. 
Type a few characters.
Tap on the title bar, "Blocks" slider, on any item in the status list, or around the action buttons.

Expected:
Keyboard is dismissed

Actual:
Keyboard remains up.

Note: 
There are a few places around the screen that can be tapped to dismiss the keyboard, such as the action buttons.

**Comment by rajsesh-msft** [comment]
Per #1577
