### ISSUE TITLE
CGBitmapImageBacking::GetRenderTarget is crashing

### ISSUE THREAD

**Issue by antoine-haas** [Microsoft/WinObjC#1563]
The CGBitmapImageBacking::GetRenderTarget method is crashing with the following call stack:

00 4fffdfc8 70214495 KERNELBASE!RaiseException+0x62 [d:\rs1\minkernel\kernelbase\xcpt.c @ 904] 
01 4fffe00c 6f10702c VCRUNTIME140_APP!_CxxThrowException+0x65 [f:\dd\vctools\crt\vcruntime\src\eh\throw.cpp @ 131] 
02 4ffff4dc 6f1070e4 CoreGraphics!wil::details::ReportFailure+0xdc [d:\build\agent9\_work\5\s\frameworks\include/wil/result.h @ 3132] 
03 4ffff50c 6f126ff0 CoreGraphics!wil::details::ReportFailure_Hr+0x24 [d:\build\agent9\_work\5\s\frameworks\include/wil/result.h @ 3151] 
04 4ffff534 6f1253ff CoreGraphics!wil::details::in1diag5::_Throw_Hr+0x20 [d:\build\agent9\_work\5\s\frameworks\include/wil/result.h @ 4355] 
05 4ffff59c 6f12faab CoreGraphics!CGBitmapImageBacking::GetRenderTarget+0x12f [d:\build\agent9\_work\5\s\frameworks\coregraphics\cgbitmapimage.mm @ 462] 
06 4ffff690 6f10c666 CoreGraphics!CGContextCairo::CGContextDrawGlyphRun+0x4b [d:\build\agent9\_work\5\s\frameworks\coregraphics\cgcontextcairo.mm @ 1840] 
07 4ffff69c 6df4f0a3 CoreGraphics!CGContextDrawGlyphRun+0x16 [d:\build\agent9\_work\5\s\frameworks\coregraphics\cgcontext.mm @ 1244] 
08 4ffff6d4 6df4bf18 CoreText!CTRunDraw+0xe3 [d:\build\agent9\_work\5\s\frameworks\coretext\ctrun.mm @ 296] 
09 4ffff700 0068c31d CoreText!CTLineDraw+0xa8 [d:\build\agent9\_work\5\s\frameworks\coretext\ctline.mm @ 228] 
WARNING: Stack unwind information not available. Following frames may be wrong.
0a 4ffff73c 0068c7c8 djayPro+0x29c31d
0b 4ffff7a0 0067c64d djayPro+0x29c7c8
0c 4ffff7cc 6d39259d djayPro+0x28c64d
0d 4ffff7dc 6d3932f9 libdispatch!_dispatch_call_block_and_release+0xd [z:\winobjc\deps\3rdparty\libdispatch\src\queue.c @ 125] 
0e 4ffff810 6d393ebe libdispatch!_dispatch_queue_drain+0xe9 [z:\winobjc\deps\3rdparty\libdispatch\src\queue.c @ 1548] 
0f 4ffff82c 6d393ae7 libdispatch!_dispatch_queue_invoke+0x2e [z:\winobjc\deps\3rdparty\libdispatch\src\queue.c @ 1421] 
10 4ffff874 6d391453 libdispatch!_dispatch_worker_thread2+0xa7 [z:\winobjc\deps\3rdparty\libdispatch\src\queue.c @ 1643] 
11 (Inline) -------- libdispatch!_native_work_callback+0x4e [z:\winobjc\deps\3rdparty\libdispatch\platform\windows\pthread_workqueue_winrt.cpp @ 325] 
12 4ffff88c 6d3915bf libdispatch!<lambda_2694e763ed48b22494e2a182ae0c76de>::operator()+0x53 [z:\winobjc\deps\3rdparty\libdispatch\platform\windows\pthread_workqueue_winrt.cpp @ 354] 
13 4ffff898 687b4c6f libdispatch!Microsoft::WRL::Details::InvokeHelper<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<2>,ABI::Windows::System::Threading::IWorkItemHandler,Microsoft::WRL::FtmBase,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil>,<lambda_2694e763ed48b22494e2a182ae0c76de>,1>::Invoke+0xf [c:\program files (x86)\windows kits\10\include\10.0.10586.0\winrt\wrl\event.h @ 257] 
14 4ffff8c4 687b46ea threadpoolwinrt!Windows::System::Threading::CThreadPoolWorkItem::CommonWorkCallback+0xaf [d:\rs1\onecoreuap\base\threadpool\winrt\impl\threadpool.cpp @ 467] 
15 4ffff8f4 76fb75c3 threadpoolwinrt!Windows::System::Threading::CThreadPoolWorkItem::BatchedCallback+0xaa [d:\rs1\onecoreuap\base\threadpool\winrt\impl\threadpool.cpp @ 578] 
16 4ffff9e4 76fb64d6 ntdll!TppWorkpExecuteCallback+0x153 [d:\rs1\minkernel\threadpool\ntdll\work.c @ 671] 
17 4ffffb80 752762c4 ntdll!TppWorkerThread+0x396 [d:\rs1\minkernel\threadpool\ntdll\worker.c @ 1083] 
18 4ffffb94 76fe0719 kernel32!BaseThreadInitThunk+0x24 [d:\rs1\base\win32\client\thread.c @ 64] 
19 4ffffbdc 76fe06e4 ntdll!__RtlUserThreadStart+0x2f [d:\rs1\minkernel\ntdll\rtlstrt.c @ 997] 
1a 4ffffbec 00000000 ntdll!_RtlUserThreadStart+0x1b [d:\rs1\minkernel\ntdll\rtlstrt.c @ 914] 
windbg> .open -a 6f12faab

**Comment by rajsesh-msft** [comment]
Discussed a couple of ideas with @DHowett-MSFT, who will look at this.

**Comment by rajsesh-msft** [comment]
Found some internal crash dump that shows the HR to be: 
D2DERR_NO_HARDWARE_DEVICE 0x8899000B.

**Comment by triplef** [comment]
Thanks for tracking this down @rajsesh-msft! Is this something we can catch on our end or will this require a fix in the SDK?

**Comment by rajsesh-msft** [comment]
@triplef very likely need a fix in the SDK, although i still don't have the root cause on why this would happen.

**Comment by triplef** [comment]
@rajsesh-msft Would a full dump still help or does the internal dump you found provide all info we can get?

**Comment by rajsesh-msft** [comment]
@triplef, yes, it would still help to get the full dump to recover what we can from the D2D state.

**Comment by rajsesh-msft** [comment]
This doesn't repro anymore with the CGD2D merge.
