### ISSUE TITLE
WoCCatalog [ARM|Release] UI does not update while downloading 50mb file using "Download with Blocks" in URL Session

### ISSUE THREAD

**Issue by bebauer-msft** [Microsoft/WinObjC#1564]
Phone: Lumia 950 device (14995 build)
Master commit: 4804ed9

Build/run WOCCatalog in Release.
Tap "Foundation Test -> URL Session"
Change URL to "http://download.thinkbroadband.com/50MB.zip"
Enable "Blocks" slider
Tap "Download"
Observe new status line created. 

Expected:
Status line and percentage completed update.

Actual:
Status line never updates, remains at 0%, and never shows "Completed" when download finishes.

Note: 
Functionality works as expected with "Blocks" disabled.

**Comment by rajsesh-msft** [comment]
Closing per #1577
