### ISSUE TITLE
WoCCatalog [ARM|Release] Shadow page is scaling the 6 elements incorrectly.

### ISSUE THREAD

**Issue by bebauer-msft** [Microsoft/WinObjC#1567]
Phone: Lumia 950 device (14995 build)
Master commit: 4804ed9

Build/run WOCCatalog in Release.
Tap "Shadow"
Observe 6 shapes

Expected:
All 6 shapes appear in the full view

Actual:
In portrait mode the circle and oval are cut off on the right

![wp_ss_20161215_0006](https://cloud.githubusercontent.com/assets/24572685/21248403/bbfee154-c2eb-11e6-92bb-8a69b2692fe1.png)

**Comment by rajsesh-msft** [comment]
@bebauer-msft is this a regression?

**Comment by bebauer-msft** [comment]
@rajsesh-msft Yes. Things also get really interesting when you rotate the device. Scaling is off and arrow images move around.

**Comment by bebauer-msft** [comment]
@rajsesh-msft Yes this is a regression. It used to all fit on screen upon initially opening the page.

**Comment by ArnOmsft** [comment]
@bebauer-msft, can you confirm with which build did the regression appear?
Thanks.

**Comment by tadam-msft** [comment]
These elements can be scrolled into view.

**Comment by DHowett-MSFT** [comment]
@tadam-msft I've seen this on a Surface Book too, and in a different application (CGCatalog). I believe there is something wrong with our layer scaling code.

In light of that, it is worth investigating further.

**Comment by jaredhms** [comment]
Can you share repro steps, @DHowett-MSFT.  I don't _think_ the WoCCatalog sample was supposed to be scaling.

**Comment by DHowett-MSFT** [comment]
@jaredhms 

It looks like the issue in this bug is different from what I'm seeing.

This bug is simply that WOCCatalog's shadow page is hardcoded to render to a width of 600 points.

The bug I am seeing is that a view with a `drawRect:` displayed on a non-1.0-scale device is rendering at 1.5x width but 1.0x height, but only above certain widths. (???)

**Comment by DHowett-MSFT** [comment]
I wrote my issue up in #2084.
