### ISSUE TITLE
Canabalt [ARM|Release] Start screen buttons are missing text

### ISSUE THREAD

**Issue by bebauer-msft** [Microsoft/WinObjC#1569]
Phone: Lumia 950 device (14995 build)
Master commit: 4804ed9

Build/run Canabalt in Release.
Start game
Observe start screen

Expected:
Start and Help buttons are displayed

Actual:
Buttons are empty

![wp_ss_20161215_0007](https://cloud.githubusercontent.com/assets/24572685/21253788/facad17a-c315-11e6-8ed2-6e61f77122b8.png)

**Comment by aballway** [comment]
This is fixed as of 3de7a98 on develop

**Comment by rajsesh-msft** [comment]
Closing since this is fixed in develop.
