### ISSUE TITLE
Canabalt, Climbers [x86|Debug, Release] Minimizing and reopening the app disables interaction

### ISSUE THREAD

**Issue by nicholasgerard-msft** [Microsoft/WinObjC#1571]
x86 running 14975
https://github.com/Microsoft/WinObjC/commit/4804ed9bf1b16225116ff7bb06477ce3c8c300d7

Run Canabalt or Climbers, minimize the game window and reopen it. Graphics will be frozen in the game window but music continues. Maximizing the window restarts graphics.

**Comment by rajsesh-msft** [comment]
@nicholasgerard-msft do you have any regression info?

**Comment by nicholasgerard-msft** [comment]
I've never seen this before (I've tried the same sequence on previous builds) and didn't find any bugs matching it.

________________________________

**Comment by ashvarma** [comment]
I tried this on several previous releases and the behavior is the same. The sound pauses as does the graphics and activating/maximizing the app doesn't resume the app - it basically stays frozen (the graphics doesn't "restart"). 
Here are the builds I tried - 
20161213.2
20161130.1
20160908.1

**Comment by rajsesh-msft** [comment]
We broke this once before.  See #1026.  At this point, at least some apps worked.

**Comment by rajsesh-msft** [comment]
Fixed with #1640.
