### ISSUE TITLE
WOCCatalog [x86|Debug] Controls: Popovers cause app to crash

### ISSUE THREAD

**Issue by nicholasgerard-msft** [Microsoft/WinObjC#1574]
x86 running 14975
https://github.com/Microsoft/WinObjC/commit/4804ed9bf1b16225116ff7bb06477ce3c8c300d7

Launch app. Navigate to Display Mode and enable Tablet Mode. Navigate to Controls. Launch a popover via the "Popover (left arrow direction)" button. Close it by hitting the done button. App will crash.

**Comment by ehren** [comment]
This is fixed by #1511 (aside: the dismissViewControllerAnimated: implementation was always improper with popovers - but only resulted in a crash after some related memory leaks were fixed - requiring the new pull).

**Comment by ashvarma** [comment]
I tried this with both release and debug versions of the app - with build 20161213.1 - and I'm unable to repro this. Will follow up with Nick offline

**Comment by ArnOmsft** [comment]
I can repro with Debug\20161213.1 as well.

**Comment by ArnOmsft** [comment]
this will be addressed by #1601.

**Comment by jaredhms** [comment]
Fixed by #1601.
