### ISSUE TITLE
WoCCatalog [ARM|Release] Alert sound and System sound buttons no longer triggers audio cue

### ISSUE THREAD

**Issue by bebauer-msft** [Microsoft/WinObjC#1575]
Phone: Lumia 950 device (14393 build)
Master commit: 4804ed9

Build/run WOCCatalog in Release.
Make sure "Ringer & Notifications" volume is up on device.
Make sure "Media + Apps" volume is up on device.
Tap "AudioToolbox"
Tap "Audio Sound"
Tap "System Sound"

Expected:
Audio Sound produces a vibrate and a tone
System sound produces a tone

Actual:
Audio Sound produces a vibrate and NO sound
System sound produces nothing.

_This is a regression._

**Comment by rajsesh-msft** [comment]
@bbowman is this related to 2a0de15ff2272153a10c6c903305e29df6c0ee27?

**Comment by bbowman** [comment]
Doubtful. This path (WinObjC/Frameworks/AudioToolbox/SystemSound.mm) does the following:

```
            WMPMediaPlayer* mediaPlayer = [WMPBackgroundMediaPlayer current];
            
            if (mediaPlayer.currentState == WMPMediaPlayerStatePlaying) {
                [mediaPlayer pause];

                // This runs the callback function, if any, for the audio file that was playing.
                _handleMediaEndedEvent();
            }

            [mediaPlayer setAutoPlay:false];
            [mediaPlayer setIsLoopingEnabled:false];

            if (vibration) {
                vibrateDevice();
            }

            _latestSystemSoundID = inSystemSoundID;
            [mediaPlayer setUriSource:[systemSoundObject mediaUri]];
            [mediaPlayer play];
```

Which suggests the issue may be with projections or our Uri handling (which is supposed to be pointing to a wav file off of the Bundle:

```
    // Currently using the example wav file located at deps/3rdparty/openal-soft-winphone/examples.
    // The file duration 1 min 15 secs, which is a bit on the longer side.
    CFURLRef url = (__bridge CFURLRef)[[NSBundle mainBundle] URLForResource:@"test" withExtension:@"wav"];
```

**Comment by bebauer-msft** [comment]
After rebooting the device I am unable to get this to repro. Must have been an issue with the device. Closing for now.
