### ISSUE TITLE
WoCCatalog [ARM|Release] Tapping "CoreMotion" multiple times pushes the "CoreMotion" page onto the navigation stack multiple times

### ISSUE THREAD

**Issue by bebauer-msft** [Microsoft/WinObjC#1576]
Phone: Lumia 950 device (14393 build)
Master commit: 4804ed9

Build/run WOCCatalog in Release.
Tap "CoreMotion" 5 quickly times in a row 
Tap the back arrow in the upper left

Expected:
App navigates back to the main menu

Actual:
App navigates to the same CoreMotion page the same number of times the menu item was pressed.

_This is a regression_

**Comment by rajsesh-msft** [comment]
This should happen with any page, there is nothing specific to coremotion page w.r.t navigation.

**Comment by yiyang-msft** [comment]
checked in the revert which causes this issue.
