### ISSUE TITLE
WoCCatalog [ARM|Release] Display Mode state is incorrect when returning to page

### ISSUE THREAD

**Issue by bebauer-msft** [Microsoft/WinObjC#1578]
Phone: Lumia 950 device (14393 build)
Master commit: 4804ed9

Build/run WOCCatalog in Release.
Tap "DisplayMode"
Change Preset modes to "Tablet768x1024"
Navigate back to menu
Tap "DisplayMode"
Observe selected value for Present Modes

Expected:
Preset mode has "Tablet768x1024" selected

Actual:
Present mode has "Native" selected.

_This is a regression_

**Comment by yiyang-msft** [comment]
checked in the revert which causes this issue.
