### ISSUE TITLE
file ObjCUWP_Windows_ApplicationModel_Contacts.lib missing from git

### ISSUE THREAD

**Issue by spalda2** [Microsoft/WinObjC#1587]
Error	LNK1104	cannot open file 'ObjCUWP_Windows_ApplicationModel_Contacts.lib'	AddressBook.UnitTests	C:\workspace\Windows\winobjc\build\Tests\UnitTests\AddressBook\LINK	1

**Comment by rajsesh-msft** [comment]
We have seen this issue intermittently, building (not rebuilding) should fix this.

**Comment by mukhole** [comment]
@spalda2 
This namespace is part of ObjCUWP_Windows_RandomStuff.lib, and the linker should get this file automatically when you include WIndowsApplicaitonModelContacts.h.
Are you explicitly telling the linker to link against ObjCUWP_Windows_ApplciationModel_Contacts.lib?

**Comment by pradipd** [comment]
Please reopen if mukhole suggestion to use WIndowsApplicationModelContacts.h does not work.
