### ISSUE TITLE
Wrong generation of manifest file

### ISSUE THREAD

**Issue by spalda2** [Microsoft/WinObjC#1588]
Error	APPX0501	Validation error. error C00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 10, Column 57, Reason: 'islandwood' violates pattern constraint of ....

This happens after building freshly imported project and building it.

**Comment by edvv** [comment]
@spalda2 Probably, put CN= before the word islandwood in the manifest file; or update winobjc on your computer.

Sincerely,

Ed

**Comment by spalda2** [comment]
I know and i do it every time the file is re-generated..very annoying indeed and clearly a bug in the importing tool.

**Comment by memontic-ms** [comment]
@spalda2 This was fixed in the vsimporter tool in commit [212dba2](https://github.com/Microsoft/WinObjC/commit/212dba27bce015da0f31fe490bb8a7b0d7e91032) and has been in the pre-release since version [0.2.161107](https://github.com/Microsoft/WinObjC/releases/tag/0.2.161107).

**Comment by spalda2** [comment]
ok...i see that in that commit....I'll re-import the project then....
