### ISSUE TITLE
Missing support for UILayoutSupport and layout guides

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#159]
error : cannot find protocol declaration for 'UILayoutSupport'
error : property 'topLayoutGuide' not found on object of type 'ObjectPropertiesVisibilityViewController *'

**Comment by davelamb** [comment]
Fixed with 93a7a6a306ad262c77c524c87cc166f4551c2c22 with the caveat that the length property isn't implemented.
