### ISSUE TITLE
Patterns should be anchored to the bottom (0,0) vs top (0,0) origin

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#1591]

**Comment by DHowett-MSFT** [comment]
This is still mentioned from CGContext by issue number.

@msft-Jeyaram can you please confirm this is fixed?

**Comment by msft-Jeyaram** [comment]
Yes this is fixed. hmmm but the rotation bug is still there.
The bug number needs to be updated. I'm doing that.
