### ISSUE TITLE
Import package parsing error on @import

### ISSUE THREAD

**Issue by kkdai** [Microsoft/WinObjC#16]
error case:
@import UIKit;

work case:
#import "UIKit/UIkit.h"

**Comment by jmsaunders-ms** [comment]
We don't compile with modules enabled at this time; we haven't yet looked into defining module maps for our frameworks.

Thankfully including frameworks the old-fashioned way will continue to work in both environments but I agree it's unfortunate.

I'll leave this open for now to see if a hero wants to try making them work.

**Comment by kkdai** [comment]
Is any way I could contribute about this? Does this must fixed in Clang compiler?

**Comment by jmsaunders-ms** [comment]
Our version of clang should support this and it should be possible to work on this externally.

That said, as far as I know nobody has ever tried it.
