### ISSUE TITLE
XAMLCatalog UITextField page font's overlap after panning

### ISSUE THREAD

**Issue by tadam-msft** [Microsoft/WinObjC#1600]
After panning on the UITextField page you see content from another entry overlapping the current entry.  Looks like some sort of recycling issue.  The issue also repros on the UISlider page.   Screenshot attached
![wp_ss_20161220_0001](https://cloud.githubusercontent.com/assets/21350288/21373053/855d9670-c6d0-11e6-9032-cdd8ff15bd89.png)

**Comment by yiyang-msft** [comment]
fixed.
