### ISSUE TITLE
UITableViewCell with UILabel drawing text improperly

### ISSUE THREAD

**Issue by aballway** [Microsoft/WinObjC#1602]
UITableViewCells using UILabels to draw text in CTCatalog are being drawn partially off screen.

**Comment by jaredhms** [comment]
@aballway please add more details/repro steps.

**Comment by aballway** [comment]
Sorry, I missed that comment.  This can be repro'd by running CTCatalog and opening the _Font Functions_ page.  Scrolling down, the text in the right column will be drawn partially off screen.

**Comment by yiyang-msft** [comment]
Fixed with 78259bd9686dc0e8a741ecec6a67f35505b3b7d9
