### ISSUE TITLE
Mutable collections in foundation must not allow nil objects to be inserted

### ISSUE THREAD

**Issue by sakrist** [Microsoft/WinObjC#1607]
I think it's critical issue.

Example of code:
```
NSMutableDictionary *dictionary = [NSMutableDictionary dictionary];
dictionary[@"key1"] = @"string";
dictionary[@"key2"] = nil;
dictionary[@"key3"] = NULL;
dictionary[@"key4"] = [NSNull null];
```

On iOS dictionary has only **key1** and **key4**, print in debug:
```(lldb) po dictionary
{
    key1 = string;
    key5 = "<null>";
}
```

logged on WinObjC:
```
{
    key2 = (null)
    key3 = (null)
    key1 = string
    key5 = <null>
}
```

---
But need to remember that on iOS version of Foundation, next line cause exception:
`[dictionary setObject:nil forKey:@"key5"];`

Exception log:
```
2016-12-22 11:59:42.631 Test[44238:4517602] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: key5)'
```

But on WinObjC, it will let you insert nil object.

**Comment by rajsesh-msft** [comment]
Note, this is also an issue in NSCFArray setObject, (possibly NSCFAttributedString).  Our assumption is that CF will handle null values.  The api contract is that foundation APIs have to throw in these circumstances.  Could we fix all these instances in one shot (see also #1435)
