### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by bryanbridges** [Microsoft/WinObjC#1610]
Severity	Code	Description	Project	File	Line	Suppression State
Warning		An unexpected error occurred trying to initialize Android Designer. Please verify the Android SDK path and the  Java Development Kit path on Tools->Options->Xamarin->Android Settings menu. Please see the logs for more details.		 	0

**Comment by rajsesh-msft** [comment]
@bryanbridges it is not clear when you get this error, or what you were trying to do.  Please provide more details.

**Comment by rajsesh-msft** [comment]
Closing the issue as this doesn't seem to be related to the bridge.  @bryanbridges if you have additional information, please do re-open, thanks!
