### ISSUE TITLE
MSB3245

### ISSUE THREAD

**Issue by bryanbridges** [Microsoft/WinObjC#1611]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB3245	Could not resolve this reference. Could not locate the assembly "UIKit". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	WOCCatalog (WOCCatalog\WOCCatalog)	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	1820

**Comment by rajsesh-msft** [comment]
Please see https://github.com/Microsoft/WinObjC/wiki/FAQ#unsupported16BitApplicationAndErrorMSB3073Anchor.
