### ISSUE TITLE
MSB3073

### ISSUE THREAD

**Issue by bryanbridges** [Microsoft/WinObjC#1612]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\Users\Var\Documents\WinObjC-0.2.161107\WinObjC-0.2.161107\msvc\..\bin\hmapmaker.exe" "C:\Users\Var\Documents\WinObjC-0.2.161107\WinObjC-0.2.161107\samples\WOCCatalog\WOCCatalog.vsimporter\WOCCatalog-WinStore10\Debug\WOCCatalog-project.txt" "C:\Users\Var\Documents\WinObjC-0.2.161107\WinObjC-0.2.161107\samples\WOCCatalog\WOCCatalog.vsimporter\WOCCatalog-WinStore10\Debug\WOCCatalog-project.hmap"" exited with code 216.	WOCCatalog (WOCCatalog\WOCCatalog)	C:\Users\Var\Documents\WinObjC-0.2.161107\WinObjC-0.2.161107\msvc\sbclang.targets	600

**Comment by rajsesh-msft** [comment]
Please see the FAQ on this, this is likely what is causing your other issues as well: https://github.com/Microsoft/WinObjC/wiki/FAQ#unsupported16BitApplicationAndErrorMSB3073Anchor
