### ISSUE TITLE
Starboard DNSServiceRegister in failure log

### ISSUE THREAD

**Issue by jboich** [Microsoft/WinObjC#1613]
Hi.
Some of the customers have a problem with our app: the app crashes soon after launch. Unfortunately, I ca not reproduce this issue.
The following failure log indicates that it looks like the problem is inside WINOBJC bridge:

Frame	Image	Function	Offset
0	Starboard 	DNSServiceRegister	 0x5CE	
1	Starboard 	EbrMkdir	0x1B	
2	CoreFoundation	NS_mkdir 	0xC	
3	CoreFoundation	CFCopyExtensionForAbstractType	0x2B	
4	CoreFoundation	CFPreferencesDomainExists	0x533	
5	CoreFoundation	CFPreferencesDomainExists	0x3CA	
6	CoreFoundation	CFPreferencesStandardDomain	0xC6	
7	CoreFoundation	CFApplicationPreferencesSetStandardSearchList	0x3B	
8	CoreFoundation	CFStandardApplicationPreferences	0x99	
9	CoreFoundation	CFPreferencesCopyAppValue	0xB	
10	Foundation	NSSwapHostShortToBig	0x195B5	
11	MyAppName	-[CustomViewController setup:]	0x82	
12	MyAppName	-[CustomViewController setup]	0x12	
13	MyAppName	-[ViewController	0xDF	
14	MyAppName	-[ViewController setup]	0x30E	
15	MyAppName	-[MainViewController viewDidAppear:]	0x99	
16	UIKIT	UIOrientationFromString	0x29998	
17	UIKIT	UIImageJPEGRepresentation	0x6CCD	
18	UIKIT	UIImageJPEGRepresentation	0x7166	
19	MyAppName	-[AppDelegate application:didFinishLaunchingWithOptions:]	0x28A	
20	UIKIT	UIOrientationFromString	0x6CC	
21	Foundation	NSDeallocateObject	0xAFC	
22	Foundation	WinObjC_SetZombiesEnabled	0x3600	
23	UIKIT	UIViewControllerFirePageEvent	0xD4648	
24	SHCore	Microsoft::WRL::Details::RuntimeClass_Microsoft::WRL::Details::InterfaceList_CScalingInfoBase,Microsoft::WRL::Details::InterfaceList_IWindowMonitorChangeListener,Microsoft::WRL::Details::InterfaceList_ICurrentWindowChangeListener,Microsoft::WRL::Details::	0x84	
25	Windows_UI_Xaml	DirectUI::WindowGenerated::get_Bounds	0x40	
26	UIKIT	UIViewControllerFirePageEvent	0xE6E73	
27	UIKIT	UIApplicationLaunched	0x16A	
28	combase	CStdStubBuffer_Invoke	0xDE	
29	combase	__SEH_epilog4_GS	0x1B	
30	combase	DefaultStubInvoke	0x207	
31	ntdll	_RtlUserThreadStart	0x1B	

Method `setup` of the CustomViewController contains reading and writing data from/to NSUserDefaults :

        NSInteger currentVersion = [[[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleVersion"] integerValue];
        NSInteger lastVersion = [[[NSUserDefaults standardUserDefaults] objectForKey:LAST_OPENED_BUNDLE_VERSION] integerValue];
        
        [[NSUserDefaults standardUserDefaults] setObject:@(currentVersion) forKey:LAST_OPENED_BUNDLE_VERSION];
        [[NSUserDefaults standardUserDefaults] synchronize];

Any advice of what could be the reason of the issue and how to fix it?

Thanks in advance! Kind regards, Julia

**Comment by rajsesh-msft** [comment]
@jboich Thanks for reporting the issue.  Looking at the trace, this call stack doesnt make a lot of sense.  Do you have any information on the kind of devices this is happening in?  Since this is happening in app launch time, i want to rule out launch timeout.

It would also be great if you can confirm the version of the bridge you are using.

**Comment by jboich** [comment]
Hi, @rajsesh-msft . Thanks for getting back to me!
 
> Do you have any information on the kind of devices this is happening in? 

Yes, please look at the file attached. 

> It would also be great if you can confirm the version of the bridge you are using.

How to check the version if I built it from source ('develop' branch)?
<img width="665" alt="screenshot 2017-01-04 11 19 29" src="https://cloud.githubusercontent.com/assets/22300615/21641052/2472025e-d271-11e6-9519-0ed69787ac26.png">

**Comment by rajsesh-msft** [comment]
Thanks for the details. Does the version of your app in the store use sources from develop branch, or is this a beta version? In general, you want to use the build from master branch (official release) as It is more stable.

You could provide the change that you synced to from develop branch to produce the build.

**Comment by rajsesh-msft** [comment]
@bbowman, while we dig for other cabs, looks like CPathMapper() has an invalid mapped path?

**Comment by jboich** [comment]
Hi, @rajsesh-msft .

>  Does the version of your app in the store use sources from develop branch,

Yes, it does. The build of WinObjC bridge uses sources from develop branch and includes commits made on 7th of December 2016. Later commits are not included.

>In general, you want to use the build from master branch (official release) as It is more stable.

Thanks for this info! Will do this for future releases.

**Comment by jboich** [comment]
Hi, @rajsesh-msft  and @ArnOmsft . 
< so I just wanted to check if you were able to have a consistent repro?

Our team could find out how to reproduce this issue:

1. Create new local user with name in language other then English + name must contain space. For instance in russian 'Саша Пушкин' or german: "ÖÖÖ testÄ".
2. Sign in to the account created at step 1
3. Install and Launch WOCCatalog example
4. Select Foundation tests -> UserDefaults

Actual:
App crashes 

Crash happens at line:
` NSString* placeHolder = [NSString stringWithFormat:@"%@", [standardDefaults stringForKey:@"FavoriteWord"]];`

@rajsesh-msft 
>  looks like CPathMapper() has an invalid mapped path

yes, path is nullptr

Please see screenshots attached.
![capture1](https://cloud.githubusercontent.com/assets/22300615/21720986/fe794c84-d41d-11e6-81d9-87d102eb7e4e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/22300615/21720987/fe94c626-d41d-11e6-982a-dc94dc1a55df.PNG)
![capture3](https://cloud.githubusercontent.com/assets/22300615/21720988/fe950c9e-d41d-11e6-8893-1ce020463f4e.PNG)

**Comment by jboich** [comment]
Hi again.
The issue is due to CFStringGetCStringPtr() returns NULL.
I found this [solution](https://jongampark.wordpress.com/2009/06/24/be-careful-with-cfstringgetcstringptr-and-its-companion-calls/
) , applied it to "_preferencesDirectoryForUserHostSafetyLevel" in CFPreferences.c in winobjc bridge and it resolved the issue.

**Comment by rajsesh-msft** [comment]
@jboich thanks for the repro and investigation.  I see that you also have a proposed fix for this, would you please submit a pull request for this?

**Comment by rajsesh-msft** [comment]
This is fixed through #1668
