### ISSUE TITLE
CGPathCreateCopyByTransformingPath is missing

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#162]
Or be missing entirely.  The method call won't compile as it should

**Comment by ArnOmsft** [comment]
This method is currently stubbed. You can also check our CGD2D branch [here](https://github.com/Microsoft/WinObjC/tree/CGD2D) which will soon replace our current implementation of Core Graphics.

**Comment by rajsesh-msft** [comment]
Indeed, @MSFTFox fixed it with #1550.  This will be available in our Feb release.
