### ISSUE TITLE
Investigate perf issue with _DWriteGetFrame()

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#1621]

**Comment by ms-jihua** [comment]
![image](https://cloud.githubusercontent.com/assets/16024095/21624423/d1a6323a-d1bb-11e6-8656-828fbce7bfe6.png)

Here's a sample trace from XamlCatalog's custom text view, on top of changes from #1603, and an experimental fix for #1620. When we get deep into the spiral, the view begins to lag. Tracing shows that the primary bottleneck seems to be in drawInRect:, with the time being spent in CFRelease and CGPathRetain sticking out.

![image](https://cloud.githubusercontent.com/assets/16024095/21624516/403d0516-d1bc-11e6-984d-8e9224e5252e.png)

Uncertain exactly how tractable things under _DWriteGetFrame() are. I pointed out a few potential improvements in closing comments for #1374, but for the most part it looks fairly well-distributed.

**Comment by rajsesh-msft** [comment]
We will revisit other perf bottlenecks when #1620 is completed.  This may be entirely gated now on #1490.
