### ISSUE TITLE
_setScrollEnabled not implemented correctly.

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1624]
Dear WinObjC Engineers,

In UIScrollView.mm

`- (void)_setScrollEnabled:(BOOL)enable`

is not implemented correctly - it does not toggle from two states and does not set _scrollView.isEnabled so it corresponds with isScrollEnabled. In fact, scrolling enabled is distinctly different from scroll bar visible, i.e.: the getter and setter are not symmetrical and the setter is not implemented correctly.

Sincerely,

Ed

**Comment by ArnOmsft** [comment]
Thanks for reporting this.

**Comment by ArnOmsft** [comment]
@edvv, can you confirm if that's a blocking issue for you or not to help us prioritize this?
Thanks.

**Comment by edvv** [comment]
@ArnOmsft It is non-blocking and fixed on this end. Thanks for asking :-)

**Comment by yiyang-msft** [comment]
The setter is correct based on the semantics of XAML scrollviewer. We fixed the getter to match the setter.
