### ISSUE TITLE
A few Functional Test failures after commit b3e269e

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#1626]
After commit b3e269e, the following functional tests started to fail.
    CortanaVoiceCommandForegroundActivation::Cortana_VoiceCommandForegroundActivationDelegateMethodsCalled [Failed]
CortanaProtocolForegroundActivation::Cortana_ProtocolForegroundActivationDelegateMethodsCalled [Failed]
ToastNotificationForegroundActivation::ToastNotification_ForegroundActivationDelegateMethodsCalled [Failed]
ActivatedAppReceivesToastNotification::ToastNotification_ActivatedAppReceivesToastNotification [Failed]
FileActivationForegroundActivation::FileActivation_TestForegroundActivationDelegateMethodsCalled [Failed]

Repro is pretty straight forward:
git checkout b3e269e
build winobjc.
Run functional tests.

**Comment by jaredhms** [comment]
Fixed with https://github.com/Microsoft/WinObjC/pull/1640
