### ISSUE TITLE
Accelerate framework missing

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#163]
Entire  <Accelerate/Accelerate.h> framework seems to be missing

**Comment by MaddTheSane** [comment]
The Accelerate framework does use *BLAS* and *LAPACK*, along with their own libraries, I'm sure.

**Comment by mlfarrell** [comment]
You're right.  Apple's accelerate used GCD / OpenCL under the hood I think but for now, any decent objc wrapper around LAPACK named "accelerate" will likely solve most issues

**Comment by s5msft** [comment]
Initial version available as of bed20a4b6
