### ISSUE TITLE
WXCContentControl missing pointer hovered event processing

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1637]
Dear WinObjC Engineers,

WXCContentControl is missing some pointer event processing, including hover; such as those found in WUIIInkUnprocessedInput, e.g.: addPointerLostEvent addPointerHoveredEvent.

Sincerely,

Ed

**Comment by ArnOmsft** [comment]
Thanks for reporting this.

**Comment by tadam-msft** [comment]
PointerHovered and PointerLost aren't part of the ContentControl's interface, those are only on InkUnprocessed input--can you use those directly.  If you need the Hover functionality, you can rely on PointerEnter and PointerExit functionality to determine when control is hovered over.

**Comment by edvv** [comment]
@tadam-msft Thanks for the added information. Given that a WXCContentControl is installed onto the visual tree, how to I get the indirection (reference) to unprocessed ink input instance? Once I have that reference (a pointer) then I can call upon it, but I need to know the proper way to reference it within a given node in an object tree.

**Comment by jaredhms** [comment]
@edvv, I don't have much experience with the Inking APIs, but as far as I know, [WUIIInkUnprocessedInput ](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.input.inking.inkunprocessedinput) doesn't interact with arbitrary (or any) WXCContentControls.  Rather, it is meant to be paired with a [WUIIInkCanvas](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.inkcanvas) instance.  

Can you share more details on what you're trying to achieve?  

For normal (non-InkCanvas) Xaml elements/UIViews, if you want to track hover state, you can do something like the following:

[[myView xamlElement] addPointerEnteredEvent:^(RTObject* sender, WUXIPointerRoutedEventArgs* e) {
            // Hover-on handling
        }];

[[myView xamlElement] addPointerExitedEvent:^(RTObject* sender, WUXIPointerRoutedEventArgs* e) {
            // Hover-off handling
        }];

**Comment by jaredhms** [comment]
You'll also need to remove the subscriptions in your dealloc, so this is a bit more correct:

EventRegistrationToken _pointerEnteredEventRegistration = { 0 };
EventRegistrationToken _pointerExitedEventRegistration = { 0 };

...

__block MyType* weakSelf = self;
_pointerEnteredEventRegistration = [[myView xamlElement] addPointerEnteredEvent:^(RTObject* sender, WUXIPointerRoutedEventArgs* e) {
// Hover-on handling via weakSelf 
}];

_pointerExitedEventRegistration = [[myView xamlElement] addPointerExitedEvent:^(RTObject* sender, WUXIPointerRoutedEventArgs* e) {
// Hover-on handling via weakSelf 
}];

...

in dealloc:

[[myView xamlElement] removePointerEnteredEvent:_pointerEnteredEventRegistration];
[[myView xamlElement] removePointerExitedEvent:_pointerExitedEventRegistration];

**Comment by edvv** [comment]
@jaredhms Thank you for your help. I got what I needed, so I'm closing this.
