### ISSUE TITLE
AV in LIBOBJC2.DLL!isEmptyProtocol() when loading a module that implements *only* a forward-declared protocol

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#1647]
I thought we fixed this last march, but I am still able to reproduce the issue easily:

1. Once #1380 goes in, comment out the bottom line of UIApplication.h that #imports UIApplicationDelegate.h
2. Rebuild the functional tests
3. Run the functional tests under the debugger

You'll hit an AV in isEmptyProtocol() because the functional tests implement an undefined/forward-declared UIApplicationDelegate protocol.

**Comment by DHowett-MSFT** [comment]
Fixed with #2869
