### ISSUE TITLE
How do I upgrade the version of WinObjC used with a project?

### ISSUE THREAD

**Issue by rogersachan** [Microsoft/WinObjC#1658]
If I used 0.1 to convert my project earlier, can I delete the 0.1 folder and put 0.2 in its place and use the newer version of the bridge without issue?

**Comment by rajsesh-msft** [comment]
In general, yes.

Please be sure to look at the [breaking change] (https://github.com/Microsoft/WinObjC/issues?q=is%3Aissue+%22BREAKING+CHANGE%22+is%3Aclosed) announcements first to see if there are any that will impact you. 

Re-run vs-importer and port over any changes you made after running vsimporter last time.

Please open issues if you run into anything.
