### ISSUE TITLE
GestureRecognizers do not work for UIWebView

### ISSUE THREAD

**Issue by jboich** [Microsoft/WinObjC#1682]
If you attach any gesture recognizer to the instance of UIWebView class, no action will be triggered when user does corresponded manipulations in web view.
Also, a subclass of UIWebView class won't get any touch events.

This behavior is because XAML webview control does not support manipulation events:
A common workaround is to use InvokeScriptAsync with the JavaScript eval function to use the HTML event handlers, and to use window.external.notify from the HTML event handler to notify the application using WebView.ScriptNotify. (see Remarks section in [documentation](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.webview.aspx))

To apply this workaround in bridge we 
1. added extra delegate method in UIWebViewDelegate  
2. added handler of ScriptNotify event to xamlWebControl in UIWebView.mm and invoke delegate method created at step 1

I will submit PR for this

**Comment by tadam-msft** [comment]
Issue was fixed with PR #1683
