### ISSUE TITLE
UILabel.adjustsFontSizeToFitWidth doesn't appear to be functioning properly

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#1689]
If you go into the UIView sample in XamlCatalog on desktop, the instruction text is much smaller than it should be.  In the below image, the red rect shows the width of the label, yet the text clearly doesn't span the width of the red rect.

![image](https://cloud.githubusercontent.com/assets/13719817/21874430/bbc6125e-d829-11e6-80e0-b28a5980db09.png)

**Comment by DHowett-MSFT** [comment]
This property is only respected when the label is smaller than the text that would fit in it at its default point size.

To quote the reference documentation,

> If this property is set to true, and the text in the text property exceeds the label’s bounding rectangle, the label reduces the font size until the string fits or the minimum font scale is reached.

**Comment by jaredhms** [comment]
That implies that nothing should happen if the text fits, yet it's tiny.

**Comment by DHowett-MSFT** [comment]
In the image, it looks like its text height matches its view height and was therefore scaled down?

**Comment by jaredhms** [comment]
That rect is actually around the _internal_ TextBlock; here's the rect around the actual UIView:

![image](https://cloud.githubusercontent.com/assets/13719817/21905720/51e153e6-d8bd-11e6-9260-fb711bf138dd.png)

**Comment by DHowett-MSFT** [comment]
That is a significantly better screenshot!

**Comment by tadam-msft** [comment]
Fixed with UILabel refactoring work.
