### ISSUE TITLE
Undefined types from Security framework

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#169]
Following types are not defined:

SecCertificateRef
SecPolicyRef
SecTrustRef
SecTrustResultType
SecKeyRef

possibly more

Additionally many of the security framework methods such as SecPolicyCreateSSL are returning 'int' instead of CFType's which isn't correct

**Comment by rajsesh-msft** [comment]
Thanks for the feedback, this is now in our backlog and may be available in a future release.

**Comment by rajsesh-msft** [comment]
Thanks for the feedback.&nbsp; Implementing Security framework is added to our backlog and may be available in a future release.
