### ISSUE TITLE
UILabels can fail to render *anything* on phone

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#1690]
If you comment out the 'label.adjustsFontSizeToFitWidth = YES;' in XamlCatalog's UIViewViewController, and run the sample on phone, none of the instruction labels' text is rendered.  The views are there and they're the correct size, but the text isn't rendered at all.

**Comment by yiyang-msft** [comment]
I have tested the latest develop on phone with/without label.adjustsFontSizeToFitWidth = YES; and also, I also tested develop before f0ba901226e73b50e67ef5972b8548b9ab4a5dcd which fixed the linebreakMode in UILabel. in all my testing, I didn't see a repro of the above issue - that is the description didn't get rendered. 

Scanning the history I don't see any other change in between 08b3fbc0c1d53df16f3e6430f633e3e9f95f367f (commit when issue reported) and d294d7c1e5c6839d69b27f6393523644a99b4834 (now)  could possible impact UILabel other than f0ba901226e73b50e67ef5972b8548b9ab4a5dcd. With that, I closed this issue as not repro.

**Comment by jaredhms** [comment]
Seems more likely that your UILabel fix also fixed this?  Regardless, I'll give it another try locally.  Thanks!

**Comment by yiyang-msft** [comment]
f0ba901 is when I fixed the UILabel, I synced back to commit earlier than that and I saw the description gets wrapped on phone, which is the bug  f0ba901 to fix. but description still shows up for me, instead of not showing anything - this is with/without label.adjustsFontSizeToFitWidth = YES.
