### ISSUE TITLE
NSDictionary setObject methods should throw when object == nil

### ISSUE THREAD

**Issue by aballway** [Microsoft/WinObjC#1697]
This requires support from the compiler

**Comment by DHowett-MSFT** [comment]
No it doesn't.

**Comment by DHowett-MSFT** [comment]
This issue was filed due to a misunderstanding.

The compiler already uses `setObject:forKeyedSubscript:` instead of `setObject:forKey:` when subscripting a mutable dictionary.
The reference platform specifies that `dict[key] = nil;` remove the object keyed by `key` from the dictionary `dict`.
