### ISSUE TITLE
WOCCatalog: GLKit does display a blank screen on Lumia 640XL

### ISSUE THREAD

**Issue by ArnOmsft** [Microsoft/WinObjC#1703]
Phone: Lumia 640XL (14997)
App: WOCCatalog from 20161213.2
Launch the app and go to GLKit: a blank white screen is displayed with just the toggle switch "Multisampling on" visible and no animation. Switching Multisampling to off switches the screen to blue and still no animation is displayed.

**Comment by rajsesh-msft** [comment]
This seems hardware related.
