### ISSUE TITLE
Very odd issue with ifstream and string

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#172]
I can only chalk this up to the way you guys must have built your clang installation

This one cannot handle reading strings from ifstreams

code (.mm file)
  ifstream ins(fpath, ifstream::in);
  string token;
  ins >> token;

produces
 error : invalid operands to binary expression ('ifstream' (aka 'basic_ifstream<char, char_traits<char> >') and 'string' (aka 'basic_string<char, char_traits<char>, allocator<char> >'))

**Comment by pradipd** [comment]
Try:
#include <string>

http://en.cppreference.com/w/cpp/string/basic_string/operator_ltltgtgt

**Comment by pradipd** [comment]
That should be:
#include `<string>`

**Comment by nicholasgerard-msft** [comment]
@mlfarrell Is this issue resolved for you? If so, please close it out.

**Comment by nicholasgerard-msft** [comment]
@mlfarrell Closing this for now. Please reopen if the problem persists for you in the [latest release of the bridge](https://github.com/Microsoft/WinObjC/releases).
