### ISSUE TITLE
Testing bolts 1.8.4 version fails while building in visual studio

### ISSUE THREAD

**Issue by venkatkongara** [Microsoft/WinObjC#1720]
Pre-reqs:
 Provide information on your environment.
•OS Version Win10 10586.104
•Visual Studio 2015
•Islandwood SDK version  3a18ee2 

Repro steps:
 I have copied the code from mac book and went into the directory to create *.sln file using vsimporter.
 I have opened the *.sln file by double clicking it. As shown in the below images it opens properly with Bolt-ios as a build dependency. But while building it gives the shown below error.

Expected behavior:
 build smoothly without errors on importing some files from Bolts framework

Actual behavior:
 Bolts.lib (BFExecutor_F456FB2F.obj) : error LNK 2019: unresolved external symbol _pthread_get_stackaddr_np referenced in function remaining_stack_size
 Bolts.lib (BFExecutor_F456FB2F.obj) : error LNK 2019: unresolved external symbol _pthread_get_stacksize_np referenced in function remaining_stack_size

![bfexecutor has this method](https://cloud.githubusercontent.com/assets/14223035/22045641/450eedb0-dcd0-11e6-898f-c19a81c6ebe4.PNG)
![pthreaderrorbolts_1_8_4_compilingvsimporter](https://cloud.githubusercontent.com/assets/14223035/22045642/4510c3ba-dcd0-11e6-9936-93ef5098da6f.PNG)

**Comment by rajsesh-msft** [comment]
There are currently no UWP apis that allow us to control/read the stack size, so this functionality won't work on windows.
