### ISSUE TITLE
Archival.BackwardsCompatibilityWithOldWinObjCArchives test fails on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#1724]
[ RUN      ] Archival.BackwardsCompatibilityWithOldWinObjCArchives
ArchivalTests.mm:444: Failure
Value of: rootObject
  Actual: NULL
Expected: @"RootObject"
Which is: RootObject
[  FAILED  ] Archival.BackwardsCompatibilityWithOldWinObjCArchives (0 ms)

Judging by the name, it's possible that this should be an OSX_DISABLED_TEST

**Comment by DHowett-MSFT** [comment]
oops, this is a winobjc-specific test :cry:
