### ISSUE TITLE
NSBundle.Paths test fails on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#1725]
[ RUN      ] NSBundle.Paths
ReferenceFoundation/TestNSBundle.mm:48: Failure
Value of: nullptr
  Actual: NULL
Expected: bundle.appStoreReceiptURL
Which is: _MASReceipt/receipt -- file:///Volumes/WinObjC/build/Tests/UnitTests/Foundation/OSX/
[  FAILED  ] NSBundle.Paths (10 ms)

**Comment by rajsesh-msft** [comment]
@aballway other tests have likely fallen behind as well.
