### ISSUE TITLE
SpriteSample is crashing on launch

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#1736]
SpriteSample is crashing on launch for all configurations (arm/win32 debug/release).

**Comment by jaredhms** [comment]
This is a double-free that's hit when we drain the autoreleasepool upon initial app launch.  It appears to have been introduced by #1710; reverting commit deb99af6 fixes the crash.

Here's a stack that's causing a double-free:

>	GLKIT.DLL!+[GLKTextureLoader textureWithContentsOfFile:options:error:](objc_class * self, objc_selector * _cmd, NSString * fname, NSDictionary * opts, NSError * * err) Line 282	Objective-C++
 	SpriteSample.exe!-[SpriteClass initWithFile:effect:](SpriteClass * self, objc_selector * _cmd, NSString *) Line 44	Objective-C
 	SpriteSample.exe!-[Renderer initGLData:](Renderer * const self, objc_selector * _cmd, CGSize screenSize) Line 47	Objective-C
 	SpriteSample.exe!-[AppDelegate application:didFinishLaunchingWithOptions:](AppDelegate * const self, objc_selector * _cmd, id *) Line 57	Objective-C
 	UIKIT.DLL!UIApplicationMainInit(NSString * principalClassName, NSString * delegateClassName, unsigned int defaultOrientation, int activationType, objc_object * activationArg) Line 283	Objective-C++
 	UIKIT.DLL!ApplicationMainStart(const char * principalName, const char * delegateName, float windowWidth, float windowHeight, ActivationType activationType, IInspectable * activationArg) Line 158	Objective-C++
 	UIKIT.DLL!RunApplicationMain(Platform::String ^) Line 68	C++
 	UIKIT.DLL!DoApplicationLaunch(ActivationType activationType, Platform::Object ^ activationArg) Line 290	C++
 	UIKIT.DLL!_ApplicationLaunch(ActivationType activationType, Platform::Object ^ activationArg) Line 306	C++
 	UIKIT.DLL!UIApplicationLaunched(Windows::ApplicationModel::Activation::LaunchActivatedEventArgs ^ args) Line 192	C++
