### ISSUE TITLE
WinRT projections should autorelease all objects returned from create* factory functions

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#1752]
For example; this code leaks because the WFPoint isn't added to the autoreleasepool:

`WFPoint* pointInFromLayer = [WXPointHelper fromCoordinates:point.x y:point.y];`

It _looks like_ this only pertains to structs WFPoint, WFRect, etc. but we should scrub the rest of the projections to confirm.  Anything that goes through _createRTProxy is fine because it returns an autoreleased object.

**Comment by mukhole** [comment]
Fixed.
