### ISSUE TITLE
WinRT projections should annotate factory methods with NS_RETURNS_RETAINED and NS_RETURNS_AUTORELEASED

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#1753]
All of our create* factory methods should be annotated with NS_RETURNS_AUTORELEASED for clarity.

Also, we currently use 'ACTIVATOR' on our make* methods, but we should just switch them all to NS_RETURNS_RETAINED for clarity.

**Comment by DHowett-MSFT** [comment]
It looks like we might want to go with the attribute on this one, since there is no NS_RETURNS_AUTORELEASED.

`__attribute__((ns_returns_autoreleased))`

**Comment by pradipd** [comment]
https://github.com/Microsoft/WinObjC/commit/991023e70e34e035eb7a25a70dd20b9894349232
