### ISSUE TITLE
Functional Tests fail during test cleanup.

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#1757]
Perhaps due to an over-release.

**Comment by DHowett-MSFT** [comment]
This is due to an over-release in the CALayerAppearanceTests. Assigning to @tadam-msft for triage.

Proximal cause: Overboard use of `__block` causes the nested callback blocks to not retain any referenced objects; some objects are autoreleased and some are manually released before their time on earth is up.

**Comment by oliversa-msft** [comment]
This should not block today's release. It's a rarely repro'ed issue in the test cleanup which does not fail the TAEF test. I'm changing the pattern to these tests in a PR shortly as well.

**Comment by oliversa-msft** [comment]
I attempted to repro the issue after applying the new UX change (which also removes __block decoration) and I've been unable to reproduce the offending stack. 

Previously I was only able to see the leaked object once in about 50 attempts but it's potentially just harder to repro with my local setup. Worth keeping a eye out for any recurrence.
