### ISSUE TITLE
Islandwood News crash when trying to insert nil font into dictionary

### ISSUE THREAD

**Issue by aballway** [Microsoft/WinObjC#1758]

**Comment by DHowett-MSFT** [comment]
How'd this happen? Are we using a NSDictionary somewhere a CFDictionary belongs?

**Comment by aballway** [comment]
Seems to be caused by app code expecting the font family to be the font name, and trying to create a font with a nonexistent family fails.  Moving to @ms-jihua because she's more familiar with the codepath.
