### ISSUE TITLE
[NSLayoutManager __layoutAllText] sometimes throws due to an empty frame

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#1779]
This can be repro'd in IslandwoodNews after #1778:

CTLineRef fitLine = static_cast<CTLineRef>(CFArrayGetValueAtIndex(CTFrameGetLines(frame.get()), 0));

When entering an article, the frame will often be empty, causing the underlying CFArray to throw <a CF-y version of index out of bounds>.

**Comment by aballway** [comment]
This is the same as the original issue @msft-Jeyaram reported in #1751

**Comment by rajsesh-msft** [comment]
I don't think so. The call stacks were different.

**Comment by ms-jihua** [comment]
It was until he changed it. I think @msft-Jeyaram settled on using #1751 for the UIPageViewScrollView issue, and this one for the NSLayoutManager issue.
