### ISSUE TITLE
cannot find "Mapkit/MapKit.h"

### ISSUE THREAD

**Issue by yw346090249** [Microsoft/WinObjC#179]
I want to use the framework MapKit, and the error came out after turning it into UWP project using vsimporter.  
C:\Users\yanwe\OneDrive\onWork\IoW\MyOwnApp\MyLocation\MyLocations\MyLocations-Prefix.pch(18,13): fatal error : 'MapKit/MapKit.h' file not found

**Comment by joagwa** [comment]
How did you fix this?

**Comment by yw346090249** [comment]
I did not fix it but just saw that the MapKit was just on process, so I close this issue.

**Comment by SAPNALnT** [comment]
How to fix this issue?
