### ISSUE TITLE
Unable to build  CoreGraphics.Drawing tests on OSX

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#1805]
It looks like the recent change f194201e5e199e9461eec5e3f6a9da0d7a459258 broke it.

Looks like the template changes aren't happy with OSX :(

`..//../../include/xplat/Starboard/SmartTypes.h:541:19: note: copy constructor is implicitly deleted because 'unique_cf<CGImage *>' has a user-declared move assignment operator
    unique_cf<T>& operator=(unique_cf<T>&& other) = delete;
                  ^
DrawingTest.cpp:120:14: error: call to implicitly-deleted copy constructor of 'ImageDelta'
        auto delta = comparator.CompareImages(referenceImage.get(), image.get());
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DrawingTest.cpp:214:27: note: in instantiation of member function 'testing::DrawTest<PixelByPixelImageComparator<PixelComparisonModeMask<64> > >::TearDown' requested here
template class ::testing::DrawTest<PixelByPixelImageComparator<PixelComparisonModeMask<64>>>;
`

**Comment by aballway** [comment]
@DHowett-MSFT
