### ISSUE TITLE
NSURL tests fail on OSX

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#1806]
NSURLSessionConfigurationTests.m:55: Failure
Value of: sessionConfiguration.TLSMaximumSupportedProtocol
  Actual: 0
Expected: kTLSProtocol12
Which is: 8
FAILED: TLSMaximumSupportedProtocol should be 8

[  FAILED  ] NSURLSessionConfiguration.defaultSessionConfiguration (1 ms)
[ RUN      ] NSURLSessionConfiguration.ephemeralSessionConfiguration
NSURLSessionConfigurationTests.m:69: Failure
Value of: sessionConfiguration.TLSMaximumSupportedProtocol
  Actual: 0
Expected: kTLSProtocol12
Which is: 8
FAILED: TLSMaximumSupportedProtocol should be 8

[  FAILED  ] NSURLSessionConfiguration.ephemeralSessionConfiguration (0 ms)
[ RUN      ] NSURLSessionConfiguration.backgroundSessionConfigurationWithIdentifier
NSURLSessionConfigurationTNSURLSessionConfiguration.defaultSessionConfigurationests.m:85: Failure
Value of: sessionConfiguration.TLSMaximumSupportedProtocol
  Actual: 0
Expected: kTLSProtocol12
Which is: 8
FAILED: TLSMaximumSupportedProtocol should be 8

[ RUN      ] NSURL.NSURLTests
NSURLTests.m:28: Failure
Value of: actual
  Actual: http://www.test.com/.foo
Expected: expected
Which is: http://www.test.com/
FAILED: expected != actual

**Comment by ms-jihua** [comment]
I am unable to repro this failure (10.11.6) but judging by the failure we might be assuming too much about the underlying machine anyway?

**Comment by msft-Jeyaram** [comment]
closing this as behaviours changed from 10.10 to 10.11.
We will keep up with the latest versioning for now.

**Comment by msft-Jeyaram** [comment]
These fail on 10.12.3.
I've updated the failure logs above.
