### ISSUE TITLE
NSMutableDictionary inserting nil tests fail on OSX

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#1807]
NSMutableDictionary.InsertingNilForKeyedSubscriptShouldRemoveValue
2017-01-25T00:57:58.6709060Z unknown file: Failure
2017-01-25T00:57:58.6721240Z Unknown C++ exception thrown in the test body.

NSMutableDictionary.InsertingNilWithSubscriptingShouldRemoveValue
2017-01-25T00:57:58.6758270Z unknown file: Failure
2017-01-25T00:57:58.6770150Z Unknown C++ exception thrown in the test body.

**Comment by msft-Jeyaram** [comment]
@aballway could you take a look at this, given you added these tests

**Comment by DHowett-MSFT** [comment]
@aballway if only we had added `EXPECT_NO_THROW` to those cases that I suggested, we'd know know exactly which line failed ;)

**Comment by aballway** [comment]
I am unable to repro on develop running on Version 10.11.5

**Comment by msft-Jeyaram** [comment]
Looks like the  build agent is out of date:
sw_vers -productVersion
10.10.5

**Comment by msft-Jeyaram** [comment]
closing this as behaviours changed from 10.10 to 10.11.
We will keep up with the latest versioning for now.
