### ISSUE TITLE
NSProcessInfo get properties test fails on OSX

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#1808]
[ RUN      ] NSProcessInfo.NSProcessInfoGetProperties
NSProcessInfoTests.mm:60: Failure
 Value of: processInfo.processName
Actual: Foundation.UnitTests.exe
Expected: processName
Which is: Foundation.Unit
Process name should be equal

**Comment by ms-jihua** [comment]
I am unable to repro this failure (10.11.6)

**Comment by msft-Jeyaram** [comment]
closing this as behaviours changed from 10.10 to 10.11.
We will keep up with the latest versioning for now.
