### ISSUE TITLE
NSProgress chain implicit tests fail on OSX

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#1809]
[ RUN      ] NSProgress.ChainImplicit
NSProgressTests.mm:194: Failure
Value of: [prog2 completedUnitCount]
Actual: 0
Expected: 50

 [ RUN      ] NSProgress.ChainImplicit_EdgeCases
NSProgressTests.mm:241: Failure
Value of: [prog2 completedUnitCount]
 Actual: 60
 Expected: 80

**Comment by msft-Jeyaram** [comment]
@ms-jihua  could you take a look at this, these tests were enabled via e6e6ece8504fc8bc850f8d9fdf0730b45fbee55a

**Comment by ms-jihua** [comment]
I am unable to repro this failure (10.11.6)

**Comment by msft-Jeyaram** [comment]
closing this as behaviours changed from 10.10 to 10.11.
We will keep up with the latest versioning for now.
