### ISSUE TITLE
windows bridge support openGLES or directX

### ISSUE THREAD

**Issue by edthereaper** [Microsoft/WinObjC#181]
im iOS developer, and i dont really know, how are the graphics supports of windows graphics mobile device but the bridge will support the exchange of openGLES to directx mobile (guest that the win mobile support directx) ?

Thanks

**Comment by neuswcjr** [comment]
This bridge tool use angle project to convert OpenGL ES to the directx. The original win10 uwp only support directx, same as win8.1/wp8.1 universal apps.

**Comment by rogersachan** [comment]
I don't understand this conversation. What is the "angle project"?
