### ISSUE TITLE
UITextView used EbrCenterTextInRectVertically; figure out why.

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#1812]
This was removed in CGD2D, as EbrCenterTextInRectVertically was living in CGContext. It might be more of a CoreText concern.

**Comment by rajsesh-msft** [comment]
This should immediately and obviously break text layout in UITextView and UITabBarButton?

**Comment by jaredhms** [comment]
Text is vertically centered in UILabel; perhaps UITextView is also vertically-centered by default.  Not sure how critical this is though, as we'll be porting them to Xaml at some point in the ~near future.
