### ISSUE TITLE
Need performance benchmark tests for CoreText

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#1819]
Would be useful to time these scenarios.  The goal is to have a simple commandline test similar to the unit tests, but rather than pass fail, these would run the perf scenarios and log the various metrics.  Here are some basic metrics we want to have:

1.	Drawing a frame with 100 sentences.
2.	Drawing 10000 lines.
3.	Drawing 100,000 runs.
4.	Drawing 10,000,000 glyphs.
5.	Drawing using NSString drawAtPoint and variations.
6.	Drawing using NSAttributedString drawAtPoint.

Once we have this, we could plug this into nightly build for build-over-build tracking of perf numbers to catch future regressions.

**Comment by edvv** [comment]
@rajsesh-msft Suggestion: If you set a baseline against Release 41 ( https://github.com/Microsoft/WinObjC/issues/1500 ) then that would give pass/fail criterion and the unit tests would be more fudge proof.
