### ISSUE TITLE
[CGD2D Validation] WOCCatalog ImageView page crashes

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#1838]
unable to launch the ImageView (which cycles through few images).

This works fine on develop (as of full build 20170125.1).

The stack looks like it's going off in Xaml

>  	KernelBase.dll!_RaiseException@16()	Unknown
 	vcruntime140d_app.dll!__CxxThrowException@8()	Unknown
 	LIBOBJC2.DLL!0f5e6c47()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for LIBOBJC2.DLL]	
 	FOUNDATION.DLL!-[NSException raise](NSException * self, objc_selector * _cmd) Line 131	Objective-C++
 	Windows.UI.Xaml.dll!DirectUI::PointerRoutedEventArgsGenerated::QueryInterfaceImpl(const _GUID & iid, void * * ppObject) Line 41	C++
 	Windows.UI.Xaml.dll!ctl::ComObjectBase::QueryInterfaceBase(const _GUID & iid, void * * ppValue) Line 40	C++
 	0c96541c()	Unknown
 	OBJCUWP_WINDOWS_UI_XAML.DLL!040e89f3()	Unknown
 	Windows.UI.Xaml.dll!DirectUI::EventArgs::GetCorePeer(CEventArgs * * ppPeer) Line 49	C++
 	UIKIT.DLL!___scrt_stub_for_is_c_termination_complete()	Objective-C++
 	Windows.UI.Xaml.dll![thunk]:ImageProviderDecodeHandlerTask::Release`adjustor{8}' (void)	C++
 	Windows.UI.Xaml.dll![thunk]:ImageProviderDecodeHandlerTask::Release`adjustor{8}' (void)	C++
 	Windows.UI.Xaml.dll![thunk]:ImageProviderDecodeHandlerTask::Release`adjustor{8}' (void)	C++
 	Windows.UI.Xaml.dll![thunk]:ImageProviderDecodeHandlerTask::Release`adjustor{8}' (void)	C++
 	Windows.UI.Xaml.dll![thunk]:ImageProviderDecodeHandlerTask::Release`adjustor{8}' (void)	C++
 	user32.dll!760cc4c0()	Unknown
 	user32.dll!760c6b09()	Unknown
 	ntdll.dll!_KiUserCallbackDispatcher@12()	Unknown
 	win32u.dll!779a295c()	Unknown
 	user32.dll!760bebce()	Unknown
 	user32.dll!760bea08()	Unknown
>	Windows.UI.Xaml.dll!CXcpBrowserHost::SyncScriptCallbackRequest(void * pVoidBH, CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int flags, IScriptObject * pScriptObject, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *) pHandler) Line 1035	C++
 	Windows.UI.Xaml.dll!CEventManager::RaiseHelper(xvector<REQUEST *> * pRegisteredRequests, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int bRefire, long(__stdcall*)(void *, CDependencyObject *, EventHandle, CDependencyObject *, CEventArgs *, int, IScriptObject *, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *)) pfnScriptCallback, unsigned int & bFired, CDependencyObject * pSenderOverride) Line 1046	C++
 	Windows.UI.Xaml.dll!CEventManager::Raise(EventHandle hEvent, int bRefire, CDependencyObject * pSender, CEventArgs * pArgs, bool fRaiseSync, bool fInputEvent, bool bAllowErrorFallback, CDependencyObject * pSenderOverride) Line 878	C++
 	Windows.UI.Xaml.dll!CEventManager::RaiseRoutedEvent(EventHandle hEvent, CDependencyObject * pSource, CRoutedEventArgs * pArgs, bool bIgnoreVisibility, bool fRaiseSync, bool fInputEvent, CDependencyObject * coerceToHandledAtElement) Line 1234	C++
 	Windows.UI.Xaml.dll!CInputManager::RaiseDelayedPointerUpEvent(TouchInteractionMsg * pMsgGesture, CDependencyObject * pElement) Line 5620	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessGestureInput(CDependencyObject * pElement, TouchInteractionMsg * pMsg) Line 5375	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessTouchInteractionCallback(const xref_ptr<CUIElement> & element, TouchInteractionMsg * message) Line 5269	C++
 	Windows.UI.Xaml.dll!CCoreServices::ProcessTouchInteractionCallback(const xref_ptr<CUIElement> & element, TouchInteractionMsg * message) Line 1040	C++
 	Windows.UI.Xaml.dll!CTouchInteractionElement::TouchInteractionCallback(TouchInteractionMsg * message) Line 42	C++
 	Windows.UI.Xaml.dll!CTouchInteractionHelper::InteractionEngineCallback(const INTERACTION_CONTEXT_OUTPUT * pOutputFromICM) Line 808	C++
 	Windows.UI.Xaml.dll!CTouchInteractionHelper::StaticInteractionEngineCallback(void * pvData, const INTERACTION_CONTEXT_OUTPUT * outputFromICM) Line 39	C++
 	ninput.dll!COutputConverter::Process(class CInteractionContextConfiguration const &,enum InteractionContextProperties::MeasurementUnits,enum CInteractionContextGlobal::FeedbackSettings,enum DIGITIZER_KIND,struct tagRECT const &,struct tagRECT const &,struct INTERACTION_INPUT const *,unsigned int,struct INTERACTION_OUTPUT const &)	Unknown
 	ninput.dll!CInteractionContextImpl::OutputCallback(void *,struct INTERACTION_OUTPUT const *)	Unknown
 	ninput.dll!CInteractionGroupingFilter::_SendOutput(struct INTERACTION_OUTPUT const &)	Unknown
 	ninput.dll!CInteractionGroupingFilter::_OnInput(struct INTERACTION_OUTPUT const &)	Unknown
 	ninput.dll!CInteractionGroupingFilter::Input(void *,struct INTERACTION_OUTPUT const *)	Unknown
 	ninput.dll!COutputCoalescingFilter::Flush(void)	Unknown
 	ninput.dll!COutputCoalescingFilter::_OnInput(struct INTERACTION_OUTPUT const &)	Unknown
 	ninput.dll!COutputCoalescingFilter::Input(void *,struct INTERACTION_OUTPUT const *)	Unknown
 	ninput.dll!CInteractionEngineImpl::DigitizerInput(enum DIGITIZER_KIND,unsigned __int64,unsigned int,unsigned int,struct INTERACTION_INPUT const *)	Unknown
 	ninput.dll!_ProcessInputInteraction@28()	Unknown
 	ninput.dll!CInteractionContextImpl::ProcessFrameHistory(unsigned int,unsigned int,struct tagPOINTER_INFO const *)	Unknown
 	ninput.dll!_ProcessPointerFramesInteractionContext@16()	Unknown
 	Windows.UI.Xaml.dll!CTouchInteractionHelper::ProcessPointerInformation(const InputMessage & msg) Line 913	C++
 	Windows.UI.Xaml.dll!CTouchInteractionHelper::ProcessPointerMessage(const InputMessage & msg) Line 74	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessPointerMessagesWithInteractionEngine(unsigned int pMsg, InputMessage * pInteractionElement, CUIElement * pManipulationElement, CUIElement * bIgnoreManipulationElement, unsigned int pInteractionContext, CTouchInteractionHelper * bForceDisableGesture, unsigned int) Line 4944	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessInteractionPointerMessages(unsigned int pointerId, InputMessage * pMsg) Line 4710	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessPointerInput(InputMessage * pMsg, int * pfHandled, unsigned long hWindowID) Line 3374	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessInput(InputMessage * pMsg, int * handled, unsigned long hWindowID) Line 1208	C++
 	Windows.UI.Xaml.dll!CCoreServices::ProcessInput(InputMessage * pMessage, int * fHandled, unsigned long hWindowID) Line 930	C++
 	Windows.UI.Xaml.dll!CXcpBrowserHost::HandleInputMessage(unsigned int uMsg, MsgPacket * pMsgPack, bool & fHandled, unsigned long hWindowID) Line 1354	C++
 	Windows.UI.Xaml.dll!CJupiterControl::HandlePointerMessage(unsigned int uMsg, unsigned int wParam, long lParam) Line 601	C++
 	Windows.UI.Xaml.dll!CJupiterControl::HandleWindowMessage(unsigned int uMsg, unsigned int wParam, long lParam) Line 330	C++
 	Windows.UI.Xaml.dll!CJupiterWindow::CoreWindowSubclassProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 1072	C++
 	Windows.UI.Xaml.dll!CJupiterWindow::StaticCoreWindowSubclassProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 519	C++
 	user32.dll!760ca97b()	Unknown
 	user32.dll!760bc488()	Unknown
 	ntdll.dll!_NtCallbackReturn@12()	Unknown
 	user32.dll!760b5feb()	Unknown
 	Windows.UI.Xaml.dll!DirectUI::FrameworkView::Run() Line 105	C++
 	twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::Run()	Unknown
 	twinapi.appcore.dll!<lambda>(void)()	Unknown
 	SHCore.dll!_WrapperThreadProc()	Unknown
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown

**Comment by msft-Jeyaram** [comment]
no longer seeing the crash on CGD2D, able to cycle through all the images fine.

**Comment by DHowett-MSFT** [comment]
This was the same crash as #1837!
