### ISSUE TITLE
GLKitComplex doesnt show background

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#1840]
possibly other GLKit related regressions on ARM.  Likely related to #1715.

**Comment by rajsesh-msft** [comment]
Looks like the texture is failing to load because CGImageCreateWithPNGDataProvider is returning nil. Likely d62e5e7967d97b775a2de76efbc91c4d1bd905fc

**Comment by DHowett-MSFT** [comment]
Could this be fallout from #1659? Some resource paths changed.

**Comment by rajsesh-msft** [comment]
@DHowett-MSFT, likely yes, thanks.  looks like the xcodeproject is incomplete.

**Comment by arjun-msft** [comment]
I'm seeing white background on the latest build as well

**Comment by ashvarma** [comment]
I don't see a white background - I do see a missing/black background though.
