### ISSUE TITLE
[x86] [ARM] WOCCatalog Foundation Tests - In URL Session, clicking Resume crashes the app

### ISSUE THREAD

**Issue by ashvarma** [Microsoft/WinObjC#1844]
Latest master build - with 1701 payload

**Comment by rajsesh-msft** [comment]
@aballway This is a result of #1607.      

[self _registerDownloadTask:newTask withCompletionHandler:completionHandler]; 

is called in multiple places in NSURLSession, but if resumeData is nil, we insert a nil object into the array and blow up.

**Comment by rajsesh-msft** [comment]
Not clear if reference platform allows this.

**Comment by rajsesh-msft** [comment]
Checked reference platform, this is indeed expected to crash.  We were previously passing nil value for resumeData and expecting the session to return a nil.
