### ISSUE TITLE
CoreGraphics - fix reliability issues 

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#1848]
- [x] #1194 
- [x] #1895

**Comment by DHowett-MSFT** [comment]
#1501 is solved in CGD2D already, so I checked it off for when it merges.

**Comment by DHowett-MSFT** [comment]
#1349 is tracking fonts only now. Image interpolation mode is supported as of #1557.

**Comment by DHowett-MSFT** [comment]
#1391 tracks the work in #1349 for fonts.
