### ISSUE TITLE
Can't open the source file "Foundation.tlh"

### ISSUE THREAD

**Issue by bleupierre** [Microsoft/WinObjC#185]
![vl n bgmpnfl8pva7tv 1ha](https://cloud.githubusercontent.com/assets/11518955/9843826/86b71264-5af0-11e5-94cb-6b822ad37135.png)
When I run the project, in the error list, it says: 
can't open the source file"........../projectName.vsimporter/...../Debug/Foundation.tlh"

**Comment by asimonov-msft** [comment]
@bleupierre The .tlh errors come from IntelliSense because it doesn't yet understand Objective C. These errors should not cause compilation problems.

**Comment by bleupierre** [comment]
@asimonov-msft  thank you, it's helpful for me
