### ISSUE TITLE
[Islandwood Manor] "Tap Explore to enter the room" arrow is placed incorrectly

### ISSUE THREAD

**Issue by ArnOmsft** [Microsoft/WinObjC#1854]
This was found using the 20161102.1 github develop (commit e7ae8b7b0362c440bc585acfbd06b8bc62264f71), 14957 rs_onecore_dep

Repro Steps:
1. Launch the app
2. Follow until after 'Go to the Living Room'.

Expected: The arrow floats over the 'Explore' button.
Results: The arrow floats inconsistently.

Note that it's only THIS PARTICULAR arrow that has this behavior. All other arrows seem to behave as expected.

**Comment by ArnOmsft** [comment]
From the original bug:
On the master 1029.1 build, this arrow did not appear at all, so this appears to be a bug that was uncovered by something else being fixed.

and:
MainViewController.m in IslandwoodManor app:
- (void)animationArrowAroundControl:(NSObject<SBLockableSupport> *)control

This grabs the arrow location from the UIView, and that seems broken.  This was probably related to the UILayer changes?

**Comment by rajsesh-msft** [comment]
Closing this issue as this seems sporadic and specific to the app.
