### ISSUE TITLE
[x86] Islandwood House - towards the end an unexpected UI flashes before the pop up

### ISSUE THREAD

**Issue by ashvarma** [Microsoft/WinObjC#1866]
This is on the master build which has the 1701 payload - 20170127.1

Play the game till the very end. Just before you see the pop up which says - 
"Islandwood Demo
Thanks for playing ..."

you'll see some colorful text and other UI layers which momentarily show up and then disappera

**Comment by rajsesh-msft** [comment]
This seems app specific, so closing this for now.
