### ISSUE TITLE
Can't run the project

### ISSUE THREAD

**Issue by bleupierre** [Microsoft/WinObjC#187]
![n 0a k q kg q nk 8oi](https://cloud.githubusercontent.com/assets/11518955/9897762/c5f28726-5c7e-11e5-8355-a4598f893848.png)

I have opened my iOS project with vsimporter, but I  can't run it.
I don't know the reason.

**Comment by s5msft** [comment]
A lot more APIs have been implemented and/or stubbed since this issue was filed. Give your app a try with a more recent build of the SDK and feel free to open new issues for specific bugs/missing APIs/etc.
