### ISSUE TITLE
UTF8 encoded file paths don't work as expected on windows

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#1875]
All of the EbrFile* apis use char* and assume "ascii" encoding, which works okay for English. All of core foundation URL apis assume UTF-8 encoding (specifically url % encoding), and we assume it is ascii.

The most visible impact of this is that NSUserDefaults does not synchronize settings if the user name is in non-english and uses accent characters.

**Comment by rajsesh-msft** [comment]
@jboich thanks for reporting the issue with NSUserDefaults.

**Comment by rajsesh-msft** [comment]
The right place to fix this would be at Ebr* api level.  Rest of the code uses char* assuming UTF-8 encoded strings as ASCII strings. It would be straightforward to change CPathMapper to use wchar_t and enforce that conversion in the Ebr apis to UTF-16.

**Comment by jboich** [comment]
Hi, @rajsesh-msft ! I also would like to add that I noticed that at the current moment when **_CFCreateDirectory** gets path containing invalid characters, it returns **true** even if folder did not create. I think it's connected to the current issue.

Regards,
Julia

**Comment by rajsesh-msft** [comment]
@jboich, yes i saw that as well.  The issue appears to be silent failure when trying to create directories for which you don't have permissions (if the UTF8 encoded string is treated as Ascii, the user name "appears" different.  With #1891, this should be resolved.
