### ISSUE TITLE
I can't run the WOCCatalog on the Mobile Emulator

### ISSUE THREAD

**Issue by cloudmonkeypeng** [Microsoft/WinObjC#188]
I can run it on local machine or simulator.

But I can't run it on Mobile Emulator 10.0.10240.0 WXGA 4.5 inch 1GB (Debug ,Win32)

![image](https://cloud.githubusercontent.com/assets/3436559/9900451/7bb05228-5c93-11e5-893d-261cd3d99a1a.png)
![image](https://cloud.githubusercontent.com/assets/3436559/9900456/85a70128-5c93-11e5-8e1a-b9c02b8e53f1.png)

Where can I find the dependent dll? Or should I do something else?

**Comment by cloudmonkeypeng** [comment]
![image](https://cloud.githubusercontent.com/assets/3436559/9900486/b750c8b2-5c93-11e5-93be-8c1d2b70845f.png)

**Comment by rajsesh-msft** [comment]
This issue should have been resolved now.

**Comment by cloudmonkeypeng** [comment]
Yeah , now it works!
