### ISSUE TITLE
[CGD2D] [WocCatalog] Double text display in Text Display page

### ISSUE THREAD

**Issue by aballway** [Microsoft/WinObjC#1881]
Expected (on develop):
![image](https://cloud.githubusercontent.com/assets/7557395/22480151/3d23d068-e7a5-11e6-9a69-a6974b8b264e.png)

On CGD2D:
![image](https://cloud.githubusercontent.com/assets/7557395/22479684/86a02e50-e7a3-11e6-84ff-d406a914124a.png)

**Comment by DHowett-MSFT** [comment]
This is know, and it is due to shadows now being supported. All of the APIs responsible fro this say "shadows ignored", but lo and behold, they are not ignored. This is operating as expected for the reference platform ca. 6.0-7.0.

**Comment by DHowett-MSFT** [comment]
Originally in #1830.
