### ISSUE TITLE
XAMLCatalog custom text view AVs

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#1910]
Repro:
1) Open XAMLCatalog
2) Custom Text View
3) Type anything into the box

This repros in develop as of the CGD2D merge (#1892). However, I was using this as a test scenario until fairly late into CGD2D, so I suspect that the change that caused this was a part of the last merge from develop to CGD2D (#1889).

**Comment by oliversa-msft** [comment]
Investigating

**Comment by oliversa-msft** [comment]
We have a root cause and a fix for that issue in the projection. However, we are trying to find a band aid in the mean time as well until the projection fix can be made.

**Comment by oliversa-msft** [comment]
Hmmm, the band of unsafe_unretained didn't work; might need to address #1950 earlier if there are few alternatives.

**Comment by tadam-msft** [comment]
Resolving as a duplicate of 1950
