### ISSUE TITLE
Is there anybody who has imported an iOS project successfully without error or missing functions? 

### ISSUE THREAD

**Issue by yw346090249** [Microsoft/WinObjC#192]
If there is, would you mind sharing your project with me? I could not imported a simple iOS project without errors or missing functions.

**Comment by cloudmonkeypeng** [comment]
https://github.com/cloudmonkeypeng/WinObjC_demo

You can find it here. I think it can give you a help. 
This repo is just my toy. I am not sure I will maintain it later.

：）

**Comment by yw346090249** [comment]
Thx

**Comment by yw346090249** [comment]
@cloudmonkeypeng hi, how can I use it? When I open the solution (.sln file), the first project shows unavailable.

**Comment by cloudmonkeypeng** [comment]
Yeah, you just need open the .sln file.  I clone my repo again, and debug the repo correctly.

I guess maybe something wrong with your environment.
![image](https://cloud.githubusercontent.com/assets/3436559/9930353/bcd6449c-5d65-11e5-8d20-0fd037d2c0ee.png)

Can you debug the WOCCatalog in the samples?

**Comment by yw346090249** [comment]
@cloudmonkeypeng thank you for your answer. The first time I loaded your repo, and it told me that I need to install something. After I installed, it still did not work and told that load failed. When I tried to load manually, it told that "One or more errors occurred" without details.

**Comment by yw346090249** [comment]
@cloudmonkeypeng which way did you use to import the iOS project into windows project? vsimporter or the other way described in the wiki?

**Comment by cloudmonkeypeng** [comment]
I have used vsimporter to import the project.

**Comment by yw346090249** [comment]
@cloudmonkeypeng do you know how to import a project with the method two. I'm not very clear about how to use it. I have one try but it failed to build the project.

**Comment by yw346090249** [comment]
@cloudmonkeypeng I saw the picture of your repo and it seems that you just use the "label", right? I created a project using only "label" however when I tried to debug it in VS2015, it failed. Have you ever tried other elements such as "image view" and "textField"?

**Comment by fdierick** [comment]
@yw346090249 I have used UITextField, UITextView & simple view controller-based navigation (UINavigationController, UITabBarController). Right now the trick is to build & manage all your views programmatically, but I hear Storyboards & XIBs are high on the priority list.

**Comment by cloudmonkeypeng** [comment]
@yw346090249   I have found  if your downloaded SDK in another path which isn't same with us. My project will can't launch . I will test method two , "image view" and "textField".

**Comment by cloudmonkeypeng** [comment]
@yw346090249  I have test "image view " and "textField". I also find samples in the  WOCCatalog.
But my codes don't show well . Maybe it's a new bug.
```
- (void)viewDidLoad {
      [super viewDidLoad];

      UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(0, 100, 200, 30)];
      label.text = @"Hello World, Hello IslandWood,Hello WinObjC";
      label.backgroundColor = [UIColor blackColor];
      label.textColor = [UIColor yellowColor];
      label.textAlignment = UITextAlignmentCenter;
      label.font = [UIFont fontWithName:[[UIFont familyNames] objectAtIndex:10] size:20];

      UITextField *text = [[UITextField alloc]initWithFrame:CGRectMake(20, 20, 130, 30)];
      text.borderStyle = UITextBorderStyleRoundedRect;
      text.text = @"textTest";

      [self.view addSubview:label];
      [self.view addSubview: text];
}
```
Feel free to correct me . Because I'm a fish in IOS

**Comment by nicholasgerard-msft** [comment]
@yw346090249 Please file a new issue if you're still encountering problems importing your project to Visual Studio. A good place to start with the bridge is the included samples or by browsing the materials in [the wiki](https://github.com/Microsoft/WinObjC/wiki).
