### ISSUE TITLE
Crash in objc_loadWeakRetained

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#1924]
We’re seeing crashes with the following top of the stack trace:

```
libobjc2!objc_msgSend+0x47:

Stack trace:
ChildEBP RetAddr  
0888ef34 5528d5b5 libobjc2!objc_msgSend+0x47 [c:\users\duhowett\src\winobjc\deps\3rdparty\libobjc2\msvc\objc_msgsend.x86-32.masm.inl @ 15732480]
0888ef5c 007110f4 libobjc2!objc_loadWeakRetained+0xc5 [c:\users\duhowett\src\winobjc\deps\3rdparty\libobjc2\arc.m @ 712]
```

The failure reasons are `NULL_CLASS_PTR_READ_c0000005_libobjc2.dll!objc_loadWeakRetained`
and `NULL_POINTER_READ_c0000005_libobjc2.dll!objc_loadWeakRetained`.

The crash is in [deps\3rdparty\libobjc2\arc.m:712](https://github.com/Microsoft/libobjc2/blob/58a7fd2146eaa7312bd315e9e74e45433198e91f/arc.m#L712) and it looks like _objc_weak_load/_NSWeakLoad() is getting an invalid reference to the object, which causes the crash in objc_msgSend().

**Comment by DHowett-MSFT** [comment]
@triplef This is caused by a data loss bug in libobjc2's hash table implementation.

Microsoft/libobjc2#1.
