### ISSUE TITLE
CoreGraphics.Drawing build fails on reference platform

### ISSUE THREAD

**Issue by aballway** [Microsoft/WinObjC#1925]
Doesn't seem to be happy about unique_cf

CGContextDrawing_ImageMaskTests.cpp:167:36: note: in instantiation of function template specialization 'std::__1::unordered_map<unsigned int,
      woc::unique_cf<CGImage *>, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<const
      unsigned int, woc::unique_cf<CGImage *> > > >::emplace<int, woc::unique_cf<CGImage *> >' requested here
                    clippingImages.emplace(newShape | newType, std::move(clipImage));
                                   ^
..//../../include/xplat/Starboard/SmartTypes.h:541:19: note: copy constructor is implicitly deleted because 'unique_cf<CGImage *>' has a
      user-declared move assignment operator
    unique_cf<T>& operator=(unique_cf<T>&& other) = delete;
                  ^
1 error generated.
make: *** [..//../../build/Tests/UnitTests/CoreGraphics.Drawing/OSX/Objects/CGContextDrawing_ImageMaskTests.cpp.o] Error 1

**Comment by DHowett-MSFT** [comment]
That's less of a crash
and more of a build failure
