### ISSUE TITLE
_RegisterDependencyProperties should be moved out of the Layer::Layer constructor

### ISSUE THREAD

**Issue by oliversa-msft** [Microsoft/WinObjC#1930]
We cannot guarantee the the layer will be created first when we call _initWithXamlElement and expect that all dependency properties have been registered. We should move the registration of layer dependency properties into higher level initialization method such XamlCompositor::Initialize.

**Comment by ArnOmsft** [comment]
Marking this as urgent since Oliver mentioned this is blocking him.
