### ISSUE TITLE
We are trying to call ApplicationData.Current.LocalFolder while holding the loader lock in Corefounctaion dllmain

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#1955]
Callstack (I left some frames out (...) for brevity)
 	ntdll.dll!_ZwWaitForMultipleObjects@20 Line 821	Unknown
 	KernelBase.dll!WaitForMultipleObjectsEx Line 1551	C
....    
 	combase.dll!_RoGetActivationFactory Line 900	C++
 	combase.dll!RoGetActivationFactory Line 993	C++
>	Starboard.dll!Windows::Foundation::GetActivationFactory<ABI::Windows::Storage::IApplicationDataStatics> Line 240	C++
 	Starboard.dll!Windows::Foundation::GetActivationFactory<Microsoft::WRL::ComPtr<ABI::Windows::Storage::IApplicationDataStatics> > Line 921	C++
 	Starboard.dll!_IwGetWritableFolder Line 182	C++
 	Starboard.dll!IwGetWritableFolder Line 207	C++
 	Starboard.dll!CPathMapper::CreateDefaultPaths Line 142	C++
 	Starboard.dll!CPathMapper::CPathMapper Line 130	C++
 	Starboard.dll!EbrStat64i32 Line 152	C++
 	CoreFoundation.dll!_NS_stat64i32 Line 808	Objective-C++
 	CoreFoundation.dll!_CFGetPathProperties Line 597	Objective-C++
 	CoreFoundation.dll!_CFIsResourceCommon Line 96	Objective-C++
 	CoreFoundation.dll!_CFIsResourceAtURL Line 107	Objective-C++
 	CoreFoundation.dll!_CFBundleURLHasSubDir Line 217	Objective-C++
 	CoreFoundation.dll!_CFBundleGetBundleVersionForURL Line 301	Objective-C++
 	CoreFoundation.dll!_CFBundleCreate Line 906	Objective-C++
 	CoreFoundation.dll!CFBundleCreate Line 1036	Objective-C++
 	CoreFoundation.dll!RegisterCoreFoundationBundle Line 1390	Objective-C++
 	CoreFoundation.dll!DllMain Line 1407	Objective-C++
 	CoreFoundation.dll!dllmain_dispatch Line 195	C++
 	CoreFoundation.dll!_DllMainCRTStartup Line 248	C++
 	ntdll.dll!_LdrxCallInitRoutine@16	Unknown
....

**Comment by rajsesh-msft** [comment]
@pradipd what is broken because of this?
