### ISSUE TITLE
UIAlertViewStylePlainTextInput not supported

### ISSUE THREAD

**Issue by fdierick** [Microsoft/WinObjC#196]
I have an app which prompts the user for a text input using an NSAlert set to UIAlertViewStylePlainTextInput mode. The alert shows up on Windows (yay!) but there is not text input field :-(

Code:
```
[alert setAlertViewStyle:UIAlertViewStylePlainTextInput];
alert.delegate = self;
[alert show];
```

Expected Result: Windows equivalent of "UIAlertview" pops up WITH a textfield.
Actual Result: Windows equivalent of "UIAlertview" pops up without embedded textfield.
Outcome: I am sad.

**Comment by ArnOmsft** [comment]
UIAlertview have been deprecated in iOS 8. We do not support this style in the current implementation and when we'll implement this we'll use UIAlertController introduced in iOS 8.
Closing this.
