### ISSUE TITLE
Crash in AsyncDevice::rotateResourceIdentities

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#1964]
We’re seeing multiple crashes with the following failure reason:
`NULL_CLASS_PTR_READ_c0000005_nvwgf2um.dll!AsyncDevice::rotateResourceIdentities`

Stack trace (cab ID a73e0ba3-d5f6-454e-a2df-5193430db42c):
```
nvwgf2um+0x139234:

Stack trace:
ChildEBP RetAddr  
WARNING: Stack unwind information not available. Following frames may be wrong.
1399f218 679926e5 nvwgf2um+0x139234
1399f27c 6ca45b82 nvwgf2um+0xa26e5
1399f350 6c9a1746 d3d11!NDXGI::CDevice::RotateResourceIdentities+0x322
1399fb44 6c97d57c dxgi!CDXGISwapChain::PresentImplCore+0x18476
1399fbb0 6c97dd89 dxgi!CDXGISwapChain::PresentImpl+0x7b
*** WARNING: Unable to verify checksum for libGLESv2.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for libGLESv2.dll - 
1399fc14 63369293 dxgi!CDXGISwapChain::[IDXGISwapChain4]::Present1+0x79
00000000 00000000 libGLESv2!glWaitSync+0x47e53
```

We’re unsure whether this might be caused by something in our code, but given our code is not contained in the stack trace we’d appreciate if this could be investigated.

**Comment by rajsesh-msft** [comment]
@triplef This is a crash in the NVidia display driver.  We can discuss the next steps here offline.
