### ISSUE TITLE
objc/blocks_runtime.h doesnot work with modules turned on in visual studio

### ISSUE THREAD

**Issue by venkatkongara** [Microsoft/WinObjC#1976]
Try and use Block_copy()/Block_release() Macros from c++( objc/blocks_runtime.h). 
Visual studio 2015 complains that an unresolved identifier is used.
I have installed 10.0.14393.0 Windows SDK for building/running Visual studio.

**Comment by rajsesh-msft** [comment]
@venkatkongara can you clarify your scenario?  Why are you using objective-c from c++ source file?  Do you mean objective c++?  Also a small repro case will help.

**Comment by venkatkongara** [comment]
@rajsesh-msft I am trying to use Block_copy()/Block_release()  c++ Macros in Objective C to maintain the life cycle of the block in the source code of AFNetworking SDK to be able to use it on Visual Studio projects.

**Comment by venkatkongara** [comment]
static const void * AFNetworkReachabilityRetainCallback(const void *info) {
    return Block_copy(info);
}

static void AFNetworkReachabilityReleaseCallback(const void *info) {
    if (info) {
        Block_release(info);
    }
}


These are the defined functions in a .m file with #import <netinet/in.h> at the top of the file.

**Comment by ms-jihua** [comment]
Hi @venkatkongara, I'm unable to repro your issue on VS2017. Could you try to build your code in VS2017 and tell us whether you still encounter this problem?

**Comment by memontic-ms** [comment]
Fixed in #2544
