### ISSUE TITLE
OSX unit tests don't respect gtest_filter or other args

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#1978]
Repro steps:
1) Build OSX unit tests
2) Run OSX unit tests --gtest_filter=*SomethingReasonable*

Expected: limited set of tests run
Actual: all tests run

This seems to be caused by our hard-coding of args in EntryPoint.cpp::74

**Comment by rajsesh-msft** [comment]
could you address this along with the other OSX compat tests?

**Comment by ms-jihua** [comment]
as a starting point, the issue seems to be that we changed how we take args in EntryPoint.cpp when we moved to TAEF.

**Comment by rajsesh-msft** [comment]
@ms-jihua load balancing this back to you :).

**Comment by ms-jihua** [comment]
Scratch my comment, I missed that @aballway already fixed this in #2251.
