### ISSUE TITLE
Projections expose protected interfaces

### ISSUE THREAD

**Issue by bviglietta** [Microsoft/WinObjC#1983]
The UWP projections expose protected interfaces, which are not intended to be used by client code.

For example, the projected XAML Control class and all its subclasses expose the IControlProtected interface, which has the [protected] attribute and therefore shouldn't be accessible. I should not be able to write this code:

WXCButton* button = [WXCButton make];
[button getTemplateChild:@"name"];    // Bad! This method should not be visible

**Comment by mukhole** [comment]
Blocked on bug#2319
