### ISSUE TITLE
iOS -> Win PC? 

### ISSUE THREAD

**Issue by Romascu** [Microsoft/WinObjC#1989]
Hello, is it possible to make a iOS app run on Windows Desktop (and in the store)?

Thank you.

**Comment by rajsesh-msft** [comment]
@Romascu you can use the source code for your iOS app and build it as a windows store app for both desktop and windows phone devices.  Your mileage may vary depending on which frameworks you use.  Please be sure to check-out our [Wiki](https://github.com/Microsoft/WinObjC/wiki/Getting-Started).
