### ISSUE TITLE
 OpenGL ES example does not work on DirectX Feature Level 9_3

### ISSUE THREAD

**Issue by jboich** [Microsoft/WinObjC#1993]
If DirectX Feature Level 9_3 parameters are used to initialize EGL then the model in  OpenGL ES example of WOCCatalog does not render. Inside bridge the next line causes GL_INVALID_OPERATION  error
`   glBlitFramebufferANGLE(0, 0, _rbWidth, _rbHeight, 0, 0, _rbWidth, _rbHeight, GL_COLOR_BUFFER_BIT, GL_NEAREST);`
of  `- (BOOL)presentRenderbuffer:(int)target`
 
Also using multisampling causes GL_OF_MEMORY exception when calling 
`- (BOOL)renderbufferStorage:(int)target fromDrawable:(CAEAGLLayer*)surface`

**Comment by rajsesh-msft** [comment]
Given that this is not widely reported, we will close this issue for now.  Lets re-activate if this becomes a blocker in the future.
