### ISSUE TITLE
cancelPerformSelector... written wrong

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1995]
Dear WinObjC Engineers,

In NSRunLoop.mm:

- (void)cancelPerformSelector:(const char*)selector target:(NSObject*)target argument:(NSObject*)argument {

is written wrong.

Sincerely,

Ed

**Comment by DHowett-MSFT** [comment]
Wow, we're still treating selectors as character strings? That'll never work.

_(that is the complaint here, right? it looks like it should work otherwise.)_

**Comment by edvv** [comment]
@DHowett-MSFT 


- The signature does not use SEL (you are right)

- The API does not appear in the header file (thus unsuspectingly overwriting what should be the published API with a private implementation that is not right.

- The implementation does not use a mark and sweep, thus the O(computation) is inefficient (although it probably does not matter too much).

**Comment by rajsesh-msft** [comment]
Would be a good opportunity to fix issues 1 and 2.  We can change the linear scan to some kind of map if it really turns out to be a performance issue.

**Comment by aballway** [comment]
Closed with #2121
