### ISSUE TITLE
NSData base64EncodedStringWithOptions works very slow

### ISSUE THREAD

**Issue by jboich** [Microsoft/WinObjC#1996]
Hi.
Converting of audio file of size around 7MB to string using base64EncodedStringWithOptions takes 2 minutes. Also to be able to playback audio file I have to delete all newlines  in the string I get from base64EncodedStringWithOptions and this operation takes 1 minute. So the app won't respond to user for 3 minutes because of these convertings.

```
NSLog(@"start encode data");
NSString *str = [audioData base64EncodedStringWithOptions:NSDataBase64Encoding64CharacterLineLength];
NSLog(@"end encode data");
str = [str stringByReplacingOccurrencesOfString:@"\r\n" withString:@""];
NSLog(@"end replacing newlines");
```

I took a look into the bridge and if I delete the code that adds linebreaks than the operation base64EncodedStringWithOptions takes 0.094 seconds
```

`/*  // Add new line every (lineLength) chars
            // Iterate backwards to avoid compensating for changes in length
            for (size_t i = newLineCount; i > 0; i--) {
                [mutableEncodedString insertString:newLineChar atIndex:(i * lineLength)];
            }

			*/`

```

Why are these newlines added? Is it possible to get rid of them or make some optimization?

Thank you in advance!
Kind regards,
Julia

**Comment by DHowett-MSFT** [comment]
The documentation for `NSDataBase64Encoding64CharacterLineLength` states:

> Set the maximum line length to 64 characters, *after which a line ending is inserted.*

(emphasis mine)

While it looks like our version has performance issues, it doesn't seem reasonable to request newlines and then remove them. If you remove the `NSDataBase64Encoding64CharacterLineLength` option, you don't need to worry about newlines and you should save a lot of time.

**Comment by jboich** [comment]
Hi, @DHowett-MSFT . Thanks for a quick feedback!

> but instead of asking for newlines and then removing them, you could save a lot of time by simply not asking for newlines.

yes, you are totally right :)

In OSX and iOS NSDataBase64Encoding64CharacterLineLength adds only '\n' but 
in Windows it also adds '\r'
because of '\r' ending the audio file does not play

**Comment by DHowett-MSFT** [comment]
Oh! I was just looking at that code. We might have a Default Value mismatch between the various CR/LF options.

In the interim, does removing the newline option unblock you? :smile:

**Comment by jboich** [comment]
Hi, @DHowett-MSFT .

> In the interim, does removing the newline option unblock you? 

Yes, this approach work great:
` NSString *str = [audioData base64EncodedStringWithOptions:0];`

**Comment by rajsesh-msft** [comment]
Thanks @DHowett-MSFT, @jboich.  I will keep this issue active to at least change this to a caveat.
