### ISSUE TITLE
CGBitmapContextCreate() regression when using latest HEAD of master branch. 

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#1997]
We use some code like the following to resize a UIImage using CoreGraphics.

When using a build of winobjc from the HEAD of master (ffe05fa6e5c7819a6cb2c9105ed9694245656842) this code no longer works and the created `newImage` is nil.

Picking through it, it seems `CGBitmapContextCreate()` returns a nil `CGContextRef`.

This code works fine using the 0.2 170201 1st Feb release.

```
UIImage *image = [UIImage imageNamed:@"someImage"];
CGSize size = CGSizeMake(64.0, 64.0);
CGFloat scaleFactor = [UIScreen mainScreen].scale;
CGRect newRect = CGRectIntegral(CGRectMake(0, 0, size.width, size.height));
CGImageRef imageRef = image.CGImage;
	
CGContextRef bitmap = CGBitmapContextCreate(NULL,
                                                newRect.size.width * scaleFactor,
                                                newRect.size.height * scaleFactor,
						CGImageGetBitsPerComponent(imageRef),
						0,
						CGImageGetColorSpace(imageRef),
						CGImageGetBitmapInfo(imageRef));
	
CGContextScaleCTM(bitmap, scaleFactor, scaleFactor);

CGContextDrawImage(bitmap, newRect, imageRef);
	
CGImageRef newImageRef = CGBitmapContextCreateImage(bitmap);
UIImage *newImage = [UIImage imageWithCGImage:newImageRef scale:scaleFactor orientation:UIImageOrientationUp];
	
CGContextRelease(bitmap);
CGImageRelease(newImageRef);
```

**Comment by DHowett-MSFT** [comment]
@rupertdaniel can you share the debugging output from context create time? We should be printing out the failing context parameters.

When you don't pass `data`, CGBitmapContext should accept almost any format. It's very strange that it's not!

**Comment by msft-Jeyaram** [comment]
@rupertdaniel @DHowett-MSFT  I suspect it's due to bytesPerRow being 0 and automatic calculations aren't happening. So we try to find a bpp of 0 in the map.

**Comment by DHowett-MSFT** [comment]
Good catch, @msft-Jeyaram.

**Comment by rupertdaniel** [comment]
@DHowett-MSFT if you still need it here is some input/output from the call to `CGBitmapContextCreate()`

`bitmapRef: 00000000 bitsPerComponent: 8 colorSpace: 09A32760 bitmapInfo: 8196`
