### ISSUE TITLE
Building and using Windows Runtime components in Objective-C

### ISSUE THREAD

**Issue by Alovchin91** [Microsoft/WinObjC#20]
I would like to see an ability to build Windows Runtime components that can be used from any supported language using the existing Objective-C code. This would make possible for Objective-C devs spending as little effort building Windows Runtime components using the existing code as possible.

For now, there is only info on how to use Windows Runtime APIs from Objective-C code, but there is nothing I can find regarding how Objective-C code can be used from C++/CX. Building Windows Runtime components could be achieved in two ways: building the ability to create WinRT components into Objective-C compiler and linker, and/or enabling interoperability between C++/CX and Obj-C code so WinRT components could be built using C++/CX that imports Obj-C functions.

Also consider the ability to use custom WinRT components written in any WinRT language (C++, C#, etc.) from Objective-C code.

**Comment by rhaning** [comment]
This is on our backlog and we are actively prototyping. Stay tuned.

**Comment by rogersachan** [comment]
Any progress?

**Comment by jboich** [comment]
> consider the ability to use custom WinRT components written in any WinRT language (C++, C#, etc.) from Objective-C code.

I would like to have this too!

**Comment by rajsesh** [comment]
https://github.com/Microsoft/WinObjC/tree/master/tools/objc2winmd is the tool.  The built version of this is available in the tools package from the latest release.  This should work for many common OBJC data types, please check it out.
