### ISSUE TITLE
Evaluation virtual machines won’t boot

### ISSUE THREAD

**Issue by alakoring** [Microsoft/WinObjC#2000]
From https://developer.microsoft.com/en-us/windows/bridges/ios I tried downloading the VirtualBox VM. When I tried using it, I got repeated UMOUNTABLE BOOT VOLUME blue screens.

I then bought VMware Fusion and downloaded the VMware image. Same thing. (It gives me an alert, You do not have write access to a partition, but I click Allow All.)

Last year I had managed to get the VirtualBox VM up and running (I just didn't get around to trying out Windows Bridge for iOS).

Would it be possible to get new VMs? I think this is a good time in the project to see how useful Windows Bridge could be.

(VMware Fusion Version 8.5.3 (4696910) running on macOS 10.12.3)

**Comment by alakoring** [comment]
I somehow managed to get this to work with VMware but cannot remember how. Please give a paragraph of instructions as to how to make the VM — I think I imported (where previously I was trying to create from scratch) but not sure from what.

Please consider that your audience is iOS developers — I have not touched Visual Studio in over 5 years. (Which is why I really appreciate the idea of these VMs and want to get them to work.)

**Comment by weswmsft** [comment]
I'll refer you to the documentation for your VM provider -- it is different for every VM solution. The basic recipe is to create a VM, mount the Windows ISO in the VM, boot and install Windows.  Accessing your source files from outside the VM should be done over network shares as the shared folder feature does not work well.
