### ISSUE TITLE
Can’t build against Foundation

### ISSUE THREAD

**Issue by alakoring** [Microsoft/WinObjC#2008]
My app uses CocoaLumberjack. It won’t build:

Error		could not acquire lock file for module 'Foundation'	CocoaLumberjack-iOS	\\vmware-host\Shared Folders\SixAges\Libraries\CocoaLumberjack-master\Framework\Lumberjack\CocoaLumberjack-Prefix.pch	6	

where the .pch file is

```
//
// Prefix header for all source files of the 'Lumberjack' target in the 'Lumberjack' project
//

#ifdef __OBJC__
	#import <Foundation/Foundation.h>
#endif
```

I’m using the 1612 VM.

**Comment by alakoring** [comment]
I saw that you said to copy & paste the log (https://github.com/Microsoft/WinObjC/wiki/FAQ#how-do-i-get-my-project-log-file-to-help-determining-the-cause-of-an-issue) but 621K seems a bit big…

[Six Ages.log.zip](https://github.com/Microsoft/WinObjC/files/788379/Six.Ages.log.zip)

**Comment by alakoring** [comment]
Aha, I copied everything from a shared folder and no longer get that issue, I get

Error		'asl.h' file not found	CocoaLumberjack-iOS	C:\Users\User\Documents\SixAges\Libraries\CocoaLumberjack-master\Classes\DDASLLogCapture.m	25	

which is probably merely something that has not been ported.

(Building from a shared folder would be really good, since I have no idea how to set up Git in Visual Studio and the folder in question is almost 5GB and it would be nice not to duplicate it.)

**Comment by antoine-haas** [comment]
@alakoring, CocoaLumberjack has indeed not yet been ported as per issue #173. For the shared folder issue, I'm going to follow up in issue #2007 to properly track them separately.

**Comment by weswmsft** [comment]
I think there was follow up offline on this. The vm shared folders are problematic and using network shares will correct the issue.
