### ISSUE TITLE
performSelectorOnMainThread:... issue

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#2009]
Dear WinObjC Engineers,

In the file:
NSKeyValueCoding.mm

method:
performSelectorOnMainThread:...

when:
waitUntilDone is NO
(or even YES)

I see that it eventually directly calls:
- [NSRunLoop _wakeUp];
for the main thread run loop.

But, I fail to see how the thread execution context is changed. It appears that the performSelectorOnMainThread is actually executing on the thread that it is called upon (albeit using the run loop of the main thread).

Is that true?

Sincerely,

Ed

**Comment by rajsesh-msft** [comment]
@edvv, the main thread tasks are performed in main thread thorough the dispatcher.  I don't see an actual issue here, are you getting the callbacks on the wrong thread?

**Comment by edvv** [comment]
@rajsesh-msft performSelectorOnMainThread:... has been replaced with custom dispatching which works as expected, so this issue is no longer a blocker and I'm closing it.
