### ISSUE TITLE
VSImporter incorrectly adds additional deps for framework libraries

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#2017]
Actual:
`
<AdditionalDependencies>%(AdditionalDependencies);CoreGraphics.lib;Foundation.lib;UIKit.lib;libsqlite3.lib;libxml2.lib</AdditionalDependencies>`

Expected:

`<AdditionalDependencies>%(AdditionalDependencies);libsqlite3.lib;libxml2.lib</AdditionalDependencies>`

**Comment by bbowman** [comment]
maybe not a real issue.

**Comment by memontic-ms** [comment]
fixed in #2418
