### ISSUE TITLE
Sample application(my app) crashes with error

### ISSUE THREAD

**Issue by ninjanpotter** [Microsoft/WinObjC#202]
1st Question: First time while building the build file , it successfully built and generated the sdk. And everything went fine. Now again I built the build . Its showing this error. (Should I build it only once)

Error : cannot open input file 'StarboardWin32.lib' Package D:\PortingPOC\WinObjC-master\build\Package\LINK 1

2nd Question: I tried building the sample projects , it worked fine. Now using vsimporter.exe from cmd , I got the solution file for my ios project but it throws the following error while building?

Error LNK1181 cannot open input file 'StarboardXaml.lib'

 D:\PortingPOC\WinObjC-master\build\SDKPackage\Release\samples\trialView\trialView.vsimporter\trialView-WinStore10\LINK 1

**Comment by asimonov-msft** [comment]
@ninjanpotter Which solution, configuration and platform are you using to build the SDK?
The second error you described looks to be related to the SDK build failure.

**Comment by ninjanpotter** [comment]
For 1st one : Solution: WinObjC\build.
                      Configuration:  ???? Please tell me what it is? I set the path of winobjc in VC++ directories paths.
                    Platform:  U mean the IDE or Language? 

For 2nd one: That's my own application which I developed in xcode myself and added inside samples folder and got a solution file using vsimporter.exe.

**Comment by ninjanpotter** [comment]
And please mention about \LIBPATH . The error is based on the linker I guess.

**Comment by PooyaZv** [comment]
Our apologies for the delayed response. We have a new release of the compiler. Can you try with the new version to see if the problem still persists?

**Comment by PooyaZv** [comment]
@ninjanpotter : I will close this issue since we don't have enough information to proceed including whether or not the issue has been resolved with the substantial changes since when it was opened. Should you run into this again, please let us know and we'd be happy to look into it further.
