### ISSUE TITLE
Break CoreGraphics and CoreText's dependencies on Foundation + UIKit

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#2026]
Right now, CoreGraphics and CoreText build as Objective-C and use Foundation collections and CGColor bridges UIColor in reverse (that is: CGColor lazy-loads UIColor even though UIKit depends on CoreGraphics).

In an ideal world, CG and CT would be C++ frameworks depending only on CoreFoundation.

**Comment by msft-Jeyaram** [comment]
This can be closed as per the below pull requests:

#2427, #2437, #2586, #2479,#2437,#2379,  #2511, #2374, #2361, #2364, #2538
