### ISSUE TITLE
[TAEF] Graphics Drawing tests show invalid results

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#2027]
the tests that should be failing shows up as passed.

**Comment by DHowett-MSFT** [comment]
Do you have a concrete example of this?

**Comment by msft-Jeyaram** [comment]
Enable a failing test.
Any of the disabled ones should make it work.
If you want specific try:
DISABLED_DRAW_TEST_F(CGPatternTests, PatternFillWindowsLogoRotate
or 
DISABLED_DRAW_TEST_F(CGPatternTests, PatternDrawPath
or 
DRAW_TEST_F(CGContext, Canva,
etc
