### ISSUE TITLE
Implement stubbed Transform path apis

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#2043]
CGPathCreateCopyByTransformingPath
CGPathCreateMutableCopyByTransformingPath

**Comment by MSFTFox** [comment]
These APIs are already marked interoperable and in use by CGContext in CGContextAddPath. This was implemented to resolve the failures in transforms and CGPath in pull request #1550.

**Comment by rajsesh-msft** [comment]
There is a TODO in https://github.com/Microsoft/WinObjC/blob/develop/Frameworks/CoreGraphics/CGContext.mm#L1100.  Lets remove that then.

**Comment by rajsesh-msft** [comment]
Closing.  will deal with this separately. @DHowett-MSFT hopefully we can address this in you PR.
