### ISSUE TITLE
Establish baseline and target app launch performance targets

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#2049]
Gather baseline health status/targets for on-disk footprint, launch time, and post-launch working sets in:

- WinObjC MinApp (HelloUI - probably should remove animation from the label though)
- C# MinApp (HelloUI clone that we'll need to create)
- BigApp (IWNews)

**Comment by jaredhms** [comment]
This task also tracks finding/filing more perf bugs in the app launch path.

**Comment by rajsesh-msft** [comment]
Closing this proactive perf analysis task, we can revive this as needed for specific scenarios.
