### ISSUE TITLE
Implement -[NSString containsString:]

### ISSUE THREAD

**Issue by alakoring** [Microsoft/WinObjC#2057]
```
if ([zone.name containsString: @"Spill"]) {
```

Error		no visible @interface for 'NSString' declares the selector 'containsString:'	

```
/* Simple convenience methods for string searching. containsString: returns YES if the target string is contained within the receiver. Same as calling rangeOfString:options: with no options, thus doing a case-sensitive, locale-unaware search. …
*/
- (BOOL)containsString:(NSString *)str NS_AVAILABLE(10_10, 8_0);
```

**Comment by rajsesh-msft** [comment]
In the meanwhile, you can use rangeOfString instead.

**Comment by alakoring** [comment]
Right, though I was so happy to finally be able to require iOS 8 and use the more readable one.

Turns out I need `-localizedCaseInsensitiveContainsString:` as well.

**Comment by rajsesh-msft** [comment]
@alakoring, a number of new methods were added to NSString interface, none of which are defined or implemented.  Both these methods are short hands for rangeOfString and rangeOfString:options.  

I've added this to the backlog now.  However, you can implement these as well and submit a pull request (https://github.com/Microsoft/WinObjC/wiki/How-to-Contribute) if you need these sooner.  We are open source after all :)
