### ISSUE TITLE
Unable to Clear/Fill an Arc geometry that sweeps 0<->2*PI

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#2059]
We add an arc to the context and attempt to fill it via d2d's fillGeometry.
D2D succeeds in doing that, but visually we don't see the fill.

sample code:
`    CGRect cirleRect = CGRectMake(0, 0, 100, 100);
    CGContextAddArc(context, 50, 50, 50, 0.0, 2 * M_PI, 0);
    CGContextClip(context);
    CGContextClearRect(context, cirleRect);`

Within the CGContext, we obtain the clippingGeometry for the current state and attempt to fill it.
This is where we don't see the desired result.

Note: If create an equivalent ellipse geometry and attempt to fill it, we obtain the desired output.
I suspect there are some issues with how our arc geometry is being generated.

**Comment by DHowett-MSFT** [comment]
Thanks for filing this. I wonder if the same thing happens if you use `CGContextFillPath` instead of `CGContextClip` + `CGContextClearRect`!

**Comment by msft-Jeyaram** [comment]
It's only with CGContextAddArc , creating from 2pi to 0.
Creating a mutable path and adding lines, works fine for fill and clear rect.

@MSFTFox  knows what's going on with the Arc creation and looking into it

**Comment by msft-Jeyaram** [comment]
depends on this being fixed #2062
