### ISSUE TITLE
VSImporter Bundle projects don't build with VS2017 RC.

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#2060]
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(358,5): error MSB8016: This project does not support the current Configuration Type (Utility).

as an example failure. This project needs re-thought.

**Comment by memontic-ms** [comment]
Merged into packaging branch. 
Bundle projects still need more thought and a redesign.
