### ISSUE TITLE
[WOCCatalog] App exits unexpectedly while idle

### ISSUE THREAD

**Issue by kellymor** [Microsoft/WinObjC#2064]
After building the WOCCatalog sample for Debug/Win32 and using the sample app, it eventually closes unexpectedly.

Install WOCCatalog (debug) from release drop share
Open WOCCatalog
Walk through WOCCatalog Test Script
Leave the app idle

Expected Result:
App remains active and responsive

Actual Result:
App exits unexpectedly with following error:  'ApplicationFrameHost.exe' (Win32): Unloaded 'C:\Windows\System32\Windows.UI.dll'
Exception thrown at 0x00007FFF6180BEF8 (KernelBase.dll) in ApplicationFrameHost.exe: 0x80010108: The object invoked has disconnected from its clients.

**Comment by ashvarma** [comment]
Tried on 2 separate machine - unable to repro this issue

**Comment by kellymor** [comment]
Adding stack trace from the failure:

>	EdgeManager.dll!Microsoft::WRL::Details::RuntimeClass<Microsoft::WRL::Details::InterfaceList<IInspectable,Microsoft::WRL::Details::InterfaceList<Windows::UI::Core::INavigationFocusEventArgs,Microsoft::WRL::Details::InterfaceList<Windows::UI::Core::ICoreWindowEventArgs,Microsoft::WRL::Details::Nil> > >,Microsoft::WRL::RuntimeClassFlags<1>,1,1,0>::Release() Line 2017	C++
 	threadpoolwinrt.dll!Windows::System::Threading::CThreadPoolTimer::TimerCallback(_TP_CALLBACK_INSTANCE * instance, void * context, _TP_TIMER * timer) Line 545	C++
 	ntdll.dll!TppTimerpExecuteCallback(_TP_CALLBACK_INSTANCE * Instance, _TP_TASK * Task) Line 2293	C
 	ntdll.dll!TppWorkerThread(void * Parameter) Line 1109	C
 	kernel32.dll!BaseThreadInitThunk(unsigned long RunProcessInit, long(__stdcall*)(void *) StartAddress, void * Argument) Line 64	C
 	ntdll.dll!__RtlUserThreadStart(long(__stdcall*)(void *) StartAddress, void * Argument) Line 997	C
 	ntdll.dll!_RtlUserThreadStart(long(__stdcall*)(void *) StartAddress, void * Argument) Line 914	C

**Comment by oliversa-msft** [comment]
This is not a recent regression; @kellymor and @jaredhms confirmed it is present in December's release as well.

**Comment by rajsesh-msft** [comment]
This is a platform bug for which fix is in the works.
