### ISSUE TITLE
Finish NSArray KVO methods

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#2068]
These should throw exceptions per documentation.

addObserver:forKeyPath:options:context:
removeObserver:forKeyPath:
removeObserver:forKeyPath:context:

These should be implemented:

addObserver:toObjectsAtIndexes:forKeyPath:options:context:
removeObserver:fromObjectsAtIndexes:forKeyPath:context:
removeObserver:fromObjectsAtIndexes:forKeyPath:

**Comment by DHowett-MSFT** [comment]
@rajsesh is this for NSArray?

**Comment by rajsesh-msft** [comment]
@DHowett-MSFT yes.  I thought the title of "f" was descriptive enough.
