### ISSUE TITLE
Missing drawInRect method in NSString

### ISSUE THREAD

**Issue by volkrass** [Microsoft/WinObjC#207]
Code looks like this:

CGRect rc = CGRectMake (x, y, cx, cy);
NSString* number = [NSString stringWithFormat:@"%i",i];
[number drawInRect:rc withAttributes:attributes];

I get following errors:
objcrt.dll!objc_RaiseNotImplementedException(const char * format, ...) Line 109
objcrt.dll!objc_not_found_handler(objc_object * obj, const objc_selector * sel) Line 60
objcrt.dll!objc_msg_lookup(objc_object * obj, const objc_selector * sel) Line 100
myapp.exe!_i_ChartView__drawRect_(ChartView * rect, objc_selector *

I see that in UIStringDrawing.h there is a method:
- (void)drawInRect:(CGRect)rect withAttributes:(NSDictionary *)attrs; 

It seems to be that this method is added by Microsoft because in chameleon code i'can't find it.
@s5msft : Question is where is the implementation?

**Comment by rajsesh-msft** [comment]
Available in release 0.1.0.151222

**Comment by volkrass** [comment]
@rajsesh-msft Last missing function in my project for now :) Thanks a lot.
