### ISSUE TITLE
Pori app saves images upside down and cropped

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#2095]
![image](https://cloud.githubusercontent.com/assets/13719817/23321562/ea8d46ec-fa94-11e6-9bac-0f6df4cdbc8f.png)

**Comment by DHowett-MSFT** [comment]
This is perhaps the funniest thing I've seen all week.

**Comment by jaredhms** [comment]
@yiyang-msft, last time this regressed, it was a bug in UIScrollView.  Can you please take a look?

**Comment by DHowett-MSFT** [comment]
You're going to love this.
