### ISSUE TITLE
Linker Error: LNK2019 unresolved external symbol ___objc_class_name_SKStoreProductViewController

### ISSUE THREAD

**Issue by Buju77** [Microsoft/WinObjC#210]
I'm trying to port one of our smaller projects to WinObjc but i'm getting linker errors.

Is my project settings somehow wrong or is StoreKit not implemented yet? Because its a linker error. Is there a way to work around this?

**Comment by ArnOmsft** [comment]
StoreKit is not supported and will not work to submit your app on the Windows Universal Store. You have to use StoreKit to submit your app on the Apple store and in the same way you'll have to use the Microsoft In-App purchase API to submit your app on the Universal Windows store. We're thinking of implementing an interop layer that would minimize the work for you but we have more important work to focus on for now. But you should be able to use the Windows APIs already, you can find more info here https://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.store.aspx and also on https://dev.windows.com/en-us/monetize in the "In-app purchases" section.
Thanks.

**Comment by mgoemmel** [comment]
There are two files in Frameworks/limbo: SKProductsRequest.mm and SKPaymentQueue.mm. They both look like a first try for a possible bridge between the Windows Universal Store and the AppStore. I guess most iOS developers would need StoreKit to handle InApp purchases, which seems to be possible to implement to me. The way the Universal Windows Store and the Apple AppStore is handling InApp purchases is nearly identical, isn't it.

So a brigde should be not that hard to implement. Or am I wrong?

**Comment by technotrance** [comment]
You should develop like a smaller type of library with inter functional adjustable programme based utility for eg being able to upload a driver for a programme this will act as a far better link for your programmes and a tip put it into a drawer but to finalise you must put in like a log in and log out system other wise the programme will not operate

**Comment by ArnOmsft** [comment]
The Objective-C projections of the WinRT APIs for in-app purchase (Windows.ApplicationModel.Store namespace) are available and are the way to go to implement your in-app purchase scenario on Windows. We actually ship with our weekly release a sample app called WinRTSample that include an example of in-app purchase implementation, that should help.

**Comment by ArnOmsft** [comment]
And you should no longer get the linker error since we stubbed out all the unsupported methods a few weeks ago, so you should retry with the latest release. Note that does not mean StoreKit will work, you won't get the linker error anymore but you still need to use the projections to get your in-app purchase scenario working in Windows. Thanks.
