### ISSUE TITLE
Use of undeclared identifier 

### ISSUE THREAD

**Issue by riasatmirsk** [Microsoft/WinObjC#211]
Import the iPhone app project into visual studio. Build the project and it displays the 7 errors use of undeclared identifier 'UIUserNotificationSettings' Use of undeclared identifier 'notificationSettings' use of undeclared identifier 'UIUserNotificationSettings'  use of undeclared identifier 'AF_INET' Use of undeclared identifier 'KSCNetworkFlagsReachable' use of undeclared identifier 'KSCNetworkFlagsConnectionRequired'  and this error also no visible @interface for 'UIApplication' declares the selector 'registerUserNotificationSettings'. How can i resolve these errors.

**Comment by rhaning** [comment]
We've added these items to our backlog to review for a future release.
