### ISSUE TITLE
UIViewController viewDidAppear/viewDidDisappear called too soon

### ISSUE THREAD

**Issue by ehren** [Microsoft/WinObjC#2114]
During a modal dismiss, the current implementation tears down the presented-presenting relationship just before calling the user completion block (but after viewDidDisappear: is called on the modal). This doesn't match the ref platform where e.g. presentingViewController should be nil on viewDidDisappear: of the modal.

(cause of a crash in our app due to some tricky conditional logic checking if a view controller is presenting a modal during a view event).

**Comment by edvv** [comment]
The beingDismissed and beingPresented properties are just stubs, so it is difficult to be picky about this issue. There are a lot of code sections that need thorough thinking out, and this is one of them. This is also an issue on iOS itself, and there is a lot of implementation-dependent code that attempts to navigate the view controller calling sequences.

**Comment by tadam-msft** [comment]
Fixed with #2195
