### ISSUE TITLE
LNK1181	cannot open input file 'SystemConfiguration.lib'

### ISSUE THREAD

**Issue by segadude** [Microsoft/WinObjC#212]
When I try to build my Xcode project, I get the following error:

`LNK1181	cannot open input file 'SystemConfiguration.lib'`

I simply ran vsimporter, so all the options are the default options. A class I use in my app relies on the System Configuration framework. There is a "SystemConfiguration" folder in my winobjc folder.

**Comment by asimonov-msft** [comment]
@segadude Were you using a pre-packaged SDK or did you clone the git repository? In the latter case, you need to first build build/build.sln

**Comment by segadude** [comment]
I don't remember if I was using the pre-packaged SDK or not, I think I tried both. I downloaded the February 18, 2016 release from the releases page, and while my app still doesn't build successfully, I no longer get this error.

**Comment by asimonov-msft** [comment]
@segadude Please file additional issues for any remaining build failures that you are seeing. :smile:
