### ISSUE TITLE
VsImporter does not import header

### ISSUE THREAD

**Issue by weswmsft** [Microsoft/WinObjC#2122]
When importing AFNetworking the 1)	objc/block_runtime.h doesn’t get imported automatically and so it is currently not working with modules turned on.

**Comment by memontic-ms** [comment]
blocks_runtime.h is getting into the WinObjC.Language package correctly but it can't be found correctly with modules enabled. This needs a change in libobjc2: either an addition to libobjc2's modulemap or an additional include somewhere in libobjc2's headers.

**Comment by DHowett-MSFT** [comment]
This is a duplicate of #1976.

**Comment by memontic-ms** [comment]
### Repro
In a file with options 
```
<CompileAs>CompileAsObjCpp</CompileAs>
<ObjectiveCModules>true</ObjectiveCModules>
```
And the import
```
#import <objc/blocks_runtime.h>
```
The following will not compile because a definition for Block_copy cannot be found
```
void* info;
Block_copy(info);
```
