### ISSUE TITLE
Any estimates for missing ARM support?

### ISSUE THREAD

**Issue by volkrass** [Microsoft/WinObjC#214]
README includes this:
x86 only today ARM support coming soon.

**Comment by PooyaZv** [comment]
We have a technology preview out for ARM. Please use any release after Feb 18th and let us know if you run into any issues.

**Comment by volkrass** [comment]
Great guys! Will come back with feedback asap. Keep up the good work!

**Comment by s5msft** [comment]
Please open new issues if you find specific problems/bugs.
