### ISSUE TITLE
[Mademoiselle Pori] The top section with clothes becomes hidden

### ISSUE THREAD

**Issue by kellymor** [Microsoft/WinObjC#2140]
1. Launch the Mademoiselle Pori app from current build drop share
2. Go into the dressing room
3. Using a mouse, drag clothing from the top row down, do NOT release, drag clothing back up to row, THEN release
 
Expected Result: 
Clothing item goes back on the row
Row of clothing items remains visible

Actual Result: 
After releasing the clothing item on the clothing row, the row disappears

Workaround:
Exit to home screen then return to the dressing room.
Changing clothing item type does NOT restore the clothing item row

**Comment by rajsesh-msft** [comment]
the conclusion was that this is the app behavior - not something we regressed.
