### ISSUE TITLE
[ARM] [x86] GLKitComplex images are missing

### ISSUE THREAD

**Issue by ashvarma** [Microsoft/WinObjC#2150]
On the most recent master build - 20170228.1

Image on the Teapot is missing for these scenes - 	
		Vertex Lit, Specularity, Texture
		Solid Color, Textured w/ Decal	 

And - Vertex Colors, Textured is black and white and the Text “Tea” is missing on the labels on the tea pot

**Comment by msft-Jeyaram** [comment]
Taking a look into this

**Comment by msft-Jeyaram** [comment]
These are the expected Images:

![image](https://cloud.githubusercontent.com/assets/18413092/23543434/1142b6c0-ffa7-11e6-945a-bdea5959691e.png)

![image](https://cloud.githubusercontent.com/assets/18413092/23543477/3b8623cc-ffa7-11e6-884f-e7e2142f0de9.png)

![image](https://cloud.githubusercontent.com/assets/18413092/23543497/4f5a5b66-ffa7-11e6-8d2c-59440592120c.png)

**Comment by msft-Jeyaram** [comment]
I have the fix and sending out a CR for it.
