### ISSUE TITLE
[ARM] Foundation-Dev tests URL Session - resume doesn't seem to work 

### ISSUE THREAD

**Issue by ashvarma** [Microsoft/WinObjC#2151]
On the most recent master build - 20170228.1
Download, Cancel and then Resume – doesn’t resume the download, it stays in the cancelled state

**Comment by DHowett-MSFT** [comment]
@ashvarma the text field below the download table should be populated with details about the task when you cancel it and attempt to resume it. Could you share those details?

**Comment by DHowett-MSFT** [comment]
This is by design; the default URL in the Foundation URL Session test view controller gives a very, very small response (47 bytes). By the time the download is created, it's finished. If you cancel it before it starts, the headers specify that it cannot be resumed.

**Comment by rajsesh-msft** [comment]
Also: we have automated functional tests https://github.com/Microsoft/WinObjC/blob/develop/tests/functionaltests/Tests/NSURLSession.mm#L656 for this scenario.  The test app itself was written for a demo.
