### ISSUE TITLE
[x86] TypograhyInsight - Kerning – shows chewed up letters

### ISSUE THREAD

**Issue by ashvarma** [Microsoft/WinObjC#2153]
This is on the latest master build - 20170228.1

Launch the app
Select Kerning 
Hit Next Word button (top right corner)… all words from here on out (you can keep hitting Next Word) have chewed up letters

**Comment by DHowett-MSFT** [comment]
@ashvarma I looked at the Kerning page for the first attempted 1702 release, and didn't find anything unexpected. Can you share a screenshot of the behaviour to assist in triage? Thanks!

**Comment by msft-Jeyaram** [comment]
Since I was looking at it the other app, here you go:
Actual:
![image](https://cloud.githubusercontent.com/assets/18413092/23543595/bbb14aae-ffa7-11e6-8921-a5ae52eb60e9.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/18413092/23543631/e17e9570-ffa7-11e6-9aac-858f943c8504.png)

**Comment by rajsesh-msft** [comment]
This page doesn't use any core text/cg apis.

**Comment by DHowett-MSFT** [comment]
This page uses UILabel extensively, and UILabel uses CoreText for sizing.

It looks like `_DWriteGetFrameSize` is returning a size that is smaller than the requested size, but it's too small to contain the characters.

**Comment by aballway** [comment]
I tracked the issue back to commit [78259bd9686dc0e8a741ecec6a67f35505b3b7d9] from pull request #1768 and is likely related to #2158

**Comment by DHowett-MSFT** [comment]
Also, I can see the red reference text in my local testing...

**Comment by yiyang-msft** [comment]
fixed with 6fcf514c273d32104026c0a973a10ca84d36a5f3.
