### ISSUE TITLE
[x86] WOCCatalog - UISearchBar cancel button doesn't do anything 

### ISSUE THREAD

**Issue by ashvarma** [Microsoft/WinObjC#2154]
This is in the most recent master build - 20170228.1

UISearchBar – the first TextField that has the Cancel (which is second from the bottom) – the Cancel doesn’t clear the contents. 

For the last TextField which also has a cancel button, it clears the contents

**Comment by yiyang-msft** [comment]
The first search bar didn't set the delegate thus do nothing. If you try the second one with cancel button, it sets the delegate and will clear the text. Thus this is by design. However, i will enhance the app to make it clear what the expectation is.
