### ISSUE TITLE
[Packaging] Building solution generates a large number of command prompt windows

### ISSUE THREAD

**Issue by aballway** [Microsoft/WinObjC#2160]
When building a cluster of windows will pop out that seem to be running clang.exe

**Comment by bbowman** [comment]
@memontic-msft and I both hit this at various points but then it never repro'ed. What changed recently for you?

**Comment by aballway** [comment]
I had to build from scratch after doing a clean -dfx.  Maybe related to initial nuget setup?

**Comment by bbowman** [comment]
pushed fix.
