### ISSUE TITLE
Release 45 regressions:

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#2161]
Dear WinObjC Engineers,

Release 45 regressions:

- CGContextAddLines() draws a point to the origin {0,0} upon stroke; this happens with or without a CGContextClosePath() call.

- Arcs with volume greater than a semicircle do not draw correctly, this includes [canonical] circles (and ellipses). In this case, the arc origin is offset outside the volume so that the arc bend is reflected. (see the attached files circles44.png and circles45.png for comparison between release 44 and 45 respectively; they are suppose to be the same image).

- As noted in the release notes, radial linear gradients are not working.

Release 45 notable improvement:

- Text drawing is substantially faster than in release 44 and the text clipping works as expected.

Note:

- It would be helpful (now that D2D merge is done) if releases were more often.

Sincerely,

Ed

Release 44:
![circles44](https://cloud.githubusercontent.com/assets/15889800/23578652/2361dc10-00aa-11e7-825b-dd8276a5a645.png)

Release 45:
![circles45](https://cloud.githubusercontent.com/assets/15889800/23578653/2363acd4-00aa-11e7-8b4a-2b9342a3907d.png)

**Comment by edvv** [comment]
Regarding CGContextAddLines(), see:

https://developer.apple.com/reference/coregraphics/1455461-cgcontextaddlines

"The first point in the array specifies the initial starting point."

NOTE:

https://github.com/Microsoft/WinObjC/blob/b06f7b32815237aad6e41c4a35d33008233244d9/Frameworks/CoreText/DWriteWrapper_CGPath.mm

says: "CGPathAddLines does a CGPathMoveToPoint to the first point,"

BUT:

https://github.com/Microsoft/WinObjC/blob/17d53bd912bea247b558c08a69916836d0fd0d7e/Frameworks/CoreGraphics/CGContext.mm

CGPathAddLines()

implementation does not do a moveto to begin with so it must be picking up on a default gstate current point of {0,0}.

Also, the unit tests for these functions need to be updated to reflect the correct implementations.

**Comment by DHowett-MSFT** [comment]
@edvv Thank you; this is a whole lot of really good information. We have an ongoing code review fixing the large/small sweep arc and start point bugs at #2136.

Are you creating this image with raw CG calls, or are you using your own translation layer?
If you are using straight CG and you don't mind sharing that code, I would love to integrate it into our test suite so we can track future regressions in this area.

I may break this into multiple issues and retain this one for arcs. If so, I'll mention you so that you get notifications.

**Comment by edvv** [comment]
@DHowett-MSFT  The image was made with raw CG calls. Here is an example code frag:

CGContextRef ctx= UIGraphicsGetCurrentContext();
CGContextSetLineWidth(ctx,10);
CGContextSetRGBStrokeColor(ctx,1.0,0.0,0.0,1.0);
CGContextAddArc(ctx,100.0,100.0,50,0.0,M_PI*2,YES);
CGContextStrokePath(ctx);

That draws a red circle. The actual code is part of a library/application I spoke offline with Arnaud about using.

Sincerely,

Ed

**Comment by DHowett-MSFT** [comment]
@edvv I believe these to be fixed with the merge of #2274, #2221, and #2136.
