### ISSUE TITLE
System Import/Export Controllers/Functions

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#2162]
Dear WinObjC Engineers,

It would be very helpful if these system-level import and export functions and classes were implemented:

UIImageWriteToSavedPhotosAlbum()

MFMailComposerViewController

UIPrintInteractionController

UIImagePickerController

Sincerely,

Ed

**Comment by rajsesh-msft** [comment]
@edvv these are not currently in plan.  You could use the projection apis instead to perform all of the above, here are some pointers.  

**Writing to photos album:**

Windows.Storage.StorageLibrary (WSStorageLibrary using projections) to save and retrieve pictures from the pictures library.  You can look at https://github.com/Microsoft/WinObjC/blob/develop/Frameworks/AssetsLibrary/ALAsset.mm#L72 for an example.

**UIImage picker**
https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.Pickers.FileOpenPicker would be the good alternative.

**Printing**

https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Printing and projections should help.

**Email**

https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Email.EmailManager#Windows_ApplicationModel_Email_EmailManager_ShowComposeNewEmailAsync_Windows_ApplicationModel_Email_EmailMessage_

**Comment by edvv** [comment]
@rajsesh-msft Thanks for the pointers. That answers the question so I'm going to close this issue.
