### ISSUE TITLE
Error APPX0702 

### ISSUE THREAD

**Issue by ad87mb** [Microsoft/WinObjC#2179]
Not exist. "....\Debug\Base.lproj\Main.Storyboardc" in Microsoft.AppXPackage.Targets

**Comment by ArnOmsft** [comment]
Hi, can you describe what you're doing and when does this error show-up? Are you getting this when running vsimporter against your project?
Thanks.

**Comment by weswmsft** [comment]
Can you please provide more details and explain how we can reproduce the bug?

**Comment by memontic-ms** [comment]
Microsoft.AppXPackage.Targets looks like (app) build-time targets, so probably not vsimporter.

Could not reproduce this error.  Closing.
