### ISSUE TITLE
Creating Win32 "classic" exe or dll with WinObjC

### ISSUE THREAD

**Issue by gvollant** [Microsoft/WinObjC#218]
Hello,
Do you plan support of creating Win32 "classic" exe or dll (ie not "Windows Apps", but Win32 Desktop or server executable, like executable for Windows 7) with WinObjC ?

Of course, I'll not plan use class with address OpenGL or user interface (only thread, memory, file...)

regards
Gilles Vollant

**Comment by nicholasgerard-msft** [comment]
The focus of the iOS bridge is on Universal Windows Platform (UWP) apps. We currently have no planned support for classic Win32 applications. You may be interested in signing up for updates on Microsoft's Project Centennial, which you can read more about [here](https://devpreviewsignup.windows.com).

**Comment by privet56** [comment]
:-(
