### ISSUE TITLE
CoreGraphics is missing Drawing test collateral

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#2187]
* [ ] Line Caps
* [ ] Line Joins
* [ ] Line Dash
* [ ] Miter Limit
* [ ] Creating a 1px stroke by using half-point offsets `0.5, 0.5`

**Comment by rajsesh-msft** [comment]
@MSFTFox since you are addressing some of these in your recent PR, could you handle this as well?

**Comment by MSFTFox** [comment]
My changes address some of these but for full test coverage we would need to go over the other APIs as well. I think an additional parameterized test covering all 5 of these options with various paths would be great. I would like to avoid bloating the CopyByStroking PR with this additional test collateral though so I think it would be best to address this in a separate PR.

**Comment by rajsesh-msft** [comment]
@MSFTFox yes, lets tackle the remaining items in 1704.
