### ISSUE TITLE
[Packaging] Required test file deleted

### ISSUE THREAD

**Issue by aballway** [Microsoft/WinObjC#2188]
In 3b1a0dd760c099f78e82e27a9155bca17b27225e tests/unittests/ImageIO/photo7_4layers_683x1024.gif was deleted, which is causing test failues.  Unsure why this did not cause a test failure for the commit.

**Comment by bbowman** [comment]
@aballway commit 78f6f8baf24cf87ca065fbc6f9efa0a712b9edc5 put it back. pull latest and you should be good to go. It snuck in because I didn't run a build for the commit since it was adding an unused (at the time) file.
