### ISSUE TITLE
Memory issues when passing a locale to [NSString compare:options:range:locale:].

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#2193]
Passing a NSLocale instance to `[NSString compare:options:range:locale:]` causes a memory leak.

The following sample code can be used to reproduce the issue:
```
NSString* testS1 = [@"string" stringByAppendingString:@"my one"];
NSString* testS2 = [@"string" stringByAppendingString:@"my second"];

for(int i=0;i<1000000;i++) {
        [testS1 compare:testS2 options:NSCaseInsensitiveSearch | NSNumericSearch range:NSMakeRange(0,10) locale:[NSLocale currentLocale]];
}
```

Attached is a screenshot of the stack shown in the memory profiler tool in VS.

![2017-03-09](https://cloud.githubusercontent.com/assets/237035/23748855/4850a800-04bd-11e7-9527-e5b73d3c32e2.png)

**Comment by rajsesh-msft** [comment]
@ms-jihua looks like a leak in libicu, or our usage of it.  could you please take a look?
