### ISSUE TITLE
Release 45 CGContextDrawRadialGradient() regression

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#2196]
This type of code worked in release 44:

```
CGFloat components[8] = {1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0};
CGPoint centerpoint = {200.0, 200.0};

CGGradientRef gradient = CGGradientCreateWithColorComponents(CGColorSpaceCreateDeviceRGB(), components, NULL, 2);

CGContextDrawRadialGradient(ctx, gradient, centerpoint, 0.0, centerpoint, 50.0, 0);
```

But is not working on Release 45. This is a very standard radial gradient. Is there a way to get it to work?

**Comment by msft-Jeyaram** [comment]
@edvv  taking a look at this.
 I can add in the support, although it didn't quite match what we were expecting

**Comment by edvv** [comment]
@msft-Jeyaram Can you please post a code frag of what you were expecting that duplicates the function of what I posted. Perhaps what you expect is better and I can adjust on this end.

**Comment by msft-Jeyaram** [comment]
@edvv A fix is on the way to support your scenario :)

**Comment by edvv** [comment]
@msft-Jeyaram Thank you very much.
