### ISSUE TITLE
Unable to create packages for Windows 10 Store

### ISSUE THREAD

**Issue by Alx06** [Microsoft/WinObjC#220]
As everything looks to work now on my first project (thanks a lot for the support!),
I'm trying to create packages to send to the Store.

I'm unable to generate them because I'm facing this error:

APPX1609 "The package contains a Debug framework reference 'Name = Microsoft.VCLibs.140.00.Debug, MinVersion = 14.0.23019.0, Publisher = 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US''. Ensure all framework references in the package are valid frameworks hosted by the Store."

I can't find how to enable the release version of this framework.
I tried to force the value to 'false' in the 'Microsoft.AppxPackage.Targets" file, it does not work :(

Any help would be appreciated.

**Comment by s5msft** [comment]
This looks like a build settings issue: some component/project in your app is linking against MSVCRTD -- they all need to be built against the release runtime.

Look under *Properties | Clang | Runtime Library* and *Properties | C++ | Runtime Library*

**Comment by hervevi** [comment]
Thanks a lot for your help, but unfortunately that is not the problem (that was wrong, but I still got the same error).

The error points to the file C:\Dev\ProjectName\ProjectName.vsimporter\ProjectName-WinStore10\Package.appxmanifest that you can download there: https://www.dropbox.com/s/dm8j12itd572nck/Package.appxmanifest.txt?dl=0

The error comes from this dependency:
<Dependencies>
    <TargetDeviceFamily Name="Microsoft.VCLibs.140.00" MinVersion="10.0.0.0" MaxVersionTested="10.0.0.0" />
  </Dependencies>

I tried a lot of things there, but it always links the Debug version.
(I also tried to modify the Microsoft.AppxPackage.Targets as sais before).

Are you personally able to generate packages in release mode?

**Comment by hervevi** [comment]
I tried to generate the packages for the sample project, and the same error occurs...

**Comment by s5msft** [comment]
Good catch -- we're able to repro the issue here. We'll investigate/fix/report back.

**Comment by hervevi** [comment]
good news :)
good luck for that!

**Comment by asimonov-msft** [comment]
@Alx06 Please try the following workaround.

Open msvc/sbclang.targets and comment-out the **RuntimeLibrary** tag for ConsumeRuntimeComponent.cpp:
```
<ItemGroup Condition="'$(AppContainerApplication)' == 'true' And '$(IslandwoodDRT)' == 'true'">
    <ClCompile Include="$(MSBuildThisFileDirectory)ConsumeRuntimeComponent.cpp">
      <PrecompiledHeader>NotUsing</PrecompiledHeader>
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
    </ClCompile>
</ItemGroup>
```

Then try rebuilding.

**Comment by Alx06** [comment]
Thanks for the tip Artem, but that didn't work for me.
What worked for me was to open msvc/sbclang.targets and to modify the RuntimeLibrary in this way:

`<ItemGroup Condition="'$(AppContainerApplication)' == 'true' And '$(IslandwoodDRT)' == 'true'">
    <ClCompile Include="$(MSBuildThisFileDirectory)ConsumeRuntimeComponent.cpp">
      <PrecompiledHeader>NotUsing</PrecompiledHeader>
      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
    </ClCompile>
</ItemGroup>`

Now I'm able to generate packages locally, that's good.

But, generating packages for the store doesn't work.
The error this time is in Microsoft.AppXPackage.targets line 2760 with this error message : "Unable to remove directory "Release\PackageUploadLayout\" Access to path 'ClrCompression.dll' is denied.

So I tried to comment out the line `<RemoveDir Directories="$(AppxUploadLayoutDir)">` (line 2760 on Microsoft.AppXPackage.targets)

And now I've this error:

`Unable to copy file "C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd" to "Release\PackageUploadLayout\WinMetadata\Windows.winmd". Access to the path 'Release\PackageUploadLayout\WinMetadata\Windows.winmd' is denied.	`

(line 2762 on Microsoft.AppXPackage.targets)

And so I give up!!!

What an adventure!!!

**Comment by Alx06** [comment]
Any news for this bug?

**Comment by davelamb** [comment]
There's a fix coming down the pipe for the debug runtime issue you were hitting. Expect to see it soon.

As for the other errors your seeing, it looks like something is holding onto some files in your package directory. You can use a tool like Process Explorer to find latent processes holding onto file handles and close them down, or reboot your system.

**Comment by mufanfan** [comment]
hit the same error:

APPX1609 "The package contains a Debug framework reference 'Name = Microsoft.VCLibs.140.00.Debug, MinVersion = 14.0.23019.0, Publisher = 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US''. Ensure all framework references in the package are valid frameworks hosted by the Store."

When will it be fixed?

**Comment by Alx06** [comment]
Is that officially fixed in the new release?

**Comment by Alx06** [comment]
I'm still not able to generate the packages for the Store :(
I'm facing this issue now: https://connect.microsoft.com/VisualStudio/feedback/details/1800078/unable-to-remove-directory-obj-x64-release-packageuploadlayout-access-to-the-path-applicationinsights-config-is-denied

I don't know what to do :(

I'm also unable to understand how to test on an external device (yes, I'm new to this Visual Studio environment). Can someone help me with that too please?

**Comment by Alx06** [comment]
It's said to delete the folder "obj" but I d'ont have such folder...

**Comment by s5msft** [comment]
@Alx06 right now you're not able to test on an external device as ARM support for our compiler is still being built.

We're working hard on it.

**Comment by Alx06** [comment]
I don't understand: I can't export an exe file on run it on another pc with windows10?

So, I can't create packages for the Store, and I can't create executable files for other PCs, so what can I do with my projects?

**Comment by Alx06** [comment]
Anything new for me?

**Comment by ArnOmsft** [comment]
I believe this issue has been fixed with the last SDK we released, can you confirm?
Thanks.

**Comment by Alx06** [comment]
Yes it's okay for me.
