### ISSUE TITLE
[Packaging] Create nuget build task workaround package

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#2200]
see https://github.com/NuGet/Home/issues/4532 for details. This is fixed now but we need a portable workaround until the fix ships.

**Comment by onovotny** [comment]
I put this in a package on this MyGet feed: `https://www.myget.org/F/msbuildsdkextras/api/v3/index.json`. Package is `Microsoft.NuGet.Build.Tasks.Workaround`

**Comment by bbowman** [comment]
Pushed this workaround.
