### ISSUE TITLE
[Packaging] Change samples and build.sln to use PackageReference

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#2201]

**Comment by memontic-ms** [comment]
All of build.sln has been updated to PackageReference at [memontic/PackageReference](https://github.com/memontic-ms/WinObjC/tree/memontic/PackageReference)
It needs the fix in the updated NuGet build task so this PR will have to wait until #2200 in implemented.

**Comment by memontic-ms** [comment]
Merged into packaging (and develop)
