### ISSUE TITLE
Unable to use .winmd in OBJ-C UWP

### ISSUE THREAD

**Issue by cloudmonkeypeng** [Microsoft/WinObjC#221]
After import an OBJ-C successfully, it can build and run.
I want to use a winmd which is coded by myself.
So I have added the References(.winmd), declared it by "using namespace".
But I can't use it.  The error is "use of undeclared identifier 'NativeMathSDK' "

1.  After add .winmd, what should I do ?
2.  I 'm not sure CX can be used in OBJ-C UWP. If not , how can I use .winmd?

**Comment by cloudmonkeypeng** [comment]
I can use .winmd in .ConsumeRuntimeComponent.cpp .  What is the difference between .ConsumeRuntimeComponent.cpp and *.cpp(I added)?

**Comment by cloudmonkeypeng** [comment]
Change the property pages about .cpp. 
Same as .ConsumRuntimeComponent.cpp

1.  Item Type: C/C++ compiler
2. Code Generation->Runtime Library: Multi-threaded Debug DLL (/MDd)
3. Precompiled Headers-> Precompiled Header: Not Using Precompiled Headers
4. Command Line -> Additional Options: “$(AdditionalOptions) -D_WOC_APP”

**Comment by cloudmonkeypeng** [comment]
Change wiki about the *.cpp property pages . [WinObjc-wiki](https://github.com/cloudmonkeypeng/WinObjc-wiki)
Unfortunately the wiki can't pull request. Maybe need you help to update the wiki manually.

The update is:

### Add *.cpp and use cx/Windows APIs
If you want to call Windows APIs in *.cpp*, you should set the proper pages same as *ConsumeRuntimeComponent.cpp*.

Right click the *.cpp and choose Properties and set the pages:

1. Item Type: C/C++ compiler
2. Code Generation->Runtime Library: Multi-threaded Debug DLL (/MDd)
3. Precompiled Headers-> Precompiled Header: Not Using Precompiled Headers
4. Command Line -> Additional Options: "$(AdditionalOptions) -D_WOC_APP"

Then you can use c++/cx or Windows APIs.

**Comment by cloudmonkeypeng** [comment]
Hey, what happened? Do you have some good information share with me? :)

**Comment by ArnOmsft** [comment]
Sorry there might be a misunderstanding here. We updated the Wiki to reflect your feedback (thanks for this) and then we closed this issue. Did we miss something?
Thanks.

**Comment by cloudmonkeypeng** [comment]
No. I set the *.cpp as my write.  I also find the wiki has updated. 
How effective you are!

**Comment by ArnOmsft** [comment]
Closing this then. Thanks for your help.
