### ISSUE TITLE
NSException details should be available in crash dumps

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#2229]
Crash dump files (CABs) of crashes caused by a raised NSException should contain details about the NSException such as the exception name, reason, and userInfo properties.

When running in the debugger this information should be printed to the console (#666).

**Comment by DHowett-MSFT** [comment]
The incoming fixes will make sure that the exception reason is preserved in heap dumps. We can open a new issue to track future work, such as including the userinfo and the like.

The Windows Error Reporting APIs don't offer the richness we're seeking here, so this might be a platform ask.
