### ISSUE TITLE
Memory leaks in NSURLProtocol_WinHTTP.mm

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#2232]
The method `[NSURLProtocol_WinHTTP _asyncHttpOperation:completedWithStatus:]` leaks objects. I think this is because the method is called on a system thread that does not have a NSAutoreleasePool setup.

This can be reproduced using the code:

```
for (int i = 0; i < 100; i++) {    
    @autoreleasepool{
        NSURLSession *session = [NSURLSession sharedSession];
        NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"https://www.bing.com"]];
        NSURLSessionDataTask  *task = [session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error){
            NSLog(@"TASK completed");
        }];
        [task resume];
    }
}
```

Attached is a screenshot of the memory profile capture in VS.

![image](https://cloud.githubusercontent.com/assets/237035/23910050/bdf28ffa-08d8-11e7-88f8-bfa2d75a1154.png)

**Comment by DHowett-MSFT** [comment]
To whomever picks this up while I am gone: I have a partial fix [here](https://github.com/DHowett-MSFT/WinObjC/tree/201703-fix-2232).

Issues:
* There are still leaks.
* I could not get the memory profiler to show me proper Objective-C call stacks with VS2017.
* It looks like we are _still_ leaking the collection that comes back from `WRLToNSCollection`; the code in NSURLProtocol_WinHTTP should be autoreleasing it, but maybe the class that is holding on to it is not releasing it.
