### ISSUE TITLE
Build machine occasionally fails to clean up repo when building sample apps

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#2238]
3.	2017-03-15T18:57:52.9276745Z The directory is not empty.
4.	2017-03-15T18:57:53.0370527Z ##[error]Process completed with exit code 145.

Worked on Debug but not Release so maybe an issue with a file lock hanging around after the build complete? ClangCompileTask likes to linger for awhile so maybe thats the culprit?

**Comment by pradipd** [comment]
Looks like vctip was writing out link.VCTIP.* files well after the build was finished.
After disabling vctip, we've had 3 successful builds in a row.  
Before that, the failure rate was ~50%.
Will reopen if we see this again.
