### ISSUE TITLE
KVO: missing support for observing NSUserDefaults

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#224]
NSUserDefaults seems to be currently missing support for KVO, i.e. when registering for change notifications for a user defaults key, no KVO event is triggered when the key is changed.

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)
