### ISSUE TITLE
main thread in unit tests is not considered mainThread

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#2242]
TEST(DoesntMatter, DoesntMatter) {
ASSERT_TRUE([[NSThread currentThread] isMainThread]);
}

passes on OSX but not on WinObjC

**Comment by DHowett-MSFT** [comment]
We may have an issue on this already; the main thread is never set up in the unit tests nor is the main run loop spun because UIKit handles that ( ☹️ )

**Comment by rajsesh-msft** [comment]
@ms-jihua - yes, any code that requires this to work should use the FTs instead.  The interesting part though is all tests are now TAEF tests, so this should in theory be possible, but probably an overkill for most API tests which is what the unit tests have to be.

For your case, can you use functional tests instead?

**Comment by jaredhms** [comment]
Correct; our 'main thread' is tied to the CoreWindow, so it's only available in functional tests.

**Comment by jaredhms** [comment]
Although as Raj said, now that our UTs run in a UWP we could probably fix this?

**Comment by rajsesh-msft** [comment]
Any scenario that is complex than simple API test is by design not a unit test.  Since we do have the functional test, lets just use that for such scenarios.
