### ISSUE TITLE
LNK1181 errors when building sample files

### ISSUE THREAD

**Issue by mufanfan** [Microsoft/WinObjC#228]
Used the SDK a month ago, at that time I can build the samples files successfully.

Today, I downloaded the latest SDK and tried to build the same sample files: 

(1) Building Samples/HelloUI, got the error as below:  
LNK1181 cannot open input file 'starboardXaml.lib'

(2) Building Samples/WOCCatalog, got the error as below:
LNK1181: cannot open input file 'OpenGLES.lib'

**Comment by cloudmonkeypeng** [comment]
Maybe you can build StarboardXaml and OpenGLES project by yourself, then build all WinObjC SDK again.
I guess the sample will find the lib.

**Comment by rajsesh-msft** [comment]
I did download the latest sdk and am able to build the samples just fine.  What configuration are you using?

**Comment by triplef** [comment]
I think the second error ("cannot open input file 'OpenGLES.lib'") should be fixed with this PR:
https://github.com/Microsoft/WinObjC/pull/222

**Comment by rajsesh-msft** [comment]
I have tried the samples from the Oct30 preview release and have been able to build all of the samples and run them.&nbsp; Can you point out which project (Store 10, WP 8.1, etc) that you are using?

**Comment by rajsesh-msft** [comment]
I have tried the samples from the Oct30 preview release and have been able to build all of the samples and run them.&nbsp; Can you point out which project (Store 10, WP 8.1, etc) that you are using?

**Comment by triplef** [comment]
I think this might only happen when building the SDK from source, at least that seems to be the case for #222.

**Comment by drewjohnsonstpaul** [comment]
mufanfan, you mention that you tried to build the same samples. 

To clarify: 
- did you open and attempt to build the original sample projects that you built last month, or 
- did you take the latest sample files from the SDK and attempt to build them?

Thanks!

**Comment by SAPNALnT** [comment]
same error for me.
i used Woccatalog-winstore10.sln.
got error LNK1181 - can not input file'OpenGLES.lib'
thanks!

**Comment by SAPNALnT** [comment]
and FOR helloUI 
Error	LNK1181	cannot open input file 'StarboardXaml.lib'	:(

**Comment by mufanfan** [comment]
I tried it on another PC and got the same error.

Steps:
(1) go to the folder \WinObjC-master\samples\HelloUI;
(2) double click HelloUI-WinStore10.sln and open it in Visual studio;
(3) Click debug -> Start Debugging
(4) Get the error as below: 

1>------ Build started: Project: HelloUI (HelloUI\HelloUI), Configuration: Debug Win32 ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "XamlCompositorCS". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>  ConsumeRuntimeComponent.cpp
1>  ..\..\HelloUI\HelloUI.m
1>  ..\..\HelloUI\main.m
1>LINK : fatal error LNK1181: cannot open input file 'StarboardXaml.lib'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

########### Visual Studio info:
Visual Studio Enterprise 2015 
Version 14.0.23107.0 D14REL

########### Windows 10 info:
Windows 10 Enterprise

**Comment by mufanfan** [comment]
In addition, it worked totally fine with the earlier SDK that was release around 10/09/2015

**Comment by mufanfan** [comment]
On another PC, I have Visual Studio Community and Windows 10 pro, always get the same error.

**Comment by antoine-haas** [comment]
We’ve tracked this down and it’s a debug-only issue. A fix has been identified and is coming soon.

**Comment by mufanfan** [comment]
That's great, looking forward to this updated version.

**Comment by asimonov-msft** [comment]
@mufanfan What is the size of the SDK zip file that you downloaded? [Here](https://github.com/Microsoft/WinObjC/releases/download/0.1.0.151030/winobjc.zip) is a link to the latest file.

The pre-packaged SDK (released October 30) should be about 179Mb zipped and 578Mb unzipped. It should contain a number of dll and lib files in lib\Universal Windows\x86

**Comment by mufanfan** [comment]
Okay, the sdk you provided is totally fine. I didn't encounter any issues. 
But I'm so confused, I always click the 'Download Zip' button on https://github.com/Microsoft/WinObjC and click , and a 245MB WinObjc-master.zip file will be downloaded. That SDK has all kinds of Link1181 errors and can't create store packages at all.

**Comment by keluo-ms** [comment]
@mufanfan The "Download Zip" button on the right that you are clicking downloads the whole branch. If you only want the prebuilt files, you'll want to navigate to the "releases" page and download the latest "Winobjc.zip" file available. 

https://github.com/Microsoft/WinObjC/releases

**Comment by mufanfan** [comment]
Thanks so much to Keluo-ms for your clarification. 

Here I have another question, I'm trying to build a open-source ios project and I got below errors which prevent me from creating the store packages: 

1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1778,5): warning APPX0104: Certificate file 'climbers_TemporaryKey.pfx' not found.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1778,5): warning APPX0107: The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.

To my understanding, the TemporaryKey.pfx is auto-generated by VS, right? 
Is there anything or settings I didn't do? Thanks.

**Comment by mufanfan** [comment]
I also checked the \samples\HelloUI\HelloUI.vsimporter\HelloUI-WinStore10 folder, there's already a HelloUI_TemporaryKey.pfx file there. 

Is this a vsimporter's issue?

**Comment by mufanfan** [comment]
Okay, so I created a brand new climbers project,  and then manually copied the climbers_TemporaryKey.pfx under my ios project folder \climbers.vsimporter\climbers-WinStore10 

And it works, the store appxupload package is successfully generated!!! Finally. 
But still, will you fix this minor issue?

**Comment by keluo-ms** [comment]
@mufanfan, can you please file a new issue to track the .pfx issue? This helps us keep track of distinct issues.

And thanks for taking the time test our project, we really appreciate it :smile:
