### ISSUE TITLE
[Packaging] Packaging breaking-change and transitioning documentation should be more clear

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#2281]
All of the wiki/readme documentation has been updated; it's now current with respect to packaging, but it's not very clear how developers should migrate their systems.  

1. We should add a section (maybe to the top of the ReadMe) that clearly calls out this significant breaking change, with steps to walk through for the transition to packaging.  We probably need _two_ sets of steps; one for basic SDK users, and another for users who build the SDK locally and therefore need to target local packages.  The steps should include links to the other relevant documentation as needed, and they should also include examples -- command line args to vsimporter, changes to nuget configs, etc.

2. The packaging documentation could use more examples and links.  Here are _a few_ examples of how things could be more clear:

> **How do I upgrade to Packaging from an old SDK?**

> If you are using a prebuilt SDK, download Visual Studio 2017, and re import your app using the latest winobjc-tools command line package (Instructions on README).

_This just points to the top of the README; it would be much more helpful to link to explicit instructions on how to reimport._

> If you are building the SDK locally, please install Visual Studio 2017, the Nugetizer VSIX (either from the winobjc-tools package or directly as described below), and make sure any local/internal NuGet feeds are configured to pick up latest beta packages if desired.

_Links to Nugetizer VSIX, and to the 'directly as described below' sections would be helpful.  An example of how I'd 'make sure any local/internal NuGet feeds are configured to pick up latest beta packages if desired' would also be helpful._

> **How do I consume packages locally?**
> NuGet allows using a local directory as a package feed when restoring packages. In order to make this as seamless as possible, the output directories for WinObjC packages have been added to the nuget.config files where feasible (in the samples directory for instance). In cross repository scenarios, please set WINOBJC_SDK_ROOT to your cloned directory and configure the nuget.config to use that.

_Which nuget.config?  Do I need to add a nuget.config to my ported app's directory, or are you referring to the one at the root of WINOBJC_SDK_ROOT?  We should also probably call it 'the WINOBJC_SDK_ROOT environment variable' for clarity._

> In addition to finding packages, consuming a just produced package locally means updating the consumer to automatically pick up the new version. Luckily by adding winobjc.packagereference.override.targets as an import to your project (an example can be found at bottom of WOCCatalog.vcxproj) the version that the consumer depends on can be swapped out on the fly. Again for cross repo scenarios, it advisable to set WINOBJC_SDK_ROOT.

**This doesn't make any mention of using * vs pr* etc. for targeting different versions.  Can we make this more clear?**

> NOTE: Local packages are always preferred when using the override targets so make sure to not forget about locally produced packages on the machine that may be influencing builds.

_Can you clarify?  Does this mean, 'Be sure to clear the nuget package cache on build machines.'?_

**Comment by bbowman** [comment]
@jaredhms @andrejo-msft I have updated the wiki at https://github.com/Microsoft/WinObjC/wiki/Packaging let me know if there is still additional information you want captured there.
