### ISSUE TITLE
NSLogging tests are failing.

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2285]
The following unit-tests fail consistently on my dev box.
NSLogging_NSLoggingWideBasicTests::Test [Failed]
NSLogging_NSLoggingNSStringBasicTests::Test [Failed]
NSLogging_NSLoggingWideFormatTests::Test [Failed]
NSLogging_NSLoggingNSStringFormatTests::Test [Failed]
NSLogging_NSLogTests::Test [Failed]

I've repro'd this on the MS/develop branch.
Repro steps:
git clean -fdx
init.cmd
.tools\nuget restore build\build.sln
msbuild /p:configuration=debug /p:platform=x86 build\build.sln
run the tests in either powershell or the command line:
1. <powershell> run-unitests.ps1
2. <cmd line> te *.unittests.dll

**Comment by rajsesh-msft** [comment]
The tests pass if I run them in proc te.exe foundation.windowsonly.unittests.dll /inproc.

**Comment by rajsesh-msft** [comment]
I take that back, they passed because they were all blocked. No UWP execution inproc.

**Comment by rajsesh-msft** [comment]
If you are building debug locally, this would fail unless you build the tools project locally as well.  The debug hooks are only available on debug builds, so if you restore tools package, this will fail.

I am leaving the tests as is, so we get coverage for the logging pipeline in our build server.

**Comment by pradipd** [comment]
That's a weird developer experience.  I and many others build debug.  And, our process mandates we run UT's locally before submitting a PR.  Now we will have to take extra time to go back and build release just to run UT's.

Also, how would an external developer figure out that debug UT"s are expected to fail?

I'd much prefer to disable these tests in debug.
Or change our process (we can add a script) to build all the necessary bits to run tests in debug and release.

**Comment by pradipd** [comment]
Also, wouldn't this be considered a regression?  this is something we were clearly able to do before.
Now, we are saying UT's with debug bits don't work.

**Comment by rajsesh-msft** [comment]
If you build the tools.sln locally, this would work fine. The "Right" thing would be to move these tests to the logging project (part of tools.sln) - that is what these tests are testing anyway.

**Comment by pradipd** [comment]
Can we file a task to move the tests then if that is the right solution?

**Comment by rajsesh-msft** [comment]
@pradipd *this* is the task :).

**Comment by rajsesh-msft** [comment]
I am just going to disable these tests.  Right now, in release mode, it isn't doing any validation and in debug mode, it requires the tools project to be built in debug mode as well.
