### ISSUE TITLE
Documentation for initial winobjc-tools calls for an upgrade instead of install

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#2286]
The develop readme.MD refers to the chocolatey installation of the winobjc-tools package.

https://github.com/Microsoft/WinObjC/blob/develop/README.md

**choco upgrade winobjc-tools**

However, this command will fail if winobjc-tools is not already installed.

According to [chocolatey's page for winobjc-tools](https://chocolatey.org/packages/winobjc-tools), you need:
**choco install winobjc-tools -pre** 

I did follow this process and got a successful installation.

**Comment by bbowman** [comment]
No it won't fail. Upgrade is the prefered call. See https://chocolatey.org/docs/commandsupgrade
