### ISSUE TITLE
Incorrect patch for CURL

### ISSUE THREAD

**Issue by stammen** [Microsoft/WinObjC#229]
The winrt patch for CURLis out of date in deps/3rdparty. The CURLsubmodule SHA is 38e07886ed2792988217a2ffa482ce3a69ca92c2 and the patch is for SHA 5abfa9db8a70974b10b2b5ee1da363ae47fb63a8 which does not seem to exist in the checked out CURLsubmodule. When curl.bat tries to apply the patch it fails due to incompatible versions. The CURLbuild will then fail.

Also, this version of CURL will not pass WACK testing, The patch needs to be updated.

**Comment by rajsesh-msft** [comment]
We don't use cURL anymore.
