### ISSUE TITLE
Missing implementation for NSFileManager containerURLForSecurityApplicationGroupIdentifier

### ISSUE THREAD

**Issue by ArnOmsft** [Microsoft/WinObjC#2295]
It's used by alakoring to load/save game data and currently causes a crash.

**Comment by rajsesh-msft** [comment]
It is not a matter of a missing API, application group identifiers are a platform feature.  The closest approximation of this for UWPs is the publisher shared cache folder.  It has several caveats:

[See documentation Publisher Cache Folder](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.ApplicationData#Windows_Storage_ApplicationData_GetPublisherCacheFolder_System_String_)

- The cache itself can be cleared by the user, so it should not be the only place the user settings are saved.
- There are no group collection concept - that is, all apps by the publisher have access to the shared cache.  This itself is not a big limitation.

We should be able to implement the said API with these caveats.  Also the app manifest needs to be updated.  This may possibly be done automatically by vsimporter. 

https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html

https://blogs.windows.com/buildingapps/2016/05/24/sharing-your-local-app-data/

**Comment by rajsesh-msft** [comment]
Also need samples - in the winobjc-samples repo that demo this.
