### ISSUE TITLE
NSData dataWithContentsOfURL hangs

### ISSUE THREAD

**Issue by bviglietta** [Microsoft/WinObjC#2298]
Trying to fetch the contents of a URL hangs. For instance, this call will never return, even though the HTTP request completes successfully:

    NSURL* url = [NSURL URLWithString:@"https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2.png"];
    NSData* data = [NSData dataWithContentsOfURL:url];

**Comment by ms-jihua** [comment]
Tried a unit test with:

NSURL* url = [NSURL URLWithString:@"https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2.png"];
NSData* data = [NSData dataWithContentsOfURL:url];
ASSERT_OBJCNE(nil, data);

which completed successfully after a few seconds. Trying the associated sample app...

**Comment by rajsesh-msft** [comment]
Unit tests don't quite have a main loop the same way a normal application does.  it may be worth testing this in an app (FoundationDevTests app for example) or a functional test.

**Comment by rajsesh-msft** [comment]
@ms-jihua just confirmed that this never really worked.  Adding this to 1704 work.
