### ISSUE TITLE
'sys/xattr.h' file not found

### ISSUE THREAD

**Issue by SAPNALnT** [Microsoft/WinObjC#230]
i imported my iphone code to Winstore10.sln
after building i got this 'sys/xattr.h' file not found error in appdelegate.m
did any come across like this?

**Comment by antoine-haas** [comment]
We haven't faced this issue before. Can you get us more details on your project and, if possible, the repro steps so we can investigate the issue?

**Comment by antoine-haas** [comment]
Please reopen the issue when you have more info, if the latest release doesn't fix your problem.
