### ISSUE TITLE
CoreGraphics does not respect line width scaling

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#2301]
In UIKit line width is supposed to be 2x and in CoreGraphics line width is supposed to be 1x.

In our implementation, a scale of 2x is never respected for lines

**Comment by DHowett-MSFT** [comment]
Tentative work on this in [my 201611-stroke-betrayal branch](https://github.com/DHowett-MSFT/WinObjC/tree/201611-stroke-betrayal)

**Comment by DHowett-MSFT** [comment]
The solution put forth in 201611-stroke-betrayal no longer works; it's of questionable utility to investigate why.

**Comment by msft-Jeyaram** [comment]
😢

**Comment by rajsesh-msft** [comment]
Since this is platform limitation, closing this.
