### ISSUE TITLE
vsimporter fails to generate a xxxx_TemporaryKey.pfx file for ios projects

### ISSUE THREAD

**Issue by mufanfan** [Microsoft/WinObjC#231]
When importing an IOS project by using vsimporter, the tool fails to generate a xxxx_TemporaryKey.pfx file, which preventing developers to create store packages. 

Below is copied from https://github.com/Microsoft/WinObjC/issues/228

Here I have another question, I'm trying to build a open-source ios project and I got below errors which prevent me from creating the store packages:

1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1778,5): warning APPX0104: Certificate file 'climbers_TemporaryKey.pfx' not found.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1778,5): warning APPX0107: The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.

**Comment by asimonov-msft** [comment]
@mufanfan This behavior is intended.

To create your own test certificate:
1. Open the project's _Package.appxmanifest_ in Visual Studio.
2. Select the _Packaging_ tab.
3. Under Publisher, select _Chose Certificate..._
4. Under _Configure Certificate..._ select _Create test certificate..._

If you go through Visual Studio's _Create App Packages..._ dialogue, a real certificate should be created automatically:
1. Right click on your project in Visual Studio and select _Store -> Create App Packages..._
2. Select _Yes _under _Do you want to build packages to upload to the Windows Store?_
3. Sign in with your developer account.
4. Follow the rest of the prompts to create and test your App Package.
