### ISSUE TITLE
[ARM] CGGradient_LinearGradient* tests are failing on phone.

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2310]
CGGradient_LinearGradient3::Test [Failed]
CGGradient_LinearGradientWithLowOpacity::Test [Failed]
CGGradient_LinearGradientWithAlpha::Test [Failed]
CGGradient_LinearGradientWithLowOpacityShort::Test [Failed]
CGGradient_LinearGradient::Test [Failed]
CGGradient_LinearGradientDrawWithCGColor::Test [Failed]
CGGradient_LinearGradientShortBothSides_Options_0::Test [Failed]
CGGradient_LinearGradientShortBothSides_Options_kCGGradientDrawsBeforeStartLocation::Test [Failed]
CGGradient_LinearGradientShortBothSides_Options_kCGGradientDrawsAfterEndLocation::Test [Failed]
CGGradient_LinearGradientOneLocation::Test [Failed]
CGGradient_LinearGradient2::Test [Failed]
CGGradient_LinearGradientNullLocations::Test [Failed]
CGGradient_LinearGradient2Short::Test [Failed]

**Comment by msft-Jeyaram** [comment]
Initial investigation, earlier passed on local build arm.
It seems that the images were blank when generated and it seems only for some cases.
Looking at it further.

**Comment by msft-Jeyaram** [comment]
Unable to debug on ARM.
unable to debug via TDP as tdp seems to cause an RPC error when checking for nuget version.

Unable to launch an application onto the phone via visual studio for debugging.
It keeps on asking a pair coding and is rejecting the code that's shown on the phone. (note even if discovery is turned off, it keeps on asking for pin).

Adding traces and debugging, while i sort out the debugging on ARM thing.

**Comment by msft-Jeyaram** [comment]
Update:
We are still having issues with debugging on ARM :( w/ visual studio 2017.

The root cause seem to be that although the gradient brush is being created, fill fails to do anything on ARM.

**Comment by msft-Jeyaram** [comment]
Root cause is due to this bug on ARM.
 #1769
