### ISSUE TITLE
vsimporter shouldn't add winobjc.packaging for middleware projects

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2316]
I think we are unnecessarily  adding WinObjC.Packaging to middleware projects.
The only project that needs winobjc.packaging is the *package.nuproj project (say that 3 times fast).

Repro:
vsimporter -genprojections Sample-WinStore10.sln
The following project.json's have winobjc.packaging, but,  I don't think they need them.

x:\dev\2\WinObjC_internal\Source\objc2winmd\ProjectionsTest\Sample.vsimporter\Sample-WinStore10\project.json
x:\dev\2\WinObjC_internal\Source\objc2winmd\ProjectionsTest\SampleWinRT\project.json

**Comment by memontic-ms** [comment]
As WinObjC.Packaging is set up now, any project with output that should to go into the package needs to include the WinObjC.Packaging package (just like how NuGet.Build.Packaging is set up).

WinObjC.Packageable.props/targets will be applied to projects like Sample-WinStore10 and SampleWinRT.
WinObjC.Packager.props/targets will be applied to the SampleWinStore10-Package project.

**Comment by pradipd** [comment]
I see.  thanks for the explanation.
