### ISSUE TITLE
The generated code for middleware projects should not depend on internal headers

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2317]
The generated code for middleware projects depends on starboard.h and included headers under:
Frameworks\include
include\xplat

**Comment by mukhole** [comment]
This will be fixed as a part of task https://github.com/Microsoft/WinObjC/issues/2346 which will make the required headers public and expose them using nuget packages.

**Comment by pradipd** [comment]
I didn't realize you already filed an issue.  Will close this as it is a duplicate of #2346.

**Comment by pradipd** [comment]
Reopening and making this the tracking bug since it is more generic than 2346.

**Comment by pradipd** [comment]
StrongId in SmartTypes.h should be moved to "Foundation or even lower. It's a great opportunity for us to make ObjC/C++ interop better!" (DHowett-MSFT )

FoundationErrorHandling.h needs to be made public since wil\result.h depends on it.
