### ISSUE TITLE
WOCCatalog[x86|Release]: Pickers: Date resets if set to high values

### ISSUE THREAD

**Issue by asimonov-msft** [Microsoft/WinObjC#2329]
Master commit: 1903d21d5ef471c0bfe236717d5fce5fc736cee7

**Repro steps:**
1. Open WOCCatalog and bring up Pickers
2. Click on **date** and pick **January 31 2017**
3. Click on **time** or **date** to save the selection
4. Click on **date** again to see the selection.

**Expected:**
The selection is **January 31 2017**.

**Actual:**
The selection changes to another value, depending on the height of the window:
* For a very short window, it changes to January 28.
* For a very tall windows, it changes to January 12.

**Comment by bbowman** [comment]
@asimonov-msft is this a regression?

**Comment by tadam-msft** [comment]
This issue is the same as #1845, closing as a duplicate.
