### ISSUE TITLE
missing introspection functions

### ISSUE THREAD

**Issue by spalda2** [Microsoft/WinObjC#233]
1>lerror LNK2019: unresolved external symbol _ivar_getTypeEncoding
1>unresolved external symbol _ivar_getTypeEncoding
1>error LNK2001: unresolved external symbol _object_setIvar
1>error LNK2001: unresolved external symbol _object_getIvar
1>error LNK2001: unresolved external symbol _property_getAttributes
1>error LNK2001: unresolved external symbol _class_getProperty
1>error LNK2001: unresolved external symbol _property_getName

**Comment by rajsesh-msft** [comment]
This is fixed with the new objc runtime, which is part of our release: 0.1.0.160128

**Comment by rajsesh-msft** [comment]
This is in our backlog and will be addressed in a future release.

**Comment by rajsesh-msft** [comment]
This is in our backlog and will be addressed in a future release.
