### ISSUE TITLE
OverrideProjects.ps1 leaves an incorrect project.json

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2339]
If the project.json lists all the dotnet imports like:
  "frameworks": {
    "dotnet": {
      "imports": [
        "netstandard1.0",
        "netstandard1.1",
.....

overrideprojects.ps1 ends up modifying the project.json and leaves:
    "frameworks":  {
                       "dotnet":  {
                                      "imports":  "netstandard1.0 netstandard1.1 netstandard1.2 ....."

And this causes nuget restore and msbuild to return cryptic errors:
nuget restore throws.
msbuild /t:restore returns  "response status code does not indicate success: 401 (Unauthorized)"

But, the  actual error is the malformed project.json.
We should also follow up with nuget and msbuild teams to get more useful error messages.

**Comment by pradipd** [comment]
Also, the error is the missing brackets around the list of dotnet imports.
"imports": [
...
]
The brackets are missing in the malformed project.json

**Comment by pradipd** [comment]
And the missing ", " between elements

**Comment by bbowman** [comment]
msbuild /t:restore returns "response status code does not indicate success: 401 (Unauthorized)"

Is normal. This means you are trying to get packages from a feed that needs credentials and you don't have the credential provider. Using the /t:restore unfortunately doesn't pick up Cred providers. I already filed an issue on them for that. Please try nuget.exe and let me know if the project.json still doesn't work.

**Comment by pradipd** [comment]
But that is not the real error.  That is a red herring.
The real error is that the project.json is malformed.

**Comment by pradipd** [comment]
I'm blocked on this for middleware.  So, I'm assigning this to myself.

**Comment by pradipd** [comment]
Fixed by #2350
