### ISSUE TITLE
 MobileCoreServices library missing

### ISSUE THREAD

**Issue by spalda2** [Microsoft/WinObjC#234]

**Comment by kennethtroch** [comment]
I have the same problem, i get the following error:
Error 'MobileCoreServices/MobileCoreServices.h' file not found

It's just on an import of the MobileCoreServices header file

**Comment by ap3rus** [comment]
+1, exactly the same issue.

**Comment by rajsesh-msft** [comment]
This is in the backlog and may be available in one of our future releases.

**Comment by ap3rus** [comment]
@rajsesh-msft Great, thanks!

**Comment by joalmeid** [comment]
Is there any update on this? Being a MobileCoreServices  a set of fundamental system services for apps, these should be supported. initially. For example AFNetworking depends on this.

**Comment by rajsesh-msft** [comment]
@joalmeid both MobileCoreServices and AFNetworking are in our near term roadmap.  [roadmap](https://github.com/Microsoft/WinObjC/wiki/Roadmap).  Coming soon.

**Comment by technotrance** [comment]
Try using mine
