### ISSUE TITLE
Release 45 D2D Regression

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#2340]
There is a Release 45 regression on D2D code where under one test D2D takes 100% of eight logical core CPU for about 30 seconds and then throws an exception - this was not present in previous releases.

**Comment by rajsesh-msft** [comment]
@eddv what test is this? Is there a call stack or repro code?

**Comment by edvv** [comment]
@rajsesh-msft It is an internal test. I'll attempt to get more information in April by which time I hope to have more resources (to address winobjc issues) as well. The OP is a heads up post for now until I get more info.

**Comment by rajsesh-msft** [comment]
Thanks @edvv.  We'll wait for that info - in the meanwhile, there is nothing actionable for us here, so will wait to hear from you.

**Comment by edvv** [comment]
@rajsesh-msft Just checking in on this one. Release 0.2.170407 takes a little longer to meltdown; so it did improve a bit from the previous release. I'll try to get some more specifics as soon as I can.

**Comment by ArnOmsft** [comment]
@edvv , we'll need more info from you to be able to do something here. Thanks.

**Comment by edvv** [comment]
@ArnOmsft I am planning on picking this up again on Release 47.

**Comment by rajsesh-msft** [comment]
@edvv any updates on this issue?

**Comment by edvv** [comment]
@rajsesh-msft This can no longer be duplicated under the current interation so I am closing this issue.
