### ISSUE TITLE
Instructions for building samples do not mention how to restore WinObjC nuget packages

### ISSUE THREAD

**Issue by asimonov-msft** [Microsoft/WinObjC#2342]
When building the samples using Visual Studio 2017 RTM, the build fails because VS does not automatically restore the required WinObjC nuget packages. The workaround is to restore the packages from the command line, as follows:
```
.\.init.cmd
.\.tools\nuget.exe restore <path to sample solution file>
```
Until automatic restore is fixed in VS 2017, we should add these steps to our README.

**Comment by bbowman** [comment]
merged fix. thanks.
