### ISSUE TITLE
StrongId type should be made public

### ISSUE THREAD

**Issue by mukhole** [Microsoft/WinObjC#2346]
include\xplat\SmartTypes.h (StrongId type) could be made part of WinObjC.Frameworks.Core or  WinObjC.Frameworks.UWP.Core.

**Comment by DHowett-MSFT** [comment]
This should be in Foundation or even lower. It's a great opportunity for us to make ObjC/C++ interop better!

**Comment by pradipd** [comment]
Closing.  Please use #2317 to track this issue.

**Comment by DHowett-MSFT** [comment]
@pradipd please move relevant comments to the new issue.
