### ISSUE TITLE
[Foundation Dependency Removal] CoreText removal of Foundation usage

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#2354]
- [x] CTFontManager: Should use CFSTR vs NSString
- [x] CTFontCollection: Should use CFSTR vs NSString
- [x] CTFrame: Should use CFSTR vs NSString
- [x] CTFontCollection: Should use CFSTR vs NSString
- [x] CTRun: Should use CFSTR vs NSString
- [x] CTTextTab: Should use CFSTR vs NSString
- [x] CTTypesetter: Should use CFSTR vs NSString

**Comment by ms-jihua** [comment]
?

**Comment by msft-Jeyaram** [comment]
Wrong item, re-purpose.

**Comment by msft-Jeyaram** [comment]
Item - [ ] CTLine: remove usage of NSMutableAttributedString falls under issue #2357 
As there too many usage of NS* components.
As other items are complete, closing this out.
