### ISSUE TITLE
[packaging] WinObjC.Logging package has a dependency on GitVersionTask

### ISSUE THREAD

**Issue by memontic-ms** [Microsoft/WinObjC#2360]
As of develop @ 4861f8b

WinObjC.Logging will pull GitVersionTask in as a dependency to projects that use WinObjC.Logging.

You can see in the nuspec it has:
```
    <dependencies>
      <dependency id="GitVersionTask" version="4.0.0-beta0011" />
    </dependencies>
```

From my knowledge WinObjC.Logging shouldn't need GitVersionTask...

**Comment by bbowman** [comment]
Agreed

**Comment by bbowman** [comment]
Taking. I'll clean this up across the board since we have a checked in version now.

**Comment by bbowman** [comment]
Should be gone with latest develop changes to versioning.
