### ISSUE TITLE
Complete NSFileHandle stubs

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#2367]
initWithCoder:
encodeWithCoder:
fileHandleWithStandardOutput
fileHandleWithStandardError
readInBackgroundAndNotify

Also:
NSFileHandleReadCompletionNotification

**Comment by DHowett-MSFT** [comment]
I wonder how onw encodes a file handle; it's a pointer to an ephemeral thing. 😕

**Comment by DHowett-MSFT** [comment]
By way of answering my own question: they cannot be coded. Attempts to do so throw an exception unless an `NSXPCCoder` is used.

Since we do not support Mach IPC, we will just implement them to throw exceptions.
