### ISSUE TITLE
New build error with new Release

### ISSUE THREAD

**Issue by Alx06** [Microsoft/WinObjC#237]
Now I've this error when building my solution :

1>C:\winobjc\msvc\sbresources.targets(218,5): error MSB3073: The command ""C:\winobjc\msvc\..\bin\acbuilder.exe" --target-device iphone --target-device ipad --compile "" """ exited with code 1.

Should I use vsimporter each time a release is published?

**Comment by SaeedAkhter-MSFT** [comment]
Thanks for the feedback.  Ideally you only need to run vsimporter once as long as the structure of the project has not changed.

Is it possible to provide steps to reproduce the problem?  That would help us to investigate further.

**Comment by Alx06** [comment]
I just tried to build my project.
Provide me a way to send you my project, that will be more easy.

**Comment by steventroughtonsmith** [comment]
This looks to be the _AssetCatalogCompile step, perhaps on projects that don't include an asset catalog? I was able to comment it out in sbresources.targets without issue

**Comment by Alx06** [comment]
Thanks for this tip.
I did it and it doesn't fail at the same point now.
Now, I'm unable to deploy my solution.
And so I can't run my project anymore...
The new error is
Error Error : DEP0700 : Registration of the app failed. Deployment Register operation with target volume C (....) failed with error 0x80073CFD. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80073cfd)

But I'm now able to build the packages for the Store !!! (without testing them anywhere...).
But the validation part did failed, with these errors:

Supported API test

FAILED
Supported APIs
Error Found: The supported APIs test detected the following errors:
API OpenSemaphore in api-ms-win-core-synch-l1-1-0.dll is not supported for this application type. System.Threading.dll calls this API.
API CreateSemaphore in api-ms-win-core-kernel32-legacy-l1-1-0.dll is not supported for this application type. System.Threading.dll calls this API.
API ExecuteAssembly in uwphost.dll is not supported for this application type. UWPShim.exe calls this API.
API DllGetActivationFactory in uwphost.dll is not supported for this application type. UWPShim.exe has an export that forwards to this API.
ObjCUWP.dll references the namespace Windows.Networking.Vpn which is not allowed for this app type.
Impact if not fixed: Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements.
How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Windows Store apps. Please note, C++ apps that are built in a debug configuration will fail this test even if it only uses APIs from the Windows SDK for Windows Store apps. See the link below for more information: 


Where is my mistake?

**Comment by asimonov-msft** [comment]
@Alx06 Can you recall the last time you were able to successfully deploy the app? What changes happened since then?

Regarding the Store validation errors - we are looking into these.

**Comment by Alx06** [comment]
It was 2 WinObjC versions ago.
I've updated Windows 10 and Visual Studio since that too.

What about getting my project and testing directly with it?

**Comment by SaeedAkhter-MSFT** [comment]
Hi Alx06, if this is an example project that can be shared publicly, please feel free to push a new project on GitHub and we will take a look.

If you would like to share it with Microsoft as confidential information, I recommend that you apply to join the "Islandwood Developer Program".  Please email me at s-a-e-e-d-a@m-i-c-r-o-s-o-f-t.com (please remove all hyphens) and I can walk you through that process.

**Comment by asimonov-msft** [comment]
@Alx06 Please try using the latest version of the SDK, released today.

You should remove any previously-generated VS files and re-import your Xcode project from scratch using vsimporter. I did this with the code you sent us, and the app built and ran without any modifications.

**Comment by Alx06** [comment]
I tried, and unfortunately I'm facing some new issues (and an old one too).
I just sent you an email for that, good luck!

**Comment by asimonov-msft** [comment]
@Alx06 I will ask Saeed to forward your message to me. However, in the future, please post your issues here, whenever possible. That way other people can benefit from the troubleshooting process and the solutions we come up with.

In the meantime, please make sure that you remove all previous Visual Studio files and build products before re-importing. After backing everything up, I would suggest completely removing:
> All *.vsimporter directories
> All *.vcxproj.user files (these can cause a variety of issues on re-import)
> All *.sdf and *.sln files
> All build product directories created by VS

Otherwise, you may get weird errors such as:
```1>Package.appxmanifest : error APPX0703: Manifest references file '6664b0ae-f861-48d6-a627-db56a1922a19.dll' which is not part of the payload.```

**Comment by asimonov-msft** [comment]
@Alx06 Looking at the errors you are getting, I'd recommend reinstalling Visual Studio 2015.

From what I understand, you've made changes to a few targets files that come with Visual Studio (e.g. Microsoft.AppxPackage.Targets). In general, changing these files is not a good idea and can cause very strange behaviour. It may solve one problem, but introduce many more.

**Comment by Alx06** [comment]
I've created a virtual machine on my mac, installing windows 10 and visual studio community 2015, and now everything is working fine, thanks to you!!!
I've generated the packages and uploaded them to the store.
Everything looks fine, I'm waiting for the validation right now :)

Many thanks!!!

**Comment by ArnOmsft** [comment]
That's a good news! You should receive an email with the outcome of the certification in the coming 24 hours. Did you run the Windows Application Certification Kit tool before submitting your package to the store and if so did it show any errors?

**Comment by Alx06** [comment]
When running the WACK, I just got an error: 

"Windows App Certification Kit - Test Results 
Error Found: The supported APIs test detected the following errors:
ObjCUWP.dll references the namespace Windows.Networking.Vpn which is not allowed for this app type."

but that was okay for the store validation, so it's okay for me.

**Comment by Alx06** [comment]
I didn't get any email from the certification but my app is now on store, that's great!!!

Thanks dor your support
