### ISSUE TITLE
Can't build build.sln on command line.

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2380]
Repro steps:

```
REM to get nuget 
init.cmd
REM Clear all nuget stuff.
nuget locals all -clear
REM start from the beginning...
init.cmd
git submodule update --init --recursive tools
nuget restore tools\tools.sln
msbuild /m /p:configuration=debug /p:platform=x86 tools\tools.sln
nuget restore build\build.sln
msbuild /m /p:configuration=debug /p:platform=x86 build\build.sln
```

The errors are always different.
Sometimes a lib can't be found.
Sometimes it's a package.

Am I doing something wrong?
We do this (or something similar) on the build machines, so, I'm not sure what the difference is.
At the very least, can you tell me if this works for you?

**Comment by DHowett-MSFT** [comment]
Updated to properly format; @pradipd if you use ` ``` ` around blocks of code, it will blockquote them.

**Comment by bbowman** [comment]
The build machines builds from the command line daily and I fixed some issues recently. Please reopen if you are still seeing issues.
