### ISSUE TITLE
Build Machine Produces Slightly Different Image Results

### ISSUE THREAD

**Issue by MSFTFox** [Microsoft/WinObjC#2396]
With the fixes for line joins on CGPaths, we've noticed a slight variation in what local images are produced versus what the build machine produces. This appears to be a fix in how line endings are done, particularly in regards to figures that have been or are being closed. The build machine produces more accurate results, removing what appeared to be a slightly extra line.

![000100_ roking_lines pathwiden_33_testimage copybystroking_lines 1 000000 linejoinround linecapsquare context](https://cloud.githubusercontent.com/assets/17168010/24570541/c597da8a-1620-11e7-9560-5ab3858952ce.png)
![000101_ roking_lines pathwiden_33_testimage copybystroking_lines 1 000000 linejoinround linecapsquare context](https://cloud.githubusercontent.com/assets/17168010/24570542/c59fbd54-1620-11e7-8e6c-a8e6f74c32c5.png)

You can see our reference image here at the bottom of the star, where the start and end of the drawing is, that there is a small extra diagonal line. Because of this, we will be thresholding the tests for the affected images since the outputs differ.

**Comment by rajsesh-msft** [comment]
Before we go down the path of the "acceptable deltas", lets understand what the differences between your local build vs the build server are.  If they are in the same flight, we expect same results.
