### ISSUE TITLE
CoreData support?

### ISSUE THREAD

**Issue by razvandub** [Microsoft/WinObjC#240]
Hi, 

Is CoreData support on your roadmap? 

Thanks.

**Comment by jeffdav** [comment]
+1

**Comment by hendelito** [comment]
Same here! +1

**Comment by technotrance** [comment]
Already at it

**Comment by razvandub** [comment]
Great, thanks.

**Comment by nicholasgerard-msft** [comment]
@technotrance could you clarify? Are you working on implementing support for CoreData in the bridge?

**Comment by technotrance** [comment]
Yes

**Comment by technotrance** [comment]
And repair encryption

**Comment by nicholasgerard-msft** [comment]
@technotrance would be great to discuss your implementation/scope/timeline – would you mind shooting me an email at nicholas dot gerard at microsoft dot com?

**Comment by s5msft** [comment]
Closing as a dup of #57
