### ISSUE TITLE
Islandwood House application ends differently.

### ISSUE THREAD

**Issue by tadam-msft** [Microsoft/WinObjC#2404]
2/28 version of application ends with simple white popup with an OK button and no images that says “Thanks for playing the demo of Islandwood House”.  Clicking OK, closes the app".  3/31 version ends with Tell Friends dialog that matches the UI of the rest of the app.

**Comment by rajsesh-msft** [comment]
BUILD2016_DEMO=1 got overwritten.

**Comment by bbowman** [comment]
pushed fix.
