### ISSUE TITLE
CGCatalog CGPathAddArcFullCircle has incorrect reference image

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#2408]
![addarc](https://cloud.githubusercontent.com/assets/15148713/24626482/4c9544b8-1866-11e7-8475-94ec69f20c54.jpg)

**Comment by DHowett-MSFT** [comment]
Oh man, we even checked in the correct reference image.

**Comment by DHowett-MSFT** [comment]
Oh, this will be resolved with the merge of #2221 [here](https://github.com/Microsoft/WinObjC/pull/2221/files#diff-5583113078c6f3f300bac2017e6eaa4a)

**Comment by MSFTFox** [comment]
Yes, this addressed in the latest pull request.
