### ISSUE TITLE
[ARM] GLKitComplex images are missing 

### ISSUE THREAD

**Issue by ashvarma** [Microsoft/WinObjC#2420]
On the most recent master build - 20170331.3
Image on the Teapot is missing for these scenes -
Vertex Lit, Specularity, Texture
Solid Color, Textured w/ Decal

And - 
Vertex Colors, Textured is black and white and the Text “Tea” is missing on the labels on the tea pot
Solid Color, Textured w/ Decal - is also black and white 

This issues looks just like #2150 - however I'm only seeing this now on ARM, previously it was broken on ARM and x86

**Comment by msft-Jeyaram** [comment]
Do you know when this start to re-appear again?

I was trying to setup my phone and attempt to install the app with visual studio (also using the scripts).
Looks like the build I flashed on isn't being picked up by my computer :(.

I'll try it again in the morning

**Comment by ashvarma** [comment]
The previous master build had the same issue on both ARM and x86. This was supposed to be fixed with #2150. I haven't tried this with an ARM develop build that had the fix for 2150

**Comment by msft-Jeyaram** [comment]
I tried it with the current version of windows on phone, with master build 20170331.3 and was unable to reproduce the bug.

This may be related to D2D changes that occurred with the new version of windows #2284

**Comment by DHowett-MSFT** [comment]
I do not believe that the minimum precision changes that causes #2284 could be implicated in a complete loss of textures.

**Comment by msft-Jeyaram** [comment]
@DHowett  it's not entirely that, but it looks like there were changes in the new version of windows that is causing this & the issue in your bug . They are not the same root cause, but it looks like there are changes in the new version of windows we need to look into, so same grouping. 

 This bug (as the other bug #2284) needs  further investigation.

**Comment by DHowett-MSFT** [comment]
I cannot reproduce this on ARM.
