### ISSUE TITLE
Build Machine Fails to Pull LFS Files

### ISSUE THREAD

**Issue by MSFTFox** [Microsoft/WinObjC#2423]
The CI Build appears to fail very quickly (within a minute) when pulling images from my current pull request. It gets through about 90% of the new images, and then fails with: _error: external filter git-lfs smudge -- %f failed._

**Comment by pradipd** [comment]
git lfs has issues.
As a workaround all build machines are configured with "git lfs install --skip-smudge" which avoids downloading files on a pull.  However, we now have an extra "git lfs pull" in every build step that involves pulling a repo.
