### ISSUE TITLE
WinObjC nuget: Specify assembly (UIKit.Xaml.dll) for root namespace UIKit in the generated nuget package.

### ISSUE THREAD

**Issue by weswmsft** [Microsoft/WinObjC#2424]
The root namespace name is UIKit and the binary name is UIKit.Xaml.dll.
We need to figure out a way to map these in our nuget package.

**Comment by bbowman** [comment]
@weswmsft how does this impact?

**Comment by bbowman** [comment]
I think this is correct now? Or isn't impacting the new packages? Please reopen if I misunderstood.
