### ISSUE TITLE
Bug in Animation when playing with frame size and position

### ISSUE THREAD

**Issue by Alx06** [Microsoft/WinObjC#243]
Take any UIView (like an UIImageView).
Set it's image.
Set it's frame to, for instance,  myView.frame = CGRectMake (50,50,100,200);

now run this code:

[UIView animateWithDuration:0.3
                             animations:^{
                               myView.frame = CGRectMake (0,0,10,20);
                             }
                             completion:^(BOOL finished){
                             }];

you'll see that the animation is completely wrong.

**Comment by Alx06** [comment]
There is a workaround:
Use myView.transform=CGAffineTransformScale(myView.transform,2.0,2.0); 
and that's working fine.

**Comment by bdrlamb-ms** [comment]
Can you elaborate on what you saw?  I ran it and it appeared to work alright.  Were there any other animations being applied to the view?

**Comment by Alx06** [comment]
The image start to grow, then jump to the right position with the right size. No other animation were applied on the view.

**Comment by bdrlamb-ms** [comment]
Do you have a sample project you could share that repros the issue?  I stuck this into an empty project and it looked fine:

    UIImageView *view = [UIImageView new];
    view.image = [UIImage imageWithContentsOfFile: @"Logo.scale-100.png"];
    [self.view addSubview: view];
    view.frame = CGRectMake (50,50,100,200);
    view.backgroundColor = [UIColor redColor];

    [UIView animateWithDuration:0.3
animations:^{
view.frame = CGRectMake (0,0,10,20);
}
completion:^(BOOL finished){
}];

**Comment by Alx06** [comment]
Try to include your imageview in another one.
I can't provide you right now a sample project.

**Comment by Alx06** [comment]
Did you try to insert a UIImageView as a subview of another UIImageView and to animate its frame?

**Comment by bdrlamb-ms** [comment]
I did, it still looked OK.  Are you using autolayout or an autoresizing mask on any of these views?

**Comment by Ramu-msft** [comment]
We have made some changes to our animation recently. If you still see this problem, please reactivate and provide more information.
