### ISSUE TITLE
OSX tests no longer build

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#2444]
Sorry for not realizing the implications earlier, but as a result of moving SmartTypes.h in #2419, OSX tests no longer build. I'm not certain what the correct fix here is, as the majority of headers in tools/include cannot be included on OSX.

**Comment by MSFTFox** [comment]
Hit this yesterday as well. Definitely need a proper fix to compare new test collateral coming in as this blocks #2187 and #2299.

**Comment by DHowett-MSFT** [comment]
@ms-jihua and I discussed this yesterday, and came up with three equally-terrible options.

1. Copy the header in both the language package directory and the xplat include directory.
2. Use symbolic links to make sure that they're the same file
   * This will not work over a file share, and this will not work on Windows <= Creators Update (and even there, it will only work for administrators)
3. Include a stub xplat/Starboard/SmartTypes.h that contains `#include <../../../xx/yy/zz/SmartTypes.h>`

**Comment by aballway** [comment]
Blocks #1725 as well
