### ISSUE TITLE
Investigate design/architecture surrounding NSURL____ classes

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#2466]
It seems moderately likely that our current object model surrounding NSURLConnection, Protocol, Session, Request and Response, are incorrect. Connection callbacks are currently built on top of Protocol callbacks, which do not appear to support uploading, making it unclear how Connection should support uploading. Additionally, the mapping of Projections objects to NS objects seems intuitively incorrect, as Protocol wraps nearly all of them, and the rest wrap basically none.

Spend some time figuring out what the correct approach here is.

**Comment by rajsesh-msft** [comment]
Please be sure to add support for 
NSURLProtocol	propertyForKey:inRequest:
NSURLProtocol	setProperty:forKey:inRequest:
NSURLSessionTask	suspend
