### ISSUE TITLE
WinObjC.Tools build error: The target "CreateManifestResourceNames" does not exist in the project

### ISSUE THREAD

**Issue by ehren** [Microsoft/WinObjC#2483]
I end up hitting this with the WinObjC.Tools, WinObjC.Logging, and WinObjC.Packages targets of tools.sln (when attempting the workaround in #2482)

**Comment by memontic-ms** [comment]
This sounds like a NuGet restore issue.
Assuming you have already run [.\init.ps1](https://github.com/Microsoft/WinObjC/wiki/Building-From-Source) once already, try running
`.\.tools\nuget.exe restore .\tools\tools.sln`
then rebuild.

If that doesn't work, can you respond with the contents of `WinObjC\tools\WinObjC.Tools\WinObjC.Tools.nuget.targets`?

**Comment by ehren** [comment]
Hmm, I just hit the first ```The target "CreateManifestResourceNames" does not exist in the project.	WinObjC.Logging	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2630``` with a clean build.

I ran ```Init.ps1``` again before doing the ```.\.tools\nuget.exe restore .\tools\tools.sln```  which looks to have succeeded; hadn't tried that from the command line previously.

Here's the .targets:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)nuget.build.packaging\0.1.186\build\NuGet.Build.Packaging.targets" Condition="Exists('$(NuGetPackageRoot)nuget.build.packaging\0.1.186\build\NuGet.Build.Packaging.targets')" />
  </ImportGroup>
</Project>
```

**Comment by ehren** [comment]
oops, this last time I built the project my visual studio was pointing to a different copy of the repo. It's possible I haven't run Init.ps1 in that repo. Trying a build from the proper repo this time...

**Comment by ehren** [comment]
and it worked. I think trying this yesterday, I never ran the tools.sln specific nuget restore. Thanks! Will try using the copy of WinObjC tools for the main build.
