### ISSUE TITLE
Unable to launch apps/browser from an Islandwood App 

### ISSUE THREAD

**Issue by ashvarma** [Microsoft/WinObjC#2487]
Climbers - selecting Game sources on the main menu no longer does anything
on build 20170331.3 this used to take you to the GitHub page 
However, on the most recent master build - 20170407.8 - this does nothing. And if you minimize/suspend the app it eventually terminates/crashes. 

I also noticed that links from within Pori have stopped working

**Comment by ashvarma** [comment]
By the way Climbers on ARM the link seems to work. So this seems to be x86 related

**Comment by DHowett-MSFT** [comment]
I'm unable to reproduce this on x86, even with the 20170407.8 x86 Climbers build.

**Comment by DHowett-MSFT** [comment]
(_ut supra_ with Pori)

**Comment by rajsesh-msft** [comment]
Doesn't repro, potentially an intermittent OS issue.
