### ISSUE TITLE
Can't link with libxml2

### ISSUE THREAD

**Issue by Alx06** [Microsoft/WinObjC#252]
I can't link with the libxml2.lib at all.
What am I missing?

**Comment by ArnOmsft** [comment]
Can you give more information about what you're doing that does not work?
Thanks.

**Comment by Alx06** [comment]
I'm trying to use the KissXML library (https://github.com/robbiehanson/KissXML)
but I've a lot of link errors, telling me that the libxml2 lib can not be located.

**Comment by Alx06** [comment]
![screen shot 2015-12-02 at 11 23 26](https://cloud.githubusercontent.com/assets/426031/11528464/2cab873e-98e7-11e5-9030-b188a08312e1.png)

**Comment by Alx06** [comment]
Don't know why messages are in French and in English, my windows is in English and my visual studio too. And I installed the English language pack (and activated it)...

**Comment by Alx06** [comment]
(Don't know why messages are in French and in English, my windows is in English and my visual studio too. And I installed the English language pack and activated it...)

First error is this one:

![screen shot 2015-12-02 at 11 25 57](https://cloud.githubusercontent.com/assets/426031/11528509/7f701444-98e7-11e5-8362-046e74be043b.png)

If i comment out the #include <iunicode/ucnv.h>, I get this error:

![screen shot 2015-12-02 at 11 27 00](https://cloud.githubusercontent.com/assets/426031/11528530/a2df620e-98e7-11e5-8dd8-78b03f63227d.png)

Then I comment out the 2 lines with UConverter, and then I get these errors:
![screen shot 2015-12-02 at 11 23 26](https://cloud.githubusercontent.com/assets/426031/11528561/d7733a90-98e7-11e5-91bc-4f8218979ea6.png)


Hope this helps!

**Comment by asimonov-msft** [comment]
@Alx06 Try the following workaround:
1. Get a copy of the WinObjC source code from GitHub
2. Locate the unicode directory in deps\prebuilt\include\icu
3. Copy the missing unicode directory into the include directory of the WinObjC SDK you are compiling against
4. Try to compile again

**Comment by Alx06** [comment]
I tried, and now I'm facing only the last issue: https://cloud.githubusercontent.com/assets/426031/11528561/d7733a90-98e7-11e5-91bc-4f8218979ea6.png

**Comment by Alx06** [comment]
Good news: I made a mistake in the configuration file.
libxml2.lib was not included in the Debug configuration.

So, here are the 3 remaining errors:

![screen shot 2015-12-03 at 13 53 42](https://cloud.githubusercontent.com/assets/426031/11561318/e2c5c7d4-99c6-11e5-8c2b-047fd7c4dbe0.png)

Looks like "CFTrimWhitespace" has not been implemented in WinObjC,
so I removed the corresponding calls to these methods,
and now there is only 1 remaining error:

Error	LNK2005	
_round already defined in LevelVC_40CD42D.obj	
ucrtd.lib(ucrtbased.dll)	

Hope someone here can help me...

**Comment by asimonov-msft** [comment]
@Alx06 Juding from [this](https://msdn.microsoft.com/en-us/library/dn353646.aspx) the Windows crt defines a round() function, resulting in duplicate symbols.

**Comment by Alx06** [comment]
Yes it was a "round" function defined in my source code that was the problem.
Link is working now, thanks for the help.
I close the issue :)
