### ISSUE TITLE
Can't build sdk under Visual Studio 2015 Update 1 

### ISSUE THREAD

**Issue by cloudmonkeypeng** [Microsoft/WinObjC#253]
Does anyone try to build the SDK under the VS2015 Update 1?

I faced the error "Failed to load C2(entry point not found)"

**Comment by cloudmonkeypeng** [comment]
I faced the error in another develop environment， too.
![image](https://cloud.githubusercontent.com/assets/3436559/11520821/dc9470b2-98e1-11e5-9695-242f80deae65.png)

Maybe I need change some default config?

**Comment by asimonov-msft** [comment]
@cloudmonkeypeng Can you please verify that you changed the solution platform to "x86" from "ARM" before building?

**Comment by cloudmonkeypeng** [comment]
@asimonov-msft   I'm sorry for my negligence.  Thanks for your help.
It can build 55 succeeded, 1 failed now.  But our project also have one issue under Update 1.

Error 	LNK1104	
cannot open file 'D:\WinObjC\build\Win32\Debug\Universal Windows\SecurityLib.Universal.lib'

Is it a known issue?

**Comment by cloudmonkeypeng** [comment]
![image](https://cloud.githubusercontent.com/assets/3436559/11581420/b7e8c1cc-9a7c-11e5-8938-b1425ab22ad9.png)
