### ISSUE TITLE
NSString missing method

### ISSUE THREAD

**Issue by jpros** [Microsoft/WinObjC#255]
Hi there,
NSString is missing the method stringByAppendingFormat:.

**Comment by triplef** [comment]
Indeed looks like it’s commented out:
https://github.com/Microsoft/WinObjC/blob/a3c7ddfa8bd6cb362e738064971dc4f9ace6164c/Frameworks/limbo/NSString.mm#L416

Not sure why - the implementation looks fine on first sight.

**Comment by rajsesh-msft** [comment]
Available in release 0.1.0.151222

**Comment by jpros** [comment]
Great job guys! :+1:
