### ISSUE TITLE
Is *.a library supported?

### ISSUE THREAD

**Issue by neuswcjr** [Microsoft/WinObjC#256]
In my ios app, there are several *.a static library used. How are these libraries supported? I tried WinObjC on my project and turns out it can't link these libraries.

**Comment by 150up** [comment]
Interested, but in my case I've also available an .dll version.

**Comment by cloudmonkeypeng** [comment]
I guess you can try to use .dll or .winmd

**Comment by neuswcjr** [comment]
In my case, the dll version library only support vs2010, _MSC_VER = 1600. When I use VS2015, it just refuse to link, which is also the biggest trouble for me to make the original UWP app. So I hope the bridge for IOS can solve this.

**Comment by technotrance** [comment]
1600 I would guess you mean by pixels

**Comment by PooyaZv** [comment]
We support .lib. So if you have the source for those libraries you can re-compile them to generate .lib static libs and link against them.
