### ISSUE TITLE
CGContextClosePath() not implemented right

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#2567]
In release 0.2.170407, CGContextClosePath() is still not working right.

RE:
https://github.com/Microsoft/WinObjC/issues/2163

**Comment by rajsesh-msft** [comment]
@edvv thanks for opening the issue.  Can you please provide information on what is not working right?

**Comment by edvv** [comment]
@rajsesh-msft See the attached two images of a closed polygon.

This is on iOS/Mac:

![closepathios](https://cloud.githubusercontent.com/assets/15889800/25198769/8dd15cf2-2516-11e7-9efb-c2e298ed2538.png)

This is on WinobjC:

![closepathwinobjc](https://cloud.githubusercontent.com/assets/15889800/25198770/8dd5aafa-2516-11e7-8b86-f4710121834b.png)

Notice how the lower left vertex of the polygon is closed on iOS/Mac, but not on WinObjC.

**Comment by edvv** [comment]
@rajsesh-msft I should have also stated that the lower left vertex is the first and last point in the path and closing the last point (to the first) should render the vertex as a vertex is rendered at any other point (vertex) in the path.

**Comment by MSFTFox** [comment]
@edvv This issue was fixed but has not made it to the current release yet. I would recommend trying this code path again with either a develop build or waiting until the next release. If you're still experiencing the issue then, please let us know. Thanks for your help!
