### ISSUE TITLE
CGContextDrawRadialGradient() not implemented right

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#2568]
In release 0.2.170407, CGContextDrawRadialGradient() is still not working right.

RE:
https://github.com/Microsoft/WinObjC/issues/2196

**Comment by msft-Jeyaram** [comment]
Could you indicate what is not correct?
I included the code you gave and various other changes and was able to get a rendering matching the ref platform.

**Comment by edvv** [comment]
The attached project gives a radial gradient on iOS but not on winobjc

[rgradient.zip](https://github.com/Microsoft/WinObjC/files/937630/rgradient.zip)

![gradient](https://cloud.githubusercontent.com/assets/15889800/25197746/09662680-2513-11e7-8444-623361816e41.png)

**Comment by msft-Jeyaram** [comment]
Thanks @edvv 
I'm taking a look at this.

Accidenly pressed closed.

**Comment by msft-Jeyaram** [comment]
@edvv The implementation has not made it to release yet.
please try again with the release that contains the Radial Gradient changes.

Thanks.
Jeyaram
