### ISSUE TITLE
UIAlertView's text displays out of bounds and doesn't wrap (20170407.8)

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#2572]
![image](https://cloud.githubusercontent.com/assets/14316954/25203039/93be3432-250c-11e7-9fd3-c1a8233e82ae.png)

**Comment by edvv** [comment]
This happens in Graph IDE as well (as would be expected). I suppose this will be fixed when https://github.com/Microsoft/WinObjC/issues/2443 is complete.

**Comment by edvv** [comment]
@DHowett-MSFT FYI: This is fixed in the current iteration of Graph IDE as well. Thank you.

**Comment by DHowett-MSFT** [comment]
@edvv Awesome! Thanks for confirming.
