### ISSUE TITLE
Symbols are missing for apps 

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2575]
It looks like binaries built in the release phase are not indexed on symweb.
The symbols are present on the share, but, symweb won't pick them up.

**Comment by bbowman** [comment]
@pradipd any more info here?

**Comment by pradipd** [comment]
Simple fix.  Just haven't had a chance to do it.
We aren't running the IndexSymbols.ps1 in our release defs.

**Comment by pradipd** [comment]
Ooops. didn't mean to close.

**Comment by bbowman** [comment]
I tried to fix it today. Check after tomorrow's build and see if it's fixed?

**Comment by pradipd** [comment]
We need to add it to the other 2 repo's we build.

**Comment by bbowman** [comment]
I did
