### ISSUE TITLE
AV in IslandwoodHouse on recent master builds

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#2578]
Could this be related to 4c6f2edcb0?

0:007> .lastevent
Last event: 74e0.4d2c: Access violation - code c0000005 (first/second chance not available)
  debugger time: Wed Apr 19 15:28:07.032 2017 (UTC - 7:00)
0:007> kn
00 0811f954 0145a351 libobjc2!objc_msgSend+0x17 [e:\src\winobjc\deps\3rdparty\libobjc2\msvc\objc_msgsend.x86-32.masm.inl @ 15732480] 
01 0811f970 518b0c61 IslandwoodHouse!-[RequestManager checkTimeout:]+0x45 [d:\build\agent3\_work\r1\a\rst\internal\mysterymanor\project\libs\iphonedev\network\requestmanager.m @ 304] 
02 0811f984 518af26e Foundation!-[NSObject performSelector:withObject:]+0x11 [d:\build\agent7\_work\17\s\frameworks\foundation\nsobject.mm @ 274] 
03 0811f99c 51893b2b Foundation!-[NSDelayedPerform perform]+0x2e [d:\build\agent7\_work\17\s\frameworks\foundation\nsdelayedperform.mm @ 68] 
04 0811f9b4 518b0c61 Foundation!+[NSObject(Foundation) _delayedPerform:]+0x1b [d:\build\agent7\_work\17\s\frameworks\foundation\nskeyvaluecoding.mm @ 697] 
05 0811f9c8 518afc60 Foundation!-[NSObject performSelector:withObject:]+0x11 [d:\build\agent7\_work\17\s\frameworks\foundation\nsobject.mm @ 274] 
06 0811f9f8 518deabe Foundation!-[NSTimer fire]+0x110 [d:\build\agent7\_work\17\s\frameworks\foundation\nstimer.mm @ 118] 
07 0811fa20 518b2785 Foundation!-[NSRunLoopState fireFirstTimer]+0x13e [d:\build\agent7\_work\17\s\frameworks\foundation\nsrunloopstate.mm @ 239] 
08 0811fa48 518b29d2 Foundation!-[NSRunLoop limitDateForMode:]+0xa5 [d:\build\agent7\_work\17\s\frameworks\foundation\nsrunloop.mm @ 199] 
09 0811fa64 518b2ad5 Foundation!-[NSRunLoop runMode:beforeDate:]+0xc2 [d:\build\agent7\_work\17\s\frameworks\foundation\nsrunloop.mm @ 258] 
0a 0811fa88 5192a426 Foundation!-[NSRunLoop run]+0x45 [d:\build\agent7\_work\17\s\frameworks\foundation\nsrunloop.mm @ 295] 
0b 0811faa0 5192b656 Foundation!ScheduleMainRunLoop+0x46 [d:\build\agent7\_work\17\s\frameworks\foundation\maindispatcher.mm @ 52] 
0c 0811faa8 628b8e8f Foundation! ?? :: ?? ::Invoke+0x16 [c:\program files (x86)\windows kits\10\include\10.0.14393.0\winrt\wrl\event.h @ 240] 
0d 0811faf4 628b903e Windows_UI!Windows::UI::Core::CDispatcher::ProcessInvokeItem+0x23e [onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 1189] 
0e 0811fb34 628b9309 Windows_UI!Windows::UI::Core::CDispatcher::ProcessMessage+0x6c [onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 276] 
0f 0811fbb8 628a4725 Windows_UI!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal+0xa0 [onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 1798] 
10 0811fc24 55a4bdcb Windows_UI!Windows::UI::Core::CDispatcher::ProcessEvents+0x65 [onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 576] 
11 (Inline) -------- Windows_UI_Xaml!CJupiterWindow::RunCoreWindowMessageLoop+0x4f [onecoreuap\windows\dxaml\xcp\dxaml\lib\jupiterwindow.cpp @ 1275] 
12 (Inline) -------- Windows_UI_Xaml!CJupiterControl::RunMessageLoop+0x66 [onecoreuap\windows\dxaml\xcp\dxaml\lib\jupitercontrol.cpp @ 884] 
13 (Inline) -------- Windows_UI_Xaml!DirectUI::DXamlCore::RunMessageLoop+0x74 [onecoreuap\windows\dxaml\xcp\dxaml\lib\dxamlcore.cpp @ 2062] 
14 0811fc68 6a3cc23d Windows_UI_Xaml!DirectUI::FrameworkView::Run+0x8b [onecoreuap\windows\dxaml\xcp\dxaml\lib\frameworkview_partial.cpp @ 100] 
15 0811fc7c 6a3efc4c twinapi_appcore!Windows::ApplicationModel::Core::CoreApplicationView::Run+0x3d [onecoreuap\shell\coreapplication\application\lib\coreapplicationview.cpp @ 1607] 
16 0811fcac 77677c3d twinapi_appcore!<lambda_134299af2ab2bf22cc3ff6fac91b23ec>::operator()+0xc9 [onecoreuap\shell\coreapplication\application\lib\coreapplicationview.cpp @ 1103] 
17 0811fd34 745d86c4 SHCore!_WrapperThreadProc+0xdd [onecoreuap\shell\shcore\libs\thread\thread.cpp @ 321] 
18 0811fd48 77843f37 kernel32!BaseThreadInitThunk+0x24 [base\win32\client\thread.c @ 64] 
19 0811fd90 77843f07 ntdll!__RtlUserThreadStart+0x2f [minkernel\ntdll\rtlstrt.c @ 997] 
1a 0811fda0 00000000 ntdll!_RtlUserThreadStart+0x1b [minkernel\ntdll\rtlstrt.c @ 914] 

dv /t /v
01 0811f970 518b0c61 IslandwoodHouse!-[RequestManager checkTimeout:]+0x45 [d:\build\agent3\_work\r1\a\rst\internal\mysterymanor\project\libs\iphonedev\network\requestmanager.m @ 304] 
@ebx              class RequestManager * self = 0x0ecfd8fc
0811f97c          class objc_selector * _cmd = 0x0398fc38
0811f980          class NSNumber * connId = 0x10a52928
@esi              class RequestData * requestData = 0x1b34fb0c
<unavailable>     class objc_object * target = <value unavailable>
<unavailable>     class objc_selector * onFailure = <value unavailable>

**Comment by ms-jihua** [comment]
The connection seems to be dealloc'd by the time we reach this code. Trying to figure out where the correct place is to add an extra retain/release.

**Comment by rajsesh-msft** [comment]
This is fixed now.
