### ISSUE TITLE
choco nupkg file store invalid

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#2583]
If I put winobjc-tools nuget file at this location:

C:\Users\ed\temp\winobjc-tools.0.2.170408-dev-20170416100207.nupkg 

and issue this command:

choco list -source C:\Users\ed\temp

then choco does not identify the nupkg as a valid file store. When I issue this command:

choco install winobjc-tools -source C:\Users\ed\temp

choco does not install from the file(s).

**Comment by bbowman** [comment]
https://github.com/chocolatey/choco/wiki/CommandsSources

You will want to add the source first and then refer to it by name instead of location (a little cumbersome I know). Let me know if that still isn't working.

**Comment by bbowman** [comment]
@edvv closing for now. Please reopen if you are still having issues
