### ISSUE TITLE
UITapGestureRecognizer.h(36,8) :  error: ARC forbids Objective-C objects in struct

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#2592]
When using the compiler in release 0.2.170407 (nuget), we are now getting this compiler error:

`UITapGestureRecognizer.h(36,8) :  error: ARC forbids Objective-C objects in struct`

Not sure why we have just started getting this error, as it seems like the def of `struct savedTouch` has been like this for a while.

**Comment by DHowett-MSFT** [comment]
@rupertdaniel This is a long shot, but do you have Objective-C Modules enabled on your project configuration in the Clang subsection?

**Comment by rajsesh-msft** [comment]
+struct savedTouch {
+    id _touch;
+    CGPoint _savedPos;
+};

should move to uikitinternal or be removed.

**Comment by rupertdaniel** [comment]
@DHowett-MSFT no we don't have modules enabled in our configuration.

**Comment by DHowett-MSFT** [comment]
@rupertdaniel Thanks for the confirmation.

To expand on @rajsesh-msft's point: This looks like an internal implementation detail that we leaked out into a public header. That structure isn't even used in the public interface for UITapGestureRecognizer.

@tadam-msft will be better able to route this issue.
