### ISSUE TITLE
Debug apps build in winobjc_internal are failing to launch

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2593]
Repro:
Install any of the win32 or arm debug apps built from winobjc_internal.

Source code:
    // If this assertion fails, a bad pointer has been passed in.  It may be
    // totally bogus, or it may have been allocated from another heap.  The
    // pointer must have been allocated from the CRT heap.
    _ASSERTE(_CrtIsValidHeapPointer(block));

Callstack:
00 ucrtbased!free_dbg_nolock
01 ucrtbased!_free_dbg
02 ucrtbased!free
03 CoreFoundation!__CFStringAppendFormatCore

**Comment by bbowman** [comment]
This Release CoreFoundation -> Debug App and that is correctly triggering the free to use the Debug crt. The allocation however must still be on the release CRT. I will need to track down what exactly I missed. Perhaps a weird other function or a call was proxied through a dll that doesn't have the CRT replacement in it (libobjc2? does it hand out memory for new classes?)

**Comment by bbowman** [comment]
ucrtbase!_realloc_base+0x30
CoreFoundation!__CFDataGrow+0xf8
CoreFoundation!CFDataSetLength+0xbe

Is at least one. Probably most of the _base symbols need redirected as well.

**Comment by DHowett-MSFT** [comment]
libobjc2 does not use a redirected heap, correct. That's part of why it's one of those things we ship in two versions :(

**Comment by bbowman** [comment]
@DHowett-MSFT was just guessing. Looking more I just missed things.
