### ISSUE TITLE
Wack tests are failing because unsupported API's are being called.

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2594]
<REQUIREMENT NUMBER="15" TITLE="Supported API test" RATIONALE="The application should only refer to the APIs allowed by the Windows SDK for Windows Store Apps.">
      <TEST INDEX="38" NAME="Supported APIs" DESCRIPTION="Windows Store App must only use supported platform APIs." EXECUTIONTIME="00h:02m:51s.88ms">
        <MESSAGES>
          <MESSAGE TEXT="API _dupenv_s in api-ms-win-crt-environment-l1-1-0.dll is not supported for this application type. WinObjCRT.dll calls this API." />
          <MESSAGE TEXT="API _wdupenv_s in api-ms-win-crt-environment-l1-1-0.dll is not supported for this application type. WinObjCRT.dll calls this API." />
        </MESSAGES>
        <RESULT><![CDATA[FAIL]]></RESULT>
      </TEST>
    </REQUIREMENT>

**Comment by bbowman** [comment]
LOL. why in the world would the app ucrt even expose this then. Thats so dumb.
