### ISSUE TITLE
Internal Compiler Error compiling Mantle

### ISSUE THREAD

**Issue by tmm1** [Microsoft/WinObjC#2596]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1001	An internal error has occurred in the compiler.	Mantle-Mac	vendor\mantle\mantle\nsvaluetransformer+mtlpredefinedtransformeradditions.m	185	
```

https://github.com/Mantle/Mantle/blob/8a1d9f8c484af0be299f49b168f7d7ed327fc9f4/Mantle/NSValueTransformer%2BMTLPredefinedTransformerAdditions.m#L185

**Comment by rajsesh-msft** [comment]
@tmm1 I tried to compile this - hit a couple of other minor compiler errors, but not the Internal Compiler Error (ICE).  It would be great if you can isolate the ICE failure.

**Comment by rajsesh-msft** [comment]
closing this issue, please re-open if this still reproduces with latest tools.
