### ISSUE TITLE
Is it possible to create a library?

### ISSUE THREAD

**Issue by teras** [Microsoft/WinObjC#2601]
In my ObjC projects I have my own library with things I use all the time. There I had created a static library which I link my project when needed.

Is it possible to do the same here? Such as create a library project which would produce the iOS-API friendly Windows library, which will be added to all my future bridged iOS->Windows projects?

Thank you for listening.

**Comment by bbowman** [comment]
@teras you can make static libraries that depend on WinObjC apis. Just make sure that you include references to winobjC in the final project so that the symbols in the static library can be found.

**Comment by edvv** [comment]
See: https://github.com/Microsoft/WinObjC/issues/236 and https://github.com/Microsoft/WinObjC/issues/2341

I am planning to try again if the merge mentioned in this issue: https://github.com/Microsoft/WinObjC/issues/1208 for libobjc2 mentioned by @DHowett-MSFT takes place just to see if there is an improvement.

**Comment by teras** [comment]
Indeed it looks possible to create C/C++ static libraries, I also found the walkthrough for it. 
For my needs though, I haveto use Objective-C files (since the original files are in Objective C).

I tried the obvious tricks to do so, but I was unable to succeed. No Objective C (.m) file was properly recognized ad compiled.
Am I missing something?

In case building static libraries with ObjC content is impossible right now, as a last solution, is it at least possible to create dynamic libraries with ObjC, or is this likewise not possible?

**Comment by rajsesh-msft** [comment]
@teras, it is not clear what you are running into.  If you have an xcode project for the static library in question, you can use vsimporter and you should be able to build the windows version of the static library.  

If you are creating a static library from scratch on visual studio, please follow the instructions here: https://github.com/Microsoft/WinObjC/wiki/Using-the-SDK.  If you are getting build errors,  grabbing the [logs](https://github.com/Microsoft/WinObjC/wiki/FAQ#how-do-i-get-my-project-log-file-to-help-determine-the-cause-of-an-issue)  would help.  

To answer your question though, yes, you can create both static libs and dlls that use objective-c.

**Comment by teras** [comment]
Indeed, this worked. Thank you.
