### ISSUE TITLE
NSURLSession delegate methods called out of order.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#2602]
Using build 0.2.170407 (nuget), NSURLSession delegate methods can be called out of order. Specifically the delegate methods:

`- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error;`

can be called before the last:

`- (void)URLSession:(NSURLSession *)session dataTask:(NSURLSessionDataTask *)dataTask didReceiveData:(NSData *)data;`

Which results in the response not having all the data present when completed.

NSURLSession uses an NSOperationQueue to dispatch the delegate callbacks, I'm wandering if there is an issue with the changes made in #2240 relating to the `maxConcurrentOperationCount`.

In our case the delegate queue has `maxConcurrentOperationCount` set to 1, so delegate methods should be called in the order they are posted by NSURLSession.

**Comment by DHowett-MSFT** [comment]
@rupertdaniel Thanks for reporting this. We're tracking the fix in #2521.

Our `Windows.Web.Http` NSURLProtocol implementation does not guarantee the dispatch of client delegate callbacks on the client thread, but it's supposed to (cf. [this](https://developer.apple.com/library/content/samplecode/CustomHTTPProtocol/Listings/Read_Me_About_CustomHTTPProtocol_txt.html) buried Apple document). Our revamp of NSOperationQueue exposed this issue.

NSOperationQueue makes no guarantees about the order of operation execution, but our original implementation executed them in per-priority insertion order. #2240 exposed NSURLProtocol's invalid behavior, but did not regress the operation queue's functionality.

Closing in favor of #2521.
