### ISSUE TITLE
Dependency Properties should be attached directly to custom XAML controls

### ISSUE THREAD

**Issue by nathpete-msft** [Microsoft/WinObjC#2607]
Currently we must attach Dependency Properties for our UIKit XAML controls to `FrameworkElement` due to type information for custom XAML controls not being exposed to the testing framework.

An unfortunate side effect of this is that `FrameworkElement` will be polluted with our Dependency Properties, and potential conflicts could arise due to duplicate property names from multiple controls.
As a temporary workaround to prevent naming conflicts with properties on `FrameworkElement`, each property will be prefixed with the owning control name: `ControlName_PropertyName`. For example, a `DependencyProperty` for the `IsActive` property on `ProgressRing` would be: `ProgressRing_IsActive`.

Once it is possible to expose the type information of our custom XAML controls to the testing framework, these Dependency Properties should be cleaned up to attach to controls directly and remove the naming prefixes.

**Comment by bbowman** [comment]
@nathpete-msft what do you mean by: 

> Once it is possible to expose the type information of our custom XAML controls to the testing framework

Perhaps we can chat about what we need in testing?

**Comment by nathpete-msft** [comment]
@jaredhms looked into this issue before, and I think he might have better understanding on what needs to be done to resolve this.

**Comment by bbowman** [comment]
@nathpete-msft if you are owning this task / bug, I'd like you to figure that out. I did most of the investigation with @jaredms and can answer questions.

**Comment by jaredhms** [comment]
@bbowman  - we need TAEF's appx test execution.
