### ISSUE TITLE
Unknown argument: '-Xanalyzer'

### ISSUE THREAD

**Issue by kensington133** [Microsoft/WinObjC#261]
I have successfully imported my app into Visual Studio with the vsimporter.exe, However when I try and build the application I get multiple occurrences of the error `CLANG : error : unknown argument: '-Xanalyzer'` in the Build window.

I did some searching and found that the new version of XCode uses treats unknown arguments as errors
 
> The Apple LLVM compiler in Xcode 5.1 treats unrecognized command-line options as errors.

_Taken from: https://bruteforce.gr/bypassing-clang-error-unknown-argument.html_

Is this error being caused by something similar within Visual Studio?

Any advice to get my app to compile would be greatly appreciated.

**Comment by ZuSe** [comment]
I have the same problem with my existing Xcode 7 App. 
It seems like the error appears when trying to compile the Pods.

I would appreciate any advise, I really like the idea behind winObjC :)

**Comment by sasukaru** [comment]
hi everyone,
i have exactly the same probleme, i have t'y to retargeted the solution as https://github.com/Microsoft/WinObjC/issues/55 , but it didn't work : (

**Comment by ganchito55** [comment]
I have the same problem and I think that the problems are the pods.
![captura](https://cloud.githubusercontent.com/assets/4716972/13333991/ec99afca-dc09-11e5-836f-25ad4620dc0d.PNG)

**Comment by nicholasgerard-msft** [comment]
@ganchito55 you're correct, this happens when you're using a CocoaPod generated Xcode workspace instead of an Xcode project. We don’t currently support CocoaPods since our clang compiler front end doesn’t support virtual filesystems, which CocoaPods depends on. Right now we suggest manually including third party frameworks and SDKs.

**Comment by asimonov-msft** [comment]
Unfortunately, this is a limitation of the clang driver we are using.

The only workaround, at this time, is to open the VCXPROJ files in a text editor and remove the offending flags. The -Xanalyzer option takes a required argument (e.g. _-Xanalyzer -analyzer-disable-all-checks_), so **be sure to remove both tokens**.
