### ISSUE TITLE
Implement newly added CGColor Apis

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#2614]
Recently the following APIs were added:
- [ ] CGColorCreateGenericCMYK
- [x] CGColorCreateGenericRGB
- [x] CGColorCreateGenericGray
- [ ] CGColorCreateCopyByMatchingToColorSpace

**Comment by rajsesh-msft** [comment]
We don't have an immediate need for the other two methods, please stub them instead.  We'll cross the bridge when we get there.
