### ISSUE TITLE
How do I copy a dll loaded using loadlibrary to the final appx package?

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2615]
My app explicitly links security.dll.   
What msbuild properties do I need to use to include it in the final appx?
What msbuild prop/targets do I use if I want to include the binary and its dependencies?

**Comment by bbowman** [comment]
Should be none?

**Comment by bbowman** [comment]
I misunderstood the original question. This is around being able to call LoadLibrary.

**Comment by DHowett-MSFT** [comment]
Wow, that is not reflected in the body of the issue _at all_. Especially the part about "explicitly links".

**Comment by bbowman** [comment]
@DHowett-MSFT much to my surprise that is exactly what *explicitly links* means. https://msdn.microsoft.com/en-us/library/784bt7z7.aspx

**Comment by DHowett-MSFT** [comment]
![](http://img09.deviantart.net/5ae0/i/2010/310/3/c/mind_blown_by_yhrite-d329zgm.jpg)

**Comment by bbowman** [comment]
See https://github.com/Microsoft/WinObjC/pull/2631
