### ISSUE TITLE
HelloUI fails to launch after C++/winrt switch

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#2619]
KERNELBASE!RaiseException+0x62
VCRUNTIME140_APP!_CxxThrowException+0x65
UIKit!winrt::impl::throw_hresult+0x2de
UIKit!winrt::Windows::Foundation::IUnknown::as<winrt::Windows::UI::Xaml::Controls::TextBlock>+0x56
UIKit!-[UILabel _initUILabel]+0x112
UIKit!-[UILabel initWithFrame:]+0x93
HelloUI+0x10f5
UIKit!_UIApplicationMainInit+0x5e6
UIKit!RunApplicationMain+0x4bb
UIKit!DoApplicationLaunch+0x29a
UIKit!_ApplicationLaunch+0x1fd
UIKit!UIApplicationLaunched+0x16a
HelloUI+0x4453
Windows_UI_Xaml!DirectUI::FrameworkApplicationGenerated::OnLaunchedProtected+0x44
Windows_UI_Xaml!DirectUI::FrameworkView::OnActivated+0xbc
Windows_UI_Xaml!Microsoft::WRL::Callback::__l2::<lambda_c07226b0ad2d361bff900a8596192414>::operator()+0x1d
Windows_UI_Xaml!Microsoft::WRL::Details::InvokeHelper<Windows::Foundation::Collections::VectorChangedEventHandler<IInspectable *>,<lambda_c07226b0ad2d361bff900a8596192414>,2,-1>::Invoke+0x28
twinapi_appcore!Microsoft::WRL::EventSource<Windows::Foundation::ITypedEventHandler<Windows::ApplicationModel::Core::CoreApplicationView *,Windows::ApplicationModel::Activation::IActivatedEventArgs *>,Microsoft::WRL::InvokeModeOptions<-2> >::InvokeAll::__l2::<lambda_1ed4baef827929e5ad54274a6ed92695>::operator()+0x18
twinapi_appcore!Microsoft::WRL::InvokeTraits<-2>::InvokeDelegates<<lambda_1ed4baef827929e5ad54274a6ed92695>,Windows::Foundation::ITypedEventHandler<Windows::ApplicationModel::Core::CoreApplicationView *,Windows::ApplicationModel::Activation::IActivatedEventArgs *> >+0x4f
twinapi_appcore!Microsoft::WRL::EventSource<Windows::Foundation::ITypedEventHandler<Windows::ApplicationModel::Core::CoreApplicationView *,Windows::ApplicationModel::Activation::IActivatedEventArgs *>,Microsoft::WRL::InvokeModeOptions<-2> >::DoInvoke<<lambda_1ed4baef827929e5ad54274a6ed92695> >+0x44
twinapi_appcore!Microsoft::WRL::EventSource<Windows::Foundation::ITypedEventHandler<Windows::ApplicationModel::Core::CoreApplicationView *,Windows::ApplicationModel::Activation::IActivatedEventArgs *>,Microsoft::WRL::InvokeModeOptions<-2> >::InvokeAll+0x10
twinapi_appcore!Windows::ApplicationModel::Core::CoreApplicationView::Activate+0x440
RPCRT4!Invoke+0x34
RPCRT4!NdrStubCall2+0x452
combase!CStdStubBuffer_Invoke+0xde
RPCRT4!CStdStubBuffer_Invoke+0x35
combase!InvokeStubWithExceptionPolicyAndTracing::__l6::<lambda_1ba7c1521bf8e7d0ebd8f0b3c0295667>::operator()+0x4e
combase!ObjectMethodExceptionHandlingAction<<lambda_1ba7c1521bf8e7d0ebd8f0b3c0295667> >+0xa8
combase!InvokeStubWithExceptionPolicyAndTracing+0x8e
combase!DefaultStubInvoke+0x356
combase!SyncStubCall::Invoke+0x1b
combase!SyncServerCall::StubInvoke+0x21
combase!StubInvoke+0x3d2
combase!ServerCall::ContextInvoke+0x5a3
combase!CServerChannel::ContextInvoke+0x49
combase!DefaultInvokeInApartment+0x5b
combase!ASTAInvokeInApartment+0xd7
combase!AppInvoke+0x904
combase!ComInvokeWithLockAndIPID+0x483
combase!ComInvoke+0x1c5
combase!ThreadDispatch+0xa4
combase!CComApartment::ASTAHandleMessage+0x49
combase!ASTAWaitContext::HandlePriorityEventsFromMessagePump+0x51
Windows_UI!Windows::UI::Core::CDispatcher::ProcessMessage+0x185
Windows_UI!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal+0xa0
Windows_UI!Windows::UI::Core::CDispatcher::WaitAndProcessMessages+0x2d
twinapi_appcore!Event::WaitAndProcessEvents+0x62
twinapi_appcore!<lambda_134299af2ab2bf22cc3ff6fac91b23ec>::operator()+0x55
shcore!_WrapperThreadProc+0xdd
KERNEL32!BaseThreadInitThunk+0x24
ntdll!__RtlUserThreadStart+0x2f
ntdll!_RtlUserThreadStart+0x1b

    auto labelGrid = [self _winrtXamlElement].try_as<Controls::Grid>();
    Controls::TextBlock textBlock = nullptr;
    if (labelGrid) {
        textBlock = XamlControls::GetLabelTextBlock(labelGrid);
    } else {
        // If we didn't get a UIKit.Label, that's ok - as long as
        // we've received a TextBlock directly.
        textBlock = [self _winrtXamlElement].as<Controls::TextBlock>(); <--- THIS IS WRONG.
    }

**Comment by rajsesh-msft** [comment]
Fixed through #2634
