### ISSUE TITLE
Error : assigning to 'GLKMatrix3' (aka 'struct _GLKMatrix3') from incompatible type 'int'

### ISSUE THREAD

**Issue by gisardo** [Microsoft/WinObjC#262]
Repro steps:
- Create OpenGL plain template with ObjC in XCode
- Import with vsimporter (project after importing: https://onedrive.live.com/redir?resid=733E3FFAB634EC2C!888052&authkey=!APoo4yWVP_uhz4E&ithint=file%2czip)

Compiler error:

1>------ Build started: Project: MyOpenGLObjCGame (MyOpenGLObjCGame\MyOpenGLObjCGame), Configuration: Debug Win32 ------
1>  ConsumeRuntimeComponent.cpp
1>  ..\..\MyOpenGLObjCGame\AppDelegate.m
1>  ..\..\MyOpenGLObjCGame\GameViewController.m
1>D:\winobjc\samples\FromMacBook\OpenGLstd\MyOpenGLObjCGame\GameViewController.m(216,21): warning : implicit declaration of function 'GLKMatrix3InvertAndTranspose' is invalid in C99 [-Wimplicit-function-declaration]
1>D:\winobjc\samples\FromMacBook\OpenGLstd\MyOpenGLObjCGame\GameViewController.m(216,50): warning : implicit declaration of function 'GLKMatrix4GetMatrix3' is invalid in C99 [-Wimplicit-function-declaration]
1>D:\winobjc\samples\FromMacBook\OpenGLstd\MyOpenGLObjCGame\GameViewController.m(216,19): error : assigning to 'GLKMatrix3' (aka 'struct _GLKMatrix3') from incompatible type 'int'

**Comment by Ramu-msft** [comment]
This issues doesn't repro with latest SDK, probably due to recent enhancements in this library. Please test this in the latest version of the SDK.
