### ISSUE TITLE
Support building in detached head mode

### ISSUE THREAD

**Issue by bviglietta** [Microsoft/WinObjC#2623]
WinObjC can't be built when git is in detached head mode, because GitVersionTask fails to determine the current branch name.

**Comment by bbowman** [comment]
Easy workaround is to create a branch or set PackageVersionOverride. It would be nice to support though with a warning. I think basically what I will do is set PackageVersionOverride if the branch can't be determined and its not currently set to something like 0.0.1-detached. It obviously won't follow all the jazz to be the latest daily but if you build everything locally it will still pick it up.
