### ISSUE TITLE
[x86] GLKitComplex/WoCCatalog freezes while transitioning between window states in GL scenarios (snapped, free-floating, etc)

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#2624]
Master commit: https://github.com/Microsoft/WinObjC/commit/9d41b1649075a328f9569d811ba66410c4d34364 
Workstation: Z440 (multi-monitor)

I am testing the commit above, and am using a build from [debug|release]/x86 of GLKitComplex.
*also repro'd on WoCCatalog in GL screens.*

I sideload the app.
It goes through its normal set of transformations. 
I use the windows + arrows keys to move it through different states (new-snap, free-floating, maximize).

Expected:
The app moves from one location to another with the tea kettle still turning.

Actual: 
After a few transitions of the app, the tea kettle freezes and the frame no longer renders. glkit eventually closes.

![image](https://cloud.githubusercontent.com/assets/5649461/25448070/318a1294-2a6c-11e7-970e-f01a86db8bdd.png)

This issue started to appear sometime between:

4/7: https://github.com/Microsoft/WinObjC/commit/43caf1228f111227a06863afb3f71f312e658aac
4/18: https://github.com/Microsoft/WinObjC/commit/9d41b1649075a328f9569d811ba66410c4d34364

**Comment by andrejo-msft** [comment]
The same problem can be seen from mousing the app around the screen into corners, the side, etc.

I have not seen the problem occur with non-GL frame as of yet.

**Comment by DHowett-MSFT** [comment]
This sounds like it could be a memory leak.

**Comment by andrejo-msft** [comment]
I don't see a jump in memory use via task manager. 

One note: it's not limited to GLKitComplex; I can repro on WocCatalog's OpenGLES 1.1 screen as well.

**Comment by rajsesh-msft** [comment]
@DHowett-MSFT could you please dig into this?

**Comment by ehren** [comment]
Noticed earlier that some files need ARC enabled in GLKit. I can open a pull unless anyone has a patch in progress.

**Comment by DHowett-MSFT** [comment]
@bviglietta this is happening in some code that was switched to C++/WinRT:

### CAEAGLLayer.mm
```objc
/**
 @Status Interoperable
*/
- (void)setContentsScale:(float)factor {
    [super setContentsScale:factor];

    Media::ScaleTransform scaleTransform;
    scaleTransform.ScaleX(1.0 / factor);
    scaleTransform.ScaleY(1.0 / factor);

    _swapChainPanel.RenderTransform(scaleTransform); // <-- HERE
}
```
### Exception
```
Unhandled exception at 0x09B0E60F (Windows.UI.Xaml.dll) in GLKitComplex.exe:
The thread's stack pointer was outside the legal stack extents for the thread.
```

It can fairly readily be reproduced by resizing the window until it dies.

Anything you know of?

**Comment by DHowett-MSFT** [comment]
Sorry, call stack:

```
 	[Inline Frame] Windows.UI.Xaml.dll!ctl::ComBase::AddRefOuter() Line 297	C++
 	Windows.UI.Xaml.dll!DirectUI::FrameworkElementGenerated::QueryInterfaceImpl(const _GUID & iid, void * * ppObject) Line 66	C++
 	Windows.UI.Xaml.dll!DirectUI::SwapChainPanel::QueryInterfaceImpl(const _GUID & iid, void * * ppObject) Line 95	C++
 	[Inline Frame] Windows.UI.Xaml.dll!ctl::ComObjectBase::QueryInterfaceBase(const _GUID &) Line 40	C++
 	Windows.UI.Xaml.dll!ctl::ComObject<DirectUI::SwapChainPanel>::QueryInterface(const _GUID & iid, void * * ppValue) Line 30	C++
 	QuartzCore.dll!winrt::Windows::Foundation::IUnknown::as<winrt::Windows::UI::Xaml::IUIElement>() Line 2446	Objective-C++
 	QuartzCore.dll!winrt::impl::require_one<winrt::Windows::UI::Xaml::Controls::SwapChainPanel,winrt::Windows::UI::Xaml::IUIElement>::operator winrt::Windows::UI::Xaml::IUIElement() Line 490	Objective-C++
 	QuartzCore.dll!winrt::Windows::UI::Xaml::impl_IUIElement<winrt::Windows::UI::Xaml::Controls::SwapChainPanel>::RenderTransform() Line 10820	Objective-C++
>	QuartzCore.dll!-[CAEAGLLayer setContentsScale:]() Line 63	Objective-C++
```

**Comment by bviglietta** [comment]
Could conceivably be the same issue as #2618, which I recently introduced and then fixed.

**Comment by DHowett-MSFT** [comment]
@bviglietta This is with #2618 applied.

**Comment by DHowett-MSFT** [comment]
(it also does not look like a failure to resolve a type, or to load a class; it looks like a stack corruption or a stack overrun?)

**Comment by bviglietta** [comment]
Then I guess I haven't seen this before. I can take a look at it.
