### ISSUE TITLE
WOCCatalog: Location: Latitude/Longitude figures are swapped

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#2625]
Open WOCCatalog app in x86 and select Location. Allow for precise location.

Expected: appropriate latitude/longitude
Actual: Latitude and longitude are swapped.

Redmond output example:
![image](https://cloud.githubusercontent.com/assets/5649461/25449221/f68a9caa-2a6f-11e7-848c-39eeb58c208e.png)

**Comment by rajsesh-msft** [comment]
@andrejo-msft - is this a regression?

**Comment by DHowett-MSFT** [comment]
LOL.

@rajsesh-msft I don't think this is a regression: check out the code!

```objc
        [locVal setText:[NSString stringWithFormat:@"Longitude: %.3f        Latitude: %.3f        ",
                                                   location.coordinate.latitude, location.coordinate.longitude]];
```

**Comment by andrejo-msft** [comment]
Yup. It's just a problem that we appear to have missed with our eyes for a while.

**Comment by edvv** [comment]
@DHowett-MSFT So, switch the variables or the text? Here is an interesting read:

http://stackoverflow.com/questions/7309121/preferred-order-of-writing-latitude-longitude-tuples
