### ISSUE TITLE
Compiler fails on specific statements

### ISSUE THREAD

**Issue by nmetulev** [Microsoft/WinObjC#263]
This code can not compile with the error:

> Error     expected ':'  
> Error     expected ';' after method prototype Pods-SDWebImage

```
@interface NSData (ImageContentTypeDeprecated)

+ (NSString *)contentTypeForImageData:(NSData *)data __deprecated_msg("Use `sd_contentTypeForImageData:`");

@end
```

Code from [here](https://github.com/KMindeguia/movies)

**Comment by christopheplat** [comment]
FYI, this bug has been fixed via commit 063c14dc94ae4f27a407dfec31c8a7d464c70df0.
