### ISSUE TITLE
[x86] [WoCCatalog] App crashes upon typing into Copying field

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#2632]
Master commit: https://github.com/Microsoft/WinObjC/commit/9d41b1649075a328f9569d811ba66410c4d34364 
Workstation: Z440 (multi-monitor)

Open WoCCatalog.
Open **Copy And Paste**.
Type into **Text is copied from here**

**Expected**: 
Field is filled with what you want to type in.

**Actual**:
App crashes immediately after a couple of characters are typed in.

The repro is largely reliable (80% of the time). In other attempts, I had to try it a couple of times (entering and exiting the Copy/Paste page.

In the previous release, this sample would freeze the app, then crash.

**Comment by jaredhms** [comment]
@andrejo-msft - can you provide a call stack?

**Comment by rajsesh-msft** [comment]
Probably a variation of #2618?

**Comment by andrejo-msft** [comment]
I'm missing some symbols which is causing me to not get you something useful. I'll see what I can find, but I was able to reproduce it both as a packaged test app as well as building from the prerelease 4/24 packages.

**Comment by yiyang-msft** [comment]
call stack: 
 	[External Code]	
 	libobjc2.dll!objc_exception_throw(void * object) Line 134	C++
 	ObjCUWPWindowsApplicationModelDataTransfer.dll!wil::details::ReportFailure(void * callerReturnAddress, unsigned int lineNumber, const char * fileName, const char * functionName, const char * code, void * returnAddress, wil::FailureType type, HRESULT hr, const wchar_t * message, details::ReportFailureOptions options) Line 3144	Objective-C++
 	ObjCUWPWindowsApplicationModelDataTransfer.dll!wil::details::ReportFailure_Hr() Line 3165	Objective-C++
 	ObjCUWPWindowsApplicationModelDataTransfer.dll!wil::details::in1diag5::_Objc_Throw_Hr(void * callerReturnAddress, unsigned int lineNumber, const char * fileName, const char * functionName, const char * code, HRESULT hr) Line 4743	Objective-C++
 	ObjCUWPWindowsApplicationModelDataTransfer.dll!+[WADClipboard flush](objc_class * self, objc_selector * _cmd) Line 1161	Objective-C++
>	UIKit.dll!+[UIPasteboard _setStringToClipboard:]() Line 570	Objective-C++
 	UIKit.dll!-[UIPasteboard setString:]() Line 526	Objective-C++
 	WOCCatalog.exe!-[UIPasteboardViewController onCopyTextChanged:](UIPasteboardViewController * const self, objc_selector * _cmd, UITextField * textField) Line 208	Objective-C
 	Foundation.dll!-[NSObject performSelector:withObject:withObject:]() Line 282	Objective-C++
 	UIKit.dll!-[UIControl sendAction:to:forEvent:]() Line 120	Objective-C++
 	UIKit.dll!-[UIControl sendActionsForControlEvents:]() Line 157	Objective-C++
 	UIKit.dll!__??R<lambda_5>@28-[UITextField _initTextBox:]UITextField@@QBE?A?<auto>@@ABUIInspectable@Foundation@Windows@winrt@@ABUTextChangedEventArgs@Controls@Xaml@UI@56@@Z_block_invoke() Line 1423	Objective-C++
 	libdispatch.dll!_dispatch_call_block_and_release(void * block) Line 124	C
 	libdispatch.dll!_dispatch_continuation_pop(dispatch_object_t dou) Line 415	C
 	libdispatch.dll!_dispatch_queue_drain(dispatch_queue_s * dq) Line 1548	C
 	libdispatch.dll!_dispatch_queue_serial_drain_till_empty(dispatch_queue_s * dq) Line 1405	C
 	libdispatch.dll!_dispatch_manual_queue_drain(dispatch_queue_s * q) Line 107	C
 	libdispatch.dll!dispatch_main_queue_callback() Line 309	C
 	Foundation.dll!-[NSRunLoop(Internal) _processMainRunLoop:]() Line 502	Objective-C++
 	Foundation.dll!_ProcessMainRunLoop() Line 66	Objective-C++
 	Foundation.dll!??R<lambda_1>@?_DispatchMainRunLoopOnUIThread@@YAXH@Z@QBEJXZ() Line 79	Objective-C++
 	Foundation.dll! ?? :: ?? ::Invoke() Line 240	Objective-C++
 	[External Code]

**Comment by yiyang-msft** [comment]
hr 0x800401d0 : OpenClipboard Failed. It seems we ran into a Platform Clipboard bug here, which result in clipboard failed to open and thus flush. Previously we don't see this and this might be the result of newer platform built.

**Comment by yiyang-msft** [comment]
We can provide work-around and move the bug to platform team, but I don’t believe this bug is blocking.

**Comment by rajsesh-msft** [comment]
Note: I don't see this in ARM.

**Comment by rajsesh-msft** [comment]
I don't see this in the windows insider build canary flight.  As @yiyang-msft indicated, this appears to be a platform regression that has since been apparently addressed.
