### ISSUE TITLE
[x86] Visual artifact appears in text fields when no data appears

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#2633]
Master commit: https://github.com/Microsoft/WinObjC/commit/9d41b1649075a328f9569d811ba66410c4d34364 
Workstation: Z440 (multi-monitor)

I open IslandwoodNews and can create this issue easily. I have seen this in WoCCatalog as well but without as consistent a repro; I assume this is part of the new XAML tabbing/accessibility mapping work.

Open IslandwoodNews.

In Search bar, type *test* and press return.
In this releaseObserve that the work disappears, presumably to go and search for that term. 

**Expected**:
I expect that the text bar is empty.

**Actual**:
Note the little square surrounding the pixel.

This is a regression from the previous release. No such artifact appears.

**Comment by jaredhms** [comment]
@andrejo-msft - can you please paste an image?  It **_sounds like_** focus is moving to a small 'dummy button' (a 1x1 transparent button).  If so, this isn't a regression, but it **_is_** being fixed soon with #2616.

**Comment by andrejo-msft** [comment]
![image](https://cloud.githubusercontent.com/assets/5649461/25458962/fb1cae22-2a90-11e7-8eae-65267aab4ae8.png)
Looks like a good read on the problem.

**Comment by rajsesh-msft** [comment]
This is indeed fixed in develop, closing the issue.
