### ISSUE TITLE
[x86] [Debug] IslandwoodHouse does not launch

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#2635]
Master commit: https://github.com/Microsoft/WinObjC/commit/9d41b1649075a328f9569d811ba66410c4d34364 
Workstation: Z440 (multi-monitor)

Using the most recent build, we ran the IslandwoodHouse test app off of a debug build.

In my dev environment, the debug version of the app does not load. Release version works just fine.

**Comment by jaredhms** [comment]
Debug islandwoodhouse has never been stable; it usually times out (PLM terminates it for taking too long to launch).

**Comment by rajsesh-msft** [comment]
in that case..
