### ISSUE TITLE
Sample app builds are broken

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#2644]
Looks like its due to a bug in the new Demo app. @MSFTFox can you jump on this?

ViewController_E8765444.obj(0,0): Error LNK2001: unresolved external symbol ___objc_class_name_DemoScenarioImages
ViewController_E8765444.obj(0,0): Error LNK2019: unresolved external symbol __OBJC_CLASS_DemoScenarioImages referenced in function _CGRectMake
d:\Build\Agent7\_work\r1\a\winobjc-samples\scenarios\CGCT\Debug\CGCT\CGCT.exe(0,0): Error LNK1120: 2 unresolved externals
Process 'msbuild.exe' exited with code '1'.

**Comment by pradipd** [comment]
Hank,
It looks like you added some files to the app in VS.  You need to add them in xcode.
In the build, we vsimport these apps, then build them.
A local repro would be:
vsimport
nuget restore 
msbuild /m /p:configuration=debug /p:platform=win32 CGCT-WinStore10.sln

**Comment by MSFTFox** [comment]
This issue was fixed on the samples repo.
