### ISSUE TITLE
[x86] [CTCatalog] Access violation during activation

### ISSUE THREAD

**Issue by aballway** [Microsoft/WinObjC#2651]
Sometimes manifests as a heap corruption in ntdll.dll

**Comment by msft-Jeyaram** [comment]
Is this the same known bug, where you try to change fonts and it crashes?

**Comment by aballway** [comment]
Nope, this happens during activation before the main screen loads

**Comment by msft-Jeyaram** [comment]
I am unable to repo this.
I can launch and run the samples fine.

**Comment by aballway** [comment]
Seems to be an issue local to my machine, closing
