### ISSUE TITLE
Versioning Targets should be aware of locally built packages

### ISSUE THREAD

**Issue by bbowman** [Microsoft/WinObjC#2653]
It would be extra nice if the versioning targets was additionally aware of the PackageReferenceOverride targets so that if a local package is used, the consumer would be versioned with corresponding information. This is a little weird / hard since the versioning target is used for both the producer (based on tags and properties) and the consumer (where having it based on the local package versions would be nice).

**Comment by rajsesh-msft** [comment]
Since this is only extra nice, we will do it if we run into this scenario a lot.  Closing this for the time being.
