### ISSUE TITLE
Unable to resolve "xxx.vcxproj"

### ISSUE THREAD

**Issue by lafezhang** [Microsoft/WinObjC#2655]
I tried to build the SDK from source, so I followed the steps here: [https://github.com/Microsoft/WinObjC/wiki/Building-From-Source#setup](url). However, when I run  
".\.tools\nuget.exe restore .\build\build.sln",  the output from powershell window:
PS C:\Users\User\Desktop\winobjc_git\WinObjC> .\.tools\nuget.exe restore .\build\build.sln
MSBuild auto-detection: using msbuild version '15.1.1012.6693' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
Restoring packages for C:\Users\User\Desktop\winobjc_git\WinObjC\build\WinObjC.Frameworks.Core\WinObjC.Frameworks.Core.nuproj...
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CFNetwork\dll\CFNetwork.vcxproj' for 'UAP,Version=v10.0'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CoreFoundation\dll\CoreFoundation.vcxproj' for 'UAP,Version=v10.0'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Foundation\dll\Foundation.vcxproj' for 'UAP,Version=v10.0'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\MobileCoreServices\dll\MobileCoreServices.vcxproj' for 'UAP,Version=v10.0'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Starboard\dll\Starboard.vcxproj' for 'UAP,Version=v10.0'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CFNetwork\dll\CFNetwork.vcxproj' for 'UAP,Version=v10.0 (win)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CoreFoundation\dll\CoreFoundation.vcxproj' for 'UAP,Version=v10.0 (win)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Foundation\dll\Foundation.vcxproj' for 'UAP,Version=v10.0 (win)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\MobileCoreServices\dll\MobileCoreServices.vcxproj' for 'UAP,Version=v10.0 (win)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Starboard\dll\Starboard.vcxproj' for 'UAP,Version=v10.0 (win)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CFNetwork\dll\CFNetwork.vcxproj' for 'UAP,Version=v10.0 (win-x64)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CoreFoundation\dll\CoreFoundation.vcxproj' for 'UAP,Version=v10.0 (win-x64)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Foundation\dll\Foundation.vcxproj' for 'UAP,Version=v10.0 (win-x64)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\MobileCoreServices\dll\MobileCoreServices.vcxproj' for 'UAP,Version=v10.0 (win-x64)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Starboard\dll\Starboard.vcxproj' for 'UAP,Version=v10.0 (win-x64)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CFNetwork\dll\CFNetwork.vcxproj' for 'UAP,Version=v10.0 (win-x86)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CoreFoundation\dll\CoreFoundation.vcxproj' for 'UAP,Version=v10.0 (win-x86)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Foundation\dll\Foundation.vcxproj' for 'UAP,Version=v10.0 (win-x86)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\MobileCoreServices\dll\MobileCoreServices.vcxproj' for 'UAP,Version=v10.0 (win-x86)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Starboard\dll\Starboard.vcxproj' for 'UAP,Version=v10.0 (win-x86)'.
Committing restore...
Lock file has not changed. Skipping lock file write. Path: C:\Users\User\Desktop\winobjc_git\WinObjC\build\WinObjC.Frameworks.Core\obj\project.assets.json
Restore failed in 339.95 ms for C:\Users\User\Desktop\winobjc_git\WinObjC\build\WinObjC.Frameworks.Core\WinObjC.Frameworks.Core.nuproj.
Restoring packages for C:\Users\User\Desktop\winobjc_git\WinObjC\build\WinObjC.Frameworks.ThirdParty\WinObjC.Frameworks.ThirdParty.nuproj...
Committing restore...
Lock file has not changed. Skipping lock file write. Path: C:\Users\User\Desktop\winobjc_git\WinObjC\build\WinObjC.Frameworks.ThirdParty\obj\project.assets.json
Restore completed in 9.4 ms for C:\Users\User\Desktop\winobjc_git\WinObjC\build\WinObjC.Frameworks.ThirdParty\WinObjC.Frameworks.ThirdParty.nuproj.
Restoring packages for C:\Users\User\Desktop\winobjc_git\WinObjC\build\WinObjC.Frameworks.UWP.Core\WinObjC.Frameworks.UWP.Core.nuproj...
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CFNetwork\dll\CFNetwork.vcxproj' for 'UAP,Version=v10.0'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CoreFoundation\dll\CoreFoundation.vcxproj' for 'UAP,Version=v10.0'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Foundation\dll\Foundation.vcxproj' for 'UAP,Version=v10.0'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\MobileCoreServices\dll\MobileCoreServices.vcxproj' for 'UAP,Version=v10.0'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Starboard\dll\Starboard.vcxproj' for 'UAP,Version=v10.0'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CFNetwork\dll\CFNetwork.vcxproj' for 'UAP,Version=v10.0 (win)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CoreFoundation\dll\CoreFoundation.vcxproj' for 'UAP,Version=v10.0 (win)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Foundation\dll\Foundation.vcxproj' for 'UAP,Version=v10.0 (win)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\MobileCoreServices\dll\MobileCoreServices.vcxproj' for 'UAP,Version=v10.0 (win)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Starboard\dll\Starboard.vcxproj' for 'UAP,Version=v10.0 (win)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CFNetwork\dll\CFNetwork.vcxproj' for 'UAP,Version=v10.0 (win-x64)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CoreFoundation\dll\CoreFoundation.vcxproj' for 'UAP,Version=v10.0 (win-x64)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Foundation\dll\Foundation.vcxproj' for 'UAP,Version=v10.0 (win-x64)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\MobileCoreServices\dll\MobileCoreServices.vcxproj' for 'UAP,Version=v10.0 (win-x64)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Starboard\dll\Starboard.vcxproj' for 'UAP,Version=v10.0 (win-x64)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CFNetwork\dll\CFNetwork.vcxproj' for 'UAP,Version=v10.0 (win-x86)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\CoreFoundation\dll\CoreFoundation.vcxproj' for 'UAP,Version=v10.0 (win-x86)'.
Unable to resolve 'C:\Users\User\Desktop\winobjc_git\WinObjC\build\Foundation\dll\Foundation.vcxproj' for 'UAP,Version=v10.0 (win-x86)'.

can anyone help?

**Comment by bbowman** [comment]
Hi @lafezhang 

This usually indicates that nuget can't load the project for some reason. Unfortunately nuget.exe doesn't give the best error messages for this.

From a **Developer Command Prompt for VS 2017** (you should be able to search your start menu for this), navigate to the folder where **build.sln** is and try running:

`msbuild .\build.sln /t:Restore /p:Configuration=Debug /p:Platform=x86`

This will run the restore target that nuget uses to inspect the projects and should provide a little more information on what is going wrong. A first guess is that git lfs may not have run and some binary used in the build (like .\common\gitversiontask\4.0.0-beta0011\build\GitVersionTask.dll) isn't actually pulled down and it can't load the placeholder file.

Please let me know what the issue ends up being so that I can update https://github.com/Microsoft/WinObjC/wiki/Packaging#known-issues to help other folks in the future.

Thanks!

**Comment by lafezhang** [comment]
ok. It seems that the repo can not be cloned using Mac (even with git-lfs installed), it must be cloned using Windows

**Comment by bbowman** [comment]
Closing since this was figured out.
