### ISSUE TITLE
How to Debug Winobjc?

### ISSUE THREAD

**Issue by lafezhang** [Microsoft/WinObjC#2657]
Hi guys! I have successfully build WinObjc SDK from source, and run you  samples. I can Debug (step into and so on...) the sample project "HelloUI" itself. But I can not Step Into the WinObjc Source code. What should I do? 
By the way, Can you provide a way to Debug WinObjc SDK without "Nuget"?

**Comment by bbowman** [comment]
If you set your symbol path to look at the output folder of the sdk build, you should be able to get local symbols. (.\build\win32\Debug\Universal Windows\ should have all the .pdbs you are looking for). 

Why do you want to not use nuget? If you are just using the sdk, it is the easiest way to consume the sdk (you don't need to build the sdk and can easily jump between versions). please see 
https://github.com/Microsoft/WinObjC/wiki/packaging#what-benefit-does-a-developer-get-from-winobjc-shipping-via-packages for more info on why we ship with nuget.

**Comment by rajsesh-msft** [comment]
@lafezhang please let us know if you have any further questions on this.  closing the issue for now.
