### ISSUE TITLE
kCGInterpolationHigh not working?

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#2669]
In UIImage if I call the method below (which is the WINOBJC implementation but with the 3 ADD lines shown and method name change to my_* ) the image still does not interpolate very well when the CTM is scaled down (image made smaller). Is there something I am missing?

```objc
- (void)my_drawAtPoint:(CGPoint)point blendMode:(CGBlendMode)mode alpha:(float)alpha {
    CGContextRef cur = UIGraphicsGetCurrentContext();
    RETURN_IF(!cur);

    CGImageRef img = getImage(self);
    RETURN_IF(!img);

    CGContextSaveGState(cur);
    _CGContextPushBeginDraw(cur);

    auto popEnd = wil::ScopeExit([cur]() {
        _CGContextPopEndDraw(cur);
        CGContextRestoreGState(cur);
    });

    CGContextSetBlendMode(cur, mode);
    CGContextSetAlpha(cur, alpha);

    float img_height = CGImageGetHeight(img);
    float img_width = CGImageGetWidth(img);

    CGRect pos;
    pos.origin = point;
    pos.size.height = (img_height / _scale);
    pos.size.width = (img_width / _scale);

    // |1  0 0| is the transformation matrix for flipping a rect about its Y midpoint m. (m = (y + h/2))
    // |0 -1 0|
    // |0 2m 1|
    CGContextConcatCTM(cur, CGAffineTransformMake(1, 0, 0, -1, 0, 2 * (pos.origin.y + (pos.size.height / 2))));

    CGContextSetShouldAntialias(cur, YES); // ADD
    CGContextSetAllowsAntialiasing(cur, YES); // ADD
    CGContextSetInterpolationQuality(cur, kCGInterpolationHigh); // ADD

    CGContextDrawImage(cur, pos, img);
}
```

**Comment by rajsesh-msft** [comment]
Looking at https://github.com/Microsoft/WinObjC/blob/7bdcbe4077f5d018598b7354c7b4924b454033b1/include/CoreGraphics/CGContext.h#L49, kCGInterpolationHigh is inexplicably 3 instead of 4.  This results in linear interpolation instead of cubic as intended.

**Comment by edvv** [comment]
@rajsesh-msft Using kCGInterpolationMedium gives what appears to be the same result. The images are not smoothed and are jagged; looking much like kCGInterpolationHigh.

**Comment by edvv** [comment]
I compared 30 images scaled to 1/8 scale each using kCGInterpolationMedium and then using kCGInterpolationNone. Took screen shots of both renderings and compared them side by side and they look visually the same to me. Meaning CGContextSetInterpolationQuality() and CGContextSetShouldAntialias() have no effect for the code shown.

**Comment by DHowett-MSFT** [comment]
That's really curious.

@rajsesh-msft `3` corresponds to `MULTI_SAMPLE_LINEAR` (as an enumerated value, not a linear scale); it should be among the higher interpolation modes.

We're pushing the interpolation mode through to Direct2D, so I'll investigate where that's failing.

**Comment by rajsesh-msft** [comment]
@DHowett-MSFT got hit by off by one bug. 😭

**Comment by DHowett-MSFT** [comment]
Aaaaargh!

We're not copying over `shouldInterpolate` when we do image format conversion.

**Comment by edvv** [comment]
@DHowett-MSFT All the images look much better now on release 48. Thank you.

**Comment by DHowett-MSFT** [comment]
@edvv Thanks for confirming!
