### ISSUE TITLE
ERROR: initializing 'GLKVector3' (aka 'struct _GLKVector3') with an expression of incompatible type 'int'

### ISSUE THREAD

**Issue by petriw** [Microsoft/WinObjC#267]
TL;DR:
Created a new project using Cocos2d-objc on my mac, created a VS Solution, getting the following error during compile:
initializing 'GLKVector3' (aka 'struct _GLKVector3') with an expression of incompatible type 'int'

Repro:
1) Create a new Cocos2d project using XCode and the libs from http://cocos2d-objc.org/
2) import with vsimporter
3) Build and Run the VS Solution

Note:
I tried importing GLKit.h and adding GLKit.lib;OpenGLES.lib

My VS Solution:
My solution can be found here:
http://1drv.ms/1HLRSfI

**Comment by Ramu-msft** [comment]
This issues doesn't repro with latest SDK, probably due to recent enhancements in this library. Please test this in the latest version of the SDK.
