### ISSUE TITLE
Regression in layer background color

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#2671]
@msft-Jeyaram does your UIColor/CGColor bridge change #2662 fix this?

WOCCatalog Bezier Paths:

![image](https://cloud.githubusercontent.com/assets/14316954/25757723/7bbe9018-3180-11e7-8119-d6556c7fe185.png)

Backgrounds should be gray.

**Comment by rajsesh-msft** [comment]
Do we know when this regressed?

**Comment by DHowett-MSFT** [comment]
It looks like some time between `20170424` and `HEAD` :smile:

**Comment by msft-Jeyaram** [comment]
@rajsesh-msft @DHowett-MSFT  this fixes the issue.

**Comment by msft-Jeyaram** [comment]
Also doing another run of verification with two apps of different version installed to verify the latest fix.

**Comment by msft-Jeyaram** [comment]
![image](https://cloud.githubusercontent.com/assets/18413092/25764347/351ae2bc-319c-11e7-855c-840b9e4b347d.png)

**Comment by DHowett-MSFT** [comment]
It's beautiful!

**Comment by msft-Jeyaram** [comment]
closed as per #2662
