### ISSUE TITLE
iLabyrinth and iLabyrinthLite are crashing on app launch

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2675]
Repro:
take the latest build and launch it.

Callstack:
08 079cdf5c 74ad12bb ntdll!RtlFreeHeap
09 079cdf70 74ad1288 ucrtbase!_free_base
0a 079cdf80 5d046b19 ucrtbase!free
0b 079ce034 5d035b7f AudioToolbox!CAFDecoder::InitForRead+0x599 [d:\build\agent7\_work\17\s\frameworks\audiotoolbox\cafdecoder.mm @ 347] 
0c 079ce870 5d031f7e AudioToolbox!AudioFileCAF::openURL+0xef [d:\build\agent7\_work\17\s\frameworks\audiotoolbox\audiofile.mm @ 402] 
0d 079ce8a0 5d032b4c AudioToolbox!AudioFileOpenURL+0x16e [d:\build\agent7\_work\17\s\frameworks\audiotoolbox\audiofile.mm @ 526] 
0e 079ce8c0 0124b345 AudioToolbox!_ExtAudioFileOpenURL+0x1c [d:\build\agent7\_work\17\s\frameworks\audiotoolbox\audiofile.mm @ 892]

**Comment by yiyang-msft** [comment]
fixed.
