### ISSUE TITLE
Islandwood News AV on accessing nullptr when launching.

### ISSUE THREAD

**Issue by yiyang-msft** [Microsoft/WinObjC#2682]
The stack is:
UIKIT.DLL!winrt::Windows::UI::Xaml::Controls::impl_IWebView2<winrt::Windows::UI::Xaml::Controls::WebView>::DefaultBackgroundColor() Line 56524	Objective-C++
>	UIKIT.DLL!-[UIWebView setBackgroundColor:]() Line 367	Objective-C++
 	UIKIT.DLL!-[UIView initWithCoder:]() Line 852	Objective-C++
 	UIKIT.DLL!-[UIWebView initWithCoder:]() Line 234	Objective-C++
 	UIKIT.DLL!constructObject() Line 210	Objective-C++
 	UIKIT.DLL!idForItem() Line 233	Objective-C++
 	UIKIT.DLL!getObjectForKey() Line 273	Objective-C++
 	UIKIT.DLL!-[UINibUnarchiver decodeObjectForKey:]() Line 512	Objective-C++
 	UIKIT.DLL!-[UIRuntimeOutletConnection initWithCoder:]() Line 25	Objective-C++
 	UIKIT.DLL!constructObject() Line 210	Objective-C++
 	UIKIT.DLL!idForItem() Line 233	Objective-C++
 	UIKIT.DLL!constructObject() Line 135	Objective-C++
 	UIKIT.DLL!idForItem() Line 233	Objective-C++
 	UIKIT.DLL!getObjectForKey() Line 273	Objective-C++
 	UIKIT.DLL!-[UINibUnarchiver decodeObjectForKey:]() Line 512	Objective-C++
 	UIKIT.DLL!-[UINib instantiateWithOwner:options:]() Line 114	Objective-C++
 	UIKIT.DLL!-[UIViewController loadView]() Line 889	Objective-C++
 	UIKIT.DLL!-[UIViewController view]() Line 937	Objective-C++
 	IslandwoodHouse.exe!-[AppDelegate createConsole](AppDelegate * self=0x1286482c, objc_selector * _cmd=0x02036d8c) Line 99	Objective-C
 	IslandwoodHouse.exe!-[AppDelegate loading](AppDelegate * self=0x1286482c, objc_selector * _cmd=0x02036c18) Line 164	Objective-C
 	FOUNDATION.DLL!-[NSObject performSelector:withObject:withObject:]() Line 282	Objective-C++
 	FOUNDATION.DLL!-[NSOrderedPerform fireInMode:]() Line 65	Objective-C++
 	FOUNDATION.DLL!-[NSRunLoop _orderedPerforms]() Line 160	Objective-C++
 	FOUNDATION.DLL!-[NSRunLoop limitDateForMode:]() Line 193	Objective-C++
 	FOUNDATION.DLL!-[NSRunLoop runMode:beforeDate:]() Line 258	Objective-C++
 	FOUNDATION.DLL!-[NSRunLoop run]() Line 295	Objective-C++
 	FOUNDATION.DLL!-[NSRunLoop(Internal) _run]() Line 467	Objective-C++
 	FOUNDATION.DLL!ScheduleMainRunLoop() Line 52	Objective-C++
 	FOUNDATION.DLL!??R<lambda_2>@?ScheduleMainRunLoopAsync@@9@QBEJXZ() Line 108	Objective-C++
 	FOUNDATION.DLL!$0A::InvokeHelper<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<2>,ABI::Windows::UI::Core::IDispatchedHandler,Microsoft::WRL::FtmBase,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil>,eduleMainRunLoopAsync>::Invoke() Line 240	Objective-C++
 	[External Code]

**Comment by rajsesh-msft** [comment]
Fixed with #2683
