### ISSUE TITLE
Assertion failed in foundation.dll

### ISSUE THREAD

**Issue by deltakosh** [Microsoft/WinObjC#269]
My project compiles well but it does not run as I get an assertion failed located in Foundation.dll.
The project is a really simple 2D games that just uses CoreGaphics.framework

Project can be found here: https://dl.dropboxusercontent.com/u/15301403/Maze.ZIP

**Comment by ArnOmsft** [comment]
Sorry for the long time to answer this. I downloaded the project, VS would not open the VS solution so I reran VSImporter to regenerate the it using our latest release from 4/7. The project compile and run although it's not playable. Could you retry and check if you still get the same error?
Thanks.

**Comment by ArnOmsft** [comment]
Closing this since I could not repro, please retry with our latest release and re-open if you can repro.
Thanks.
