### ISSUE TITLE
Import managed dll into unmanaged console app

### ISSUE THREAD

**Issue by wlw** [Microsoft/WinObjC#2696]
I built the C# dll. Configured for unmanaged interface ( ran RegAsm.exe). All seemed okay - no errors.Had previously built a C++ app and added #import "C:\myManagedDll.tlb" raw_interfaces_only
Editor highlighted #import with:
Cannot open source file ...../myMangedDll.tlh. The file path pointed to the unmanaged code and does not exist.

**Comment by rajsesh-msft** [comment]
Are you doing this in a winobjc project?

**Comment by wlw** [comment]
Nope. Development environment is Visual Studio 2017 Community. Managed Dll C#  'class library'. Unmanaged  C++ 'console application'

**Comment by rajsesh-msft** [comment]
@wlw this project only tracks winobjc and is not the right forum for this.  stackoverflow may be a better forum for this.  Closing this issue.

**Comment by wlw** [comment]
Sorry for the inconvenience. In my travels through the net, I saw a similar question. Regards
