### ISSUE TITLE
UIColor generates a CGColor with an incorrect number of color components

### ISSUE THREAD

**Issue by SourceF** [Microsoft/WinObjC#2703]
The CGColor returned by an UIColor has a wrong number of color components. It can be reproduced with this code:

CGColorGetNumberOfComponents([UIColor colorWithRed:1 green:0 blue:1 alpha:1].CGColor);
This call should return 4, but it returns 1 instead.

**Comment by msft-Jeyaram** [comment]
@SourceF  I am taking a look at this.
We had similar tests that exercise this and it's been valid.

**Comment by msft-Jeyaram** [comment]
@SourceF  the same exact code is working as intended.
`    EXPECT_EQ(4, CGColorGetNumberOfComponents([UIColor colorWithRed:1 green:0 blue:1 alpha:1].CGColor));`

**Comment by SourceF** [comment]
fixed in “0.2.170511-dev-20170511235959”. We were using “0.2.170407"
