### ISSUE TITLE
System level intrinsics from Objective-C source file

### ISSUE THREAD

**Issue by adammika** [Microsoft/WinObjC#2717]
I'm looking to port some Objective-C macOS code that uses SSE2 intrinsics (such as `_mm_loadu_si128` and `_mm_storeu_si128`. The files are compiling just fine, but for every intrinsic call, I'm getting an `LNK2019 unresolved external symbol` during the linking process. 

I'm wondering if system level intrinsics are supported within ObjC source files, or if I'm going to have to re-write these in C++.

**Comment by rajsesh-msft** [comment]
@adammika apologies for the delay.  Yes, not all intrinsics would work with clang unfortunately.  You can however move these to a .cpp file and add them to the project as clcompile - in fact, we do that in the accelerate framework. You may have to manually edit the project file like [this]( https://github.com/Microsoft/WinObjC/blob/develop/build/Accelerate/lib/AccelerateLib.vcxproj).

**Comment by adammika** [comment]
@rajsesh-msft Thanks for the response. Just tried out your suggestion, and it works just fine for our needs. Thank you so much!
