### ISSUE TITLE
Convert NSFileManger use of WRL to cppwinrt

### ISSUE THREAD

**Issue by aballway** [Microsoft/WinObjC#2736]
SavePropertiesAsync and RetrievePropertiesAsync are not implemented so we must use WRL directly.

Blocked by https://github.com/Microsoft/cppwinrt/issues/204

**Comment by DHowett-MSFT** [comment]
It might be worth duping this upstream to Microsoft/cppwinrt!

**Comment by rajsesh-msft** [comment]
If it isn't broken, don't fix it.  We have other usage of wrl in foundation, we should not be converting these.
