### ISSUE TITLE
Linker error : unresolved _CryptAcquireContext and _CryptGenRandom

### ISSUE THREAD

**Issue by Angeman** [Microsoft/WinObjC#2772]
Hi,

I'm trying to build my iOS project using WinObjC but I get this linker error.

```
1>crypt_B64288EE.obj : error LNK2019: symbole externe non résolu _CryptAcquireContext référencé dans la fonction _cryptrand
1>crypt_B64288EE.obj : error LNK2019: symbole externe non résolu _CryptGenRandom référencé dans la fonction _cryptrand
```

Any idea where these _CryptAcquireContext and _CryptGenRandom symbols come from ? And which dependency should I add to the linker parameters to be able to link ?

Thanks

**Comment by DHowett-MSFT** [comment]
Hi @Angeman! Thanks for reporting this.

It looks like `CryptAcquireContext` and `CryptGenRandom` are Windows Desktop only APIs; they can't be used from Universal applications like the ones WinObjC makes.

If you're the author of the encryption code, you should be able to adopt the UWP APIs in the `Windows.Security.Cryptography` namespace; namely, `CryptographicBuffer`.

There's some C# documentation on doing that [here](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.cryptographicbuffer). You should be able to adapt it to the WinObjC projections in `UWP/WSCryptography.h` for Objective-C or use [C++/WinRT](https://github.com/Microsoft/cppwinrt) for C++.

**Comment by DHowett-MSFT** [comment]
Sorry, I meant `UWP/WindowsSecurityCryptography.h` :smile:

**Comment by DHowett-MSFT** [comment]
Since this looks like code outside of our control (and using the Win32 API surface), I'll close this one pending further info.
