### ISSUE TITLE
sample apps don't compile due to GitVersionTask.dll

### ISSUE THREAD

**Issue by Ron2** [Microsoft/WinObjC#2774]
I get the following compile error with the samples, like HelloOpenGL. The dll listed in the error message exists, but does not appear to be a .NET assembly (according to JetBrains' dotPeek). I tried using Nuget to install the `GitVersionTask` package, but that didn't help. I tried removing this `GitVersionTask` dependency from the sample apps but that doesn't seem easy.

> Error	MSB4062	The "GitVersionTask.GetVersion" task could not be loaded from the assembly Y:\repositories\WinObjC\common\gitversiontask\4.0.0-beta0011\build\GitVersionTask.dll. Could not load file or assembly 'file:///Y:\repositories\WinObjC\common\gitversiontask\4.0.0-beta0011\build\GitVersionTask.dll' or one of its dependencies. The module was expected to contain an assembly manifest. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	HelloOpenGL (HelloOpenGL\HelloOpenGL)	Y:\repositories\WinObjC\common\gitversiontask\4.0.0-beta0011\build\GitVersionTask.targets	68	
> 
Any ideas about how to get around this error?

**Comment by DHowett-MSFT** [comment]
This looks like it might be due to a missing git-lfs install. Have you followed the git-lfs steps in [Building from Source](https://github.com/Microsoft/WinObjC/wiki/Building-From-Source)?

**Comment by Ron2** [comment]
No, I didn't build the Framework from source, so I didn't follow those instructions. I followed the instructions from README.md -- installing VS2017 Community Edition with all the required components, Chocolately, and winobjc-tools. Then I went on to the instructions for running the sample apps: https://github.com/Microsoft/WinObjC#building--running-the-samples

**Comment by DHowett-MSFT** [comment]
Oh, I see. This may be a documentation defect.

Since the first step of that is _"Clone the Repo"_, we need to add the Git-LFS instructions there too.
The quick fix before we get the documentation updated is to install Git LFS, run `git lfs install`, and then use `git lfs checkout` in the WinObjC folder.

**Comment by Ron2** [comment]
Thank you, that got me past that problem. I still can't compile the sample apps though.

In my opinion, the sample apps should be simple and shouldn't have a Git dependency at all. But if the sample apps stay the same, then the documentation in a couple places should be fixed.

For example, I'm pretty sure I started here several weeks ago:
https://developer.microsoft.com/en-us/windows/bridges/ios

And that tells me to go here, to the release page:
https://github.com/Microsoft/WinObjC/releases

But those zip files on the release page are not complete and have the same problem as if I had used the "Clone or Download" button, right?

Also, the documentation should state that Git and Git-LFS need to be installed on Windows because the sample apps require Git as part of the build process. I use OS X and run Windows 10 on Parallels, and my Git tools are on OS X.

FYI, I tried compiling on branch 'develop' but got compile errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _UIApplicationActivated referenced in function "protected: virtual void __cdecl HelloOpenGL::App::[Windows::UI::Xaml::IApplicationOverrides]::OnActivated(struct Windows::ApplicationModel::Activation::IActivatedEventArgs ^)" (?OnActivated@?QIApplicationOverrides@Xaml@UI@Windows@@App@HelloOpenGL@@M$AAAXP$AAUIActivatedEventArgs@Activation@ApplicationModel@4@@Z)	HelloOpenGL (HelloOpenGL\HelloOpenGL)	Y:\repositories\WinObjC\samples\HelloOpenGL\HelloOpenGL.vsimporter\HelloOpenGL-WinStore10\App.xaml.obj	1	
```

I figured that the `develop` branch is a work-in-progress and that the sample apps are currently broken there. So, I checked out the latest tagged release using `git checkout 0.2.170609`.

That leads to these compile errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		WARN [07/10/17 12:37:15:54] Could not determine assembly version: System.ComponentModel.WarningException: It looks like the branch being examined is a detached Head pointing to commit 'c5fb684'. Without a proper branch name GitVersion cannot determine the build version.
   at GitVersion.GitVersionFinder.EnsureHeadIsNotDetached(GitVersionContext context)
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
   at GitVersion.ExecuteCore.<>c__DisplayClass6_0.<ExecuteInternal>b__0(IRepository repo)
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action)
   at GitVersion.ExecuteCore.ExecuteInternal(String targetBranch, String commitId, GitPreparer gitPreparer, IBuildServer buildServer, Config overrideConfig)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication)	HelloOpenGL (HelloOpenGL\HelloOpenGL)		1	

Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot calculate version. Please make sure either PackageVersionOverride is set or GitVersionTask is listed as a nuget dependency for this project and that git.exe is part of the PATH environment variable.	HelloOpenGL (HelloOpenGL\HelloOpenGL)	Y:\repositories\WinObjC\common\winobjc.versioning.common.targets	34	
```

Making any branch name seems to get by that. `git checkout -b ron`

But I can't get by the next error:
```
Error		could not acquire lock file for module 'UIKit'	HelloOpenGL (HelloOpenGL\HelloOpenGL)	Y:\repositories\WinObjC\samples\HelloOpenGL\HelloOpenGL\HelloOpenGL.m	1	
```

I tried various suggestions about changing the Output directory and setting the `WINOBJC_SDK_ROOT` environment variable. I described my attempts in this comment on a StackOverflow question:
https://stackoverflow.com/questions/36985096/winobjc-could-not-acquire-lock-file-for-module-uikit#comment77016626_37010987

I'd really like to test the Obj-C debugging features. Our product's workflow currently requires compiling a DLL using clang on OS X and then including that DLL into a Visual Studio project, but there's basically no debugging capability of the Objective-C code. We would love to be able to use WinObjC!

So, any help you could provide in getting the sample apps compiling would be greatly appreciated!

**Comment by Ron2** [comment]
I moved my WinObjC git repo to a local-to-Windows drive, and I can compile and run HelloOpenGL now. I recommend that WinObjC users don't put the git repo on a shared drive.

**Comment by bbowman** [comment]
@Ron2 ,

We also would like to have our samples be as easy to get up and running with as possible. Did you check out https://github.com/Microsoft/WinObjC-samples ? These are our more polished samples that just consume the sdk packages directly while the ones in the main repo are a little convoluted in how they try to automatically pick up locally built packages where possible. Apologies for the confusion on the documentation! Sounds like you got up and running though?

**Comment by DHowett-MSFT** [comment]
@Ron2 Thanks for the followup. I'll file a bug to update our documentation in this regard and dupe this one over to it.

**Comment by Ron2** [comment]
I'm up and running now. Thank you.

**Comment by sriranjanr** [comment]
Hey @Ron2 
I am getting the same LNK2019 errors. How do I get past it. I installed VS2017 community yesterday and I was trying to get an app to run.

Error LNK1120 2 unresolved externals aurioTouch (aurioTouch\aurioTouch) C:\Users\user\Downloads\aurioTouch\Debug\aurioTouch\aurioTouch.exe 1
Error LNK2019 unresolved external symbol _UIApplicationActivated referenced in function "protected: virtual void __cdecl aurioTouch::App::[Windows::UI::Xaml::IApplicationOverrides]::OnActivated(struct Windows::ApplicationModel::Activation::IActivatedEventArgs ^)" (?OnActivated@?QIApplicationOverrides@Xaml@UI@Windows@@app@aurioTouch@@m$AAAXP$AAUIActivatedEventArgs@Activation@ApplicationModel@4@@z) aurioTouch (aurioTouch\aurioTouch) C:\Users\user\Downloads\aurioTouch\aurioTouch.vsimporter\aurioTouch-WinStore10\App.xaml.obj 1
Error LNK2019 unresolved external symbol _UIApplicationLaunched referenced in function "protected: virtual void __cdecl aurioTouch::App::[Windows::UI::Xaml::IApplicationOverrides]::OnLaunched(class Windows::ApplicationModel::Activation::LaunchActivatedEventArgs ^)" (?OnLaunched@?QIApplicationOverrides@Xaml@UI@Windows@@app@aurioTouch@@m$AAAXP$AAVLaunchActivatedEventArgs@Activation@ApplicationModel@4@@z) aurioTouch (aurioTouch\aurioTouch) C:\Users\user\Downloads\aurioTouch\aurioTouch.vsimporter\aurioTouch-WinStore10\App.xaml.obj 1

Please let me know how you overcame these errors..

**Comment by sriranjanr** [comment]
I followed Ron's suggestions, made a separate branch and put the files in another folder and was able to get the samples running...cheers

**Comment by rajsesh-msft** [comment]
closing the issue as it appears to be resolved.

**Comment by darkoverlordofdata** [comment]
Spent all day trying to get this to work - then I found this issue.  PLEASE FIX YOUR DOCUMENTATION.
