### ISSUE TITLE
Unresolved references (_glGenVertexArraysOES, _glBindVertexArrayOES, _glDeleteVertexArraysOES)

### ISSUE THREAD

**Issue by gisardo** [Microsoft/WinObjC#278]
Compilation errors
1>------ Rebuild All started: Project: blah (blah\blah), Configuration: Debug Win32 ------
1>  ConsumeRuntimeComponent.cpp
1>  ..\..\blah\main.m
1>  ..\..\blah\MCAppDelegate.m
1>  ..\..\blah\MCViewController.m
1>MCViewController_A91E0E43.obj : error LNK2019: unresolved external symbol _glGenVertexArraysOES referenced in function __i_MCViewController__setupGL
1>MCViewController_A91E0E43.obj : error LNK2019: unresolved external symbol _glBindVertexArrayOES referenced in function __i_MCViewController__setupGL
1>MCViewController_A91E0E43.obj : error LNK2019: unresolved external symbol _glDeleteVertexArraysOES referenced in function __i_MCViewController__tearDownGL
1>D:\winobjc\samples\glbase\Debug\blah\blah.exe : fatal error LNK1120: 3 unresolved externals

Repro Code: https://onedrive.live.com/redir?resid=733E3FFAB634EC2C!888177&authkey=!AKDMh0qq9zvaYXI&ithint=file%2czip

**Comment by Ramu-msft** [comment]
This support has been added. Please test this in the latest version of the SDK.
