### ISSUE TITLE
decoration of `id`

### ISSUE THREAD

**Issue by compnerd** [Microsoft/WinObjC#2789]
Currently `id` is decorated as `PAAUobjc_object@@` which `undname` is unable to symbolicate.  However, It is unclear whether this is accidental and the decorated name should be `PAUobjc_object@@`.  This properly is undecorated by `undname` as `struct objc_object *`.

**Comment by compnerd** [comment]
CC: @DHowett-MSFT @DHowett

**Comment by DHowett-MSFT** [comment]
@compnerd Thanks for reporting this. It looks like it should be `PAUobjc_object@@`.

What issue are you seeing because of this? I think `PAAUobjc_object@@` should still unmangle as `Uobjc_object*` (losing the `struct` typekind.)

**Comment by DHowett-MSFT** [comment]
(source: MicrosoftMangle in llvm-mirror [here](https://github.com/llvm-mirror/clang/blob/master/lib/AST/MicrosoftMangle.cpp#L1828) primes the mangled name with `PA`, then calls `mangleArtificalTagType`, which should emit `U` then the name. The code here looks right.)

**Comment by compnerd** [comment]
Yeah, it does result in `Uobjc_object *.  I shall fix clang (upstream) to generate this name properly.  However, doing so means that
  - previously compiled objects will need to be rebuilt
  - the exception handling needs to be adjusted for the correct mangling of `id` for the root type CatchableType entry

**Comment by compnerd** [comment]
SVN r3117617 will now mangle `id`, `Class`, and `@interface` appropriately in the C++ context.  I have more questions about the decorations, is this the best channel for them?

**Comment by compnerd** [comment]
clang now generates the right thing.
