### ISSUE TITLE
Can not build solution with NuGet packages

### ISSUE THREAD

**Issue by jboich** [Microsoft/WinObjC#2792]
Hi, all.

I am trying to use latest WinObjC packages from the nuget.org, but I get the following error when I try to build the solution:

> You project is not referencing the “UAP,Version=v10.0” framework. Add a reference to  “UAP,Version=v10.0” in the “frameworks” section of your project.json, and then re-run NuGet restore.

I changed _“uwp10.0.14393”_ to _“UAP,Version=v10.0”_  in “frameworks” section, tried NuGet restore, it said that nothing to restore and the error is still there => I can not build the solution.
Please see screenshot attached.

Could you help me to resolve this issue, please?

![nuget_fail](https://user-images.githubusercontent.com/22300615/29668293-8af0a6da-88d7-11e7-9f61-0a6940b497ef.PNG)

**Comment by ms-jihua** [comment]
Ah, @DHowett-MSFT also ran into this bug. This is unfortunately a VS2017 15.3 bug that we're following up with the VS team on. You can work around it by restoring and building from command line, ie:

& 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe' .\build\build.sln /nologo /nr:false /p:PackageVersionOverride= /p:platform="Any CPU" /p:configuration="Debug" /p:VisualStudioVersion="15.0"

Given the number of issues we're running into with update 3, though, we might unfortunately standardize on a recommendation to build with update 2 or earlier. :(

**Comment by chiefgreek** [comment]
Hi, could you provide more information as all I get is an error message 
MSBUILD : error MSB1009: Project File Does Not exist
Switch: .\build\build.sln

My program no longer works with the latest update and there is no standalone 15.2 version to roll back to
thanks

**Comment by ms-jihua** [comment]
Change the '.\build\build.sln' in my example to whatever the actual path to your copy of build.sln is, ie: C:\WinObjC\build\build.sln.

**Comment by DHowett-MSFT** [comment]
This is tracked as NuGet/Home#5815.

**Comment by rajsesh-msft** [comment]
This should now work with latest release.

**Comment by jboich** [comment]
Hi, @rajsesh 
The issue is relevant for Visual Studio 15.6.1.

Nuget packages restore fine if I run msbuild /t:restore from Command Prompt for Visual Studio 2017 and even if I restore them when select "Restore Nuget packages" fro solution in Visual Studio.

However when I try to build solution  in Visual Studio to deploy the app I get an error

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(186,5): error : Your project is not referencing the "UAP,Version=v10.0" framework. Add a reference to "UAP,Version=v10.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.`

I am able to build the project using `msbuild <name_of_solution>.sln` in command prompt, but how I deploy and then package app to submit to the store?

Is there an easy way to do this without visual studio?

**Comment by jboich** [comment]
I figured out what causes the issue:
It takes place if project has reference to the static C++ library, which has reference to the C# Windows Runtime Component.


This schema works for plain project converted from XCode:

```
{
  "dependencies": {
	"WinObjC.Frameworks": "*",
	"WinObjC.Language": "*"
  },
  "frameworks": {
	"uap10.0": {
  	"imports": "native"
	}
  },
  "runtimes": {
	"win10-arm": {},
	"win10-x86": {},
	"win10-arm-aot": {},
	"win10-x86-aot": {}
  }
}
```


But C# Windows Runtime Component asks for UAP v.10.0.14393 as target framework when restoring packages.

If I change schema to

```
{
  "dependencies": {
	"WinObjC.Frameworks": "*",
	"WinObjC.Language": "*"
  },
  "frameworks": {
	"uap10.0.14393": {
  	"imports": "native"
	}
  },
  "runtimes": {
	"win10-arm": {},
	"win10-x86": {},
	"win10-arm-aot": {},
	"win10-x86-aot": {}
  }
}
```

packages restore to C# components fine, but then I get the following error when trying to build & deploy project:

`Your project is not referencing the "UAP,Version=v10.0" framework. Add a reference to "UAP,Version=v10.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.`
