### ISSUE TITLE
objc-syntax-highlighting not working

### ISSUE THREAD

**Issue by vaualbus** [Microsoft/WinObjC#28]
the objc-syntax-highlighting is impossible to install in vs enterprise but apparently only install in vs 2015 professional.

**Comment by rasmusgude** [comment]
It seems that the vsix has InstallationTarget set to VS Pro. ver. 12.0.
I changed it to VS.Pro 14.0 and it installed perfectly into VS2015 Enterprise.

The vsix file is basically just a zip file, so do the following:
* Unzip the `objc-syntax-highlighting.vsix` with e.g. 7-zip.
* Open `extension.vsixmanifest` and change the line `<InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[12.0]" />` into `<InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[14.0]" />`
* zip the thing back into a vsix file. e.g. `objc-syntax-highlighting_hacked.vsix` and run it.

Note that the above is only a hack to get things working.

The right thing is to fix it in the source in `\msvc\language\ObjectiveC\`. 
If/when I have time I will do a proper fix.

**Comment by vaualbus** [comment]
Thanks, I open the project add the correct version and recompile it and install the packages.
But of course my package are not signed but for me that is not a problem.

**Comment by davelamb** [comment]
The vsix found in WinObjC/bin (not in the SDK zip) has been updated to work with 2015. Give it a try, and let us know if you have any more problems.

**Comment by vaualbus** [comment]
Now it's working. Thanks.

2015-08-07 21:14 GMT+02:00 Dave Lamb <notifications@github.com>:

**Comment by johndpope** [comment]
I noticed this wasn't entirely complete - I created some objective-c syntax file here 
this were for library specific methods - it's around 500kb
https://www.editplus.com/javacpp.html

**Comment by rasmusgude** [comment]
Is the language service supposed to build/run in VS2015? 
The solution is located at  `\msvc\language\ObjectiveC.sln`

It seems to build in VS2013 and if it is to support VS2015 then the .csproj file needs to be updated or a VS2015-specific solution must be created.

It's easy to get it working just by upgrading the project and adding the correct path to VS with cmd args: 
![vs2015_objclanguage_service_screenshot](https://cloud.githubusercontent.com/assets/1769351/9171585/23e7da7c-3f6d-11e5-87ae-0eb1c08cb793.png)

**Comment by asimonov-msft** [comment]
Both the pre-built SDK, as well as the git repository, should now contain the fixed VSIX file.
