### ISSUE TITLE
UIButtons from xib file does not react to touchesUp events etc.

### ISSUE THREAD

**Issue by mgoemmel** [Microsoft/WinObjC#281]
I'm really suprised that my MainView.xib will be completely read and the buttons defined there are displayed correctly on the view while loading the nib from within my app while rootviewcontrollers initWithNib. But the buttons do not react to touchesUp, touchesDownInside etc.

I've looked into the xib2nib application and this app seems to read this data and transfer it (writing it into a UIRuntimeEventConnection with tag UIEventMask). Also in the bridge seems to read this connections while reading out of the nib (IBOutlet), but no UIRuntimeEventConnection is called, and therefore no UIEventMask is filled.

Is this a known limitation which will be fixed later, or should this work, and I need to have a deeper look into this.

Thanks
Markus

**Comment by Ramu-msft** [comment]
We recently fixed some issues related to routing touch events. Please test this with latest version of the SDK

**Comment by mgoemmel** [comment]
Great work. Seems to work now. Thx!
