### ISSUE TITLE
How to install and run the winobjc generated app to iphone

### ISSUE THREAD

**Issue by sriranjanr** [Microsoft/WinObjC#2812]
Hello,

I could not find this anywhere in documentation. Where is the IOS compatible (*.ipa) file in the visual studio project folder? If that is present how shall I run the winobjc generated app on the iphone. Please let me know. I could not find the answer to this question in the faq and other beginner tutorials. (In android we can can just take the apk file and run it to install but I could not find a .ipa file here in winobjc solution). Please let me know..

**Comment by DHowett-MSFT** [comment]
Hi @sriranjanr!
Sorry for the confusion. WinObjC is intended to be used by developers to make _Windows_ applications (distributed via `.appx` packages) that run natively on Windows machines.
It's not a solution for developing iOS applications that will run on iPhones and iPads.

**Comment by DHowett-MSFT** [comment]
I'm closing this issue, but please feel free to reopen it if you've got additional concerns!
