### ISSUE TITLE
no known class method for selector 'dataWithJsonObject:options:error:'

### ISSUE THREAD

**Issue by cmini** [Microsoft/WinObjC#2815]
I've the fallowing error compiling with bridge 0.2.170610-dev-20171111235959:

![screen shot 2017-11-14 at 09 12 22](https://user-images.githubusercontent.com/7070516/32769575-c84af6f4-c91c-11e7-802b-17b84ca9e6a4.png)

**Comment by edvv** [comment]
JSON not Json

**Comment by cmini** [comment]
Ok Thanks! There’s a way to get this error with intellisync?

On 14 Nov 2017, at 12:37, Ed VanVliet <notifications@github.com<mailto:notifications@github.com>> wrote:


JSON not Json

**Comment by cmini** [comment]
intellisync suggest me this:
[cid:B0F157CD-7CA1-4699-A6FF-77F085B72889@consularea.local]

On 14 Nov 2017, at 14:37, christian mini <cmini@axterisco.it<mailto:cmini@axterisco.it>> wrote:

Ok Thanks! There’s a way to get this error with intellisync?

On 14 Nov 2017, at 12:37, Ed VanVliet <notifications@github.com<mailto:notifications@github.com>> wrote:


JSON not Json

**Comment by DHowett-MSFT** [comment]
I'm closing this out, since it looks like your issue has been addressed. Thanks, Ed, for helping out!
