### ISSUE TITLE
Cannot add Objective C to an Existing Project

### ISSUE THREAD

**Issue by konisx** [Microsoft/WinObjC#2818]
Environment is Windows 10 with Fall Creators update and Visual Studio 2017 v15.4.4, running inside a VMWare virtual machine.

We want to use our macOS application model, written in Obj-C. to UWP. The UI will be completely rewritten using XAML (hopefully). As a first step, I have build the model part under VS (by including the source files in one of the WinObjC samples).

Now I am trying to use then in a new UWP project.  I download and expand the 0.2 Preview zip of WinObjC. In VS I create a new C++ UWP application project. It builds and runs OK. 
Following the instructions from the wiki page I add the starboard-sdk.targets Build Customization I found inside the WinOjC->tools->msvc (by the way the path to the starboard-sdk.targets should be added to the wiki page, and the name updated from starboard.targets).
Now when I try to build the app again, I get:  

`Error	LNK1104	cannot open file 'winobjcrt.lib'	Zapp1	C:\Users\admin\Documents\Visual Studio 2017\Projects\Zapp1\Zapp1\LINK	1`

The problem is that winobjcrt.lib is not included in the Preview zip. What am I missing?

**Comment by bbowman** [comment]
Hi there @konisx,

It  looks like you are trying to use the `.zip` provided at https://github.com/Microsoft/WinObjC/releases? I would recommend against this approach unless you are planning to build WinObjC from source (perhaps to include some additional customization or code change). Instead I would recommend using the Nuget Packages shown in the dashboard of the readme (The Language and Frameworks packages).

Please see the getting started guide at https://github.com/Microsoft/WinObjC/blob/develop/README.md and the in depth page on packaging https://github.com/Microsoft/WinObjC/wiki/Packaging#how-do-i-consume-packages-locally for more information.

Apologies that the https://github.com/Microsoft/WinObjC/wiki/Adding-Objective-C-to-an-Existing-Project page is out of date. It should be changed to say that you just need to add references to the two nuget packages.

Does that help?

Let me know if there is more I can do to help / what documentation would make the process easier.

-Brian

**Comment by konisx** [comment]
Thank you for answering this Brian,

So I cloned the repo and run the two setup commands
`
.\init.ps1
.\.tools\nuget.exe restore .\build\build.sln
`

I skipped the steps for building WinObjC Frameworks and Tools, since I was not sure if I had to follow them too. 

Then I added the two nugget packages and the starboard-sdk.targets depedency to a new C++ UWP application and the project build ok. Now, when I add a simple Obj-C source file to it,  I get the following error for my variable definitions:

`Error (active)	E0020	identifier "NSString" is undefined	CppApp
`

so no luck here. 

Then  I tried building WinObjC. The command 

`.\.tools\nuget.exe restore .\build\build.sln.`

gives me the following errors:

`
MSBUILD : warning : WARN [02/05/18 17:20:31:36] Multiple branch configurations match the current branch branchName of 'master'. Using the first matching configuration, 'master'. Matching configurations include: 'master', '.*' [C:\kodev\WinObjC\build\Foundation\dll\Foundation.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1601,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin" directory. [C:\kodev\WinObjC\build\WinObjC.Frameworks.Core\WinObjC.Frameworks.Core.nuproj]`

with 7 more instances of the MSB4036 errors. After that, the Tools build ok for Win32, but the Frameworks give me a lot of errors like the one below:

`Error MSB4036 The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin" directory. [C:\kodev\WinObjC\build\WinObjC.Frameworks.UWP\WinObjC.Frameworks.UWP.nuproj]	NugetRestore C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets 1601`

I am using the latest Visual Studio 2017 Community 15.5.5.

Any ideas on how to proceed?

**Comment by bbowman** [comment]
Can you provide a zip/link to your project with the single ObjC file that isn’t working?

**Comment by konisx** [comment]
Here it is:
[https://www.escape.gr/download/temp/CppApp.zip](https://www.escape.gr/download/temp/CppApp.zip)

Thanks.

**Comment by bbowman** [comment]
Sorry for taking a bit on this but I finally got a chance to check out your zip file.

I was able to get it to build by doing a few things:
1. Removing starboard-sdk.targets and starboard-sdk.props from your project. These aren't needed as they are automatically provided by the language package.
2. Adding an import Foundation/Foundation.h to the file that was complainng about missing NSString
3. Also adding a dependency to the Frameworks package. It looks like there might be a bug in NSUrlCredential and Security layering violations between the two packages. Depending on both works around the issue.

As an aside, I recommend switching from a package.config to project.json or PackageReferences style of nuget dependency declaration. packages.config litters the project with lots of imports that don't up to date very well. See  https://github.com/Microsoft/WinObjC-Samples/blob/master/Apps/Calculator/Calculator.vsimporter/Calculator-WinStore10/project.json as an example.

Closing this. Please reopen if you are still having trouble.
