### ISSUE TITLE
What about Win64 support?

### ISSUE THREAD

**Issue by konisx** [Microsoft/WinObjC#2819]
The title says it all. Is there any news on win64 support for WinObjC? It would be nice to be able to build our UWP desktop app for Windows 64-bit.

**Comment by edvv** [comment]
@konisx You may want to check in with Andrew Pardoe at this blog:

https://blogs.msdn.microsoft.com/vcblog/tag/clang/

https://blogs.msdn.microsoft.com/vcblog/2016/06/03/clang-3-8-in-the-may-release-of-clang-with-microsoft-codegen/

... and also let him know that clang is at v5.0

**Comment by rajsesh** [comment]
See also #122 - other than the codegen, our code is not 64bit safe in some places.  This is not in our immediate plans.

**Comment by konisx** [comment]
@rajsesh 

Yes I have seen #122, but that was 2 years ago and I was hoping that it got some attention.

Thank you anyway.

**Comment by rosscpeterson** [comment]
Any word on supporting 64 bit as of late June 2019?

**Comment by edvv** [comment]
@rosscpeterson I think realistically such support would need a commitment from Microsoft of a dedicated engineering team and at least a year of labor.

**Comment by DHowett-MSFT** [comment]
It definitely would. Sorry. 😦
