### ISSUE TITLE
Objective-C message forwarding via forwardInvocation:, respondsToSelector:, methodSignatureForSelector: doesn't work

### ISSUE THREAD

**Issue by ehren** [Microsoft/WinObjC#282]
These methods aren't called.

**Comment by rajsesh-msft** [comment]
This is in our backlog and we will consider it in one of the future releases.

**Comment by LeoNatan** [comment]
@rajsesh-msft If it is not implemented yet, why is this issue closed?

**Comment by DHowett-MSFT** [comment]
This was fixed in #951, #903.

**Comment by ehren** [comment]
Haven't had the time to remove the #ifdefs disabling our app's use of message forwarding in a few cases - but I'll have to try this soon. Thanks folks!
