### ISSUE TITLE
WXCInkCanvas: Access violation reading location exception 

### ISSUE THREAD

**Issue by jboich** [Microsoft/WinObjC#2823]
When I try to add **WXCInkCanvas** on a view, I get Access violation reading location exception 

```
WXCInkCanvas*inkCanvas = [WXCInkCanvasmake];
UIView *testView = [[UIView alloc] init];
[testView addSubview: inkCanvas];
```

Same issue with **WXCInkToolbar**.

Please advice how to work with InkCanvas & InkToolbar in WinObjC project.

**Comment by MSFTFox** [comment]
Xaml controls cannot be treated simply as UIView objects. What you may be looking for is the _initWithFrame_ constructor for a UIView. I would recommend trying something like...

`WCXInkCanvas *inkCanvas = [WCXInkCanvas make];
CGRect frame = CGRectMake(0, 0, 500, 500);
UIView *inkCanvasView = [[UIView alloc] initWithFrame:frame xamlElement:inkCanvas];
[mainView addSubview: testView];`

Let me know how this works out for you. Thanks!

**Comment by jboich** [comment]
Hi, @MSFTFox  Thanks a million! It works!

Here is more detailed code snippet, which works for me:

```
        WXCInkCanvas *inkCanvas = [WXCInkCanvas make];
	CGRect frame = CGRectMake(0, 0, 500, 500);
	UIView *inkCanvasView = [[UIView alloc] initWithFrame:frame xamlElement:inkCanvas];
	[_mainView addSubview: inkCanvasView];

	WXCInkToolbar *inkToolbar = [WXCInkToolbar make];
	inkToolbar.targetInkCanvas = inkCanvas;
	inkToolbar.initialControls = WXCInkToolbarInitialControlsAll;
	UIView *inkToolbarView = [[UIView alloc] initWithFrame:frame xamlElement:inkToolbar];
	[_mainView addSubview: inkToolbarView];

	_inkPresenter = inkCanvas.inkPresenter;
	_inkPresenter.inputDeviceTypes = WUCCoreInputDeviceTypesMouse | WUCCoreInputDeviceTypesPen | WUCCoreInputDeviceTypesTouch;
```

**Comment by MSFTFox** [comment]
Wonderful! I'm glad to hear it!

I'll close this issue then.
