### ISSUE TITLE
WOCCatalog-WinStore10 does not build to ARM

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/WinObjC#283]
I installed the most recent (2015-12-03) SDK .zip and successfully built/installed the WOCCatalog Universal Windows (WinStore10) solution to the Desktop.

I then entered the Configuration Manager, added the ARM architecture as a viable target, and attempted to build the same.

Build error hit: 
1>------ Build started: Project: WOCCatalog (WOCCatalog\WOCCatalog), Configuration: Debug ARM ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "XamlCompositorCS". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>  ConsumeRuntimeComponent.cpp
**1>F:\winobjc_zip\msvc\ConsumeRuntimeComponent.cpp(34): fatal error C1083: Cannot open include file: 'client.h': No such file or directory**
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ===========

msvc\*ConsumeRuntimeComponent.cpp* shows the following **ifdef**:
#ifdef _M_ARM
**#include <client.h>**
int __cdecl main(::Platform::Array<::Platform::String^>^ args)
{
	EbrDefaultXamlMain();
}
#endif

Where are we expected to pull the **client.h** file from? I don't see the file at present in the Windows Kits headers or in the SDK.

**Comment by asimonov-msft** [comment]
@andrejo-msft ARM builds are currently not supported.

**Comment by LSUPERMAN735** [comment]
Is ARM build supported now @asimonov-msft
