### ISSUE TITLE
Can I build WinObjc UWP in Mobile Emulator 10586?

### ISSUE THREAD

**Issue by cloudmonkeypeng** [Microsoft/WinObjC#284]
HI, all

I can debug the WOCCatalog in Local Machine successful.

Now I want to debug it in the Mobile Emulator.
It can deploy successful, but get a error like this. 
Do I need to do something else?

![image](https://cloud.githubusercontent.com/assets/3436559/11682744/c8f7ddc6-9ea1-11e5-895e-23a829f2e3b5.png)

![image](https://cloud.githubusercontent.com/assets/3436559/11682788/09acf3f6-9ea2-11e5-8aa8-227a540c0ec5.png)

**Comment by cloudmonkeypeng** [comment]
The last sentence is

WOCCatalog.exe' (Win32): Loaded 'U:\programs\WINDOWSAPPS\Microsoft.VCLibs.140.00.Debug_14.0.23506.0_x86__8wekyb3d8bbwe\vcruntime140_app.dll'. Cannot find or open the PDB file.
'WOCCatalog.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
The thread 0x15ac has exited with code -1073741515 (0xc0000135).
The program '[5544] WOCCatalog.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.

**Comment by JamesGu0116** [comment]
me too
