### ISSUE TITLE
xib2nib -- lot of fixes available for merge from forked repo (but can't PR)

### ISSUE THREAD

**Issue by dkimitsa** [Microsoft/WinObjC#2840]
Hi, 
I've used this tool for RoboVM linux/windows project and had fixed lot of things in it. 
Sadly all this was happening in MacOS/Linux with corresponding tools used so I can't Pull Request changes as there is a risk that these will not be compatible with MS dev tools. 

Commits can be cherry picked from this repo https://github.com/dkimitsa/WinObjC/tree/xib2nib by anyone interested and who has MS Dev Tools at hand. 

Also I developed several tools that simplify work with nib files that makes bug fixing simpler. 
Here is a technical post with tutorial https://dkimitsa.github.io/2018/02/13/wl-tech-details-2-robovm/

**Comment by DHowett-MSFT** [comment]
@dkimitsa Thanks! I'm really glad somebody's working on xib2nib!

While I'd like to just cherry-pick your changes out, we need to have potential contributors sign a contributor license agreement. If you submit a pull request -- it doesn't have to be in a mergeable format! -- we can work together on getting the right changes upstreamed.

**Comment by DHowett-MSFT** [comment]
Again, I'd like to stress not to worry if the changes can't be upstreamed. We'll do what we must to get the changes in a consumeable format, but it has to start with a pull request.

**Comment by dkimitsa** [comment]
closing as https://github.com/Microsoft/WinObjC/pull/2852 was created as mentioned by @DHowett-MSFT
