### ISSUE TITLE
Can't install syntax highlighting

### ISSUE THREAD

**Issue by nrbrook** [Microsoft/WinObjC#2841]
Trying to double click `objc-syntax-highlighting` as instructed to do to install syntax highlighting gives the error
<img width="442" alt="screen shot 2018-02-13 at 11 33 37" src="https://user-images.githubusercontent.com/1141167/36147898-ea5033d6-10b1-11e8-8271-7f0fa942af1b.png">
[VSIXInstaller_65cc708c-4a5b-4d8c-a77f-ab718bb19c74.log](https://github.com/Microsoft/WinObjC/files/1719709/VSIXInstaller_65cc708c-4a5b-4d8c-a77f-ab718bb19c74.log)

Latest visual studio installed (15.5.6), all windows updates installed (Windows 10 1709), winobjc-tools at latest version on chocolatey (v0.2.171219)

**Comment by DHowett-MSFT** [comment]
It looks like the `objc-syntax-highlighting` VSIX you're installing is targeted to VS 2015. Installing winobjc-tools via chocolatey should automatically install the appropriate extension for your version of VS.

It does, however, look like we never changed the version number on the VS2017 VSIX, so it's hard to say precisely which package you were trying to install. Sorry!

**Comment by nrbrook** [comment]
So what can I do?

**Comment by DHowett-MSFT** [comment]
The correct VSIX should have been installed by the `winobjc-tools` chocolatey package. Can you check "Extensions and Updated" (Tools menu) for **Objective-C Language Service**? Here's mine:

![image](https://user-images.githubusercontent.com/14316954/36181259-f37165da-10d8-11e8-96b9-085d8d05f681.png)

**Comment by nrbrook** [comment]
Yes, that is installed. However, Objective-C code looks like this.
<img width="783" alt="screen shot 2018-02-14 at 11 40 45" src="https://user-images.githubusercontent.com/1141167/36202517-fedf21de-117b-11e8-9400-f69447a0ea13.png">

Is that full syntax highlighting? Also I'm not getting any code completion.

**Comment by DHowett-MSFT** [comment]
Alas, that's the level of syntax highlighting (and Intellisense: #40) Visual Studio 2017 supports for Objective-C. At best it can color strings, indent per your indenting settings, and smart-complete `""`, `()`, `{}`, and `[]`.

There's an alternative mode available if you _uninstall_ the Objective-C language service that will offer completion for words that are already present in the file you're editing. It's got a few other pitfalls, though, like not properly completing matched pairs and perhaps indenting.

**Comment by nrbrook** [comment]
Ok, thanks. I would use Xcode for most editing anyway, but I wasn’t sure if I was missing something.
