### ISSUE TITLE
Analytics package suggestions?

### ISSUE THREAD

**Issue by tmoh4cker** [Microsoft/WinObjC#2854]
I see that previously Google Analytics isn't compatible with Winobjc. Is this still the case ?
If so are there any recommended analytics that can be used for a bridged project preferably one that comes with already built online platform. Thanks

**Comment by DHowett-MSFT** [comment]
Hi @chiefgreek! Sorry for the delay. We don't have any suggested analytics packages at this time. The GA UWP SDK might be useful, but it would require a little bit of bridging to get it working from Objective-C.
