### ISSUE TITLE
UITableView delegate and dataSource properties can't be set via "nib outlets"

### ISSUE THREAD

**Issue by ehren** [Microsoft/WinObjC#286]
The delegate and dataSource outlets of a UITableView, though set in Interface Builder, are coming up nil at runtime.

It seems one must explicitly set the delegate and dataSource methods in code.

(issue edited -- previous comments a bit of a red herring)

**Comment by Ramu-msft** [comment]
We have recently enhanced our support for UITableView. Please test this in the latest version of the SDK.
