### ISSUE TITLE
This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by vincentlarkin** [Microsoft/WinObjC#2879]
Hello, while trying to install WinObjC Syntax Highlighting and Language support from the latest winobjc.zip in Releases, I reached a problem where I cannot install it.
![image](https://user-images.githubusercontent.com/17298607/41133527-14d0aee4-6a8d-11e8-9044-46498e0c94d7.png)

This is my install log.
`6/7/2018 7:51:34 PM - Microsoft VSIX Installer
6/7/2018 7:51:34 PM - -------------------------------------------
6/7/2018 7:51:34 PM - vsixinstaller.exe version:
6/7/2018 7:51:34 PM - 15.7.105+ga2c5d563c6
6/7/2018 7:51:34 PM - -------------------------------------------
6/7/2018 7:51:34 PM - Command line parameters:
6/7/2018 7:51:34 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Vincent\Downloads\winobjc\bin\objc-syntax-highlighting.vsix
6/7/2018 7:51:34 PM - -------------------------------------------
6/7/2018 7:51:34 PM - Microsoft VSIX Installer
6/7/2018 7:51:34 PM - -------------------------------------------
6/7/2018 7:51:34 PM - Initializing Install...
6/7/2018 7:51:34 PM - Extension Details...
6/7/2018 7:51:34 PM - 	Identifier         : VSIX..9c35fff1-f084-44c1-a38e-68c707163aa2
6/7/2018 7:51:34 PM - 	Name               : Objective-C Language Service
6/7/2018 7:51:34 PM - 	Author             : Microsoft
6/7/2018 7:51:34 PM - 	Version            : 1.5
6/7/2018 7:51:34 PM - 	Description        : This package contains Objective-C language service components such as syntax higlighting etc
6/7/2018 7:51:34 PM - 	Locale             : en-US
6/7/2018 7:51:34 PM - 	MoreInfoURL        : 
6/7/2018 7:51:34 PM - 	InstalledByMSI     : False
6/7/2018 7:51:34 PM - 	SupportedFrameworkVersionRange : [4.5,)
6/7/2018 7:51:34 PM - 
6/7/2018 7:51:34 PM - 	SignatureState     : Unsigned
6/7/2018 7:51:34 PM - 	Supported Products : 
6/7/2018 7:51:34 PM - 		Microsoft.VisualStudio.Community
6/7/2018 7:51:34 PM - 			Version : [12.0,15.0)
6/7/2018 7:51:34 PM - 		Microsoft.VisualStudio.Premium
6/7/2018 7:51:34 PM - 			Version : [12.0,15.0)
6/7/2018 7:51:34 PM - 		Microsoft.VisualStudio.Pro
6/7/2018 7:51:34 PM - 			Version : [12.0,15.0)
6/7/2018 7:51:34 PM - 		Microsoft.VisualStudio.Ultimate
6/7/2018 7:51:34 PM - 			Version : [12.0,15.0)
6/7/2018 7:51:34 PM - 		Microsoft.VisualStudio.Enterprise
6/7/2018 7:51:34 PM - 			Version : [12.0,15.0)
6/7/2018 7:51:34 PM - 
6/7/2018 7:51:34 PM - 	References         : 
6/7/2018 7:51:34 PM - Signature Details...
6/7/2018 7:51:34 PM - 	Extension is not signed.
6/7/2018 7:51:34 PM - 
6/7/2018 7:51:34 PM - Searching for applicable products...
6/7/2018 7:51:34 PM - Found installed product - Global Location
6/7/2018 7:51:34 PM - Found installed product - Visual Studio Community 2017
6/7/2018 7:51:34 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
`
I am using Visual Studio Community 2017 and Windows version 1709

**Comment by DHowett-MSFT** [comment]
Hi @VinLark! Thanks for reaching out.

It looks like you're using our Visual Studio 2015 extension. Anything you get from the Releases page is out-of-date, as we moved to publishing our updates via Chocolatey and NuGet.

We have a brief getting started section in the README, but it mainly consists of:

* `choco install winobjc-tools` (this installs the VS extension for 2017!)
* `vsimpoter ...path\to\xcodeproj`

**Comment by vincentlarkin** [comment]
Will doing that install Language and Syntax support for VS Community 2017? After I install that, I should be able to run and compile Obj-C? @DHowett-MSFT
