### ISSUE TITLE
Support for __auto_type

### ISSUE THREAD

**Issue by ad1Dima** [Microsoft/WinObjC#2880]
Please Support __auto_type. Its Obj-C analog for var in C# or auto in C++

**Comment by DHowett-MSFT** [comment]
This may have been fixed by #2869, as the source tree for Clang 6 includes mention of `__auto_type`.

**Comment by ad1Dima** [comment]
@DHowett-MSFT does it reach Release? Cause it doesn't work for me

**Comment by ad1Dima** [comment]
It looks like it work in prerelease version.
