### ISSUE TITLE
Conversion app with WKWebView

### ISSUE THREAD

**Issue by paskur** [Microsoft/WinObjC#2881]
I can't convert my app with WKWebView from WebKit framework, it works when i replace this with deprecated UIWebView. Is that mean I cannot convert WKWebView to UWP, because it is not supported yet?

**Comment by edvv** [comment]
@paskur This is a dup of this: https://github.com/Microsoft/WinObjC/issues/2376 which defines the answer.

**Comment by MSFTFox** [comment]
As @edvv mentioned, this is a duplicate of #2376
