### ISSUE TITLE
NSObject almost reimplements the runtime's refcounting

### ISSUE THREAD

**Issue by davidchisnall** [Microsoft/WinObjC#2885]
The refcount manipulations in NSObject are exposing some implementation details that may change.  The simplest way of supporting `-_ARCCompliantRetainRelease` is to just call `objc_retain`, `objc_release` and so on from the `-retain`, `-release` and so on methods.  Please call `object_getRetainCount_np` to implement `-retainCount`.  The current version will not work well with the runtime's weakref fast paths and will return an incorrect value if an object has had a weak reference taken, if used with the 1.9 or 2.0 branches of the runtime.

**Comment by DHowett-MSFT** [comment]
I have a patch for this, but was delayed in submitting it due to other incompatibilities with 1.9. It does simplify our code quite a bit!


________________________________

**Comment by DHowett** [comment]
(#2886)
