### ISSUE TITLE
libobjc2 build from the latest prerelease package is missing /SAFESEH and friends

### ISSUE THREAD

**Issue by Liastre** [Microsoft/WinObjC#2896]
I've tried to pass windows app certification with latest prerelease packages v0.2.180221 and failed with following issue while Windows security features test:
```Binary analyzer - Error Found: File C:\Progream Files\windowsapps\<package>\libobjc2.dll has failed the SafeSEHCheck check.```

Here the screen:
![image001](https://user-images.githubusercontent.com/4630725/48476849-2a813900-e811-11e8-988b-8cd6636afa22.jpg)

**Comment by edvv** [comment]
@Liastre Interesting. We're scheduled for another deploy cycle this Friday (on our own codebase) so it will be interesting to see if this crops up.

Did you see this?: https://social.msdn.microsoft.com/Forums/vstudio/en-US/e76a6db5-b2cf-46d0-866a-f934d1ec00c4/wack-pass-on-desktop-failure-on-security-for-online-submission?forum=wpsubmit

Are you certifying against a Release build?

Are you using a local certification or online?

If local did you click the "Update" link to update your certification rules (that may cause new conditions)?

Are you able to add the suggested linker flags (apparently it is only a linker issue and you don't need to recompile a dll)?

Did you try to submit to the MS Store anyways, and does it pass certification there?

Sincerely,

Ed

**Comment by Liastre** [comment]
Hey @edvv thanks for reply, yeah seems my issue lack of details, here we go:

> Are you certifying against a Release build?

I'm building only Release for certification

> Are you using a local certification or online?

In current case I'm using local one

> If local did you click the "Update" link to update your certification rules (that may cause new conditions)?

I do update certification rules before the actual certification

> Are you able to add the suggested linker flags (apparently it is only a linker issue and you don't need to recompile a dll)?

We are using ```/DYNAMICBASE /SAFESEH /NXCOMPAT /APPCONTAINER``` in additional linker options all the way :)

> Did you see this?: https://social.msdn.microsoft.com/Forums/vstudio/en-US/e76a6db5-b2cf-46d0-866a-f934d1ec00c4/wack-pass-on-desktop-failure-on-security-for-online-submission?forum=wpsubmit

I did not, well we have an issue during local cert, and linker flags are set

> Did you try to submit to the MS Store anyways, and does it pass certification there?

Not yet, but we gonna do soon for sure

Well just to be sure I'll update certification rules and redo, if there some changes did come during two weeks.

**Comment by Liastre** [comment]
@edvv here some additional info that might be useful for you, I've asked one of winobjc developer about this issue, the answer is:
> it should not impact your ability to publish the update to the store

So It must be safe to publish an update

**Comment by edvv** [comment]
@Liastre Thanks! Good to know. We're about to do an upload/publish, maybe tomorrow - this version is better than the iPad version (IMHO). I'll let you know how it goes. Sincerely, Ed

**Comment by Liastre** [comment]
We failed to submit so was forced to use latest release version instead if prerelease. I've made ticket to support, but still no answer, will update as soon as get answer.

**Comment by DHowett-MSFT** [comment]
This should be a quick fix, but I'll run it through our test gauntlet to be sure.

Sorry for the regression!

**Comment by edvv** [comment]
@Liastre Just a quick followup: Our apps still pass certification on the MS store using a 0.2 Preview release, so I assume this is truly a regression with a prerelease only per @DHowett-MSFT  comment. Sincerely, Ed

**Comment by Liastre** [comment]
Well I've made another build using latest release packages v0.2.180220 and succeed approved submission. There a lot of misunderstood with microsoft dashboard and packages approval. For example, when I've made first test flight, I've got "**passed** with notes", and surely this is not a big deal to fail such a check.
![image](https://user-images.githubusercontent.com/4630725/49078561-6b387380-f24f-11e8-88f0-e81a3a04ada8.png)

But when I submitted same package to the store... submission was rejected, not sent to the store with a mark "attention needed", what kind of logic is it, since package flight available to customers within group anyway, that's confusing.
![image 1](https://user-images.githubusercontent.com/4630725/49078896-4db7d980-f250-11e8-8c81-ce83f2f2c174.png)

@edvv sorry for disinformation I was to check it myself on the first place
 
P.S. still no any answer from support

**Comment by edvv** [comment]
@Liastre Thank you for trying out the prerelease and saving me the time to find this issue out. I'm awestruck at how well WinObjC works and a few rough edges is no problem. I think sticking with a 0.2 Preview is a good idea until the Clang 6/7 based Previews materialize - I'm looking forward to that!
