### ISSUE TITLE
[Foundation] AutoId template specialization conflates getters with id<...> return types

### ISSUE THREAD

**Issue by davelamb** [Microsoft/WinObjC#291]
Here's a fun one for Dustin.

```
@protocol SomeProtocol
@property NSObject* someProperty;
@end

@interface SomeInterface
@property id<OtherReturnProtocol> someProperty;
@end

...

@implementation SomeClass {
    idretaintype(SomeInterface) _myIvar;
}

- (void)someMethod {
    id<OtherReturnProtocol> myLocal = [_myIvar someProperty]; // <-- ERROR: AutoId specializes on the first type it sees, implicitly casting _myIvar to id<SomeProtocol>
}

@end
```

This is especially bad if you have any calls of the form [[_myIvar someProperty] someExpectedMethod:someAutoIdVariableThatWontBeCasted], since it'll only give you a warning of a missing method, but crash hard at runtime due to the mismatched signature, and retain/release semantics of AutoId when used as a parameter (pops the wrong EBP, destroying your stack trace).

Unfortunately I don't know if there's a way to fix this on the WinObjC side, it looks like a clang frontend problem. Likely doesn't include the protocol for template expansion.

**Comment by DHowett** [comment]
This is actually crazy.
The destination of a message should be triggering `AutoId<T>::operator id()`, as it's the only implicit conversion operator. Is the issue that untyped-id doesn't respond to `someProperty`, and the resulting dispatch is ill-formed?

Regardless, if `-someProperty` returns anything coercible to `id`, Clang should be resolving `someExpectedMethod:` for type detection later via global name lookup.

Color me baffled!

**Comment by davelamb** [comment]
Oh god, it's even worse, it's resolving the dispatch preferentially to the first property getter it sees. In the case of the example, the error for myLocal is: 

    cannot initialize a variable of type 'id<OtherReturnProtocol>' with an rvalue of type 'NSObject*'

I just tried something a little less specific:
```
@interface SomeInterface 
@property NSArray* someProperty;
@end

@interface SomeOtherInterface 
@property UIView* someProperty;
@end

...

idretaintype(SomeOtherInterface) soi;
auto expectingView = [soi someProperty];
[expectingView setFrame:nil]; /// WARNING: 'NSArray*' May not respond to '-setFrame'!
```

It's not limited to just protocols and ids. It looks like it's going through some id hoops to cast however it can to the first thing that responds to a given selector. Keep in mind if I exchange `auto` for `UIView*` it works as expected, but if used inline, this could cause problems... did cause problems.

**Comment by DHowett** [comment]
Interesting! Clang throws warnings for instances where `auto` deduces `id`, though. That doesnt absolve us of running afoul of it anyway!

If I get some time this week I'll see if I can't come up with something workable. 

Can you try `(SomeOtherInterface*)soi` in the interim? That should exercise `AutoId<T>::operator Any()` instead of the implicit `operator id`.

As an aside, I think Clang's deduction of id responder types in general is something to be afraid of!

**Comment by rajsesh-msft** [comment]
@interface SomeInterface 
@property NSArray* someProperty;
@end

@interface SomeOtherInterface 
@property UIView* someProperty;
@end

This will be trouble even in reference platform when you try to do something inline.  And Dustin, go enjoy the rest of your vacation.

**Comment by davelamb** [comment]
Ok so clang is just insane. Calling messages on `id` just uses the first one (might not be deterministic) it sees, in any class, anywhere. Not normally a problem, I guess, except when you collide on return type, like `dataSource`, `delegate`, etc. As a fix, I might suggest blowing away the implicit cast to `id` in favour of something like:

```
    operator TObj*() /*const*/ {
        return (TObj*)_val;
    }
```
I'm not a template wizard, so you might need some more junk for pointerless operations, or whatever crazy domain limiters you C++ guys like. :) 

The funny thing is the `const` keyword. Looks like for message calls, clang does a cast to `TObj*` through the template, looks at the class `const` and goes "I guess that's not good enough" and casts again to `id`. With `const` gone, clang seems to behave. I think it's probably a buggable offense. 

And yes, this can wait till after you vacation is done. :)

**Comment by rajsesh-msft** [comment]
now available.
