### ISSUE TITLE
How to create a new objectivec project

### ISSUE THREAD

**Issue by darkoverlordofdata** [Microsoft/WinObjC#2916]
On your website - [https://developer.microsoft.com/en-us/windows/bridges/ios](https://developer.microsoft.com/en-us/windows/bridges/ios) it says:
"Import your Xcode project into Visual Studio by using the vsimporter tool included with the SDK, or start writing your next great Universal Windows Platform app in Visual Studio using Objective-C."

So the first part works pretty well - importing an xcode project. But for the 2nd part of that - how do I start writing a new application? There are no templates for ObjC in the new project dialog box.

**Comment by DHowett-MSFT** [comment]
Hi @darkoverlordofdata,
Thanks for trying this out. We're currently missing our project templates, as the original WinObjC originally focused on importing Xcode projects. I'm going to mark this as a task for our backlog.

Right now, the easiest way to get a "new" project would be to convert a mostly empty Xcode project. Sorry about that!

**Comment by darkoverlordofdata** [comment]
I understand - I'm concerned because Microsoft has a history of releasing unfinished projects that go nowhere due to lack of interest due to the project being unfinished. IronPython come to mind.

**Comment by darkoverlordofdata** [comment]
Actually, this solution is not working. When I copy one of the samples to it's own folder, and open it in VS, I get the one or more solutions did not open correctly error, and it is unable to compile.

**Comment by darkoverlordofdata** [comment]
You have an FAQ: Adding Objective C to an Existing Project, but it does not work. So I found an issue on that which is 1 year old - Cannot add Objective C to an Existing Project #2818, and still not fixed. This is starting to make GNUstep look good.

**Comment by darkoverlordofdata** [comment]
Ok, I finally got a project working by itself without being inside the WinObjC folder structure. I downloaded the code for this tutorial, and ran vsimporter, and it works! [https://www.raywenderlich.com/3002-beginning-opengl-es-2-0-with-glkit-part-1](https://www.raywenderlich.com/3002-beginning-opengl-es-2-0-with-glkit-part-1url)

**Comment by DHowett-MSFT** [comment]
Thanks for following up! I'll make sure we update the documentation to reflect some of this.

I'll file a followup task for the template support.
