### ISSUE TITLE
Keybord events not responding

### ISSUE THREAD

**Issue by darkoverlordofdata** [Microsoft/WinObjC#2918]
I'm creating a simple shmup game, and I am unable to trap keyboard events. Touch events work fine - I can trap mouse down for shoot, but I prefer using the spacebar, there is less repetitive injury :)

I have a main class GameViewController that subclasses UIViewController. I check [self becomeFirstResponder], an the return value is YES. I've set a keyCommands property to return the active commands (this methodology - https://nshipster.com/uikeycommand/)

However, canBecomeFirstResponder is never called, nor is the keyCommands property. So I tried to use
[self addKeyCommand:cmd] to add the keys, and I get this warning: addKeyCommand:' is deprecated: method not yet implemented [-Wdeprecated-declarations]

I understand deprecated. But I've never seen a 'not yet implemented' warning before...I assume that means the code isn't finished?
So, is the keyboard event plumbing working? Or am I just hitting my head against the wall??

**Comment by edvv** [comment]
@darkoverlordofdata Cocoa Touch has limited keyboard processing, hence a UIKit look alike will be similarly deficient. You will need to install XAML Event processing for your purpose. One of the WinObjC sample apps shows how to do that. Sincerely, Ed

**Comment by darkoverlordofdata** [comment]
Thanks - that makes sense.
