### ISSUE TITLE
-[NSValue pointerValue] should be of type void* instead of const void*

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#292]
In the reference implementation `-pointerValue` is defined to return `void *`:

```objc
@property (nullable, readonly) void *pointerValue;
```

Whereas WinObjC defines it at `const void *`, which can lead to possible compile errors:

https://github.com/Microsoft/WinObjC/blob/346c325bc5ccc195735dda7bc6e95323b6aa208b/include/Foundation/NSValue.h#L50

Note that the `-valueWithPointer:` method correctly uses a `const void *` parameter like in the reference implementation.

**Comment by jofre-ms** [comment]
The fix is in.

**Comment by rajsesh-msft** [comment]
Now available.
