### ISSUE TITLE
cannot open source file "D:/source/xxxx.tlh" Myapp "d:\source\common\utility\xxxx.h"

### ISSUE THREAD

**Issue by swa6589** [Microsoft/WinObjC#293]
Hi,

I have Imported the Xcode using vsimporter. After that I facing this issue
"cannot open source file "D:/source/xxxx.tlh" Myapp 
xxxx indicates the filename.

Any help or suggestions are appreciated

**Comment by SaeedAkhter-MSFT** [comment]
@swa6589 Thanks for reporting this issue, unfortunately we have not been able to reproduce this type of error.  Can you provide us steps that would help us reproduce this error?  If you can push example code that reproduces the problem to a GitHub project that would be great.  If you need to share confidential source code with Microsoft, then I can walk you through the paperwork offline.

**Comment by swa6589** [comment]
Thanks SaeedAkhter. Sure I will share  a document.

**Comment by Harisam26** [comment]
hi .. i tried building the woc catalog and gives me the same error as :cannot open: ".../wocCatalog/Debug/GLKit.tlh"

**Comment by baptcoll** [comment]
Hi there !

I have actually the same issue.
I already red a post about "Foundation.h" which is unrecognized and someone said "It should not cause compilation problems" (here https://github.com/Microsoft/WinObjC/issues/185).
But when I build my project under Visual Studio, I obtain this : 
"cannot open source file "F:/bdbuzz/bdbuzz-ios/bdBuzz.vsimporter/bdBuzz-WinStore10/Debug/Foundation.tlh ""
I have the same problem with "sqlite3.tlh" and "MTSerie.tlh" .

**Comment by antoine-haas** [comment]
Hi @swa6589, @Harisam26 and @baptcoll. Is any of you guys still hitting this issue with the lates release of the SDK? We still haven't been able to repro this on our side.

**Comment by antoine-haas** [comment]
We are still not able to repro this issue. Please provide additional information and reopen.
