### ISSUE TITLE
Does Windows Bridge supports Metal Framework?

### ISSUE THREAD

**Issue by Artgrey** [Microsoft/WinObjC#2936]
Hello I want to convert my iOS application to Windows, but it has a lot of Metal in it. Does your tool supports it? Also, I tried to find App Analysis tool to check if my app is compatible, but couldn't find? The link https://developer.microsoft.com/en-us/windows/bridges/ios/app-analyzer-tool brings me back to Windows Bridge page.

**Comment by DHowett-MSFT** [comment]
Unfortunately, we don't support Metal. I'm sorry!
I'll take up the concern about the analyzer link. Thanks for bringing that up. :smile:
