### ISSUE TITLE
Does Windows Bridge supports OpenGL?

### ISSUE THREAD

**Issue by Artgrey** [Microsoft/WinObjC#2937]
Hello again. Thanks a lot for your previous answer. I have another question about OpenGL support? Does Windows Bridge supports it? If not, does Windows have any solutions on how to make a workaround of this frameworks, or it is better just to make the same app on Windows from zero? Thanks.

**Comment by DHowett-MSFT** [comment]
The bridge has support for OpenGL and OpenGLES using the `ANGLE` software package. This is a supported scenario.
