### ISSUE TITLE
error MSB6006: "clang.exe" exited with code -1073741819

### ISSUE THREAD

**Issue by gary17** [Microsoft/WinObjC#294]
Compiling a somewhat larger Objective-C++ source file (3770 lines, 91935 bytes) results in the following error:

    1>------ Build started: Project: SomeApp, Configuration: Debug Win32 ------
    1>  ..\..\iOS\SomeApp\SomeLargerSourceFile.mm
    1>D:\winobjc\msvc\sbclang.targets(159,5): error MSB6006: "clang.exe" exited with code -1073741819.

The problem does not appear to be induced by any particular source code error, but rather seems to occur in post-processing (post-compilation), as inserting an invalid statement at the very last line of the source file in question:  1.) does produce a content-specific compilation error, e.g. "unknown type name", 2.) does not report any other (previous) compilation errors.

Multiple, unrelated source files with different content can produce exactly the same error.

Environment: Visual Studio Community 2015, version 14.0.24720.00 Update 1, Windows 10 64-bit.

**Comment by gary17** [comment]
FYI: moving the entire source tree across NTFS and ReFS file systems, with and without junction points, does NOT seem to correct the problem.

**Comment by gary17** [comment]
FYI: the problem persists in WinObjC version 0.1.0.160107 (January 7, 2016).

    1>D:\winobjc\msvc\sbclang.targets(161,5): error MSB6006: "clang.exe" exited with code -1073741819.

**Comment by cridlig** [comment]
I am blocked by the same issue with the latest Jan 14 version.

**Comment by zekituran** [comment]
the problem is solved by removing the line 
ObjectiveCModules="%(ClangCompile.ObjectiveCModules)"
in sbclang.targets.

**Comment by gary17** [comment]
In my case, removing `ObjectiveCModules` from `sbclang.targets` does NOT make any difference, both in case of **0.1.0.160128 (January 14, 2016)** as well as **0.1.0.160114 (January 28, 2016)**. (Appreciate the suggestion, though.)

**Comment by PooyaZv** [comment]
Gary, can we work together to further look into this issue? My email address is PoZandev@microsoft.com

**Comment by anandjp** [comment]
Hello Pooya, 
I am hitting same issue. I have sent you an email regarding this. I am using 0.1 release dated Feb 18th.

**Comment by gary17** [comment]
Pooya, I replied to your e-mail (PoZandev@microsoft.com) on 02/27, re-sending my reply.

**Comment by harcalion** [comment]
I am having the same error with WinObjC 0.1 Preview (March 4, 2016). The code file where clang exits is also big (around 1000 LOC).

**Comment by PooyaZv** [comment]
@harcalion: Can we communicate through email: PoZandev@microsoft.com

**Comment by Tessjay** [comment]
On Feb 27, 2016 3:30 AM, "Pooya Zandevakili" <notifications@github.com>
wrote:
>
> Gary, can we work together to further look into this issue? My email
address is PoZandev@microsoft.com

**Comment by Tessjay** [comment]
Hi Microsoft/WinObjC,

I'd like to add you to my professional network on LinkedIn.

- Tessa

Confirm that you know Tessa: https://www.linkedin.com/e/v2?e=0-im025dpz-qk&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=-lMYDvvn&invitationId=6117173225131696129








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im025dpz-qk&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHeN2K0coveUwAAAVOSQwcEpOEzHRyYqo4I1VWqQNOeSEaLo_qOU-Qf80L2I_3zJcDHHRRyxxjpw0ZxqgNK00ruSmS_YbF73EhYRz26Oi408uRJ66A46gMhKFzQV_I4evA9EBk5zBFcSAKx60Jx9BEBoJsIQFzZAWabUffXnIfQaT8qKohsNvJfWKqAZ01Bybav&eid=0-im025dpz-qk


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im025dpz-qk&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Tessjay** [comment]
Tessa Mcgillis would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-1k7g89-im6hsahb-i8&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=-lMYDvvn&invitationID=6117173225131696129

View Tessa Mcgillis&#39;s profile: https://www.linkedin.com/e/v2?e=-1k7g89-im6hsahb-i8&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=-lMYDvvn&invitationID=6117173225131696129





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-1k7g89-im6hsahb-i8&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-1k7g89-im6hsahb-i8&loid=AQFikHoD6AFrDQAAAVOqbxIJAa8a4x0xmgqOo8plBzq1TamOGuEzM9W89hOOJbPpjLD9UA721Nx40rmLjqKwiy99OJjRJ-wl4pg_fN4JS59Sy1zy-HE1tiR_880nlrQ2En5RmNfF5_kXCsB2e8eANIFp6J9aJ3D3Lf2IWbe78AHypwT3o459bKZ5s5y2hKlB6PQ4

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-1k7g89-im6hsahb-i8&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by harcalion** [comment]
After working with Pooya on the issue, in my case the problem with clang was caused by rethrows of (mainly) IOExceptions. Handling the exceptions in a different way resolved the issue. Thanks!

**Comment by PooyaZv** [comment]
Thank you Alvar for working with us on this issue. To elaborate, the issue is caused by @throw; statements in catch blocks. We will be working on a fix soon. In the meanwhile, one possible workaround is to replace @throw; with a @throw statement with an argument.

**Comment by gary17** [comment]
I can confirm that as of version **0.1 Preview (June 9, 2016)** the issue has been **resolved**.

As a side note, I keep running into the [fatal error C1001](https://github.com/Microsoft/WinObjC/issues/296) on the same source file. Not sure if this is a separate problem or a related-to (secondary) failure.

**Comment by PooyaZv** [comment]
Please see comments on #296.

**Comment by Tessjay** [comment]
You are invited to a Polaris Office Group!




	
    	
        	
            	
                	
                    	
                        	
                            	
                                
                            
                        
                    
                
            
            
            	
                                	
                    
                    
                    	
                        	
                            	You are invited to a Group!
                            
                            
                            	
                                Tessa McGillis<tessamcgillis18@gmail.com> has invited you to a Polaris Office group.                               
                                Join this group with Tessa McGillis to share the document and start a chat!
                                You can download Polaris Office on your PC and mobile devices to enjoy
                                more convenient features.
                                
                            
                            
                            	
                                	
                                	
                                    	
                                        	
                                            Participate
                                            
                                        
                                    
                                    
                                
                            
                            
                            
                            	
                                Thank you.
                                Your Polaris Office Team.
                                
                            
                        
                      
                                      
                
                
            
            
                
                    Polaris Office provides convenient and user-friendly platforms that users can enjoy anytime, anywhere.
                
            	
                	 Android · iOS · Fire OS · Windows · Mac · Web
                
                
                	
                    	
Please click here if you don’t want to receive messages from our mailing lists.

                        Have questions? We’re here to help! Contact us anytime!
                        Copyright ⓒ 2016 POLARIS OFFICE Corp.

**Comment by Tessjay** [comment]
Thanks!

Sent from my Huawei Mobile

**Comment by gary17** [comment]
I can confirm that as of version **0.1 Preview (June 9, 2016)** the issue has been **resolved**.
