### ISSUE TITLE
hhh

### ISSUE THREAD

**Issue by Angelwx22** [Microsoft/WinObjC#2944]

**Comment by DHowett** [comment]
You and all your friends can stop spamming this repo now.

**Comment by crazii** [comment]
> You and all your friends can stop spamming this repo now.

Does github have blacklist? Just block him and I don't want to receive spam notifications either.

**Comment by DHowett** [comment]
Not that I could find. I’ve reported them, and it may help if you do the same. Sorry about the spam.
