### ISSUE TITLE
fatal error C1001: An internal error has occurred in the compiler

### ISSUE THREAD

**Issue by gary17** [Microsoft/WinObjC#296]
Compiling a somewhat larger Objective-C++ source file (2935 lines, 71520 bytes) results in the following error:

    1>------ Build started: Project: SomeApp, Configuration: Debug Win32 ------
    1>  ..\..\..\SomeApp\SomeLargerSourceFile.mm
    1>E:\SomeApp\SomeLargerSourceFile.mm(1669): fatal error C1001: An internal error has occurred in the compiler.

There is nothing interesting at the specified location, just an opening brace of a generic C-style function body (**out**side of @implementation).

Multiple, unrelated source files with different content can produce exactly the same error. On another occasion, it is a line right before an opening brace of an Objective-C method body (**in**side of @implementation).

Environment: Visual Studio Community 2015, version 14.0.24720.00 Update 1, Windows 10 64-bit.

**Comment by gary17** [comment]
FYI: moving the entire source tree across NTFS and ReFS file systems, with and without junction points, does NOT seem to correct the problem.

**Comment by gary17** [comment]
FYI: the problem persists in WinObjC version 0.1.0.160107 (January 7, 2016).

**Comment by PooyaZv** [comment]
Gary, can we work together to further look into this issue? My email address is PoZandev@microsoft.com

**Comment by kodekuru** [comment]
I don't know this is related or not, the method test1 in the code below also crashes compiler with C1001. But test2 does not crash.

```
#import <UIKit/UIKit.h>
#import "AppDelegate.h"

int var1 = 0;
int var2 = 0;

@interface Crash : NSObject
-(BOOL)test1;
-(BOOL)test2;
@end

@implementation Crash
-(BOOL)test1
{
	@synchronized(self) {
		return var1 <= 0 && var2 >= 0;
	};
}
-(BOOL)test2
{
	@synchronized(self) {
    BOOL var3 = var1 <= 0 && var2 >= 0;
		return var3;
	};
}
@end

int main(int argc, char * argv[]) {  
	@autoreleasepool {      
	    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
	}
}
```

**Comment by PooyaZv** [comment]
@kodekuru This is a different issue related to how (variable) scoping and debug information interact. Can you try with -gline-tables-only? (see https://github.com/Microsoft/WinObjC/issues/354)

**Comment by gary17** [comment]
I can confirm that as of version **0.1 Preview (June 9, 2016)** the issue **remains** (not resolved).

The _-gline-tables-only_ suggestion was not effective.

Interestingly, I am pretty sure that before 0.1 Preview (June 9, 2016) I was getting this error with multiple source files, but afterwards I am seeing it only on one (1), large source file. _Bumped up some kind of a hard-limit, somewhere?_

A (somewhat) potentially related issue [here](https://github.com/Microsoft/WinObjC/issues/294).

**Comment by PooyaZv** [comment]
In the source code we have received from customers, so far all the crashes are have been because of exception handling code rather than the size of source files. I wonder if you're running into the same issue. These are specifically the below 3 issues: 
- https://github.com/Microsoft/WinObjC/issues/354 (finally blocks cause a crash) (fixed)
- https://github.com/Microsoft/WinObjC/issues/556 (@throw; causing a crash). (**fix was rolled out just this week i.e. Jun 9th, which might be why you are seeing fewer errors**.)
- https://github.com/Microsoft/WinObjC/issues/405, which we are working on. Can you try the workarounds in the issue page to see if it solves the crashes?

Thank you very much again for working with us on this issue.

**Comment by gary17** [comment]
I can confirm that as of version **0.2.160927 (September 27, 2016)** the issue has been **resolved**.

The compiler now emits an appropriate `error : __block variable '<name>' cannot be captured in a captured statement`.
