### ISSUE TITLE
/CLI:* options

### ISSUE THREAD

**Issue by sirinath** [Microsoft/WinObjC#30]
Add options to generate mixed, pure and / or safe CIL/CLI/CLR/.net code.

**Comment by sirinath** [comment]
@jmsaunders-ms can you look at adding the above option?

**Comment by jmsaunders-ms** [comment]
Adding support to generate CIL would likely be a fairly significant amount of work.

Can I ask why you want this functionality?

**Comment by sirinath** [comment]
There are so many good open source libraries out there. It would be nice to use them in the .net also and vise versa.

**Comment by sirinath** [comment]
If you do this at the level of LLVM IR and MSIL/CIL here about can convert from one to the other the possibilities are endless. If you add Java ByteCode to the mix then it will be even more awesome as it will make more libraries available to whatever language you use.

Also see:
http://elementscompiler.com/elements/silver/faq.aspx
http://elementscompiler.com/elements/silver/
https://github.com/remobjects/CodeGen4
https://github.com/remobjects/sugar
https://github.com/remobjects/Marzipan
http://robovm.com/

**Comment by keluo-ms** [comment]
While it would certainly be awesome, we don't currently have plans to support managed code with our project. We appreciate the feedback though and we may certainly revisit this topic in the future :smile:
