### ISSUE TITLE
A issue about  NSString  dataUsingEncoding

### ISSUE THREAD

**Issue by cloudmonkeypeng** [Microsoft/WinObjC#300]
NSString* str =@"Hello,world";
	NSData* data = [str dataUsingEncoding:NSUTF8StringEncoding];
	NSLog(@"%s",data.bytes);

	NSString* newstr = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
	NSLog(@"%@",newstr);

My test code is like this. In my opinion, NSLog should print equal string.
But "data.bytes" will print random tail every time.
![image](https://cloud.githubusercontent.com/assets/3436559/12195307/2ad8f2d6-b631-11e5-9504-4ca0ee1192ee.png)

I will submit additional tests under test/NSString.m.
Do you have any suggestions?

**Comment by cloudmonkeypeng** [comment]
NSString* testString = @"HelloWorld";

    NSUInteger len = testString.length;

    NSUInteger numBytes = 0;

    [testString getBytes:NULL maxLength:0x7FFFFFF usedLength:&numBytes 

        encoding:NSUTF8StringEncoding options:0 

        range:NSMakeRange(0, len) remainingRange:NULL];

    char* pData = (char*)malloc(numBytes);

    [testString getBytes:pData maxLength:numBytes usedLength:NULL 

        encoding:NSUTF8StringEncoding options:0

        range:NSMakeRange(0, len) remainingRange:NULL];

    NSData* ret = [NSData dataWithBytesNoCopy:pDatalength:numBytes freeWhenDone:TRUE];

    NSLog(@"%s",ret.bytes);

I also try the code which is get from "NSString dataUsingEncoding" on Xcode.

It also output string with random tail string every time.



I'm glad to discuss this question with you. :)

**Comment by rajsesh-msft** [comment]
This is actually by design.  dataUsingEncoding does not include the null termination in the string, which is required when you do %s for formatting.  So NSLog is printing all characters until you encounter the null termination character.
