### ISSUE TITLE
get request return response = null

### ISSUE THREAD

**Issue by karson711** [Microsoft/WinObjC#305]
get request return response = null,it might be which problem and how to slove this problem？thanks

**Comment by rajsesh-msft** [comment]
Could you please clarify the exact api you are using, or the code snippet?

**Comment by rajsesh-msft** [comment]
Hello, can you please provide mode details?

**Comment by rajsesh-msft** [comment]
Hello, thanks for reporting this issue.  Unfortunately, there is not enough information to proceed on this issue, please reactivate with details you might have.
