### ISSUE TITLE
Foundation NSTimeZone knownTimeZoneNames can't call twice.

### ISSUE THREAD

**Issue by cloudmonkeypeng** [Microsoft/WinObjC#306]
-(void) buttonPressed: (UIButton*)button
    {
    NSArray *zoneArrs = [NSTimeZone knownTimeZoneNames];
    }

The function can be called first time. And it will throw exception when it is called second time.

![image](https://cloud.githubusercontent.com/assets/3436559/12289907/56436c26-ba19-11e5-8cb0-0bebe627673a.png)

**Comment by rajsesh-msft** [comment]
This has been fixed a while ago.
