### ISSUE TITLE
NSLog() not working since January 7 2016 release

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#307]
Using NSLog() will no longer print to the Visual Studio "Output" window. This works fine with the previous release from December 22, 2015.

**Comment by Ramu-msft** [comment]
We recently made a change to suppress debug logging only to print logs in Debug build. The logging was suppressed in Release build for performance reasons. This change affected NSLog as well, sorry about that. We will fix this and enable debug logging for Release build as well. As a workaround, you can use the Debug build SDK to get the debug logs from NSLog.

**Comment by Ramu-msft** [comment]
This bug has been fixed and will be available in the next release.
