### ISSUE TITLE
UIWebView don`t want to be transparent

### ISSUE THREAD

**Issue by skyplat** [Microsoft/WinObjC#308]

**Comment by Ramu-msft** [comment]
Could you please provide more information on what you are trying to do? Are you trying to make the UIWebView control completely transparent? Can you provide a sample code?

**Comment by skyplat** [comment]
i converted my old iOS app to WinObjC with IBUIWebView <object class="IBUIWebView" id="591599957">
						<reference key="NSNextResponder" ref="191373211"/>
						<int key="NSvFlags">274</int>
						<string key="NSFrame">{{0, 266}, {320, 194}}</string>
						<reference key="NSSuperview" ref="191373211"/>
						<reference key="NSWindow"/>
						<reference key="IBUIBackgroundColor" ref="908262849"/>
						<bool key="IBUIOpaque">NO</bool>
						<bool key="IBUIMultipleTouchEnabled">YES</bool>
						<string key="targetRuntimeIdentifier">IBCocoaTouchFramework</string>
						<bool key="IBUIScalesPageToFit">YES</bool>
						<int key="IBUIDataDetectorTypes">1</int>
						<bool key="IBUIDetectsPhoneNumbers">YES</bool>
					</object>

**Comment by skyplat** [comment]
I converted my iOS app to WinObjC but IBUIWebView don`t want to be transparent.  
- (void)loadExamDetails
{
   
    
    NSString *sImagePath1 = [kRESOURCE_PATH stringByAppendingPathComponent:m_examData.m_sImg1];
	m_imageView1.image = [UIImage imageWithContentsOfFile:sImagePath1];
	
	NSString *sImagePath2 = [kRESOURCE_PATH stringByAppendingPathComponent:m_examData.m_sImg2];
	m_imageView2.image = [UIImage imageWithContentsOfFile:sImagePath2];
    
    [m_webView setOpaque:YES]; 
	m_webView.backgroundColor = [UIColor lightGrayColor];
	m_webView.userInteractionEnabled = NO;
    
    [self loadWebView];
}

- (void)loadWebView
{
    NSString *sHtml = [NSString stringWithFormat:@"<html><head><meta name='viewport' content='width=device-width-20; initial-scale=1.0; maximum-scale=1.0;'></head><body style='padding-left: 15px; padding-right: 15px; padding-bottom: 15px;'><font face=\"Helvetica\" color=\"Black\">%@</font></body></html>", m_examData.m_sText];
	[m_webView loadHTMLString:sHtml baseURL:nil];	
}

**Comment by Ramu-msft** [comment]
Currently we do not support the backgroundColor property in UIWebView. This support has been added and will be available in our next release.

**Comment by Ramu-msft** [comment]
&nbsp; &nbsp; Fix available in 0.1 Preview (January 28, 2016)

**Comment by skyplat** [comment]
thank you will try

**Comment by skyplat** [comment]
it`s work!
