### ISSUE TITLE
Missing file: 'sqlite3.h' file not found

### ISSUE THREAD

**Issue by RaulDev** [Microsoft/WinObjC#309]
I'm trying to execute simple and small project that include 4 forms, imported from iOS Xcode and then i got some problems. This is one of them:
· The import of "sqlite3.h" (#import <sqlite3.h>) can't find the file.

**Comment by jaredhms** [comment]
You'll need to install sqlite's "VSIX package for Universal App Platform development using Visual Studio 2015" from http://sqlite.org/download.html

**Comment by RaulDev** [comment]
Installed, and also NuGet package of sqlite3 but doesn't work.

**Comment by jaredhms** [comment]
As far as I know, you only need to install the UAP .vsix: http://sqlite.org/2016/sqlite-uap-3100100.vsix.  Perhaps the Nuget package references are getting in the way?

**Comment by RaulDev** [comment]
"sqlite3" library got from Nuget Package, It doesn't work.

**Comment by jaredhms** [comment]
None of the sqlite Nuget packages that I found work.  Have you tried removing all of your Nuget package references and instead relying solely on the UAP .vsix from sqlite.org?  I am unable to repro your issue when using only sqlite's UAP .vsix: http://sqlite.org/2016/sqlite-uap-3100100.vsix

**Comment by RaulDev** [comment]
I only have "sqlite3" Nuget pacakge active in my solution but don't run anyway. 
Also have both packages you said installed and the error won't disappear.

**Comment by rhaning** [comment]
Hi Raul, can you confirm that the SQLite extension is installed successfully by opening the Visual Studio menu: Tools -> Extension & Updates.
If it is successfully installed, it should be listed under "Installed -> SDKs" as "SQLite for Universal App Platform"

**Comment by RaulDev** [comment]
![sqlite3](https://cloud.githubusercontent.com/assets/16718281/12545782/752617b2-c345-11e5-8773-90f00488c4f2.PNG)

**Comment by jaredhms** [comment]
Thanks, Raul.  I just realized that you also need to add the Sqlite UAP extension as a reference to your project.  In Solution Explorer, expand your project's node, right click on 'References', then hit 'Add Reference...'.  Click 'Extensions' under 'Universal Windows', check the box next to 'Sqlite for Universal App Platform', then hit 'OK'.

**Comment by RaulDev** [comment]
Nice! thx mate :+1:
