### ISSUE TITLE
Ensure Clang Conformance

### ISSUE THREAD

**Issue by sirinath** [Microsoft/WinObjC#31]
Please ensure conformance to Clang C/C++/Objective C

**Comment by jmsaunders-ms** [comment]
We use clang, so our clang conformance is pretty good. :)

Do you have any specific concerns? Perhaps I misunderstood the issue here.

**Comment by sirinath** [comment]
Can you use normal C/C++ code valid in Clang?

**Comment by jmsaunders-ms** [comment]
Of course! :)

**Comment by sirinath** [comment]
OK Great
