### ISSUE TITLE
NSNumber -stringValue and -getValue: crash with shorts

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#310]
NSNumber’s -stringValue and -getValue: functions are missing cases for "short" (`s`) and "unsigned short" (`S`) types, leading to the following cases to crash:

```obj-c
	NSNumber *num = [NSNumber numberWithShort:1];
	[num stringValue]; // CRASH
```

```obj-c
	NSNumber *num = [NSNumber numberWithUnsignedShort:1];
	[num stringValue]; // CRASH
```

```objc
	NSNumber *num = [NSNumber numberWithShort:1];
	short shortNum;
	[num getValue:&shortNum]; // CRASH
```

```objc
	NSNumber *num = [NSNumber numberWithUnsignedShort:1];
	unsigned short shortNum;
	[num getValue:&shortNum]; // CRASH
```

**Comment by rajsesh-msft** [comment]
This was addressed by pull request 318, which is merged now.

**Comment by rajsesh-msft** [comment]
This was addressed by pull request 318, which is merged now.&nbsp; Will be in the next release.

**Comment by rajsesh-msft** [comment]
This was addressed by pull request 318, which is merged now.&nbsp; Will be in the next release.
