### ISSUE TITLE
Password for the VM's is unknown

### ISSUE THREAD

**Issue by cicorias** [Microsoft/WinObjC#311]
The VM's on the page [here](https://dev.windows.com/en-us/bridges/ios#vms) require a username/password. Although the password isn't listed anywhere.

**Comment by antoine-haas** [comment]
The VM's password should appear as a password hint when you try to login without a password. Let me know if that doesn't work.

**Comment by cicorias** [comment]
it says "see site"

**Comment by lux2911** [comment]
VMWARE image for MAC - same thing ...

**Comment by antoine-haas** [comment]
That's an error, thanks for catching it. The password for the VMs is P2ssw0rd.
