### ISSUE TITLE
UWP Header File Usage Question

### ISSUE THREAD

**Issue by wjk** [Microsoft/WinObjC#313]
I was planning on taking the WinObjC code, forking it, and building an IDE around it to make it easier to use. However, not all the required code is open-source. Namely, the compiler is still completely proprietary (which is very annoying, by the way), but it can easily be bundled and invoked as-is. However, the [UWP APIs bridged to Objective-C](https://github.com/Microsoft/WinObjC/tree/master/include/Platform/Universal%20Windows/UWP) raise other issues. These files state that they are `Generated from winmd2objc`, but I cannot find the source for this tool in the repo. Although the headers are reused easily enough, the real problem is the `.m` files that provide the implementations. I can't find these files, or libraries containing the code in these files, anywhere. Does clang look for these class-names and provide implementations automatically? How would I go about adding new UWP APIs that are not provided in the Microsoft code?

**Comment by wjk** [comment]
Actually, I found [the DLL containing these APIs](https://github.com/Microsoft/WinObjC/blob/master/deps/prebuilt/Universal%20Windows/x86/ObjCUWP.dll). Is there any reason that the sources that make up the code in this DLL have not been released? It would make interopability between this tool and other APIs (both Microsoft-supplied and third-party Windows Runtime components) far easier.

**Comment by s5msft** [comment]
@wjk the tool/process to generate the ObjC projections will be open sourced -- it's currently being re-architected to make it easier to use and result in smaller code. no firm ETA yet unfortunately... we'll update as soon as we have one

**Comment by rajsesh-msft** [comment]
This will be addressed through #2686.

**Comment by rajsesh-msft** [comment]
Addressed as part of #2686
