### ISSUE TITLE
instantiateViewControllerWithIdentifier return null

### ISSUE THREAD

**Issue by muellerfa** [Microsoft/WinObjC#314]
Hi,

I have developed a simple prototype to get started with windows bridge for iOS. The iOS-App shows a table view. If I tap on an entry, an runtime problem appears on the following code.

    LabelDetailViewController* labelDetailVC = [self.storyboard instantiateViewControllerWithIdentifier:@"LabelDetail"];
    [self.navigationController pushViewController:labelDetailVC animated:YES];

self.storyboard is not null, but the labelDetailVC, so I get the exception.

What I am doing wrong? Or is there an workaround? The code works on native iOS.

**Comment by Ramu-msft** [comment]
The xib2nib tool used to process the xib files, especially storyboard, is still under development. As a workaround, you can create the table view programmatically then it should work with our SDK.

**Comment by Ramu-msft** [comment]
We have made some enhancements to xib2nib tool recently. If you still see this problem, please provide the xib file for further analysis.
