### ISSUE TITLE
WinObjC indows VM vsimporter not supported

### ISSUE THREAD

**Issue by JHT1958** [Microsoft/WinObjC#320]
![vkcew](https://cloud.githubusercontent.com/assets/5244281/12420269/edb099d4-bebb-11e5-8c03-b22665a01714.jpg)
When I run vsimporter on my Windows VM 10 command line (cmd.exe) I have a message telling me the following  (VM is Parallels Desktop)

    This application cannot be executed on your PC

**Comment by antoine-haas** [comment]
Did you download the Parrallels VM from our [website] (https://dev.windows.com/en-us/bridges/ios), or are you using a personal VM?

**Comment by JHT1958** [comment]
Since I install the updated Visual Studio it works! So closed topic. Thank you
