### ISSUE TITLE
error : redefinition of 'BOOLEAN' as different kind of symbol

### ISSUE THREAD

**Issue by jpalbert** [Microsoft/WinObjC#322]
Just retried importing an iOS project, and i got this error:

![image](https://cloud.githubusercontent.com/assets/1823046/12423533/40500e26-becc-11e5-9edf-5f0340c21a28.png)

I never had this before (last time I had problems with some code involving UDP and SSL, didn't dig any further)

PS: I'm using the latest fast ring build, 11099.rs1_release.160109-1156

**Comment by SaeedAkhter-MSFT** [comment]
@jpalbert Thanks for reporting this issue.  This appears to be an error that we have not seen before.  Can you provide steps that would help us reproduce this error?  If you can push example code that reproduces the problem to a GitHub project, then that is a simple solution. If you need to share confidential source code with Microsoft, then please email me at s-a-e-e-d-a@m-i-c-r-o-s-o-f-t.com (remove all hyphens) and I can walk you through the paperwork offline.

**Comment by Ramu-msft** [comment]
Closing this issue due to no response.
