### ISSUE TITLE
MapKit.h

### ISSUE THREAD

**Issue by JHT1958** [Microsoft/WinObjC#323]
After conversion error on import #import <MapKit / MapKit.h>
thank you beforehand

Erreur		'MapKit/MapKit.h' file not found

**Comment by nicholasgerard-msft** [comment]
MapKit is not in our immediate roadmap (see [our roadmap](https://github.com/Microsoft/WinObjC/wiki/Roadmap) in the wiki), but may be included in future releases. For the time being, we suggest using XAML's MapControl in your app.

**Comment by JHT1958** [comment]
Merci c'est vraiment dommage car beaucoup d'application utilise cela 
Thank you it's a shame because many application uses this
