### ISSUE TITLE
Support for MobileCoreServices.framework

### ISSUE THREAD

**Issue by FastGeert** [Microsoft/WinObjC#324]
Hi I have read in another issue that MobileCoreServices.framework is in the backlog, but I cannot find it in the Roadmap wiki page.

**Comment by nicholasgerard-msft** [comment]
MobileCoreServices is in our backlog and we're working on it for a future release, but it's not in our immediate roadmap. [The roadmap](https://github.com/Microsoft/WinObjC/wiki/Roadmap) page on our wiki outlines our goals for the next month or two.

**Comment by rhaning** [comment]
MobileCoreServices is now supported.
