### ISSUE TITLE
LNK1181 cannot open input file 'AVFoundation.lib'

### ISSUE THREAD

**Issue by RaulDev** [Microsoft/WinObjC#325]
Starting project debug and error appeared "LNK1181 cannot open input file 'AVFoundation.lib'".
Then i'll try to comment all lines that requires 'AVFoundation.lib' but it doesn't care.
This error appears again and again.

**Comment by Harisam26** [comment]
HI.. did u get it fixed?
if so pls tell me how..

**Comment by RaulDev** [comment]
You must link the library directory of "WinObjC" projecto to your solution.
Right click on your project --> Properties --> Linker --> General --> Additional Directories

**Comment by RaulDev** [comment]
![1](https://cloud.githubusercontent.com/assets/16718281/12910582/1f35206e-cf0c-11e5-9c5a-88b3824120e2.png)

**Comment by RaulDev** [comment]
![image](https://cloud.githubusercontent.com/assets/16718281/12910584/2409ae20-cf0c-11e5-9b44-54590cac8ce7.png)
