### ISSUE TITLE
cannot open "GLKit.lib" in the latest preview

### ISSUE THREAD

**Issue by Harisam26** [Microsoft/WinObjC#329]
tried all the methods available but sample /woccatalog fails... with fatal error LNK1811: cannot input file 'GLKit.lib'

**Comment by Harisam26** [comment]
the same continues in build 0.1.0.160107

**Comment by Harisam26** [comment]
release of  22nd december file is works perfectly..

**Comment by brianker** [comment]
I have been unable to duplicate this with both the pre-built SDK (version 0.1.0.160114), and by building the SDK myself from the GitHub source.  Are you doing anything other than unzipping/building the SDK and then immediately building WOCCatalog?  do you have older SDK versions, or did you install overtop of an older SDK?

**Comment by Harisam26** [comment]
@brianker : thanks fr ur concern..  :) 

i am doing as per instructions given in wiki and github....  i tried installing atop on older ones too....but i get the same linker errors... for all files i get some linker error..  i unistalled/ removed everything completely and then tried older version (release of 22nd december and it works perfectly alight... )  if i did anything wrong  pls explain.. i am new to this... so pls..  :)

**Comment by brianker** [comment]
Would it be possible for us to get a small example solution that replicates the issue?  If your project was imported from XCode, could we get the original XCode project as well?

Thanks.

**Comment by Ramu-msft** [comment]
We can't reproduce this problem. If this still happens, please provide repro steps for further analysis.
