### ISSUE TITLE
LNK1181	cannot open input file 'FBSDKCoreKit.lib'

### ISSUE THREAD

**Issue by Leen15** [Microsoft/WinObjC#333]
I'm trying to convert our ios app that use Facebook login but at build time i receive this error:

```
  LNK1181   cannot open input file 'FBSDKCoreKit.lib'
```

I don't know how visual studio should import external sdk files, I don't see in VS Solution any folder related to FBSDKCoreKit, but in original Xcode project I've two folders:

```
  FBSDKCoreKit.framework
  FBSDKLoginKit.framework
```

When i converted the project with vsimporter i didn't received any error:

```
  C:\Users\luca\Documents\IOS Bridge\####-app-b2c-ios-develop>"C:\Users\luca\Documents\IOS Bridge\winobjc\bin\vsimporter.exe"
  [W] Ignoring "####Tests" target with unsupported product type "com.apple.product-type.bundle.unit-test".
  Generated C:\Users\luca\Documents\IOS Bridge\####-app-b2c-ios-develop\####.vsimporter\####-Headers-WinStore10\***-Headers.vcxitems
  Generated C:\Users\luca\Documents\IOS Bridge\####-app-b2c-ios-develop\####.vsimporter\####-WinStore10\####.vcxproj
  Generated C:\Users\luca\Documents\IOS Bridge\####-app-b2c-ios-develop\####-WinStore10.sln
```

Thanks.

**Comment by rhaning** [comment]
Source is required for SDK's as well so we can compile it into UWP app. The Facebook SDK for iOS is open source and we are actively working to support it. Stay tuned.

**Comment by weswmsft** [comment]
I do not believe this is still an issue.

**Comment by Leen15** [comment]
@weswmsft is now fb sdk supported?
