### ISSUE TITLE
Latest release broke preprocessor definitions in ObjC header files

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#336]
Preprocessor definitions from clang page no longer are defined properly in header files (only in .m's).  This of course broke my entire project.

**Comment by SaeedAkhter-MSFT** [comment]
@mlfarrell, thank you for reporting this issue.  Would it be possible to copy/paste the errors from your build log?

**Comment by asimonov-msft** [comment]
@mlfarrell Which preprocessor definitions are no longer defined for you? It would help immensely if you could provide us with steps to reproduce the errors you are seeing.

**Comment by mlfarrell** [comment]
I had meant my own custom macros that I defined in the property pages myself such as "DEBUG".  Sorry but I haven't had a chance to open this project in awhile.

**Comment by asimonov-msft** [comment]
@mlfarrell I'm still not sure what broke. Can you reproduce the issue with one of our sample projects?

**Comment by asimonov-msft** [comment]
Closing the issue for now. Please reopen it when you get the chance to post steps to reproduce the problem.
