### ISSUE TITLE
Is microsoft really serious about this?

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#337]
I'm sorry but, I expected a little bit more after waiting many months before trying my project again.  There's still tons of missing features and I can't even run my project after commenting out half of my functionality, since crucial core functionality is still missing (aka UIPopover).  I'm getting close to abandoning my Win10 port of this app since this project was announced LAST YEAR and we're well into 2016 without a decent ObjC SDK.  Honestly, MS should either abandon this effort and stop leading us along, or put some serious effort into it.

**Comment by s5msft** [comment]
@mlfarrell Loud and clear. The good news is we're doing just that -- scaling up the dev team.

**Comment by mlfarrell** [comment]
Glad to hear, thanks for the update!

**Comment by ArnOmsft** [comment]
@mlfarrell, just curious if you had the chance to try the latest release of the bridge.
Thanks.

**Comment by mlfarrell** [comment]
I abandoned ObjC a very long time ago.  I now use a C++ engine and my own UI framework.  I'm no longer interested in anything w.r.t WinOBJC.  thanks.

**Comment by ArnOmsft** [comment]
Thanks for the feedback, and sorry that the bridge did not work well for your app.
