### ISSUE TITLE
ANNOUNCEMENT: New Objective-C runtime in latest release

### ISSUE THREAD

**Issue by nicholasgerard-msft** [Microsoft/WinObjC#338]
In this week's release of the bridge we've officially made the move to the GNUstep Objective-C 2.0 runtime. This provides a number of benefits over our previous runtime, including:

- Access to objc_msgSend
- Proxy object forwarding
- Full access to Objective-C runtime functions

Please let us know about any issues you find in the new runtime here on Github.

**Comment by colbyrussell** [comment]
Need to close #116.
