### ISSUE TITLE
(0.1 Jan 28) App not rendering correctly

### ISSUE THREAD

**Issue by DavidBurela** [Microsoft/WinObjC#339]
The latest 0.1 Jan 28 release has a regression with the rendering. https://github.com/Microsoft/WinObjC/releases/tag/0.1.0.160128

With the Canabalt source code, the splash screen will load, but then stays on a blank screen https://github.com/ericjohnson/canabalt-ios

It still works with the previous 0.1 Jan 14 release https://github.com/Microsoft/WinObjC/releases/tag/0.1.0.160114

**Comment by DHowett** [comment]
Interesting! It looks like everything's running (and even responding to touches), it's just not rendering to the screen. I saw the "headphones recommended" splash briefly on a single launch.

I'm not certain this is related to the libobjc2 switchover; it looks like the issue persists with legacy method dispatch as well :(

**Comment by DavidBurela** [comment]
So the issue is there in Jan 28 with legacy method dispatch, but it works with Jan 14.

Not sure what else changed between those 2 releases.

**Comment by s5msft** [comment]
Yeah, this regression is unrelated to the runtime changes. @bdrlamb-ms is investigating

**Comment by Ramu-msft** [comment]
Please test this with the latest version of the SDK
