### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by Gutem** [Microsoft/WinObjC#34]
iOS developer already made some investment in hardware/software would be nice if have a native OSX support.

**Comment by xnth97** [comment]
it doesn't make sense since we don't have Visual Studio on OS X

**Comment by Gutem** [comment]
Actually, we have!
https://code.visualstudio.com/Download

**Comment by xnth97** [comment]
that's visual studio code, the atom-based text editor, not visual studio, the whole IDE
