### ISSUE TITLE
NSIndexSet not working due to missing -[NSMutableIndexSet addIndexesInRange:] implementation

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#341]
`-[NSMutableIndexSet addIndexesInRange:]` is [unimplemented](https://github.com/Microsoft/WinObjC/blob/977365eaeab49cc37ba448fb481b189743858169/Frameworks/UnifiedFoundation/Foundation/NSIndexSet.mm#L342), leaving the following methods relying on it broken:

* -[NSIndexSet indexSetWithIndex:]
* -[NSIndexSet indexSetWithIndexesInRange:]
* -[NSMutableIndexSet addIndex:]
* -[NSMutableIndexSet addIndexes:]

This in turn e.g. affects various NSArray and KVO/KVC methods.

**Comment by cre8ivepark** [comment]
Had same issue. in my case, I was using NSIndexSet to do batch update in UICollectionView, with following code:
    [self.collectionView performBatchUpdates:^{
        [self.collectionView reloadSections:[NSIndexSet indexSetWithIndex:0]];
    } completion:nil];

**Comment by jofre-ms** [comment]
The fix for this is coming soon.

**Comment by rajsesh-msft** [comment]
This is available as of last release.
