### ISSUE TITLE
UIImageView - clipsToBounds = NO property does not work 

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#342]
clipsToBounds property in UIImageView does not work when I run my project in VS. 
Once clipstToBounds is set to NO, the image should be displayed without cropping, even though it is bigger than bounding box. When I run same project in Xcode, it shows correct behavior.

Visual Studio:
![2016-02-03 11_48_08-mademoiselle pori](https://cloud.githubusercontent.com/assets/13754172/12796921/3b7b5468-ca76-11e5-8129-7ef98c8253e9.png)

Xcode:
<img width="880" alt="screen shot 2016-02-03 at 1 00 23 pm" src="https://cloud.githubusercontent.com/assets/13754172/12796915/2e9fa23a-ca76-11e5-8866-75bb87322a20.png">

**Comment by oren-MSFT** [comment]
should be fixed. Let me know if you do not see it fixed as then I might have miss diagnosed the issue.
