### ISSUE TITLE
UIImagePNGRepresentation generates wrong color

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#349]
I am saving current screen as PNG image using UIImagePNGRepresentation.
Not sure if it is UIImagePNGRepresentation issue or UIGraphicsGetImageFromCurrentImageContext() issue. This is the code that I am using for saving current screen:

```
    UIWindow *keyWindow = [[UIApplication sharedApplication] keyWindow];
    UIGraphicsBeginImageContext(keyWindow.bounds.size);
    [self.view.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage* viewImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    NSData *imageData = UIImagePNGRepresentation(viewImage);
```
Comparison between the original image & saved image:
![pori_islandwood_color0](https://cloud.githubusercontent.com/assets/13754172/12996131/d05a518a-d0e1-11e5-8534-7e41858503d0.jpg)

Just in case, this is the code I am using to save the image to local document folder.

    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
    dateFormatter.dateFormat = @"yyyy-MM-dd HH-mm-ss";
    [dateFormatter setTimeZone:[NSTimeZone systemTimeZone]];

    NSString* now = [dateFormatter stringFromDate:[NSDate date]];

    // Save Image File to Documents folder
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *documentsDirectory = [paths objectAtIndex:0];
    NSString *strPath = [documentsDirectory stringByAppendingPathComponent:[NSString stringWithFormat:@"Pori %@.png",now]];
    [imageData writeToFile:strPath atomically:YES];

Thank you!

**Comment by davelamb** [comment]
Looks like we're mistaking a BGR backing for an RGB backing. I'll have to write some swizzling code to swap that back around. Thanks!

**Comment by Ramu-msft** [comment]
This issue has been fixed. Please test this in the latest version of the SDK.
