### ISSUE TITLE
UITableView - group header colors are not applied

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#351]
in grouped style UITableView, you can override the group header's color with this code. The color overriding is not working and shows default gray color. Including Xcode and VS screen shots:
- (void)tableView:(UITableView *)tableView willDisplayHeaderView:(UIView *)view forSection:(NSInteger)section
  {
  // Background color
  view.tintColor = [UIColor orangeColor];
  
  // Text Color
  UITableViewHeaderFooterView *header = (UITableViewHeaderFooterView *)view;
  [header.textLabel setTextColor:[UIColor whiteColor]];
  }

Thanks!
![typeinsight_tableview0](https://cloud.githubusercontent.com/assets/13754172/13021769/c321dbcc-d191-11e5-853f-a5e31d4e2142.jpg)

**Comment by ArnOmsft** [comment]
Thank you for the feedback. Unfortunately the concept of tintColor does not exist on Windows so we're not planning to support this.
