### ISSUE TITLE
arc4random not cryptographically secure

### ISSUE THREAD

**Issue by MikeWeller** [Microsoft/WinObjC#36]
People rely on arc4random being a cryptographically secure source of random numbers.

The implementation in CFMisc.mm is just calling rand() a few times which is pretty terrible.

It should instead use a real cryptographic PRNG algorithm and be seeded from some kind of reliable source of random data. Either implement it properly or at least call an equivalent windows API for some secure random numbers.

**Comment by lvh** [comment]
This should emphatically be `CryptoGenRandom` calls.
