### ISSUE TITLE
UIFont familyNames not implemented

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#361]
I am using UIFont's familyNames method to retrieve list of the fonts available on Windows. Without this, there is no way to check if specific fonts are available or not on user's system. 

Code: 

    NSArray *familyNames = [[NSArray alloc] initWithArray:[UIFont familyNames]];
    fontNames = [[NSMutableArray alloc] initWithCapacity:0];
    _objects = [familyNames sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
    
    for (int i = 0; i < [familyNames count]; i++)
    {
        NSArray *fontNamesData = [UIFont fontNamesForFamilyName:[familyNames objectAtIndex:i]];
        [fontNames addObject:fontNamesData];
    }

Error: 
C:\WinObjC\Frameworks\UIKit\UIFont.mm(147)\(null)!56BBA2A2: (caller: 00AD144D) LogHr(26) tid(33b8) 80004001 Not implemented
    Msg:[Stubbed function called!] [+[UIFont familyNames](E_NOTIMPL)]

**Comment by Ramu-msft** [comment]
This issue has been fixed and it is available in the latest SDK.
