### ISSUE TITLE
KVO issue with nested properties using derived sub-keys

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#362]
The attached sample project [WinObjC-KVOBug.zip](https://github.com/Microsoft/WinObjC/files/142938/WinObjC-KVOBug.zip) shows incorrect behavior when observing a nested property with derived sub-keys.

Steps to reproduce:

1. Run the sample app, which starts observing the nested property.
2. Press **Update Name Property** to update the nested property of the selected "child0"<br>
=> console output: `Object did change: [Child0] name:...`
3. Press **Select Child 1** to select a different child<br>
=> console output `Object did change: [Child1] name:...`<br>
(as the KVO event for the observed property is fired when the selected object is changed)
4. Press **Update Name Property** to update the nested property of the selected "child1". <br>
=> console output `Object did change: [Child1] name:...` is *not* triggered

The sample app will behave correctly when run on the reference platform.

**Comment by DHowett-MSFT** [comment]
Ah, it looks like we're not re-registering subkey observers for derived properties. Good find!

**Comment by rajsesh-msft** [comment]
This is now fixed.
