### ISSUE TITLE
Problems compiling build.sln

### ISSUE THREAD

**Issue by mgoemmel** [Microsoft/WinObjC#370]
I'm trying to build from source code, but creating a x86/Release with build.sln gives me tons of this:

W:\bgmwin\winobjc-master\msvc\sbclang.targets(274,5): error MSB4062: The "Clang" task could not be loaded from the assembly W:\bgmwin\winobjc-master\msvc\ClangCompileTask.dll. Could not load file or assembly 'file:///W:\bgmwin\winobjc-master\msvc\ClangCompileTask.dll' or one of its dependencies. The module was expected to contain an assembly manifest. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Is Git LFS mandatory to compile? In the past I downloaded the source.zip and compiled it without problems.

Thanks for helping
Markus

**Comment by antoine-haas** [comment]
Yes, Git LFS is now mandatory to build the SDK from source as explained [here] (https://github.com/Microsoft/WinObjC/wiki/Building-From-Source) in our wiki. We moved many of the SDK binaries out of our repo to Git LFS to avoid bloating the size of the repo. As a result, Git LFS is needed to clone/checkout those binaries.

**Comment by rajsesh-msft** [comment]
You could extract the winobjc.zip and overlay it on the path where you have sources.  That should work.
