### ISSUE TITLE
[Tooling] Debugging watches and local values

### ISSUE THREAD

**Issue by alexdrenea** [Microsoft/WinObjC#371]
I'm not sure if this is an issue with the tools or something that I am not getting but when debugging an application it's impossible to see any meaningful values in the watch or local windows. Any .m object simply shows the pointer address but not the value.
Even simple things such as NSString are impossible to visualize debug.
Is this something missing from the VisualStudio addin?

**Comment by nicholasgerard-msft** [comment]
Object inspection is currently not supported, but we're working on it and also generally improving our Visual Studio debug tooling. Stay tuned.

**Comment by s5msft** [comment]
See #435

**Comment by antoine-haas** [comment]
Hey @alexdrenea, the latest release of the bridge supports improved Objective-C debugging, with native visualizers for NSString among others. Check the [debugging page](https://github.com/Microsoft/WinObjC/wiki/Debugging) of our wiki for more information. If you have any problems, or if some specific functionality to help you build your app is missing, please open an issue regarding that functionality in particular.
