### ISSUE TITLE
App randomly crashes on UINavigationController popViewController

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#372]
App randomly crashes when drilling-up from the sub pages to upper level pages using UINavigationController's popViewController.
[self.navigationController popViewControllerAnimated:YES];

Error message:
exeption thrown at 0x5B457FD0 (libobjc2.dll) in Pori Fashion Show.exe: 0xC0000005: Access violation writing location 0x0A714040.

Break location in UINavigationController.mm

 class AnimationNotificationParams {
    public:
    idretain _appearingController, _disappearingController;

    AnimationNotificationParams(id appearingController, id disappearingController) {
        _appearingController = appearingController;
        _disappearingController = disappearingController;
    }

    ~AnimationNotificationParams() {
        _appearingController = nil;
        _disappearingController = nil;
    }
};

![screen shot 2016-02-25 at 5 22 49 pm](https://cloud.githubusercontent.com/assets/13754172/13340633/c155afee-dbe6-11e5-96d6-33eaa202ed62.png)

**Comment by alexdrenea** [comment]
I'm getting a similar exception in 
UIVeiwController.mm -> _dismissTransitionStopped-> at priv->_dismissCompletionBlock = nil ;
I'll post exact exception once I get it.

**Comment by antoine-haas** [comment]
This has been fixed.
