### ISSUE TITLE
UIBarButtonItem - Empty button when there is a space before the character in the title

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#373]
UIBarButtonItem in the UINavigationBar shows empty button, when the text has empty space in the beginning. This is displayed well on iOS. Below code example shows a space in the string @" Glyphs".

UIBarButtonItem *btnGlyphs = [[UIBarButtonItem alloc] initWithTitle:@" Glyphs " style:UIBarButtonItemStylePlain target:self action:@selector(showGlyphs:)];

Screen shot of iOS and Windows. (with empty space & without empty space in the title string)
![bug_barbuttonitem](https://cloud.githubusercontent.com/assets/13754172/13348160/ae44b9f0-dc26-11e5-8438-3663d540ce02.jpg)

**Comment by yiyang-msft** [comment]
Hi, Please try latest drop, especially make sure it contains this change 568a9ec270114def684684de6dcc6e9f41a604be. it should fix your issue. I tried my repro but failed. 

Thanks
Yi

**Comment by Ramu-msft** [comment]
This issue should be fixed in the latest sdk.
