### ISSUE TITLE
UITextView - textColor is not applied

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#376]
UITextView ignores assigned textColor and shows default black color always.
Below example shows white text on black background. On Windows you cannot see the text since it shows default black text. Black text on white background example is also include below.
![bug_textview](https://cloud.githubusercontent.com/assets/13754172/13412620/79b29c9a-def9-11e5-9055-788e8dc86141.jpg)

**Comment by alexdrenea** [comment]
I noticed that the xib2nib converter does not know how to interpret colors set in the "sRGB" customColorSpace.
i.e. <color key="textColor" red="0.084091044962406158" green="0.77163618803024292" blue="0.55619001388549805" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>

If you set the colorText using a regular color from the interface builder color picker, it should work( the output is something like this: <color key="textColor" red="0.0" green="0.0" blue="0.0" alpha="1" colorSpace="calibratedRGB"/>)

I will be creating a pull request soon to fix the issue but int he meantime, please try and see if setting a different color works.

Also, if you could share your storyboard or xib that is failing it would also be helpful.
Thanks.

**Comment by cre8ivepark** [comment]
@alexdrenea Thanks - However, I don't use storyboard or xib. Try assigning the color from the code. It is not working.

**Comment by yiyang-msft** [comment]
Hi, I created textview programmatically with black background with white text, but it renders properly in my repro. Could you post the few lines how you create the textview during the repro so I can try on that. 

Thanks

**Comment by Ramu-msft** [comment]
This issue has been fixed and it is available in the latest SDK.
