### ISSUE TITLE
UITextView - text is distorted (stretched) over certain threshold width

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#377]
Text content in UITextView is stretched and distorted on desktop window when the window width reaches certain threshold width. Below screen shows horizontally stretched text.

<img width="1376" alt="screen shot 2016-02-29 at 3 30 52 pm" src="https://cloud.githubusercontent.com/assets/13754172/13412693/dc99655a-def9-11e5-9943-5123c2769953.png">

<img width="1698" alt="screen shot 2016-03-02 at 9 39 08 am" src="https://cloud.githubusercontent.com/assets/13754172/13469131/c92f5ddc-e05a-11e5-9c89-eeba5866729d.png">

**Comment by Ramu-msft** [comment]
We recently made some changes to the magnification logic, which should address this issue. Please test this in the latest version of the SDK.
