### ISSUE TITLE
Building Simple Project with error

### ISSUE THREAD

**Issue by ChangweiZhang** [Microsoft/WinObjC#378]
When I download the project from GitHub, I try to open and build the simple project. But when I build the project, some errors happen.

In my error list window, those error look like the following:
MSB4062 	The "Clang" task could not be loaded from the assembly D:\WinObjC-master\msvc\ClangCompileTask.dll. Could not load file or assembly 'file:///D:\WinObjC-master\msvc\ClangCompileTask.dll' or one of its dependencies. The module was expected to contain an assembly manifest. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	

![qq 20160301104256](https://cloud.githubusercontent.com/assets/4610610/13416010/63f1ee8c-df9a-11e5-953a-ee7f41df8126.png)

**Comment by rajsesh-msft** [comment]
Our project requires you to use git and git-lfs as the compiler binaries are git lfs objects.  Alternatively, you can unzip the winobjc.zip and overlay it on top of the sources.zip and that should work too.

**Comment by mgoemmel** [comment]
I've tried the overlay solution, but it does not work for me. But installing git and git lfs works.
