### ISSUE TITLE
mDNS support

### ISSUE THREAD

**Issue by MaddTheSane** [Microsoft/WinObjC#38]
I'm curious about the use of mDNS, as many iOS apps use either the dns_sd.h header directly, or some other API on top of it (usually Apple's).

Apple does have a [Bonjour SDK for Windows](https://developer.apple.com/bonjour/) already, and the source code is available under the Apache 2.0 license.

**Comment by rajsesh-msft** [comment]
@MaddTheSane we don't have explicit plans for supporting Bonjour SDK through WinOBJC.  You *should* be able to use the windows Bonjour SDK in the ported app, just like any other windows app.
