### ISSUE TITLE
NSPredicate API is missing

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#382]
The NSPredicate API is unimplemented / stubbed.

**Comment by rajsesh-msft** [comment]
Certainly in our near term backlog.

**Comment by arnoldt3** [comment]
@rajsesh-msft 
Is this resolved? I see that it's checked as completed on the roadmap.

**Comment by rajsesh-msft** [comment]
@arnoldt3 - predicateWithBlock is working.  We should have predicateWithString working in ~2weeks.

**Comment by arnoldt3** [comment]
Excellent, thanks for the quick response!

**Comment by rajsesh-msft** [comment]
This was fixed with [latest release](https://github.com/Microsoft/WinObjC/commit/88aa473d1a16c325f72a64f350356e5a6ba3ca7c)
