### ISSUE TITLE
renderInContext does also render objects with alpha==0.0f

### ISSUE THREAD

**Issue by mgoemmel** [Microsoft/WinObjC#383]
I'm using something like

UIGraphicsBeginImageContextWithOptions(self.bounds.size, YES, 0.0f);
[self.layer renderInContext:UIGraphicsGetCurrentContext()];
UIImage *oldBoardImage= UIGraphicsGetImageFromCurrentImageContext();
UIImageView *oldBoardImageView= [[UIImageView alloc] initWithImage:oldBoardImage];
UIGraphicsEndImageContext();

in one of my sources. The UIViewView contains some elements which are invisible by setting alpha to 0.0f. In the newly rendered UIImage these zero alpha elements are visible. As a quick hack I added

- (void)renderInContext:(CGContextRef)ctx {
    if (priv->hidden || priv->opacity==0.0f) {
        return;
    }
    ...
}

in CALayer.mm, but I guess this is not the correct fix to this problem. Any ideas?

Markus

**Comment by mgoemmel** [comment]
Digging a bit deeper brought me to

- (void)drawInRect:(CGRect)pos {
    [self drawInRect:pos blendMode:kCGBlendModeNormal alpha:1.0f];
}

and

- (void)drawInRect:(CGRect)pos blendMode:(CGBlendMode)mode alpha:(float)alpha {
    //  [BUG: Need to honor mode and alpha]

in UIImage.mm, which I guess is the root of the problem, right?

**Comment by oren-MSFT** [comment]
@mgoemmel are you adding a UIImage to a UIImageView then setting the alpha to zero on the UIImageView or the UIImageView's parent. More details would be greatly appreciated or code snippets as I really would like understand the issue better. Thanks in advance!

**Comment by mgoemmel** [comment]
It is an UIImageView containing a playing board graphics, which is loaded with [UIImage imageNamed]. A lot of other UIImageViews for play stones, also UIImageViews containing UIImage graphics, are added to this base view with addSubview. Some of the play stones needs to be invisible sometimes, and alpha will be set to 0.0 for these UIImageViews.

From time to time I need a stored copy of the board with all play stones for later restore. So I call renderInContext for the whole playing board UIImageView, which will normally be rendered showing the board and all the subviews (play stones) which are visible, and not showing the subviews having alpha set to 0.0.

With the bridge all objects will be rendered visible.

Please let me know if I can be of any more help.
Markus

**Comment by oren-MSFT** [comment]
We need to do some work to respect alpha's when drawing on our bitmaps but for now we are looking at a fix similar to what you did above. -(void)renderInContext:(CGContextRef)ctx { if (priv->hidden || priv->opacity<=0.01f) { return; } ... }

**Comment by mgoemmel** [comment]
I only wanted to mention the problem. So we should close the issue for now?

**Comment by oren-MSFT** [comment]
I submitted the fix and tracking the proper fix for later so going to close this issue. Thanks Markus for the help! 0ec55f3 was the commit.
