### ISSUE TITLE
error MSB4062:

### ISSUE THREAD

**Issue by willvin313** [Microsoft/WinObjC#384]
i tried compiling my app and i got this error MSB4062: The "Clang" task could not be loaded from the assembly C:\WinObjC\msvc\ClangCompileTask.dll. Could not load file or assembly 'file:///C:\WinObjC\msvc\ClangCompileTask.dll' or one of its dependencies. The module was expected to contain an assembly manifest. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by rajsesh-msft** [comment]
Are you getting the SDK from the winobjc.zip, or building your own?  If you are building from sources, please be sure to install git-lfs.  Please see https://github.com/Microsoft/WinObjC/wiki/Building-From-Source for details.
