### ISSUE TITLE
Module Foundation not found

### ISSUE THREAD

**Issue by michyprince** [Microsoft/WinObjC#388]
@import Foundation;

with this code the app won't compile, with this error: module foundation not found.

**Comment by rajsesh-msft** [comment]
@michyprince I am unable to reproduce this issue.  We have a unit test that does exactly this and it compiles.  This is under $(winobjc_sdk_root)\tests\unittests\ClangModules\ClangModules.h.  Can you provide more information on your project type or setup?

**Comment by PooyaZv** [comment]
@michyprince: We have not been able to reproduce this issue. I will close the issue for now. If the problem does persist, please let us know.
