### ISSUE TITLE
GLKit not supported.

### ISSUE THREAD

**Issue by wpbest** [Microsoft/WinObjC#39]
GLKit is not supported. GLKit was released with iOS 5. Many iOS application are dependent on the library.

**Comment by neuswcjr** [comment]
I have also encountered this issue, hope can be supported soon.

**Comment by AquinasThomas** [comment]
안녕

**Comment by s5msft** [comment]
Initial GLKit support has been exported as of 683f6d6

**Comment by s5msft** [comment]
Closing this issue since initial support has been submitted. Please create new issues for any bugs/omissions.
