### ISSUE TITLE
Adding a GLView to the storyboard leads to compile error.

### ISSUE THREAD

**Issue by GrantMeStrength** [Microsoft/WinObjC#390]
Once a GLView is added to a project, the following error is seen at Compile time:

:\Users\xxx\Desktop\winobjc\msvc\..\bin\Xib2Nib.exe" "..\..\MyApp\Base.lproj\Main.storyboard" "Release\Base.lproj\Main.storyboardc"" exited with code -1.

**Comment by Ramu-msft** [comment]
GLKView is not currently supported by xib2nib tool. In the built log you will see an error similar to the following line that shows the missing functionality.
1>         Unable to find class mapping for required object <glkView>

We will add this to our backlog. As a workaround, you can add this programatically.
