### ISSUE TITLE
[tooling] Rebuilding the tools

### ISSUE THREAD

**Issue by alexdrenea** [Microsoft/WinObjC#391]
I noticed that there is no .sln for the tools projects (vsimporter, xib2nib, etc).
Is there a particular reason for that?
I've built a .sln and project structure for them. Do you think it would be useful to submit a PR for that?

**Comment by asimonov-msft** [comment]
@alexdrenea The tools use cmake to generate the necessary VS project and solution files. The file can be found in: WinObjC\tools\vsimporter\CMakeLists.txt
