### ISSUE TITLE
WOCCatalog sample app crashes on launch when run in Debug mode

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#393]
Running the WOCCatalog sample app in Debug mode using the pre-built release of WinObjC will crash in [DisplayModeViewController:365](https://github.com/Microsoft/WinObjC/blob/master/samples/WOCCatalog/WOCCatalog/DisplayModeViewController.m#L365) when the equivalent of the following code is run (can be reproduced with the following line):

```obj-c
[UIApplication.displayMode valueForKey:@"currentMagnification"]
```

This seems to affect calling -valueForKey: on certain properties of the `WOCDisplayMode` UWP bridge class (e.g. `currentMagnification`, `hostWindowSize`), but not other properties like `currentSize`. Accessing these properties directly without KVC works fine.

Note that this _only_ happens in Debug mode using the latest pre-built release of WinObjC (March 10 or March 4 2016). This does not happen when running the app in Release mode using the pre-built SDK, or when building the SDK from source in either Debug or Release mode.

**Comment by Ramu-msft** [comment]
This is a known issue. This fix will be available in our next release.

**Comment by cesardelgadof** [comment]
I am using the example https://blogs.windows.com/buildingapps/2016/03/10/mixing-and-matching-uikit-with-xaml-and-the-windows-bridge-for-ios/ in Debug Mode but this happens:
![image](https://cloud.githubusercontent.com/assets/11799571/13723908/745e632c-e841-11e5-922f-4335edeb2c0b.png)

This does not happen in Release mode.

**Comment by rajsesh-msft** [comment]
@triplef This should be fixed in the latest release, could you please verify?

**Comment by triplef** [comment]
Verified, thanks!
