### ISSUE TITLE
UITapGestureRecognizer has a limit on how fast tap events are generated

### ISSUE THREAD

**Issue by GrantMeStrength** [Microsoft/WinObjC#396]
Tap events raised by UITapGestureRecognizer seem to be generated about 1/2 to 1/4 as quickly as on an iOS system, making it unusable for games. UISwipeGestures seem to be ok.

**Comment by yiyang-msft** [comment]
Hello,  

  I am trying to get a repro. Could you give me a little bit detail? 

  Did you attach any other additional gesture recognizer to the object other than the UITapGestureRecognizer? 

Thanks

**Comment by GrantMeStrength** [comment]
Hi –

I am using this code:

  UITapGestureRecognizer *tapRecognizer = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(handleTapFrom:)];
    [view addGestureRecognizer:tapRecognizer];

     UISwipeGestureRecognizer *swipeUpRecognizer = [[UISwipeGestureRecognizer alloc] initWithTarget:self action:@selector(handleSwipeUpFrom:)];
    [swipeUpRecognizer setDirection:(UISwipeGestureRecognizerDirectionUp)];
   [view addGestureRecognizer:swipeUpRecognizer];

    UISwipeGestureRecognizer *swipeDownRecognizer = [[UISwipeGestureRecognizer alloc] initWithTarget:self action:@selector(handleSwipeDownFrom:)];
    [swipeDownRecognizer setDirection:(UISwipeGestureRecognizerDirectionDown)];
    [view addGestureRecognizer:swipeDownRecognizer];



Removing the swipe gestures doesn’t seem to make a difference. I’m writing a game, and on the iOS device the taps are enough to fire ten items at once. On the Islandwood version, I can fire two.

Would you like a copy of the project?

-john

**Comment by yiyang-msft** [comment]
Thanks, We got a repro and understand the issue. Look into potential fixes.

**Comment by Ramu-msft** [comment]
The fix is available the latest SDK.
