### ISSUE TITLE
Feature Request : Work with React Native to convert iOS to windows

### ISSUE THREAD

**Issue by quincycs** [Microsoft/WinObjC#397]
If your not familiar with React Native,  its a fully native iOS application that is coded in mainly javascript.  React Native is obj-c that crosses that native/javascript barrier to render the actual platform control.

https://code.facebook.com/posts/1014532261909640/react-native-bringing-modern-web-techniques-to-mobile/
"we run it in an embedded instance of JavaScriptCore inside our apps and render to higher-level platform-specific components."

If this bridge worked with react native, there'd finally be ONE framework that developers could build against to make fully native (using each specific platform controls) across Android, iOS, and windows.  The approach is even better than xamarin, where RN has cross platform invisible layout controls that you can use.  E.g. it's flexbox serves as a grid layout for android, and iOS.

I've tried the vsimporter on a blank RN app, and making the VS solution was successful.  BUT as you can guess, just compiling didn't work.  Many dependencies weren't resolved, likely b/c RN libraries are being referenced that aren't installed on the windows side.  As far as i know there isn't an existing way of installing RN iOS libraries onto windows, b/c the existing installations are for Mac.

Here's an IPA of a blank RN iOS app. https://onedrive.live.com/redir?resid=B019B8B558409E86!187122&authkey=!ANLoc2m4VZ0N0Kk&ithint=file%2cipa

Let me know if I can be of any help.
-Quincy Mitchell
@quincymitch

**Comment by joewood** [comment]
Also see issues from last year:  #44, #118

**Comment by bbayraktutar** [comment]
I keep getting the same error

**Comment by rajsesh-msft** [comment]
If you are using react native, your best bet really is to use the react native support for UWP instead of using the winobjc project.  Please see this [blog](https://blogs.windows.com/buildingapps/2016/04/13/react-native-on-the-universal-windows-platform/) for details.

**Comment by quincycs** [comment]
Agreed.
