### ISSUE TITLE
Add support for locationManager

### ISSUE THREAD

**Issue by nicolasjon** [Microsoft/WinObjC#399]
Please can we have support for locationManager
Thanks.

**Comment by rhaning** [comment]
We do currently have support for CLLocationManager. Please see the following: https://github.com/Microsoft/WinObjC/tree/01508cca6e583ecb9064bdb028bdd593df057728/Frameworks/CoreLocation
Is there a specific area that you need?

**Comment by nicolasjon** [comment]
I will take a another look. I have to get the hang of isolating where the exceptions are occurring!
I know things are at an early stage. But I was really pleased with how much of my app fired up and started to work, and that I identified at least some of the currently unsupported parts.
Regards

**Comment by nicolasjon** [comment]
Had a further look
Just needed to add Location to the package.appx(!) 
Does not seem to update using dummy locations in the emulator, 
- (void)locationManager:(CLLocationManager *)manager
    didUpdateToLocation:(CLLocation *)newLocation fromLocation:(CLLocation *)oldLocation {
Just seems to get called on startup, I tried pins and live.
But -
On the device location gets called as I would expect. Also loaded the latest WINOBJC which has fixed more things. Great. Thanks!

**Comment by nicolasjon** [comment]
Just needed to add location permission to the manifest(!). Then all worked. Thanks.

**Comment by nicholasgerard-msft** [comment]
Great! Please open another issue if you encounter any bugs.

**Comment by nicolasjon** [comment]
Hi,

Not sure how helpful this is, but I have a couple of apps I am keen to get
onto W10.
Storyboard support seems to be the key issue now. I have produced a list
that might be of interest I am also keen to understand if there is anything
I am missing or how I might help further

Thanks
Nicolas


StoryBoard support Missing Nodes and Attributes.

Unknown UIBarButton item type edit

1> Unhandled
attribute:/document:(null):type:com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB

1> Unhandled attribute:/document:(null):version:3.0

1> Unhandled attribute:/document:(null):toolsVersion:9532

1> Unhandled attribute:/document:(null):systemVersion:14F27

1> Unhandled attribute:/document:(null):targetRuntime:iOS.CocoaTouch

1> Unhandled attribute:/document:(null):propertyAccessControl:none

1> Unhandled attribute:/document:(null):initialViewController:4

1> Unhandled node:/document/dependencies:(null)

1> Unhandled node:/document/dependencies/deployment:(null)

1> Unhandled attribute:/document/dependencies/deployment:(null):version:1296

1> Unhandled
attribute:/document/dependencies/deployment:(null):identifier:iOS

1> Unhandled node:/document/dependencies/plugIn:(null)

1> Unhandled
attribute:/document/dependencies/plugIn:(null):identifier:com.apple.InterfaceBuilder.IBCocoaTouchPlugin

1> Unhandled attribute:/document/dependencies/plugIn:(null):version:9530

1> Unhandled node:/document/scenes:(null)

1> Unhandled node:/document/scenes/scene:(null)

1> Unhandled attribute:/document/scenes/scene:(null):sceneID:iI7-NG-A7t

1> Unhandled
attribute:/document/scenes/scene/objects/viewController:(null):hidesBottomBarWhenPushed:YES

1> Unhandled
attribute:/document/scenes/scene/objects/viewController:(null):sceneMemberID:viewController

1> Unhandled
node:/document/scenes/scene/objects/viewController/webView/dataDetectorType:dataDetectorTypes

1> Unhandled
attribute:/document/scenes/scene/objects/placeholder:(null):userLabel:First
Responder

1> Unhandled
attribute:/document/scenes/scene/objects/placeholder:(null):sceneMemberID:firstResponder

1> Unhandled
attribute:/document/scenes/scene/objects/swipeGestureRecognizer:(null):direction:right

1> Unhandled node:/document/scenes/scene/point:canvasLocation

1> Unhandled attribute:/document/scenes/scene/point:canvasLocation:x:2094

1> Unhandled attribute:/document/scenes/scene/point:canvasLocation:y:-221

1> Unhandled node:/document/scenes/scene:(null)

1> Unhandled attribute:/document/scenes/scene:(null):sceneID:15

1> Unhandled
attribute:/document/scenes/scene/objects/tabBarController:(null):sceneMemberID:viewController

1> Unhandled
node:/document/scenes/scene/objects/tabBarController/nil:simulatedBottomBarMetrics

1> Unhandled
attribute:/document/scenes/scene/objects/tabBarController/connections/segue:(null):relationship:viewControllers

1> Unhandled
attribute:/document/scenes/scene/objects/tabBarController/connections/segue:(null):relationship:viewControllers

1> Unhandled
attribute:/document/scenes/scene/objects/placeholder:(null):sceneMemberID:firstResponder

1> Unhandled node:/document/scenes/scene/point:canvasLocation

1> Unhandled attribute:/document/scenes/scene/point:canvasLocation:x:-67

1> Unhandled attribute:/document/scenes/scene/point:canvasLocation:y:70

1> Unhandled node:/document/scenes/scene:(null)

1> Unhandled attribute:/document/scenes/scene:(null):sceneID:vfB-Ju-MhA

1> Unhandled
attribute:/document/scenes/scene/objects/navigationController:(null):title:Info

1> Unhandled
attribute:/document/scenes/scene/objects/navigationController:(null):definesPresentationContext:YES

1> Unhandled
attribute:/document/scenes/scene/objects/navigationController:(null):sceneMemberID:viewController

1> Unhandled
node:/document/scenes/scene/objects/navigationController/simulatedTabBarMetrics:simulatedBottomBarMetrics

1> Unhandled
attribute:/document/scenes/scene/objects/navigationController/connections/segue:(null):relationship:rootViewController

1> Unhandled
attribute:/document/scenes/scene/objects/placeholder:(null):userLabel:First
Responder

1> Unhandled
attribute:/document/scenes/scene/objects/placeholder:(null):sceneMemberID:firstResponder

1> Unhandled node:/document/scenes/scene/point:canvasLocation

1> Unhandled attribute:/document/scenes/scene/point:canvasLocation:x:94

1> Unhandled attribute:/document/scenes/scene/point:canvasLocation:y:-668

1> Unhandled node:/document/scenes/scene:(null)

1> Unhandled attribute:/document/scenes/scene:(null):sceneID:vX5-Uk-o5v

1> Unhandled
attribute:/document/scenes/scene/objects/navigationController:(null):title:List

1> Unhandled
attribute:/document/scenes/scene/objects/navigationController:(null):sceneMemberID:viewController

1> Unhandled
attribute:/document/scenes/scene/objects/navigationController/tabBarItem:tabBarItem:badgeValue:0

1> Unhandled
attribute:/document/scenes/scene/objects/navigationController/connections/segue:(null):relationship:rootViewController

1> Unhandled
attribute:/document/scenes/scene/objects/placeholder:(null):sceneMemberID:firstResponder

1> Unhandled node:/document/scenes/scene/point:canvasLocation

1> Unhandled attribute:/document/scenes/scene/point:canvasLocation:x:574

1> Unhandled attribute:/document/scenes/scene/point:canvasLocation:y:70

1> Unhandled node:/document/scenes/scene:(null)

1> Unhandled attribute:/document/scenes/scene:(null):sceneID:pib-su-oky

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController:(null):title:Master

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController:(null):sceneMemberID:viewController

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView:view:alwaysBounceVertical:YES

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView:view:dataMode:prototypes

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView:view:style:plain

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView:view:separatorStyle:default

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView:view:rowHeight:70

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView:view:sectionHeaderHeight:22

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView:view:sectionFooterHeight:22

1> Unhandled
node:/document/scenes/scene/objects/tableViewController/tableView/prototypes:(null)

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell:(null):selectionStyle:blue

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell:(null):accessoryType:disclosureIndicator

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell:(null):hidesAccessoryWhenEditing:NO

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell:(null):indentationLevel:1

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell:(null):indentationWidth:0.0

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell:(null):reuseIdentifier:Cell

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell:(null):rowHeight:70

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell/tableViewCellContentView:contentView:tableViewCell:oc7-nI-iY6

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell/tableViewCellContentView/subviews/label:(null):lineBreakMode:tailTruncation

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell/tableViewCellContentView/subviews/label:(null):baselineAdjustment:alignBaselines

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell/tableViewCellContentView/subviews/label:(null):adjustsFontSizeToFit:NO

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell/tableViewCellContentView/subviews/label:(null):lineBreakMode:tailTruncation

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell/tableViewCellContentView/subviews/label:(null):baselineAdjustment:alignBaselines

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell/tableViewCellContentView/subviews/label:(null):adjustsFontSizeToFit:NO

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell/tableViewCellContentView/subviews/label:(null):lineBreakMode:tailTruncation

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell/tableViewCellContentView/subviews/label:(null):baselineAdjustment:alignBaselines

1> Unhandled
attribute:/document/scenes/scene/objects/tableViewController/tableView/prototypes/tableViewCell/tableViewCellContentView/subviews/label:(null):adjustsFontSizeToFit:NO

1> Unhandled
node:/document/scenes/scene/objects/tableViewController/tableView/sections:(null)

1> Unhandled
attribute:/document/scenes/scene/objects/placeholder:(null):sceneMemberID:firstResponder

1> Unhandled node:/document/scenes/scene/point:canvasLocation

1> Unhandled attribute:/document/scenes/scene/point:canvasLocation:x:980

1> Unhandled attribute:/document/scenes/scene/point:canvasLocation:y:-243

1> Unhandled node:/document/scenes/scene:(null)

1> Unhandled attribute:/document/scenes/scene:(null):sceneID:R8r-2i-poL

1> Unhandled
attribute:/document/scenes/scene/objects/viewController:(null):title:Detail

1> Unhandled
attribute:/document/scenes/scene/objects/viewController:(null):sceneMemberID:viewController

1> Unhandled
attribute:/document/scenes/scene/objects/viewController/scrollView:view:autoresizesSubviews:NO

1> Unhandled
attribute:/document/scenes/scene/objects/viewController/scrollView:view:showsHorizontalScrollIndicator:NO

1> Unhandled
attribute:/document/scenes/scene/objects/viewController/scrollView:view:maximumZoomScale:4

1> Unhandled
attribute:/document/scenes/scene/objects/viewController/scrollView/subviews/label:(null):lineBreakMode:tailTruncation

1> Unhandled
attribute:/document/scenes/scene/objects/viewController/scrollView/subviews/label:(null):baselineAdjustment:alignBaselines

1> Unhandled
attribute:/document/scenes/scene/objects/viewController/scrollView/subviews/label:(null):adjustsFontSizeToFit:NO

1> Unhandled
node:/document/scenes/scene/objects/viewController/scrollView/subviews/label/nil:highlightedColor

1> Unhandled
attribute:/document/scenes/scene/objects/viewController/navigationItem/barButtonItem:rightBarButtonItem:systemItem:edit

1> Unhandled
node:/document/scenes/scene/objects/viewController/freeformSimulatedSizeMetrics:simulatedDestinationMetrics

1> Unhandled
node:/document/scenes/scene/objects/viewController/size:freeformSize

1> Unhandled
attribute:/document/scenes/scene/objects/viewController/size:freeformSize:width:527

1> Unhandled
attribute:/document/scenes/scene/objects/viewController/size:freeformSize:height:700

1> Unhandled
attribute:/document/scenes/scene/objects/placeholder:(null):sceneMemberID:firstResponder

1> Unhandled
attribute:/document/scenes/scene/objects/swipeGestureRecognizer:(null):direction:right

1> Unhandled
attribute:/document/scenes/scene/objects/swipeGestureRecognizer:(null):userLabel:Right
Swipe Gesture Recognizer

1> Unhandled
attribute:/document/scenes/scene/objects/viewController:(null):sceneMemberID:viewController

1> Unhandled
attribute:/document/scenes/scene/objects/placeholder:(null):userLabel:First
Responder

1> Unhandled
attribute:/document/scenes/scene/objects/placeholder:(null):sceneMemberID:firstResponder

1> Unhandled node:/document/resources:(null)

1> Unhandled node:/document/resources/image:(null)

1> Unhandled attribute:/document/resources/image:(null):name:info_24.png

1> Unhandled attribute:/document/resources/image:(null):width:24

1> Unhandled attribute:/document/resources/image:(null):height:24
