### ISSUE TITLE
Unhandled attribute:/document/scenes/scene/objects/viewController/view/subviews/scrollView/subviews/label

### ISSUE THREAD

**Issue by nicolasjon** [Microsoft/WinObjC#400]
Scroll view not yet supported by storyboard conversion
Thanks.

**Comment by oliversa-msft** [comment]
Investigating

**Comment by oliversa-msft** [comment]
To debug this further I'll need a log file or better yet the XIB or storyboard that resulted in this error. At this stage, I have to assume it's a label attribute issue which we may or may not supported.

Please supply the XIB/SB if possible otherwise we're really guessing as to the root cause.

**Comment by ArnOmsft** [comment]
Could you provide either the XIB or storyboard that triggered this error? Without this we cannot investigate more. Thanks for your help.

**Comment by ArnOmsft** [comment]
Closing this since we cannot investigate without more info. Please open a new issue with the requested info if you'd like us to investigate this.
Thanks.
