### ISSUE TITLE
[WUCCoreDispatcher runAsync:agileCallback:] throws an exception.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#403]
When calling [WUCCoreDispatcher runAsync:agileCallback:] an E_INVALIDARG exception is thrown: 

`0x40080201: WinRT originate error (parameters: 0x80070057, 0x0000001A, 0x0923F2EC)`

In the debugger the memory address 0x0923F2EC is giving the reason "The callback is not agile".

**Comment by ArnOmsft** [comment]
Thanks for flagging this, we're looking into this and I'll provide an update shortly.

**Comment by mukhole** [comment]
This has been fixed.
Master branch should pick this up in 1~2 weeks.
Closing this.
