### ISSUE TITLE
OAuth 2.0 Support

### ISSUE THREAD

**Issue by arnoldt3** [Microsoft/WinObjC#404]
OAuth 2.0 is pretty much the standard for building secure applications. I have several Fortune 500 level clients that are interested in the bridge, but need OAuth 2.0 to be supported. Support that, and you can win over some really important enterprises to use the bridge.

**Comment by rhaning** [comment]
This should work. Is there a specific scenario that you have found to be not working?

**Comment by weswmsft** [comment]
This will work by using the web auth broker in Windows.
