### ISSUE TITLE
Exception handling causes internal compiler error (C1001) in certain scenarios

### ISSUE THREAD

**Issue by PooyaZv** [Microsoft/WinObjC#405]
This issue is relevant under two scenarios:
- You have a try-catch(-finally) inside of a catch or finally
- You have ARC inside of a catch or finally (since ARC uses exception handling)

This can cause an internal compiler error.

Workaround: While we are working on a fix this issue can be mitigated through moving the code inside the catch or finally into a separate function (and simply calling that function from the catch or finally where the code used to live before)

**Comment by DHowett-MSFT** [comment]
Fixed with #2869
