### ISSUE TITLE
Alpha animation is not working on mobile phone devices

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/WinObjC#408]
Below code for changing .alpha value of the UIImageView from 1.0 to 0.0 does not work on phone device. On phone device, it just disappears without animation transition.
The symptom only shows on real device (tested on Lumia 950). it works well on simulator or desktop.

    [UIView beginAnimations:nil context:NULL];
    [UIView setAnimationDuration:WALKING_DURATION2];

    targetImageView.transform = CGAffineTransformMakeScale(1.5, 1.5);
    targetImageView.alpha = 0.0;

    [UIView commitAnimations];

**Comment by oren-MSFT** [comment]
I think i have a fix for this and we should have it out soon.

**Comment by oren-MSFT** [comment]
I think i have a fix for this and
