### ISSUE TITLE
AppDelegate Launches but ViewDidLoad never called

### ISSUE THREAD

**Issue by ImDestinedMe** [Microsoft/WinObjC#411]
I'm trying to convert my pre-existing iOS app to a UWP app using WinObjC but i'm having a lot of issues.

The current problem i'm having is that none of my views are even loading. 
I have a UIStoryboard and in the app delegate method 

`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`

It runs the following code

`self.navigationController = (UINavigationController *)[[[application windows] objectAtIndex:0] rootViewController];
    self.navigationController.viewControllers = @[[PhotoEditorViewController instance]];`

It basically retains the UINavigationController and sets only ViewController to be the PhotoEditorViewController, but the viewDidLoad method is never called on that UIViewController while the AppDelegate's code actually runs.

**Comment by Ramu-msft** [comment]
The xib2nib tool used to process storyboard and xib files is still under development. It is possible that your ViewController processing is failing and prevents the view from loading. As a workaround, you could consider creating your ViewController programmatically instead of creating from the storyboard.

**Comment by ImDestinedMe** [comment]
@Ramu-msft I changed it to have that ViewController be the initial view but the viewDidLoad method is still never called; is there any news of an upcoming release to fix this? I don't really wanna redo my entire app just because of one small problem.

**Comment by cloudmonkeypeng** [comment]
@ImDestinedMe   

Sorry for reply so late. I have tried to repro the bug and create UINavigationController and UiViewController in the AppDelegate.m.

In my opinion, if you call a initial view, the viewDidLoad should run successful.

Could you give me more information about this bug?
It will be helpful, if you can give me a repository about it. 

:)

**Comment by cloudmonkeypeng** [comment]
@ImDestinedMe 

Are you still working on this issue?  I hope to get feedback from you.

**Comment by Ramu-msft** [comment]
Closing issue due to lack of update.
