### ISSUE TITLE
Pass by reference method param not working with ARC

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#412]
There seems to be a compiler issue related to assigning values to pass by reference method parameters when the method returns on objc object type id, NSString etc and the code is compiled using ARC.

If you run the following code compiled using ARC, the value of error is always nil when printed out.

```
- (IBAction)update:(id)sender
{
    NSError *error = nil;
    [self doSomething:&error];

    NSLog(@"error: %@", error);
}

- (id)doSomething:(NSError **)error
{
    *error = [NSError errorWithDomain:@"moose" code:1 userInfo:nil];

    return nil;
}
```
Other things to note:
- If you change the return type of `doSomething:` to be a non objc object e.g. int, void, void * it works as expected.
- If you run the above code not compiled using ARC then it works as expected.

**Comment by DHowett-MSFT** [comment]
Great find! This one has bitten us before, so it's on our radar.
Thank you!



On Fri, Apr 1, 2016 at 2:05 AM -0700, "Rupert Daniel" <notifications@github.com<mailto:notifications@github.com>> wrote:


There seems to be a compiler issue related to assigning values to pass by reference method parameters when the method returns on objc object type id, NSString etc and the code is compiled using ARC.

If you run the following code compiled using ARC, the value of error is always nil when printed out.

- (IBAction)update:(id)sender
{
    NSError *error = nil;
    [self doSomething:&error];

    NSLog(@"error: %@", error);
}

- (id)doSomething:(NSError **)error
{
    *error = [NSError errorWithDomain:@"moose" code:1 userInfo:nil];

    return nil;
}


Other things to note:

  *   If you change the return type of doSomething: to be a non objc object e.g. int, void, void * it works as expected.
  *   If you run the above code not compiled using ARC then it works as expected.

-

**Comment by rajsesh-msft** [comment]
@weswmsft is tracking this with the compiler folks.

**Comment by PooyaZv** [comment]
Hello Rupert,
We have a fix to be rolled out in the next few days. Please stay tuned with our next release. Thank you for reporting this and please don't hesitate to let us know if you run into any other issues we can help with.

Thank you
Pooya

**Comment by PooyaZv** [comment]
This is fixed in SDKs released on April 21st or later. Thank you for working with us to resolve this issue. Please do not hesitate to let us know of any other issues you run into any other issues with Windows Bridge for iOS.
