### ISSUE TITLE
NSString rangeOfComposedCharacterSequencesForRange: not implemented.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#414]
AFNetworking uses [NSString rangeOfComposedCharacterSequencesForRange:] when percent escaping URL query string.

https://github.com/AFNetworking/AFNetworking/blob/2.x/AFNetworking/AFURLRequestSerialization.m#L99

This method is currently unimplemented.

**Comment by msft-Jeyaram** [comment]
@rupertdaniel  the functionality is available now.

closing as per commit 2bb45ad334d58198a8927d889c1ca04c2a786222.
