### ISSUE TITLE
Variable marked with __block is nil after assignment.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#415]
There seems to be a compiler issue when a variable marked with __block is assigned a value and is also captured within a block.

If you run the following code, compiled with ARC, the value of `someString` is nil even though is has been assigned a value.

If you don't capture `someString` in the block, then it works as expected.

```
- (IBAction)update:(id)sender
{
	__block NSString *someString = nil;
	someString = [self someValue:^{
		NSString *doSomething = someString;
    }];

	NSLog(@"value: %@", someString);
}

- (NSString *)someValue:(void (^)())block
{
	return @"Moose";
}
```

**Comment by rajsesh-msft** [comment]
@weswmsft is tracking this with the compiler folks.

**Comment by PooyaZv** [comment]
Hello Rupert,
We have a fix for this issue that we are expecting to roll out next week. Thank you for reporting this and please don't hesitate to let us know if you run into any other issues we can help with.

Thank you
Pooya

**Comment by PooyaZv** [comment]
This is fixed in SDKs released on April 21st or later. Thank you for working with us to resolve this issue. Please do not hesitate to let us know of any other issues you run into any other issues with Windows Bridge for iOS.
