### ISSUE TITLE
autoreleased objects in a libdispatch queue are not released.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#416]
Objects that are autoreleased in a libdispatch queue block are not released.

The following code will leak an NSMutableArray instance:
```
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
    [[[NSMutableArray alloc] init] autorelease];
});
```

Each libdispatch queue needs to be setup with an autoreleasepool. It seems that libdispatch and libobjc2 already have the code in place to support this. I think libdispatch needs to be built with DISPATCH_COCOA_COMPAT set.

Here are links to the relevant parts:
https://github.com/Microsoft/WinObjC/blob/master/deps%2F3rdparty%2Flibdispatch%2Fsrc%2Fqueue.c#L1633
https://github.com/Microsoft/libobjc2/blob/master/loader.c#L86

This is not an issue with the main dispatch queue, as this queue is drained as part of the main thread runloop and that is setup with an NSAutoreleasePool.

**Comment by rajsesh-msft** [comment]
@rupertdaniel Thanks for reporting this.

**Comment by rajsesh-msft** [comment]
DISPATCH_COCOA_COMPAT doesn't quite work for us because it also has mach dependencies which we don't have.  It was simple enough to enable autorelease pool for WINOBJC.  Fix is coming soon.
