### ISSUE TITLE
Running app on debug mode with WIN32 on windows 8.1pro with mobile emulator 10.0.10240.0

### ISSUE THREAD

**Issue by sssuourabh** [Microsoft/WinObjC#420]
App is loaded on emulator and get an exception
Exception thrown at 0x774924C2 in MyAPP.exe: Microsoft C++ exception: Platform::InvalidCastException ^ at memory location 0x05DFF578. HRESULT:0x80004002 No such interface supported

WinRT information: System.InvalidCastException: Unable to cast object of type 'System.__ComObject' to type 'Windows.UI.Xaml.Hosting.IElementCompositionPreviewStatics'.

   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW_WinRT(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget)

   at Windows.UI.Xaml.Hosting.ElementCompositionPreview.GetElementVisual(UIElement element)

   at XamlCompositorCS.Controls.CALayerXaml.CreateLayer()

Stack trace:
[External Code]
coreclr.dll!605d9298()
coreclr.dll!606b769f()
[External Code]
coreclr.dll!607f33cc()
[External Code]
STARBOARDXAML.DLL!DisplayNode::DisplayNode() Line 161
STARBOARDXAML.DLL!CAXamlCompositor::CreateDisplayNode() Line 1388
QUARTZCORE.DLL!CAPrivateInfo::CAPrivateInfo(CALayer * self, bool) Line 302
QUARTZCORE.DLL!_i_CALayer__init(CALayer  self, objc_selector  _cmd) Line 372
FOUNDATION.DLL!_c_NSObject__new(objc_class  self, objc_selector  _cmd) Line 62
UIKIT.DLL!_i_UIView__initPriv(UIView  self, objc_selector  _cmd) Line 121
UIKIT.DLL!_c_UIView__allocWithZone_(objc_class  self, objc_selector  _cmd, NSZone * zone) Line 148
UIKIT.DLL!_c_UIImageView__allocWithZone_(objc_class  self, objc_selector  _cmd, NSZone * zone) Line 44
FOUNDATION.DLL!_c_NSObject__alloc(objc_class  self, objc_selector  _cmd) Line 69
UIKIT.DLL!_i_UIApplication__init(UIApplication  self, objc_selector  _cmd) Line 1340
FOUNDATION.DLL!_c_NSObject__new(objc_class  self, objc_selector  _cmd) Line 62
UIKIT.DLL!UIApplicationMainInit(int argc, char   argv, NSString  principalClassName, NSString  delegateClassName, unsigned int defaultOrientation) Line 138
STARBOARDXAML.DLL!ApplicationMainStart(int argc, char   argv, const char  principalName, const char  delegateName, float windowWidth, float windowHeight) Line 136
STARBOARDXAML.DLL!WinObjcMainLoop(void * param) Line 105
[External Code]

If there is a handler for this exception, the program may be safely continued.
Any help is appreciated.

**Comment by antoine-haas** [comment]
Hi @sssuourabh. Having your machine on Windows 10, build 10586 or higher is a requirement for using the Windows Bridge for IOS SDK, so using Windows 8.1 is probably the cause of your issue. You should upgrade your machine and try again.

**Comment by antoine-haas** [comment]
Please reopen the issue if the problem persists after upgrading to Windows 10.

**Comment by sssuourabh** [comment]
if i am running with windows 10 on local machine , i am still getting the same exception
and **wkernelbase.pdb** could not be found in selected paths

@antoine-haas

**Comment by sourabh-vvdn** [comment]
Unhandled exception at 0x51C989E7 (Windows.UI.Xaml.dll) in DemoTest.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x00853638, 0x00000002).

**Comment by antoine-haas** [comment]
@sssuourabh , is this the same issue as #436, or are they separate problems?

**Comment by sssuourabh** [comment]
NO this comes when i run on local machine
