### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by andreluizbarbieri** [Microsoft/WinObjC#421]
I received two errors after run vsimporter in any xcode Project:

" An Add-In has caused an access violation while sinking on 'ProjectAdded' "
" An Add-In has caused an access violation while sinking on 'Opened' "
And ask for kill app:
" Do you wish terminate the appplication? "

However, the Samples compile very good.

**Comment by asimonov-msft** [comment]
@andreluizbarbieri Please provide more details about when you see these errors? Do they happen when importing, when you open the generated VS project, or during compile time?

**Comment by andreluizbarbieri** [comment]
I can upload the 'dialog box' that appear after open VS solution generated for winobjc
![capturar](https://cloud.githubusercontent.com/assets/14797086/14650269/717f6eee-0641-11e6-8000-92c4be7edc82.PNG)
![capturar2](https://cloud.githubusercontent.com/assets/14797086/14650270/71836c42-0641-11e6-8282-d510e5f1bf69.PNG)

**Comment by asimonov-msft** [comment]
@andreluizbarbieri I've never encountered these errors before.

A few follow up questions:
1. What version of Visual Studio are you using?
2. Do these errors happen with every project you import? Could you try running vsimporter on samples/WOCCatalog and [Canabalt](https://github.com/ericjohnson/canabalt-ios).

**Comment by andreluizbarbieri** [comment]
Yes, I import this two project but show these dialog box about acess
violation.

2016-04-19 22:25 GMT-03:00 Artem Simonov <notifications@github.com>:

> @andreluizbarbieri <https://github.com/andreluizbarbieri> I've never
> encountered these errors before.
>
> A few follow up questions:
> 1. What version of Visual Studio are you using?
> 2. Do these errors happen with every project you import? Could you try
> running vsimporter on samples/WOCCatalog and Canabalt
> <https://github.com/ericjohnson/canabalt-ios>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/WinObjC/issues/421#issuecomment-212196912>
>



-- 
AL Barbieri
http://scholar.google.com/citations?user=tylaKAMAAAAJ

**Comment by asimonov-msft** [comment]
@andreluizbarbieri What version of Visual Studio 2015 are you running? You can find out by going to Help -> About Microsoft Visual Studio.

![image](https://cloud.githubusercontent.com/assets/13038304/14787439/2601750e-0ab8-11e6-8ad9-57188d9671e0.png)

**Comment by asimonov-msft** [comment]
@andreluizbarbieri Closing this issue for now. Please reopen it if the issue persists and you're able to provide us with more information.
