### ISSUE TITLE
link1181 cannot open input file 'libgoogleanalytics.lib'

### ISSUE THREAD

**Issue by bapandyaOutlook** [Microsoft/WinObjC#424]
Hi , 

I have converted my iOS application into Universal app using WinObjC and when i compile the project in Visual studio 2015 i am getting this error : **link1181 cannot open input file 'libgoogleanalytics.lib'**

Please suggest me the solution.

Thanks,
Brijesh Pandya

**Comment by s5msft** [comment]
You’re trying to link to a file (libgoogleanalytics.lib) that can’t be found.

You’ll need to either remove that dependency from your project or, if the lib does exist, update your library path.

**Comment by ArnOmsft** [comment]
Google Analytics won't work with your Windows app so you'll have to remove the dependency. To do that in VS, go to Project / Properties / Linker / Input and you'll see the lib name in "Additional Dependencies". Click on the line and edit it to remove the lib's name. You'll have to do that for the different configurations: Debug/Win32, Release/Win32, etc.
As an alternative to Google Analytics, you should be able to use Application Insights (https://github.com/Microsoft/ApplicationInsights-CPP). We did not yet generate the objective-c projections for it (it's on our radar) but that should be feasible to call these APIs directly.

**Comment by bapandyaOutlook** [comment]
I have removed Google Analytics, but i do have two more "TestFlightSDK2.0.0" and "ZBarSDK" so if i am going to remove that two as well my core features will not work. so what you will suggest for the same ?

**Comment by ArnOmsft** [comment]
The TestFlightSDK won’t work on Windows so you’ll have to remove that dependency as well. A good alternative would be HockeyApp. We did not yet generate the Objective-C projections for this SDK (on our radar as well but I don’t have a date to share yet) but you should be able to call the C++ API directly from your Obj-C code.
For the ZBarSDK, it seems the Obj-C source code is available under the Apache license 2.0, so you could potentially incorporate this code into your iOS app and that code would be converted when creating the VS solution.

**Comment by ArnOmsft** [comment]
Updating my answer after some more investigation: it turns out HockeyApp does not have a SDK for native C++ app so that won't work. We're looking into how to address this and we'll share progress when it makes sense.
Closing this specific issue.
