### ISSUE TITLE
Converting NSString to NSURL loses information for non-Latin characters

### ISSUE THREAD

**Issue by yweijiang** [Microsoft/WinObjC#427]
I made an app with the following code:

NSString* pathAsString = @"/temp/hello/world/中文/你好.txt";
self.stringVersion.text = pathAsString;
NSURL* pathAsURL = [NSURL fileURLWithPath:pathAsString];
self.urlVersion.text = [pathAsURL path];

Where stringVersion and urlVersion are UILabels on a simple single view app. In WinObjC the latter label gets broken characters, while the NSString label shows correctly. Both labels match on iOS, as expected.

**Comment by rajsesh-msft** [comment]
Fixed in
