### ISSUE TITLE
GoogleMaps error

### ISSUE THREAD

**Issue by josepharunjoseph** [Microsoft/WinObjC#429]
Hello, 
I used pod in my objective-c code.
But when I Use this code to visual studio at that time it give errors :
1) use of undeclared identifier **'GMSServices'**	
2) expected identifier or '('  \Pods\Headers\Public\GoogleMaps\GoogleMaps\GoogleMaps.h

But when I click 2) Error it showing a popup
![error](https://cloud.githubusercontent.com/assets/14234501/14340456/992fbc6e-fca5-11e5-97ab-697862628fe2.png)

I thought may be it's a Pod error so again I took my fresh code and I tried to install **vsimporter**. At that time I checked that **Pod installation failed**. The following error came when I installed **vsimporter**:

![pod error](https://cloud.githubusercontent.com/assets/14234501/14317901/0e19a18a-fc28-11e5-94c7-0e60ae94df89.png)

And I also noticed that in visual studio solution explorer it showing me as 3 Projects
![solution explorer](https://cloud.githubusercontent.com/assets/14234501/14340659/58c3220e-fca7-11e5-8755-2e2ffa48d89e.png)

So, was I missed the file structure? IS there any specific file structure to put in visual studio?

Please help me to solve this issues. I am new in visual studio.

Thanks.

**Comment by nicholasgerard-msft** [comment]
CocoaPods are not currently supported by the bridge as our clang compiler front end does not support virtual filesystems, which CocoaPods depends on. It's a feature request we get a lot, so we're investigating adding support, but in the meantime you can try removing CocoaPods and manually including your third party libraries before running vsimporter.

**Comment by josepharunjoseph** [comment]
ok thanks @nicholasgerard-msft . I tried with my old code which have not use CocoaPods. But it give me error **'GoogleMaps/GoogleMaps.h' file  not found.** and also I found another error:

**no visible @interface for 'UISlider' declares the selector 'setValue:animated:'**

**Comment by ArnOmsft** [comment]
You're getting the "'GoogleMaps/GoogleMaps.h' file not found" error since you added the GoogleMaps SDK for iOS to your app and this is lost when converting your Xcode project into a Visual Studio solution using VSImporter. Plus we do not support GoogleMaps and you'd have to use the Bing Maps SDK which unfortunately we did not yet generate the Objective-C projections for, but this is on our radar and we'll communicate when it's available.
I'll check the 'UISlider' issue and come back to you.

**Comment by ArnOmsft** [comment]
We only do have partial support for UISlider, we're not planning to support that specific selector but we'll stub it out so it does not flag an error. You can actually check what we do support here: https://github.com/Microsoft/WinObjC/blob/master/include/UIKit/UISlider.h.
Closing this.
