### ISSUE TITLE
'CoreTelephony/CoreTelephonyDefines.h' file not found	

### ISSUE THREAD

**Issue by Nambukarthy** [Microsoft/WinObjC#430]
I can see CoreTelephony inside "winobjc\include" folder but still i am getting file not found issue.

**Comment by rajsesh-msft** [comment]
@Nambukarthy We don't have CoreTelephonyDefines.h.  As a workaround, you can comment this include out.  Please note that although we have this directory, the apis are just stubs and don't have any functionality.
