### ISSUE TITLE
LNK2001	unresolved external symbol ___objc_class_name_GAITrackedViewController

### ISSUE THREAD

**Issue by Nambukarthy** [Microsoft/WinObjC#433]
My agenda is that i just want to build my IOS app using bridge and make run in windows 10 mobile emulator with out any erro, help me to fix it.

**Comment by asimonov-msft** [comment]
@Nambukarthy That symbol comes from the Google Analytics SDK, which we unfortunately do not support.

**Comment by ArnOmsft** [comment]
You can check #424 for more info about this same issue.
Closing this.
