### ISSUE TITLE
Exception thrown at 0x636E39F2 (FOUNDATION.DLL) in ToDo.exe: 0xC0000005: Access violation reading location 0x0000001C.

### ISSUE THREAD

**Issue by Nambukarthy** [Microsoft/WinObjC#439]
I got this error in sample project (ToDoList) in the method readToDosFromDisk.

**Comment by asimonov-msft** [comment]
@Nambukarthy I am working on a fix for the issue.

**Comment by asimonov-msft** [comment]
@Nambukarthy The issue

**Comment by asimonov-msft** [comment]
@Nambukarthy The issue should now be fixed.

**Comment by Nambukarthy** [comment]
Its working fine, Thanks @asimonov-msft
