### ISSUE TITLE
VSimporter does not work when it's located on a network drive

### ISSUE THREAD

**Issue by robinmanuelthiel** [Microsoft/WinObjC#444]
I am using Parallels on my Mac and the WinObjC project is located on my Mac's partition so that it is mounted as a network drive when using Windows via Parallels.

As long as the VSimporter lies on the network drive, it fails with `[E] Invalid WINOBJC_SDK_ROOT specified: "\Mac\Slimport\Source\Windows-Bridges\WinObjC\winobjc". The SDK directory does not exist.`. As soon as I copy it to a local path like `C:/Temp` it works without problems.

**Comment by asimonov-msft** [comment]
@robinmanuelthiel vsimporter should now work much better with network paths.
