### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by sourabh-vvdn** [Microsoft/WinObjC#447]
@antoine-haas 

in [FAQ](https://github.com/Microsoft/WinObjC/wiki/FAQ#im-getting-errors-on-my-header-files-about-tlh-files-that-cant-be-opened--and---method-modifiers-being-marked-as-expected-declaration-and-unrecognized-token-for-interface-and-property-what-should-i-do) its written to ignore  errors on my header files about *.tlh files that can’t be opened, “+” and “-” method modifiers being marked as “expected declaration” and “unrecognized token” for “@interface” and “@property”.  but my app is not compiling it just stops wit these errors.

**Comment by asimonov-msft** [comment]
@sourabh-vvdn Please copy and paste the contents of the Output window after trying to compile.

**Comment by sourabh-vvdn** [comment]
Hi @asimonov-msft  
i have attached the output window after running my app.
please have a look
thanking you in anticipation

![outputlog](https://cloud.githubusercontent.com/assets/5500012/14669339/fe4736bc-0705-11e6-8e71-ef710673e1d3.png)

**Comment by antoine-haas** [comment]
@sourabh-vvdn, you attached the Error List window instead of the **Output** window. Please copy and paste (the whole content probably won't fit in a screenshot) the contents of the **Output** window, which I circled on your screenshot below. 
![output window](https://cloud.githubusercontent.com/assets/14913946/14682991/4718b4fc-06dd-11e6-8c32-a16a7418d4be.png)

**Comment by asimonov-msft** [comment]
@sourabh-vvdn The "expected selector for Objective-C method" entries appear to be genuine compiler errors. Something in that file is causing the compiler to not parse the interface correctly.

**Comment by sourabh-vvdn** [comment]
Hi 
Please check the error

1>C:\Users\rrana\Desktop\NewWinobjc\winobjc\include\AddressBookUI/ABNewPersonViewController.h(21,9): fatal error : **could not build module 'AddressBook'**

![newimage](https://cloud.githubusercontent.com/assets/5500012/14710874/d54d58e6-07f4-11e6-84c0-f9a079570715.png)

**Comment by asimonov-msft** [comment]
@sourabh-vvdn Please try to disable Objective-C Modules for your project.

![image](https://cloud.githubusercontent.com/assets/13038304/14720206/30ceff52-07b5-11e6-9adb-3d9a926b5b45.png)

**Comment by sourabh-vvdn** [comment]
@asimonov-msft  This error come when compiling ** LNK1181	cannot open input file 'libiconv.lib ** 
i checked over internet its showing give the path of lib to additional dependencies it will take 
but i didn't found this lib anywhere 
please suggest how to solve this.

**Comment by asimonov-msft** [comment]
@sourabh-vvdn Unfortunately we do not currently provide libiconv as part of the WinObjC SDK.

**Comment by asimonov-msft** [comment]
I'm closing the issue for now.

I have create a separate issue #477 to track adding libiconv to our SDK.
