### ISSUE TITLE
Error LNK2019 unresolved external symbol _index referenced in function

### ISSUE THREAD

**Issue by Nambukarthy** [Microsoft/WinObjC#448]

**Comment by asimonov-msft** [comment]
@Nambukarthy Could you please provide the full error message. It would be helpful to know where this symbol is used and what library is expected to export it.

**Comment by Nambukarthy** [comment]
@asimonov-msft Initially i got "Error - LNK2019   unresolved external symbol _index referenced in function __catch$___27-[DetailsMain createPage1:]_block_invoke_2.1740$3 ", the error occurred due to try catch block, so i removed all the try catch block in the particular page (DetailsMain), then i got these error "Error - LNK2019    unresolved external symbol _index referenced in function _CGSizeMake, Error - LNK2019    unresolved external symbol _index referenced in function _CGPointMake, Error - LNK2019    unresolved external symbol _index referenced in function _CGRectMake ", then i removed all the lines where i have used these CG methods, after removing these i end up with the issue #449, but in our ios code try catch block and CG methods have used in several pages but only i got error in DetailsMain page (Note: DetailsMain is .xib viewcontroller)

**Comment by asimonov-msft** [comment]
@Nambukarthy Closing the issue for now. Please re-open the issue if you can provide us with a repro case.
