### ISSUE TITLE
Error - MSB3073 The command ""..\_Release\winobjc\msvc\..\bin\Xib2Nib.exe" "..\..\..\PageName.xib" "Debug\PageName.nib"" exited with code -1.

### ISSUE THREAD

**Issue by Nambukarthy** [Microsoft/WinObjC#449]
I am getting this error in sbresources.targets.

**Comment by oren-MSFT** [comment]
Can you please attach the xib "..\..\..\PageName.xib? Sounds like our xib2nib tool is crashing when that xib is passed in. If you don't want it public please ping @s5msft who can help get the data from you securely. 

Thank you!

**Comment by Nambukarthy** [comment]
Thanks for your reply, Please find the file attached 
[DetailsMain.zip](https://github.com/Microsoft/WinObjC/files/229286/DetailsMain.zip)

**Comment by atexannamedbob** [comment]
One of our other developers is checking this out. Thanks for attaching the file!

**Comment by oren-MSFT** [comment]
One of our other developers is checking this out thanks for attaching the file!

**Comment by oliversa-msft** [comment]
Investigating
