### ISSUE TITLE
NSLog of NSArray objects does not try to print contained objects

### ISSUE THREAD

**Issue by yweijiang** [Microsoft/WinObjC#451]
I have the following code segment:

```
NSMutableArray* testArray = [[NSMutableArray alloc] init];
[testArray addObject:[NSNumber numberWithInt:1]];
[testArray addObject:[NSNumber numberWithInt:2]];
[testArray addObject:[NSNumber numberWithInt:3]];
NSLog(@"Log of array containing 1, 2, 3: %@", testArray);
```

This should show something like "Log of array containing 1, 2, 3: (1, 2, 3)". Instead we see this:

`Log of array containing 1, 2, 3: <NSMutableArrayConcrete: 0x14af9a4>`

**Comment by antoine-haas** [comment]
While this is not fixed, I would suggest using the Locals or Watch window of the debugger to visualize the contents of arrays at runtime, as shown below. To do this, make sure you enable the debugging features as explained on issue #435.
![nslog array](https://cloud.githubusercontent.com/assets/14913946/14755305/3ac9d9f0-0896-11e6-902c-7fc3ddc7c035.png)
