### ISSUE TITLE
Cannot create object for MFMailComposeViewController

### ISSUE THREAD

**Issue by SivaguruElangovan** [Microsoft/WinObjC#452]
Error: no known class method for selector 'alloc'

Getting above while creating object for MFMailComposeViewController
MFMailComposeViewController *mailViewController = [[MFMailComposeViewController alloc] init];

**Comment by SNanjappa** [comment]
@SivaguruElangovan Even i am facing the same issue, did you find any way to solve the issue? 
@winobjc-bot

**Comment by ArnOmsft** [comment]
This is a duplicate of #327. We do not currently have support for MFMailComposeViewController but we added this to our backlog (cf. #327).
Closing this one.
