### ISSUE TITLE
no known class method for selector 'create' in sample app in sample project (MixMatchUiKitXaml)

### ISSUE THREAD

**Issue by Nambukarthy** [Microsoft/WinObjC#457]
The code works fine before swap out the UIButton with a XAML button but issue occurs only after swap out the UIButton with a XAML button. i am getting error in this line (WXCButton *myButton = [WXCButton create];), it seems like create method is not there in bridge.

**Comment by asimonov-msft** [comment]
@Nambukarthy Please call "[WXCButton make]" instead.

**Comment by Nambukarthy** [comment]
Its working fine, Thanks @asimonov-msft

**Comment by s5msft** [comment]
This interface was changed as of this build: https://github.com/Microsoft/WinObjC/releases/tag/0.1.160318

**Comment by Juju4ka1** [comment]
Hi!
Using the most recent SDK https://github.com/Microsoft/WinObjC/releases/tag/0.1.160906 I get the following error:
no visible @interface for 'UIView' declares the selector 'setNativeElement:'	MixMatchUIKitXaml .

There is no method 'setContentsElement:' in CALayer (Please have a look at XAML interoperability section at this page: https://github.com/Microsoft/WinObjC/wiki/Using-the-SDK )

So how to mix XAML and UIKit controls using latest SDK?
