### ISSUE TITLE
Unable to find class mapping for required object <mapView>

### ISSUE THREAD

**Issue by jkellywilkerson** [Microsoft/WinObjC#461]
I posted this under another issue, but wanted to submit it as another issue since it's not related to the Segue. Please let me know how to proceed or any recommendations as to code adjustments to convert my currently published iOS app to the Windows Store.

Thanks,

JKellyWilkerson

**Comment by oliversa-msft** [comment]
Investigating - I'm not sure <mapView> is supported yet in our Xib2Nib tool.

**Comment by ArnOmsft** [comment]
The recommendation here is to remove the mapView control from your storyboard or XIB and use projected WinRT APIs instead. You can find an example of how to do that on our sample repo here: https://github.com/Microsoft/WinObjC-Samples/tree/master/Scenarios/Maps.
Thanks.

**Comment by ArnOmsft** [comment]
Closing this.
