### ISSUE TITLE
objc associatedObjects not working

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#463]
objc associated objects do not seem to be working. In the following example the value is nil when accessed in the next runloop:

```
objc_setAssociatedObject(self, @"myObjKey", @"MOOSE", OBJC_ASSOCIATION_RETAIN_NONATOMIC);

 // object is "MOOSE"
NSLog(@"object %@", objc_getAssociatedObject(self, @"myObjKey"));

dispatch_async(dispatch_get_main_queue(), ^{
        // object is nil
	NSLog(@"object %@", objc_getAssociatedObject(self, @"myObjKey"));
});
```

**Comment by DHowett-MSFT** [comment]
Is there a chance that self is getting KVO-observed (or otherwise having its class manipulated) between the two calls?

**Comment by rupertdaniel** [comment]
Yeah for that sample code the next line was actually:

`[self addObserver:self forKeyPath:@"testObject.selectedChildObject.childObject.name" options:0 context:nil];`

If I comment out the observer, objc_getAssociatedObject works as expected.

**Comment by DHowett-MSFT** [comment]
We just ran into this ourselves and are looking into solutions. Thanks for the report!

**Comment by rajsesh-msft** [comment]
This is rolled up as part of the KVO performance improvment change&nbsp;@dhowett-msft is working on.&nbsp;
