### ISSUE TITLE
WINOBJC_SDK_ROOT and MaxClangProcesses is not set when manually adding starboard.targets to an existing project

### ISSUE THREAD

**Issue by zhuowei** [Microsoft/WinObjC#465]
I tried adding Objective-C code to an existing Universal Application C++ project following the instructions on the [wiki](https://github.com/Microsoft/WinObjC/wiki/Adding-Objective-C-to-an-Existing-Project). I ran into two issues: first, I had to manually add WINOBJC_SDK_ROOT by editing the project file by hand, and after that I got this error when trying to build:
```
1>------ Build started: Project: FourPicsSolver, Configuration: Debug Win32 ------
1>P:\prog\winobjc\msvc\sbclang.targets(171,12): error MSB4086: A numeric comparison was attempted on "%(ClangCompile.MaxClangProcesses)" that evaluates to "" instead of a number, in condition "'@(ClangCompile)' != '' and ('%(ClangCompile.MaxClangProcesses)' < '-1' or '%(ClangCompile.MaxClangProcesses)' == '0')".
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

**Comment by asimonov-msft** [comment]
@zhuowei What happens if you follow the wiki and do not define WINOBJC_SDK_ROOT?

**Comment by asimonov-msft** [comment]
@zhuowei Closing issue for now. Please reopen if the issue persists and you can provide more details on a repro case.
