### ISSUE TITLE
Could not acquire lock file for module 'UIKit'

### ISSUE THREAD

**Issue by robinmanuelthiel** [Microsoft/WinObjC#469]
When trying to port the [Calculator sample from the official Windows Bridge for iOS blog](https://blogs.windows.com/buildingapps/2016/02/18/using-the-ios-bridge-to-bring-storyboards-and-auto-layout-to-windows-10/), I always get the following error after converting the project and trying to compile it:

`could not acquire lock file for module 'UIKit' Calculator (Calculator\Calculator)  W:\Source\Bridgetest\Calculator\Calculator\ViewController.h 9`

I am using the latest version of the bridge 0.1 Preview (April 29, 2016).
Oh, and I am using Parallels for my Windows VM, if this makes a difference.

Is it me or any ideas, why it could fail??

**Comment by asimonov-msft** [comment]
@robinmanuelthiel Is the sample source code and/or the WinObjC SDK located on a network share?

**Comment by robinmanuelthiel** [comment]
Yes, that was the problem. SDK and source code both were located on a network share. Intersting, that after copying the ported code to a local share it still didn't work. Only after I moved both and reran the VSIMPORTER, it began working...

**Comment by asimonov-msft** [comment]
@robinmanuelthiel Normally, vsimporter writes an absolute path to the WinObjC SDK into any imported projects. If you open the VCXPROJ file, you should be able to see a line similar to the below:
```
<WINOBJC_SDK_ROOT Condition="'$(WINOBJC_SDK_ROOT)' == ''">C:\dev\WinObjC</WINOBJC_SDK_ROOT>
```

If you invoke vsimporter with the _-relativepath_ option, it will write a relative path instead.

In both cases, you also have the option to define WINOBJC_SDK_ROOT as an environment variable, which will take precedence over the path hard-coded in the project file.

**Comment by mukhole** [comment]
Support for network drives is added, closing this.

**Comment by tmm1** [comment]
This issue still occurs if your source is located on an ExFAT filesystem.

**Comment by alakoring** [comment]
I just got this as well. I'm running Parallels, and the error is at

\\mac\Home\Transporter\6AS\SixAges\Source\App\ChapterManager.h

or if I try the Z: drive

Z:\Transporter\6AS\SixAges\Source\App\ChapterManager.h

This is shown as Network Drive, PrlSF file system.
