### ISSUE TITLE
NSOrderedSet is missing.

### ISSUE THREAD

**Issue by RG-J** [Microsoft/WinObjC#471]

**Comment by rajsesh-msft** [comment]
@bbowman please add your class cluster design comments here.

**Comment by bbowman** [comment]
We discussed this and have decided that is not worthwhile to ask you to class cluster NSOrderedSet in this review. We unfortunately don't have a good example / doc on our proposed design at the moment and feel it unfair to ask you to do something we haven't done ourselves. In light of that, we are recommending that this change cover both NSOrderedSet and NSMutableOrderedSet (as mentioned in the PR comments) and the mutable version can use the iterators etc from the immutable one via an internal header (NSOrderedSetInternal.h) that has a class extension with the "backing store" ivars at a @protected visibility. This will allow shared code and hopefully minimal extra work on your part. How does that sound?

**Comment by RG-J** [comment]
yep that sounds fair. I've already made that changes; I'm testing it
