### ISSUE TITLE
Controlling Simultaneous Gesture Recognition not supported

### ISSUE THREAD

**Issue by pittmab** [Microsoft/WinObjC#475]
There is no logic to ask the UIGestureRecognizerDelegate if two gesture recognizers should be allowed to recognize gestures simultaneously.

**Comment by pittmab** [comment]
One thing to note is that the gestureRecognizerShouldBegin: selector should be called before the selector to check if gestures should be recognized simultaneously.  So code will have to be modified in the implementation of UIPanGestureRecognizer (as an example) since it calls the shouldBegin selector within it's touchesMoved implementation.

**Comment by ArnOmsft** [comment]
Addressed via #1002

**Comment by yiyang-msft** [comment]
fixed with 1ec1a845a36aa18f053058d39c25db1423c84dfc.
