### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'libsqlite3.lib'

### ISSUE THREAD

**Issue by alejandrovelozb** [Microsoft/WinObjC#478]
Hey guys Im getting this error, Im not concerned about the warnings, just for the 'libsqlite3.lib'. There's something I can do? 

1>------ Build started: Project: IAR (IAR\IAR), Configuration: Debug Win32 ------
1>C:\Users\alejandro.veloz\Documents\GitHub\iar-mobile\src\ios\errs/CellForRespondNow.h(14,53): warning : property type 'UIImageView *' is incompatible with type 'UIImage *' inherited from 'UITableViewCell' [-Wincompatible-property-type]
1>C:\Users\alejandro.veloz\Documents\GitHub\iar-mobile\src\ios\errs\BSGoogleV3KmlParser.m(40,13): warning : 'setShouldProcessNamespaces:' is deprecated: property not yet implemented [-Wdeprecated-declarations]
1>LINK : fatal error LNK1181: cannot open input file 'libsqlite3.lib'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by asimonov-msft** [comment]
@alejandrovelozb Unfortunately, our SDK currently does not provide libsqlite3. For now, the workaround is as follows:

1. Go to https://www.sqlite.org/download.html and download a [VSIX for Universal Windows Platform](https://www.sqlite.org/2016/sqlite-uwp-3120200.vsix).
2. Install the VSIX on your machine.
3. In Visual Studio Solution Explorer, right-click on your project and select Add -> Referece...
4. Under Universal Windows -> Extensions select SQLite for Universal App Platform
![image](https://cloud.githubusercontent.com/assets/13038304/15014781/d106ca7a-11bc-11e6-95c4-ef415b0c9573.png)

**Comment by alejandrovelozb** [comment]
Thank you! But now I have another issue there's another lib 

1>LINK : fatal error LNK1181: cannot open input file 'libstdc++.lib'

They gave me this project and its kind of big and have a lot of libs, what would you recommend, try to find what libs that would work as the old ones, or starting from scratch?

**Comment by asimonov-msft** [comment]
@alejandrovelozb In regards to libstdc++.lib, try removing it from the Linker arguments (Linker -> Input -> Additional Dependencies) and see what happens.
For libraries in general, you'll need to find pre-compiled UWP ones (e.g. libsqlite3 above) or try to compile them from scratch.

**Comment by asimonov-msft** [comment]
I'm closing the issue for now.

I have create a separate issue #486 to track adding libsqlite3 to our SDK.
