### ISSUE TITLE
CFRunLoopPerformBlock API missing

### ISSUE THREAD

**Issue by afaruqui** [Microsoft/WinObjC#479]
The API can be used to run a function, for example a callback function, on a user(developer) provided  CFRunLoop and corresponding mode.

Reference [here](https://developer.apple.com/library/mac/documentation/CoreFoundation/Reference/CFRunLoopRef/#//apple_ref/c/func/CFRunLoopPerformBlock)

**Comment by rajsesh-msft** [comment]
@afaruqui yes, our current CF implementation is quite limited.  We are however working on getting the new version from the apple core libs project.  Is this blocking you in any way?

**Comment by afaruqui** [comment]
We are currently not blocked
