### ISSUE TITLE
WindObjC bridge is not supporting 64 bit version of Windows

### ISSUE THREAD

**Issue by nishant5800** [Microsoft/WinObjC#481]
When I run the below command to generate the visual studio solution file for sample xcode project,

> ..\..\bin\vsimporter.exe

I get the error "vsimporter.exe cannot start or run due to incompatibility with 64-bit version of Windows".

<img width="452" alt="screen shot 2016-05-05 at 11 35 56 am" src="https://cloud.githubusercontent.com/assets/13047019/15037126/a8eac01a-12b5-11e6-9d8e-e6935d82257f.png">

It was working fine till the previous release. Does anyone have any idea about its incompatibility with windows 7 in the current release of the bridge.

**Comment by asimonov-msft** [comment]
@nishant5800 It sounds like you didn't download the SDK from the right place. You can verify by checking the size of vsimporter.exe - I suspect it will be around 1Kb.

The latest pre-built package can be downloaded [here](https://github.com/Microsoft/WinObjC/releases/download/0.1.160429/winobjc.zip). And [here ](https://github.com/Microsoft/WinObjC/wiki/FAQ#im-getting-errors-after-downloading-the-bridge-through-the-download-zip-button-on-github-what-should-i-do)is a wiki post that explains the issue a bit better.

**Comment by rajsesh-msft** [comment]
@nishant5800 please follow instructions posted by @asimonov-msft and if that didn't work, let us know.  otherwise, i will consider this closed.
