### ISSUE TITLE
Error from 'ExternalAccessory.h'

### ISSUE THREAD

**Issue by djsmev** [Microsoft/WinObjC#485]
I am receiving this error when building my iOS app for Windows 10 mobile.
ExternalAccessory/ExternalAccessory.h file not found.
In the iOS code I have this statement '#import <ExternalAccessory/ExternalAccessory.h>', if I comment this out I receive several errors. Should I comment out these errors and rewrite the code? I tried a search here for this issue and found nothing.

**Comment by rajsesh-msft** [comment]
@djsmev yes, we don't have this framework in our SDK. If your app is using Bluetooth LE devices, you can use the [windows APIs](https://msdn.microsoft.com/library/windows/apps/dn297685) directly.  We have these APIs projected, so you can call them from OBJC as detailed [here](https://github.com/Microsoft/WinObjC/wiki/Using-the-SDK).

**Comment by rajsesh-msft** [comment]
Closing this issue, please let us know if you have further questions on this.
