### ISSUE TITLE
Missing libsqlite3 from SDK

### ISSUE THREAD

**Issue by asimonov-msft** [Microsoft/WinObjC#486]
The WinObjC SDK is missing libsqlite3, which is a standard library provided in Apple's iOS SDK.

**Comment by rajsesh-msft** [comment]
This would be by design.  The supported way to get SQLLite with UWPs is by installing the SQL-lite.vsix directly from [sql-lite](http://sqlite.org/download.html) website.  There are no plans to redistribute it with WinOBJC.

**Comment by rajsesh-msft** [comment]
Copying @asimonov-msft 's comments on #478 - how to add sqllite support to Winobjc project. 

Go to https://www.sqlite.org/download.html and download a VSIX for Universal Windows Platform.
Install the VSIX on your machine.
In Visual Studio Solution Explorer, right-click on your project and select Add -> Referece...
Under Universal Windows -> Extensions select SQLite for Universal App Platform 

![d106ca7a-11bc-11e6-95c4-ef415b0c9573](https://cloud.githubusercontent.com/assets/15148713/15187928/0d6b80fa-1758-11e6-8f80-e4404c24bd50.png)
