### ISSUE TITLE
Creating a custom gesture recognizer is not supported

### ISSUE THREAD

**Issue by pittmab** [Microsoft/WinObjC#489]
Looking at the implementation in UIApplication.mm the loop that processes the gesture recognizer loops over the classes of iOS gestures (e.g. Pinch, Swipe, etc) to fire the gesture.  This does not extend to custom UIGestureRecgonizer subclasses.

**Comment by jaredhms** [comment]
Thanks for raising the issue.  This is a known limitation, and we are actively working through an updated design for how we'll be handling gestures going forward.  Any details that you can share on your custom UIGestureRecognizer and its usage patterns would be helpful to us.

**Comment by pittmab** [comment]
In this case our use case is pretty simple.  We are just using it to collect the events while the gesture is still possible so that we can use this information once the gesture is recognized.

Do you have any idea on the timeline for the gesture rework?

Thanks,

Brent

**Comment by ArnOmsft** [comment]
Addressed via #1002

**Comment by ArnOmsft** [comment]
Marking this as a feature request, as agreed we'll take ownership of the pull request #1002.

**Comment by yiyang-msft** [comment]
fixed with 1ec1a845a36aa18f053058d39c25db1423c84dfc
