### ISSUE TITLE
Objective-C syntax highlighting doesn't work

### ISSUE THREAD

**Issue by sasikiran** [Microsoft/WinObjC#49]
I installed VS 2015 Community Edition along with the mentioned tools. After that, I downloaded WinObjc and opened the WOCCatalog solution file. The project doesn't have any syntax highlighting. I 
ran the tool objc-syntax-highlighting present inside /bin folder. The tool failed to install with error "This extension is not installable on any currently installed products." 

![capture](https://cloud.githubusercontent.com/assets/1332828/9153909/242790f0-3e95-11e5-9be5-5eb7588c7082.JPG)

09-08-2015 12.42.41 PM - Microsoft VSIX Installer
09-08-2015 12.42.41 PM - -------------------------------------------
09-08-2015 12.42.41 PM - Initializing Install...
09-08-2015 12.42.41 PM - Extension Details...
09-08-2015 12.42.41 PM - 	Identifier      : VSIX..9c35fff1-f084-44c1-a38e-68c707163aa2
09-08-2015 12.42.41 PM - 	Name            : Objective-C Language Service
09-08-2015 12.42.41 PM - 	Author          : Microsoft
09-08-2015 12.42.41 PM - 	Version         : 1.0
09-08-2015 12.42.41 PM - 	Description     : This package contains Objective-C language service components such as syntax higlighting etc
09-08-2015 12.42.41 PM - 	Locale          : en-US
09-08-2015 12.42.41 PM - 	MoreInfoURL     : 
09-08-2015 12.42.41 PM - 	InstalledByMSI  : False
09-08-2015 12.42.41 PM - 	SupportedFrameworkVersionRange : [4.5,)
09-08-2015 12.42.41 PM - 
09-08-2015 12.42.41 PM - 	Supported Products : 
09-08-2015 12.42.41 PM - 		Microsoft.VisualStudio.Pro
09-08-2015 12.42.41 PM - 			Version : [12.0]
09-08-2015 12.42.41 PM - 
09-08-2015 12.42.41 PM - 	References      : 
09-08-2015 12.42.41 PM - 
09-08-2015 12.42.41 PM - Searching for applicable products...
09-08-2015 12.42.41 PM - Found installed product - Microsoft Visual Studio Community 2015
09-08-2015 12.42.41 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
09-08-2015 12.42.41 PM - Found installed product - Global Location
09-08-2015 12.42.41 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by YangShaoQun** [comment]
check out  this: #28

**Comment by asimonov-msft** [comment]
Both the pre-built SDK, as well as the git repository, should now contain the fixed VSIX file.

**Comment by sasikiran** [comment]
Thanks! This works.

--  
Sasi kiran
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
