### ISSUE TITLE
Unhandled exception at 0x7728F72B (ntdll.dll) 

### ISSUE THREAD

**Issue by bbayraktutar** [Microsoft/WinObjC#495]
I get this problem in most applications.
what is the meaning?
![hata](https://cloud.githubusercontent.com/assets/13641809/15254691/b744d286-1940-11e6-8aa7-1f724e53b782.PNG)

**Comment by rajsesh-msft** [comment]
Without a callstack, it is hard to say.  However looking at the code, this doesnt seem to be winobjc related.

Can you provide information on what you are doing and provide the callstack?

**Comment by bbayraktutar** [comment]
I work for this application;
https://github.com/Yogayu/EmotionNote

**Comment by bbayraktutar** [comment]
I'm having the same problem in all applications.
Is this about the system?

**Comment by bbowman** [comment]
Can you post a call stack with the local variables for the failing frame? Based on the screenshot you are trying to ref new an array for the launch args. I'd validate that you aren't receiving something weird in the launch arguments. I agree with raj though and it doesn't seem like a winobjc issue.

**Comment by bbowman** [comment]
(As an additional note, you should be able to get the hr or error code from the exception which might provide more information)

**Comment by asimonov-msft** [comment]
@bbayraktutar The EmotionNote project you linked to is written in Swift, which we currently do not support.

**Comment by rajsesh-msft** [comment]
This seems unrelated to winobjc.  Closing it for now.
