### ISSUE TITLE
WOCCatalog sample doesn't build on Visual Studio 2015 Update 2

### ISSUE THREAD

**Issue by lbugnion** [Microsoft/WinObjC#496]
I had the same problem when cloning the repo or downloading the Zip file. I copied the whole Zip file to my desktop, unpacked it, opened WinObjC-master\WinObjC-master\samples\WOCCatalog\WOCCatalog-WinStore10.sln and tried to build for Debug, Win32, Local Machine. The following error happens:

MSB3073 The command ""C:\Users\lbugn\Desktop\WinObjC-master\WinObjC-master\msvc\..\bin\hmapmaker.exe" "Debug\WOCCatalog-project.txt" "Debug\WOCCatalog-project.hmap"" exited with code 216.	WOCCatalog (WOCCatalog\WOCCatalog)	C:\Users\lbugn\Desktop\WinObjC-master\WinObjC-master\msvc\sbclang.targets

Any idea on how to solve this? Is this a configuration problem?

Thanks
Laurent

**Comment by rajsesh-msft** [comment]
@lbugnion what is the size of the binary <root>\bin\hmapmaker.exe?  If it is really small, you are running into the issue called out [here](https://github.com/Microsoft/WinObjC/wiki/FAQ#im-getting-errors-after-downloading-the-bridge-through-the-download-zip-button-on-github-what-should-i-do).

**Comment by lbugnion** [comment]
That's probably what it is indeed. Thanks so much Rajesh, appreciate the prompt reply. I am talking about this stuff in a few days and need to make sure that everything is working. Take care!
