### ISSUE TITLE
The projecteced api WSMMapLocationFinder findLocationsAtAsync does not work

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#497]
The following code snippet:
    [WSMMapLocationFinder findLocationsAtAsync:geopoint success:^void(WSMMapLocationFinderResult* results){
        NSLog(@"Windows Projection API Call Success!");
    } failure:^void(NSError* error){
        NSLog(@"Windows Projection API Call Failure!");
    }];
does not work.  Neither the success nor failure block is executed.

**Comment by ArnOmsft** [comment]
Closing this since this has been fixed earlier in June.
