### ISSUE TITLE
NSSet containsObject should return NO for nil object.

### ISSUE THREAD

**Issue by RG-J** [Microsoft/WinObjC#498]

**Comment by rajsesh-msft** [comment]
@RG-J technically, you cannot pass nil here, as the method does expect non-nil value. If you try this on reference platform, you will get a warning.  Clearly, you won't see the warning if you pass a variable and it just happens to hold nil.

**Comment by RG-J** [comment]
@rajsesh-msft As per documentation it's true, but if a variable is passed in and becomes null, current implementation crashes and reference platform handles it gracefully.
