### ISSUE TITLE
fatal error : 'ContactsUI/ContactsUI.h' file not found

### ISSUE THREAD

**Issue by enyawg** [Microsoft/WinObjC#503]
I have an iOS sample app, which creates events in the Contacts & AddressBook for the user.

When I am using the bridge to build the same app for WP, it is giving me the fatal error : 'ContactsUI/ContactsUI.h' file not found

There is a Framework in iOS library, called the ContactsUI & AddressBookUI.

The full error log is:

1>------ Build started: Project: Demo (Demo\Demo), Configuration: Debug Win32 ------
1>  Note: Setting MaxClangProcesses to 1 because Modules are enabled.
1>  ..\..\Demo\ViewController.m
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\ViewController.m(14,9): fatal error : 'ContactsUI/ContactsUI.h' file not found
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABRecord.h(24,9): error : declaration of 'int32_t' must be imported from module 'CoreFoundation' before it is required
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABRecord.h(31,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABRecord.h(33,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABAddressBook.h(28,61): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABAddressBook.h(42,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABAddressBook.h(43,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABAddressBook.h(45,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABAddressBook.h(46,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABPerson.h(39,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABPerson.h(41,82): error : must use 'enum' tag to refer to type 'ABPersonImageFormat'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABPerson.h(42,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABPerson.h(43,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABGroup.h(31,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABGroup.h(32,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABMutableMultiValue.h(27,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABMutableMultiValue.h(32,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABMutableMultiValue.h(33,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABMutableMultiValue.h(34,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBook/ABMutableMultiValue.h(40,20): error : unknown type name 'bool'
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\include\AddressBookUI/ABNewPersonViewController.h(21,9): fatal error : could not build module 'AddressBook'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by asimonov-msft** [comment]
@enyawg As a workaround, try turning off header modules as outlined [here](https://github.com/Microsoft/WinObjC/issues/456).

**Comment by enyawg** [comment]
Hi Artem Simonov,

Today I received your email suggesting as follows: 

"@enyawg As a workaround, try turning off header modules as outlined here."

I turned of header modules as outlined and it removed the AddressBook errors.... Now I have this 1 fatal error:

fatal error: 'ContactsUI/ContactsUI.h' file not found (#503) although I am including theFramework in iOS library, called the ContactsUI.

Any suggestions?

The full error log is:
fatal error : 'ContactsUI/ContactsUI.h' file not found
1>------ Build started: Project: Demo (Demo\Demo), Configuration: Debug Win32 ------
1>  ..\..\Demo\BrowserViewController.m
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\BrowserViewController.m(77,39): warning : 'networkActivityIndicatorVisible' is deprecated: property not yet implemented [-Wdeprecated-declarations]
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\BrowserViewController.m(83,39): warning : 'networkActivityIndicatorVisible' is deprecated: property not yet implemented [-Wdeprecated-declarations]
1>  ..\..\Demo\main.m
1>  ..\..\Demo\URLCommand.m
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\URLCommand.m(87,39): warning : 'applicationIconBadgeNumber' is deprecated: property not yet implemented [-Wdeprecated-declarations]
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\URLCommand.m(94,43): warning : 'applicationIconBadgeNumber' is deprecated: property not yet implemented [-Wdeprecated-declarations]
1>  ..\..\Demo\ViewController.m
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\ViewController.m(14,9): fatal error : 'ContactsUI/ContactsUI.h' file not found
1>  ..\..\Demo\AppDelegate.m
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\AppDelegate.m(68,51): warning : 'alertControllerWithTitle:message:preferredStyle:' is deprecated: method not yet implemented [-Wdeprecated-declarations]
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\AppDelegate.m(71,45): warning : 'actionWithTitle:style:handler:' is deprecated: method not yet implemented [-Wdeprecated-declarations]
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\AppDelegate.m(78,21): warning : 'applicationIconBadgeNumber' is deprecated: property not yet implemented [-Wdeprecated-declarations]
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\AppDelegate.m(81,47): warning : 'actionWithTitle:style:handler:' is deprecated: method not yet implemented [-Wdeprecated-declarations]
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\AppDelegate.m(86,16): warning : 'addAction:' is deprecated: method not yet implemented [-Wdeprecated-declarations]
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\AppDelegate.m(87,16): warning : 'addAction:' is deprecated: method not yet implemented [-Wdeprecated-declarations]
1>C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\AppDelegate.m(91,16): warning : 'addAction:' is deprecated: method not yet implemented [-Wdeprecated-declarations]
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by asimonov-msft** [comment]
@enyawg Unfortunately, we currently do not have any support for the ContactsUI framework. Furthemore, the AddressBookUI framework contains only stubs at this time.

**Comment by enyawg** [comment]
Ok, Thanks Asimonov,

The other error I am getting is this:

1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1670,5): error APPX1101: Payload contains two or more files with the same destination path 'Info.plist'. Source files:
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1670,5): error APPX1101: C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo\Info.plist
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1670,5): error APPX1101: C:\Users\wayneg\Documents\winobjc-builds\0.1.160512\winobjc\samples\Demo\Demo.vsimporter\Demo-WinStore10\Debug\Info.plist

Could you enlighten me on this error APPX1101: Payload contains two or more files with the same destination path

Cheers,
Enyawg

**Comment by enyawg** [comment]
One more thing Asimonov,

So if I strip out the AddressBook & ContactsUI frameworks from the Xcode and run the vsimporter, can I add these these API's natively in Visual Studio... any good "getting started" tutorials you can recommend?

Cheers,
Enyawg

**Comment by antoine-haas** [comment]
Hello @enyawg,
The alternative to the AddressBook & ContactsUI frameworks would be the [Windows.ApplicationModel.Contacts](https://msdn.microsoft.com/library/windows/apps/br225002) namespace. You should use it's projected APIs, which can be found in it's corresponding [WindowsApplicationModelContacts.h](https://github.com/Microsoft/WinObjC/blob/develop/include/Platform/Universal%20Windows/UWP/WindowsApplicationModelContacts.h) header file.

Regarding error APPX1101, please open a new issue since it seems to be unrelated to the AddressBook & ContactsUI frameworks.
