### ISSUE TITLE
Memory leak when repeatedly adding/removing KVO observers on an object.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#504]
There seems to be a memory leak when repeatedly adding/removing KVO observers on an object.

The attached sample project demonstrates the issue.

1. Unzip, build and run app
2. Press "Update Name Property"
3. Launch Task Manager and look for "KVOBug.exe". Notice the memory continuously growing as the app is executing.

A lot of the memory allocation seems to occur in `_addNestedObserversAndOptionallyDependents` and `_addKeyObserver`, but then never gets freed when the observer is removed.

[KVOBug-memoryleak.zip](https://github.com/Microsoft/WinObjC/files/270157/KVOBug-memoryleak.zip)

**Comment by DHowett-MSFT** [comment]
Incidentally, this could be caused in part by the same root issue as #500!
Thanks for the report.



On Wed, May 18, 2016 at 3:05 AM -0700, "Rupert Daniel" <notifications@github.com<mailto:notifications@github.com>> wrote:


There seems to be a memory leak when repeatedly adding/removing KVO observers on an object.

The attached sample project demonstrates the issue.

  1.  Unzip, build and run app
  2.  Press "Update Name Property"
  3.  Launch Task Manager and look for "KVOBug.exe". Notice the memory continuously growing as the app is executing.

A lot of the memory allocation seems to occur in _addNestedObserversAndOptionallyDependents and _addKeyObserver, but then never gets freed when the observer is removed.

KVOBug-memoryleak.zip<https://github.com/Microsoft/WinObjC/files/270157/KVOBug-memoryleak.zip>

-

**Comment by DHowett-MSFT** [comment]
Sorry, I meant #501.

**Comment by DHowett-MSFT** [comment]
Have you continued seeing this since the associated object fix for #501?

**Comment by rupertdaniel** [comment]
Sorry for the delay in replying.

I've re-run the attached demo project and unfortunately I'm still seeing the same behaviour, memory usage grows and it seems to never be reclaimed.

Here is a screen grab from the memory profiler showing where the area the allocations are occurring.

![screenshot 2016-07-01 08 30 35](https://cloud.githubusercontent.com/assets/237035/16514799/1da0019a-3f66-11e6-9a35-3ba32ee2a542.png)
