### ISSUE TITLE
WinRT projections createWith does not work on CALayerXaml instances

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#509]
I’m passing one of our CALayerXaml objects as IInspectable\* into WXFrameworkElement::createWith (or WXCPanel::createWith), but the call fails in **verifyCastConformance**:  

```
// Grab the layer's backing XAML node
Microsoft::WRL::ComPtr<IInspectable> inspectableNode(GetCACompositor()->DisplayNodeToXamlNode([self->layer _presentationNode]));
self->priv->xamlElement = [WXFrameworkElement createWith:inspectableNode.Get()];
```

**verifyCastConformance** calls GetIids on the object passed in, but it's only returning 3 GUIDs:

These are the only IIDs I see for this object after the call to GetIids;
             iids[0]       {B93C018E-5625-3D8D-82B7-11655397C0B8}   _GUID
              numSupported  3      unsigned long
             iids[1]       {9C00AB21-B6BD-3C4C-AE76-E7FB5CA6CD18}   _GUID
             iids[2]       {IID_IWeakReferenceSource} _GUID

```
         obj    0x011b1870 {m_originSet=false m_backgroundColor={A=0 '\0' R=0 '\0' G=0 '\0' ...} m_backgroundBrush=0x083f1178 {...} ...}  IInspectable * {UIKIT.DLL!XamlCompositor::Controls::CALayerXaml}
         [XamlCompositor::Controls::CALayerXaml]  {m_originSet=false m_backgroundColor={A=0 '\0' R=0 '\0' G=0 '\0' ...} m_backgroundBrush=0x083f1178 {...} ...}       UIKIT.DLL!XamlCompositor::Controls::CALayerXaml
         Windows::UI::Xaml::Controls::Panel {...}  UIKIT.DLL!Windows::UI::Xaml::Controls::Panel
```

It's unclear to me how I can work around the issue.  I tried various casts on the C++/CX object to get to its IInspectable*, but all attempts resulted in the same 3 GUIDs returned from GetIids.  Is it possible we should be calling a different function in verifyCastConformance?

**Comment by pradipd** [comment]
I believe we fixed this a while ago, but forgot to close out the bug.
