### ISSUE TITLE
AV in WinRT projections when passing nil to a WinRT call

### ISSUE THREAD

**Issue by jaredhms** [Microsoft/WinObjC#510]
getCurrentPoint should accept nullptr, but it AVs instead;

        [self->priv->xamlElement addPointerPressedEvent:^(RTObject* sender, WUXIPointerRoutedEventArgs* e) {
      
          // Get the point value in window coordinates
          WUIPointerPoint* pointerPoint = [e getCurrentPoint:nil];

I tried to update _getRtInterface to do a null check on ‘o’, but I couldn’t get the UWP project to compile, so I couldn’t validate the fix.

template <typename I>
inline ComPtr<I> _getRtInterface(RTObject* o) {
    ComPtr<I> ret;
    if (o) { // <--------------- I think we need this null check
        o.comObj.As(&ret);
    }
    return ret;
}

**Comment by ArnOmsft** [comment]
Closing this since this was addressed in June.
