### ISSUE TITLE
LNK1181	cannot open input file ..\Release\Universal Windows\Logging.lib		

### ISSUE THREAD

**Issue by Nambukarthy** [Microsoft/WinObjC#513]
I have followed the instruction given in "https://github.com/Microsoft/WinObjC/wiki/Building-From-Source" i am getting ("cannot open input file" and MSB4062) issues in step 6 and step 8. I did install git lfs and confirm through git bash "git lfs initialized" that git lfs has installed already.

**Comment by antoine-haas** [comment]
@Nambukarthy, could you copy/paste all the info from the VS Output window to help us better diagnose the error?
Also, please make sure your machine fulfils all the prerequisites of the [Getting Started](https://github.com/Microsoft/WinObjC/wiki/Getting-Started) section, in particular **VS Update 2** and **Windows 10, build 10586 or higher**.

**Comment by antoine-haas** [comment]
@Nambukarthy , please reopen with more info if the issue persists with the latest release of the SDK.
