### ISSUE TITLE
UITextInput protocol not implemented

### ISSUE THREAD

**Issue by pittmab** [Microsoft/WinObjC#521]

**Comment by ArnOmsft** [comment]
This is currently stubbed out. Can you describe how this is impacting your application?
Thanks.

**Comment by pittmab** [comment]
We use this protocol to create our own custom text input widget.

On Fri, Jun 3, 2016 at 2:26 PM, Arnaud Montembault <notifications@github.com

**Comment by ArnOmsft** [comment]
We won't support this as discussed, and instead we'll provide a sample app showing how WinRT APIs can be used to achieve what you're trying to do.
Thanks.
