### ISSUE TITLE
UIResponder implementation incomplete - no call back to canBecomeFirstResponder

### ISSUE THREAD

**Issue by pittmab** [Microsoft/WinObjC#522]

**Comment by ArnOmsft** [comment]
Looking into this.

**Comment by ArnOmsft** [comment]
Can you explain what you're using this for in your app?
Thanks.

**Comment by pittmab** [comment]
I was debugging a custom widget we have and it was not being called at
all.  The default behaviour is to return NO.  Below is the Apple Docs.

Return Value

YES if the receiver can become the first responder, NO otherwise.
Discussion

Returns NO by default. If a responder object returns YES from this method,
it becomes the first responder and can receive touch events and action
messages. Subclasses must override this method to be able to become first
responder.

On Fri, Jun 3, 2016 at 3:17 PM, Arnaud Montembault <notifications@github.com

**Comment by jaredhms** [comment]
Can you please be more specific?  What type of custom widget?  Is it a custom UIView, a custom UIControl, a custom UITextField, etc?

**Comment by pittmab** [comment]
It is a custom subclass of UIView.  It provides text editing.

**Comment by ArnOmsft** [comment]
Closing this per our discussion since it does not seem to be an actual issue. Please reopen if needed.
