### ISSUE TITLE
Implement missing vImageConvert apis

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#527]
- [x] vImageConvert_ARGB8888toPlanar8
- [x] vImageConvert_Planar8toARGB8888
- [x] vImageConvert_Planar8toPlanarF
- [x] vImageConvert_Planar8toRGB888
- [x] vImageConvert_PlanarFtoPlanar8
- [x] vImageMatrixMultiply_ARGB8888
- [x] vImageUnpremultiplyData_RGBA8888

**Comment by shahmeeresmail** [comment]
Implemented as part of PR #824

**Comment by rajsesh-msft** [comment]
Thanks @shahmeeresmail
