### ISSUE TITLE
Error reading .m

### ISSUE THREAD

**Issue by evafp90** [Microsoft/WinObjC#53]
After using vsimporter, the sln is created but not compiled due to an error in CLANG file. I've followed the steps in wiki but still can't compile it. Acutally I can't apply this following step: https://github.com/Microsoft/WinObjC/wiki#item-type
thanks

**Comment by asimonov-msft** [comment]
Could you please provide more details about the error messages you're seeing?

**Comment by evafp90** [comment]
Yes, when I try to compile the .sln created by vsimporter.exe I get this error message: "Error reading 'Path\main.m'" in File "CLANG" line 1.

On the other hand, I've been unable to set the Item Type as Clang Source since the property was not appearing...

**Comment by asimonov-msft** [comment]
Please try to build and run samples\WOCCatalog from the pre-built SDK archive and let me know the result.

**Comment by evafp90** [comment]
I first tried that one and worked fine until I got an Unhandled exception (about 3 minuts after the execution).

**Comment by ArnOmsft** [comment]
Are you still facing this error?

**Comment by evafp90** [comment]
Have you updated the library or something? I haven't tried since when I posted the issue

**Comment by ArnOmsft** [comment]
We're releasing a new version of the SDK almost every week, the last one was released on 12/3 and a new release will go out today. Check here for the last version: https://github.com/Microsoft/WinObjC/releases.
Could you try again with the last version?
Thanks.

**Comment by ArnOmsft** [comment]
Hi, could you confirm if you were able to repro this issue with one of the most recent release?
Thanks.

**Comment by ArnOmsft** [comment]
Closing this since we cannot repro this issue. Please do open a new issue in case you encounter the error again. Thanks.
