### ISSUE TITLE
Unable to resolve an external symbol _inet_ntop

### ISSUE THREAD

**Issue by yaveymao** [Microsoft/WinObjC#533]
Unable to resolve an external symbol _inet_ntop, which is referenced in the function _NSMakeRange

I have already added 
# pragma comment(lib, "Ws2_32.lib")

,but still got a link error.
which lib file should I add to my project. Thanks.

**Comment by rajsesh-msft** [comment]
I am not able to repro this, can you provide a code sample or snippet that reproduces this issue?

**Comment by yaveymao** [comment]
hello, I can repro this with these steps:
1) open WinObjc sample project "WOCCatalog"
2) add some head files, and add ‘Ws2_32.lib’ for for link
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#if defined(WINOBJC)
#pragma comment(lib, "Ws2_32.lib")
#endif
3) in " application:didFinishLaunchingWithOptions:" add testing code:
	// testing code
	char addrBuf[INET_ADDRSTRLEN];
	char testData[100];
	inet_ntop(AF_INET, testData, addrBuf, (socklen_t)sizeof(addrBuf));
	////////////
then I can get a link error about '_inet_ntop'
