### ISSUE TITLE
Dealloc of NSOperationQueue causes crash

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#539]
Releasing an NSOperationQueue instance results in a crash.

To reproduce:

```
NSOperationQueue *queue = [[NSOperationQueue alloc] init];
queue = nil;
```

Attached is a screen grab of the stack trace.

![screenshot 2016-06-08 08 21 52](https://cloud.githubusercontent.com/assets/237035/15885983/517a9f96-2d52-11e6-9b76-8253b4dd1e3d.png)

**Comment by rajsesh-msft** [comment]
pthread_mutex_destroy() must check for PTHREAD_MUTEX_INITIALIZER before destroying it.  in a case like this, the Critical section is never initialized.  See 1c8165a72b22c60e9f025bc09631c41fb060a93d

**Comment by jofre-ms** [comment]
The fix is coming soon!
