### ISSUE TITLE
[QuartzCore][CoreAnimation] Transform3D rotation direction incorrect

### ISSUE THREAD

**Issue by shahmeeresmail** [Microsoft/WinObjC#544]
Transform matrix for rotation is a matrix which rotates in the opposite direction than it should.

Example:
CATransform3D rot = CATransform3DRotate(CATransform3DIdentity, M_PI_2, 0.0f, 0.0f, 1.0f);

Expected output: Rotates 90 degrees clockwise over z axis.
Actual output: Rotates 90 degrees counter-clockwise over z axis

I verified the expected output is what is output on iOS.

**Comment by rajsesh-msft** [comment]
Thanks @shahmeeresmail for fixing this.
