### ISSUE TITLE
[QuartzCore][CoreAnimation] Transform3D operations applied out of order

### ISSUE THREAD

**Issue by shahmeeresmail** [Microsoft/WinObjC#545]
When using some functions to perform a transformation on an existing matrix, it is applied out of order. This has been observed in CATransform3DRotate. The transform should take affect before any operation specified by the input matrix.

Example:
CATransform3D trans = CATransform3DMakeTranslation(5.0f, 5.0f, 5.0f);
CATransform3D transRot = CATransform3DRotate(trans, M_PI_2, 0.0f, 0.0f, 1.0f);

Actual transRot: Matrix that translates <5, 5, 5> then rotates 90deg over Z-axis.
Expected transRot: Matrix that rotates 90deg over Z-axis then translates <5,5,5>

Verified that the expected output matches the output produced on iOS.

**Comment by rajsesh-msft** [comment]
Thanks @shahmeeresmail for fixing this.
