### ISSUE TITLE
delegate "textField:shouldChangeCharactersInRange:replacementString:" not called

### ISSUE THREAD

**Issue by yaveymao** [Microsoft/WinObjC#555]
- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string

not called when inputing text in the textfield

**Comment by ArnOmsft** [comment]
Thanks for the feedback, we'll add support for this in the coming weeks

**Comment by ArnOmsft** [comment]
Support for this was added earlier, closing this.
