### ISSUE TITLE
NSUserDefaults synchronize blocks main thread

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#561]
Synchronizing NSUserDefaults is always [done on the main thread](https://github.com/Microsoft/WinObjC/blob/master/Frameworks/Foundation/NSUserDefaults.mm#L379-L384), and can easily take several hundred milliseconds or seconds depending of the size of the user defaults. This can cause the app to noticeably hang after setting a user defaults value.

Following is an example synchronizing 500 user defaults entries, which takes roughly 1 second on our development machines.

```objc
for (int i = 0; i < 500; i++) {
	[[NSUserDefaults standardUserDefaults] setValue:@(i) forKey:[NSString stringWithFormat:@"Test%d", i]];
}

NSTimeInterval start = [NSDate timeIntervalSinceReferenceDate];
[[NSUserDefaults standardUserDefaults] synchronize];
NSTimeInterval end = [NSDate timeIntervalSinceReferenceDate];

NSLog(@"Synchronize took %lf s", end-start);
```

**Comment by jofre-ms** [comment]
Reworked this to use asynchronous file writes, which reduced synchronize time for your example on my machine from approximately 0.45 seconds to 0.04 seconds.
