### ISSUE TITLE
MSB3073 The command "..\Xib2Nib.exe" "..\MainWindow.xib" "Debug\MainWindow.nib" exited with code -1

### ISSUE THREAD

**Issue by logueBT** [Microsoft/WinObjC#562]
Trying this on an app for the first time and I'm seeing this error:
MSB3073 The command "..\bin\Xib2Nib.exe" "..\MainWindow.xib" "Debug\MainWindow.nib" exited with code -1

What should I do? I've attached the file.

[MainWindow.zip](https://github.com/Microsoft/WinObjC/files/318007/MainWindow.zip)

**Comment by Ramu-msft** [comment]
Support for <Window> has been added to xib2nib and is available in the latest SDK.
