### ISSUE TITLE
Can not open libz.1.1.3.lib library. (pre-release June 9,2016)

### ISSUE THREAD

**Issue by ajitkumar1** [Microsoft/WinObjC#565]
Can not open libz.1.1.3.lib library error.
What is the step I need to do to fix the error.

**Comment by weswmsft** [comment]
I need some clarification on this issue. Can you explain what you mean by "Can not open libz.1.1.3.lib "??

**Comment by weswmsft** [comment]
I still do not understand your problem. Please provide the exact steps you are taking and the failure that happens. I simply don't have enough information right now.
