### ISSUE TITLE
Is there a support react native?

### ISSUE THREAD

**Issue by bbayraktutar** [Microsoft/WinObjC#567]
I get this error 'RCTRootView.h' file not found	. 
Is there a support react native?

**Comment by rajsesh-msft** [comment]
This is a duplicate of #397 - react native should now support native UWPs without requiring the islandwood bridge.  Have you looked at this [blog](https://blogs.windows.com/buildingapps/2016/04/13/react-native-on-the-universal-windows-platform/)?

**Comment by rajsesh-msft** [comment]
Closing this issue as dupe of #397

**Comment by bbayraktutar** [comment]
I keep getting the same error
