### ISSUE TITLE
KVO NSKeyValueObservingOptionInitial change event passes empty change dictionary. 

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#568]
If you add an KVO observer using the `NSKeyValueObservingOptionInitial` option, the generated event contains an empty change dictionary and does not include a `NSKeyValueChangeKindKey`.

The change event generated by `NSKeyValueObservingOptionInitial` should supply a change dictionary containing all the options specified in the addObserver call.

For example, adding the observer...

```[object addObserver:self forKeyPath:@"items" options:NSKeyValueObservingOptionNew | NSKeyValueObservingOptionInitial context:nil];```

...should supply an initial change dictionary containing:
```
{
    kind = 1;
    new = ... 
}
```

**Comment by technotrance** [comment]
I know my programme is good but its a bit rude always asking for diagnostics information when no one has paid any money for the completed work just a bit rude

**Comment by technotrance** [comment]
And new is illegal it is patented and protected by law and is not cla or docusigned

**Comment by DHowett** [comment]
It looks like the only thing we're missing is `kind` (d'oh!) -- if you request `NSKeyValueObservingOptionNew` you should be getting `{ new = ... }`.

**Comment by DHowett-MSFT** [comment]
It looks like the only one we're missing here is the `kind` key, right? `new` should be getting propagated.

**Comment by rupertdaniel** [comment]
Yeah you're right the `new` key is supplied so it's just the `kind` key that is missing.

**Comment by technotrance** [comment]
try changing the 32 bit graphics to the 64 bit graphics
