### ISSUE TITLE
NSURLSessionTask taskIdentifier is always 0.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#570]
NSURLSessionTask taskIdentifier is currently always 0.

Each instance of an  NSURLSessionTask should have a taskIdentifier unique within the context of it's NSURLSession.

AFNetworking relies on this taskIdentifier to link session tasks with callbacks, therefore AFNetworking does not behave correctly if there is more than one request in progress at a time.

**Comment by triplef** [comment]
Thanks for the quick fix! The commit doesn’t seem to be in the master branch yet though – do you have an ETA when it will be in the release?

**Comment by rajsesh-msft** [comment]
Due to some strangeness i can't explain, this wasn't in the latest release. It should be available in our next release (later this week).
