### ISSUE TITLE
Calling [NSMutableArray insertObjects:atIndexes:] in the context of init causes a crash on object dealloc.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#574]
If you call `[NSMutableArray insertObjects:atIndexes:]` in the init method of an object, the app will crash when that object is released.

Take this example class:

```
@interface TestObjectA ()

@property (nonatomic, strong) NSMutableArray *array;

@end

@implementation TestObjectA

- (instancetype)init
{
	if (self = [super init]) {
		self.array = [NSMutableArray array];
		[self.array insertObjects:@[@"MOOSE"] atIndexes:[NSIndexSet indexSetWithIndex:0]];	
	}
}

@end
```

If you create an instance of the object you get a crash when it is released...

```
TestObjectA *a = [[TestObjectA alloc] init]

// Then let ARC release the object when it goes out of scope
```

Attached is a screen grab of the stack trace.
![screenshot 2016-06-22 16 38 20](https://cloud.githubusercontent.com/assets/237035/16273007/d2632920-3897-11e6-92b8-110d4b13cccc.png)

**Comment by technotrance** [comment]
Email me directly I don't understand that when I uncommit my programme does the effect of discontinuing independand programme opperation I can discreatly allow you access to the actual core if need be mail bk plz

**Comment by DHowett** [comment]
Interesting! If `array->isa` is bad, we'll bomb out [here in arc.m:228](https://github.com/Microsoft/libobjc2/blob/master/arc.m#L228) when we try to release it through an ARC `storeStrong`. The curious thing is that `isa` was once fine.

Can you see if `isa` is `0xdddddddd` or `0xcdcdcdcd`? That could point to an accidental early deallocation.

**Comment by rupertdaniel** [comment]
Yeah looks like testObject `isa` is `0xdddddddd` after creation.

<img width="1102" alt="screenshot 2016-06-22 18 43 45" src="https://cloud.githubusercontent.com/assets/237035/16277123/7e897f40-38a9-11e6-9e90-445e149dfefb.png">

**Comment by DHowett-MSFT** [comment]
Is the representative snippet in your initial report totally accurate? It looks like it's missing a `return self;`, so we may just be getting garbage in `eax`.

**Comment by rupertdaniel** [comment]
Argh good catch, it was a mistake in the demo code :-( Let me get back to you on this, as the demo code was an attempt to simplify a crash we are seeing in the main app.

**Comment by rupertdaniel** [comment]
Sorry false alarm on this one.

Turns out it is https://github.com/Microsoft/WinObjC/issues/577 that is causing our crash.
