### ISSUE TITLE
'sys/types.h' file not found

### ISSUE THREAD

**Issue by appeon** [Microsoft/WinObjC#58]
I use winobjc prebuilt  tool to convert to  winstore10 project successfully, but compile the project have a error : CoreFoundation/CoreFoundation.h(11,10): fatal error : 'sys/types.h' file not found

**Comment by asimonov-msft** [comment]
@appeon What is the project type that causes this error - Application or Static Library?

**Comment by appeon** [comment]
Static Library

**Comment by asimonov-msft** [comment]
@appeon How old is the SDK that you are using? This sounds similar to a problem that should have been fixed by 2d236ea858d0e655537d956a4719a3f0260ba388

**Comment by appeon** [comment]
we use  a few third party libraries in project, these libraries are who to compile?

**Comment by appeon** [comment]
I don't build the SDK, I use the SDK itself , the SDK release date is 2015-8-5

**Comment by appeon** [comment]
The latest version of SDK has been fixed? I use  the Folder 'WinObjC-master\bin\ ' version to compile, the problem still exists: WinObjC-master\include\CoreFoundation/CoreFoundation.h(11,10): fatal error : 'sys/types.h' file not found

**Comment by asimonov-msft** [comment]
Please open the static library vcxproject file, and check that the WindowsTargetPlatformVersion and WindowsTargetPlatformMinVersion properties are specified:
```
<PropertyGroup Label="Globals">
  ...
  <WindowsTargetPlatformVersion>10.0.10240.0</WindowsTargetPlatformVersion>
  <WindowsTargetPlatformMinVersion>10.0.10240.0</WindowsTargetPlatformMinVersion>
  ...
</PropertyGroup>
```
If the properties are not specified, that means that you are somehow using an older version of the SDK.

Please also check to see that the Windows SDK include directory - **C:\Program Files (x86)\Windows Kits\10\Include** contains a **10.0.10240.0** directory. It is possible that you are using a pre-release version of Visual Studio 2015 (10.0.10150.0) which would cause the error you are seeing.

**Comment by greenhippie** [comment]
I ran into this same issue, the solution for me was to right-click on the solution, click 'Retarget solution' and select 10.0.10240.0 from the Target Platform Version drop-down (make sure all the projects were checked) and click OK.

**Comment by keluo-ms** [comment]
@greenhippie Let us know if you're still experiencing this issue. Apologies for the late response, we just went through our entire backlog and you should be seeing faster response times in the future :smile:
