### ISSUE TITLE
Cases where UITextField backgroundColor (upon focus / mouseover) should be transparent but isn't

### ISSUE THREAD

**Issue by ehren** [Microsoft/WinObjC#590]
The default behaviour of the underlying Xaml TextBox of UITextField - to use a subtle highlight on mouse over and upon gaining focus - can be disabled by setting the background color to clear.

However, there are cases where, though the background color is ostensibly set to clear (and this is evident from visual inspection of the app), the highlight on mouse over or gaining focus ends up appearing in solid white FFFFFF.

I don't have a clean sample reproducing the issue though. 

Also making the following modifications (inspired by this wp7 suggestion: http://stackoverflow.com/questions/8096805/change-focused-textbox-background-foreground-in-wp7/16814758#16814758) doesn't really improve things:

```
diff --git a/Frameworks/UIKit/UITextField.mm b/Frameworks/UIKit/UITextField.mm
index 4cf357e..4daa2cf 100644
--- a/Frameworks/UIKit/UITextField.mm
+++ b/Frameworks/UIKit/UITextField.mm
@@ -969,6 +969,8 @@ NSString* const UITextFieldTextDidEndEditingNotification = @"UITextFieldTextDidE
                 [strongSelf.delegate textFieldDidBeginEditing:strongSelf];
             }

+            [strongSelf setBackgroundColor:[strongSelf backgroundColor]];
+
             // more notification
             dispatch_async(dispatch_get_main_queue(),
                            ^{
@@ -1005,6 +1007,8 @@ NSString* const UITextFieldTextDidEndEditingNotification = @"UITextFieldTextDidE
                 [strongSelf.delegate textFieldDidEndEditing:strongSelf];
             }

+            [strongSelf setBackgroundColor:[strongSelf backgroundColor]];
+
             // more notification
             dispatch_async(dispatch_get_main_queue(),
                            ^{
@@ -1041,6 +1045,36 @@ NSString* const UITextFieldTextDidEndEditingNotification = @"UITextFieldTextDidE
     }];
 }

+- (void)_setupPointerEnteredEventHandler:(WXCControl*)control {
+    __weak UITextField* weakSelf = self;
+
+    [control addPointerEnteredEvent:^void(RTObject* sender, WUXIPointerRoutedEventArgs* e) {
+        __strong UITextField* strongSelf = weakSelf;
+        if (strongSelf) {
+            [strongSelf setBackgroundColor:[strongSelf backgroundColor]];
+
+            e.handled = YES;
+        } else {
+            e.handled = NO;
+        }
+    }];
+}
+
+- (void)_setupPointerExitedEventHandler:(WXCControl*)control {
+    __weak UITextField* weakSelf = self;
+
+    [control addPointerExitedEvent:^void(RTObject* sender, WUXIPointerRoutedEventArgs* e) {
+        __strong UITextField* strongSelf = weakSelf;
+        if (strongSelf) {
+            [strongSelf setBackgroundColor:[strongSelf backgroundColor]];
+
+            e.handled = YES;
+        } else {
+            e.handled = NO;
+        }
+    }];
+}
+
 // Helper to Initialize textbox
 - (void)_initTextBox {
     self->_textBox = [WXCTextBox make];
@@ -1082,6 +1116,8 @@ NSString* const UITextFieldTextDidEndEditingNotification = @"UITextFieldTextDidE
     [self _setupControlGotFocusHandler:_textBox];
     [self _setupControlLostFocusHandler:_textBox];
     [self _setupControlKeyDownHandler:_textBox];
+    [self _setupPointerEnteredEventHandler:_textBox];
+    [self _setupPointerExitedEventHandler:_textBox];
 }

 // Helper to Initialize passwordBox
```

I should note that with the above modifications, I've noticed (in the case of my backgroundColor == clear text field) that the highlight color will change to the proper clear color from white when minimizing and re-entering the app (while the textfield still has focus). So I think there's a lower level issue here that can't just be addressed by changes in UITextField.mm.

**Comment by ArnOmsft** [comment]
Hi ehren, are you still able to repro this behavior and could you share the code you're using to do that?
Also, by " the highlight on mouse over or gaining focus ends up appearing in solid white FFFFFF.", do you mean the background color becomes white FFFFFF instead of remaining clear as expected, or is the text itself actually turning white?
Thanks.

**Comment by ehren** [comment]
Hi @ArnOmsft 

It looks like I was mistaken in the above description with one point:

- a UITextField with clear background color will not result in a background color change upon mouseover (it stays clear).

However, I was correct that a UITextField with clear background will result in a background color change (to FFFFFF) on gaining focus.

To test you can modify the WOCCatalog app with the below patch.

```
diff --git a/samples/WOCCatalog/WOCCatalog/TextFieldsViewController.m b/samples/WOCCatalog/WOCCatalog/TextFieldsViewController.m
index 8a9b953..bf262eb 100644
--- a/samples/WOCCatalog/WOCCatalog/TextFieldsViewController.m
+++ b/samples/WOCCatalog/WOCCatalog/TextFieldsViewController.m
@@ -190,6 +190,19 @@ static const CGFloat c_labelFontSize = 17.0f;
                                                borderStyle:UITextBorderStyleLine
                                            backgroundImage:[UIImage imageNamed:@"photo1.jpg"]]];
 
+    // Row 12. Clear text field
+    [_textFields addObject:[self _createTextFieldWithColor:[UIColor blackColor]
+                                                background:[UIColor clearColor]
+                                           secureTextEntry:NO
+                                               placeHolder:@"Clear background color"
+                                              keyboardType:UIKeyboardTypeDefault
+                                               borderStyle:UITextBorderStyleNone
+                                             textAlignment:UITextAlignmentLeft
+                                         spellCheckingType:UITextSpellCheckingTypeNo]];
+
+    // change background to make color issues more evident
+    self.view.backgroundColor = [UIColor greenColor];
+
     [self tableView].allowsSelection = NO;
 }
 
```

This will be the result when the newly added text field (with clear background color) gains focus:

![screen shot 2016-10-04 at 11 59 16 am](https://cloud.githubusercontent.com/assets/252343/19082264/64299e72-8a2b-11e6-8031-b1deaf04315b.png)

Note: I've taken more of a look at some of these textfield issues recently. The above problem is due to the setup in Frameworks/UIKit.Xaml/TextBox.xaml

I've yet to find the right modifications to TextBox.xaml that would support a similar config to the default UITextField on iOS (in particular, to disable appearance changes on focus gain, disabled status, etc)

Also, independent of this problem of finding the right xaml markup to support a 'vanilla UITextField' (no focus highlighting etc), it would probably be nice longer term to allow users to specify their own xaml template for a given UITextField (perhaps on an instance by instance basis). Because in some cases I like the current behaviour (with color changes on mouseover etc) - just not everywhere.

**Comment by tadam-msft** [comment]
Decision has been made to default to the Windows behavior for UITextField
