### ISSUE TITLE
The command "C:\WinObjC\msvc\..\bin\Xib2Nib.exe" exited with code -1073741819

### ISSUE THREAD

**Issue by mashedkeyboard** [Microsoft/WinObjC#591]
Hi all,

Having an issue trying to convert [the Mattermost iOS app](https://github.com/mattermost/ios) over to UWP through Islandwood. Getting the following error:

`MSB3073 The command ""C:\WinObjC\msvc\..\bin\Xib2Nib.exe" "..\..\Mattermost\Base.lproj\Main.storyboard" "Debug\Base.lproj\Main.storyboardc"" exited with code -1073741819.`

Not being an iOS developer by trade, I've not got a clue how I would even start going about resolving this. Can anyone point me in the right direction?

Thanks!

Curtis

**Comment by tadam-msft** [comment]
The issue appears to have happened while copying files to output directory, clear the output directory or change permissions on the file and it should be good to go.
