### ISSUE TITLE
Internal WYPopoverController ivar with garbage value (forcing #ifdef workaround)

### ISSUE THREAD

**Issue by ehren** [Microsoft/WinObjC#597]
It's not totally clear why |viewContentInsets| property of WYPopoverBackgroundView has a garbage (not necessarily uninitialized) value when building a DEBUG build of the bridge. This will be worked around with a #ifdef in current code. See https://github.com/ehren/WYPopoverController/commit/721be41ad48cb4b337b5fa2dca98adbf8723e5b6 for this workaround.

**Comment by jaredhms** [comment]
@DHowett-MSFT; it sounds like this is potentially an issue with kvo.

**Comment by rajsesh-msft** [comment]
Closing since this is already merged.
