### ISSUE TITLE
Missing OpenGLES?

### ISSUE THREAD

**Issue by joewood** [Microsoft/WinObjC#6]
I'm seeing errors that OpenGLES.lib is missing. I can see libGLESv2.lib as a prebuild dependency. Am I missing a pre-req?

**Comment by davelamb** [comment]
I'd wager you haven't built //WinObjC/build/build(.W*).sln yet. That will build all the prerequisites for the samples.

**Comment by s5msft** [comment]
Alternatively, you can download a prebuilt SDK -- check under "Releases".

**Comment by joewood** [comment]
Thanks, that fixed it. Is that a missing step in the readme?

**Comment by davelamb** [comment]
The quick start instructions in the readme mention extracting the SDK and building the sample from there. It's assumed if you're starting from source you won't get any premade binaries. See the wiki for more complete build instructions.

**Comment by IvanKarpan** [comment]
OK, so I did build the package and extracted it to a path, but how do I set up WOCCatalog to actually look at the said path for the libraries?
Na magic is happening, getting the following error:
`LINK : fatal error LNK1181: cannot open input file 'OpenGLES.lib'`

I am an iOS developer absolutely new to VS and this instruction - IMO - is worth having in the README...

**Comment by IvanKarpan** [comment]
OK, got it, so you need to open the sample from the built SDK folder, not the sources, my bad.

**Comment by ninjanpotter** [comment]
1st Question: First time while building the build file , it successfully built and generated the sdk. And everything went fine. Now again I built the build . Its showing this error.

Error	: cannot open input file 'StarboardWin32.lib'	Package	D:\PortingPOC\WinObjC-master\build\Package\LINK	1

2nd Question: I tried building the sample projects , it worked fine. Now using vsimporter.exe from cmd , I got the solution file for my ios project but it throws the following error.

Error	LNK1181	cannot open input file 'StarboardXaml.lib'	
	D:\PortingPOC\WinObjC-master\build\SDKPackage\Release\samples\trialView\trialView.vsimporter\trialView-WinStore10\LINK	1

**Comment by pkamb** [comment]
I'm seeing this same `cannot open input file 'OpenGLES.lib'` error.

 > I'd wager you haven't built //WinObjC/build/build(.W*).sln yet. 

The above step is not in the readme?

I followed these directions from the readme:

1. Extract the SDK zip file to a local directory
1. Navigate to winobjc/samples/WOCCatalog in the extracted directory
1. Double-click on WOCCatalog-WinStore10.sln to open in VS2015
1. In VS2015 right-click on the WOCCatalog (Universal Windows) project
1. Select Set as StartUp project
1. Use Ctrl-F5 to build and run the app

**Comment by AtanasC** [comment]
Thank you so much!
