### ISSUE TITLE
<CoreServices/CoreServices.h>

### ISSUE THREAD

**Issue by tianguanghui** [Microsoft/WinObjC#605]
when i port my iOS project,I got the error "'CoreServices/CoreServices.h' file not found" in the file "AFHTTPSessionManager.h",the error code-->`#import <CoreServices/CoreServices.h>`

**Comment by rajsesh-msft** [comment]
This is really a bug in AFHTTPSessionManager.h

#if TARGET_OS_IOS || TARGET_OS_WATCH || TARGET_OS_TV
#import <MobileCoreServices/MobileCoreServices.h>
#else
#import <CoreServices/CoreServices.h>
#endif

The first line should also include WINOBJC.  We do have MobileCoreServices.h

**Comment by rajsesh-msft** [comment]
Closing since this is external.

**Comment by ad87mb** [comment]
I added the word "WINOBJC" in the first line and I do not recognize the code of the library
