### ISSUE TITLE
When can Islandwood apps be submitted to the Win App store?

### ISSUE THREAD

**Issue by diffent** [Microsoft/WinObjC#607]
hi, is it possible to submit apps to the win app store now if they are buit w/ the current version of the "project islandwood" WinObjC porting tool?  If not, what is the estimated calendar time we can submit?

**Comment by rajsesh-msft** [comment]
Yes, if your app builds and runs using the bridge, you should be able to submit it to the store.  In fact, there are apps in store that are built using winobjc.  Please note that the bridge is work in progress, so you may not have all the APIs that you need.

**Comment by diffent** [comment]
that is great, thanks.  is there a way you could tell us some example apps that are in the store built w/ winObjC so we can examine the results?

**Comment by rajsesh-msft** [comment]
[here](https://blogs.windows.com/buildingapps/2016/06/03/bringing-pori-fashion-show-to-windows-using-windows-bridge-for-ios-part-2/) is a blog post on an app that used the bridge.

**Comment by diffent** [comment]
Hi again, is there a list of iOS classes that are supported at a high level?
In particular I am looking for CoreGraphics (CGContext and related "Quartz 2D" drawing functions). 
I am not seeing it here:  https://github.com/Microsoft/WinObjC/wiki/Roadmap

**Comment by cre8ivepark** [comment]
Here is another my app used Windows Bridge for iOS:
https://www.microsoft.com/en-us/store/apps/typography-insight/9nblggh4qrs5
http://typeinsight.org

**Comment by eDameXxX** [comment]
@cre8ivepark BTW, do you have any plans for bringing this app to Windows Mobile?

**Comment by diffent** [comment]
Thanks, this is pretty interesting, looking fwd to checking out this app.

**Comment by antoine-haas** [comment]
Closing this issue since the question was answered.
