### ISSUE TITLE
Usage of native headers in the 'include' folder

### ISSUE THREAD

**Issue by vmagaziy** [Microsoft/WinObjC#61]
Headers for different frameworks in the 'include' folder have different copyrights and different content. For instance, headers for *libdispatch* have _native_ headers whereas headers for *UIKit* are from _The Inconfactory_ and for *Foundation* they are from _Christopher J. W. Lloyd_.

In order to make the code originally written for iOS/OS X compile with *WinObjC* SDK these headers are to be the same with ones shipped by Apple in corresponding version of SDK and the support of particular iOS/OS X SDKs is to be advertised. For instance, *WinObjC 1.0 SDK* has headers for *iOS 8.4* and all supplementary implementations correspond to these headers, so it can be stated that *WinObjC 1.0 SDK* is compatible with *iOS 8.4 SDK* with a set of possible limitations listed; at the same time for instance *WinObjC 1.4 SDK* is compatible with *iOS 9.0 SDK* with corresponding limitations, etc.

Does it make sense from your prospective? Please confirm.

**Comment by s5msft** [comment]
Directly including Apple headers in a third-party SDK is not possible.
