### ISSUE TITLE
Glob Paths Not Working in Clang

### ISSUE THREAD

**Issue by joewood** [Microsoft/WinObjC#62]
It looks like the Clang compiler doesn't work with paths with glob patterns, e.g. `..\include\**`
**vsimporter** converts these over from the xcode projects.

**Comment by asimonov-msft** [comment]
Expansion of the /** pattern is a feature of Xcode, rather than clang. Adding support for this to our build system is on my to-do list.

**Comment by asimonov-msft** [comment]
Support for glob paths in "Include Paths" and "User Include Paths" added by e1ae9ce6d3e3e0a2ed570ccbf43762da1dbd1c58.

**Comment by joewood** [comment]
Seems to work ! Thanks !
