### ISSUE TITLE
Paths copied out from a Cairo Context don't have matching elements to the path that was added.

### ISSUE THREAD

**Issue by JSavageVectorform** [Microsoft/WinObjC#621]
When Cairo adds a path to the cairo context or when you copy a path from the cairo context additional elements are being added. Currently this has only been reproduced with paths that use 'CGPathAddEllipseInRect’ or 'CGPathAddQuadCurveToPoint’. If you examine the original CGPath object after you add it to the context and make a copy from CGContextCopyPath, the original object does not have the extra element that the copy has. The CGPath will be correct before it enters the cairo context but incorrect when it is copied out from it.

**Original Path Elements of GPathAddQuadCurveToPoint Path**
kCGPathElementMoveToPoint
( 400.000000, 400.000000 )
kCGPathElementAddQuadCurveToPoint
( 140.000000, 250.000000 )
( 110.000000, 180.000000 )

**Elements after copying from Cairo Context**
kCGPathElementMoveToPoint
( 400.000000, 400.000000 )
kCGPathElementAddCurveToPoint
( 226.667969, 300.000000 )
( 130.000000, 226.667969 )
( 110.000000, 180.000000 )

**Original Path Elements of CGPathAddEllipseInRect Path**
kCGPathElementMoveToPoint
                ( 240.000000, 60.000000 )
kCGPathElementAddCurveToPoint
                ( 240.000000, 71.045692 )
                ( 195.228485, 80.000000 )
                ( 140.000000, 80.000000 )
kCGPathElementAddCurveToPoint
                ( 84.771523, 80.000000 )
                ( 40.000000, 71.045692 )
                ( 40.000000, 60.000000 )
kCGPathElementAddCurveToPoint
                ( 40.000000, 48.954304 )
                ( 84.771523, 40.000000 )
                ( 140.000000, 40.000000 )
kCGPathElementAddCurveToPoint
                ( 195.228485, 40.000000 )
                ( 240.000000, 48.954304 )
                ( 240.000000, 60.000000 )
kCGPathElementCloseSubpath
 
**Elements after copying from Cairo Context**
kCGPathElementMoveToPoint
                ( 240.000000, 60.000000 )
kCGPathElementAddCurveToPoint
                ( 240.000000, 71.046875 )
                ( 195.226563, 80.000000 )
                ( 140.000000, 80.000000 )
kCGPathElementAddCurveToPoint
                ( 84.773438, 80.000000 )
                ( 40.000000, 71.046875 )
                ( 40.000000, 60.000000 )
kCGPathElementAddCurveToPoint
                ( 40.000000, 48.953125 )
                ( 84.773438, 40.000000 )
                ( 140.000000, 40.000000 )
kCGPathElementAddCurveToPoint
                ( 195.226563, 40.000000 )
                ( 240.000000, 48.953125 )
                ( 240.000000, 60.000000 )
kCGPathElementCloseSubpath
kCGPathElementMoveToPoint
                ( 240.000000, 60.000000 )

Related to Pull Request #620

**Comment by rajsesh-msft** [comment]
Kicking the can down the road.  When we move CG to D2D, we don't have to rely on Cairo.

**Comment by rajsesh-msft** [comment]
With our plan to move Core graphics to D2D, we won't be fixing it.  Our goal would be to match reference platform implementation.
