### ISSUE TITLE
DatePicker graphical corruption

### ISSUE THREAD

**Issue by shahmeeresmail** [Microsoft/WinObjC#622]
In WOCCATALOG on Windows, the date picker has a checkered background for date and striped background for time. On iOS it has a white background for both.

This is observed in the master and dev branches.

Below is a cropped screenshot showing the issue.
![datepickercorruption](https://cloud.githubusercontent.com/assets/17790501/16666811/1db985c0-443e-11e6-9739-4c7575df2643.png)

**Comment by Ramu-msft** [comment]
The fix is available in 0.1 Preview (July 15, 2016) release.
