### ISSUE TITLE
CoreGraphics: ByteOrder & AlphaPosition not implemented correctly

### ISSUE THREAD

**Issue by shahmeeresmail** [Microsoft/WinObjC#639]
- During context or image create, byteOrder is ignored and alpha position is used incorrectly to determine how the imageBacking is created. 
- Alpha position incorrectly determined and returned in context/image accessor functions
- ColorFormat naming scheme inconsistently uses bigEndian and littleEndian to indicate byte ordering and in some cases specifies the wrong byte ordering completely.

**Comment by rajsesh-msft** [comment]
@shahmeeresmail thanks for reporting and fixing this.
