### ISSUE TITLE
External 2D Engine

### ISSUE THREAD

**Issue by xGEKKOx** [Microsoft/WinObjC#64]
Dear Staff,
what about if i import .a lib for a 2D engine? ...
Do you think it could work if the lib has all framework it need to run inside iOS?
I think there must be no error.

Anyway i will test much and i will update you all if interested in this question.
Not a real issue, but is very important for me as game developer.

**Comment by rajsesh-msft** [comment]
@xGEKKOx since winobjc is a source code solution, the lib you are including must be compiled for windows.  If it is an OBJC library, it needs to be recompiled with winobjc. Closing this issue as this is more of a question.
