### ISSUE TITLE
CoreGraphics: CGColorSpace incorrectly coupled with ColorFormat

### ISSUE THREAD

**Issue by shahmeeresmail** [Microsoft/WinObjC#640]
Right now when a color space is created, the format is determined. The format effectively also specifies the byteOrder and alphaPosition (which are both flags of bitmapInfo). However, imageCreate or contextCreate, bitmapInfo is also specified and there may be a conflict. If there is a conflict between the colorSpace format and the bitmapInfo then the colorSpace format will prevail (incorrectly).

ColorSpace should be paired with a colorSpaceModel at ColorSpaceCreate time and the ColorFormat should be determined at imageCreate or contextCreate time after taking into consideration: colorSpace, bitsPerPixel, bitsPerComponent and bitmapInfo (effectively alphaPosition + byteOrder + floatIntSelectorBit)

**Comment by rajsesh-msft** [comment]
@shahmeeresmail thanks for reporting and fixing this!
