### ISSUE TITLE
Binary property lists and keyed archives from the reference platform may behave badly

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#649]
Due to the lack of a generic umbrella bridged type, `CFKeyedArchiverUID`s, which is used in keyed archives from iOS and OS X, will not be deserialized properly. This will result in a crash when you attempt to use `NSKeyedUnarchiver` or `NSPropertyListSerialization` with archives created on the reference platform.

Normal property lists from iOS and OS X are not affected, as they will not contain UID objects.

XML archives are not affected, as they encode UIDs via `NSDictionary` (as `<dict><key>CF$UID</key><integer>1</integer></dict>`).

Reproduction case:

``` objc
// The only way to represent a raw CFKeyedArchiverUID is via binary property list.
// This property list contains:
// 0x00:        u8[8] header                       (bplist00)
// -- object table --
// 0x08: UID (0x80 0xFF)
// -- offset table --
// 0x0A: 0x08
// -- plist trailer --
// 0x0B - 0x0F: u8[5] unused                       (0x00 * 5)
// 0x10:        u8    sort version                 (0x00)
// 0x11:        u8    size of offset table entries (0x01)
// 0x12:        u8    size of embedded objects     (0x01)
// 0x13 - 0x1A: u64   number of objects            (0x01)
// 0x1B - 0x22: u64   toplevel object              (0x00)
// 0x23 - 0x2A: u64   offset to offset table       (0x0A)

const char rawPlist[] = {
    0x62, 0x70, 0x6c, 0x69, 0x73, 0x74, 0x30, 0x30, 0x80, 0xff, 0x08, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a
};
NSData* plistData = [NSData dataWithBytes:rawPlist length:_countof(rawPlist)];
NSObject* UID = [NSPropertyListSerialization propertyListFromData:plistData mutabilityOption:0 format:nullptr errorDescription:nullptr];
```

**Comment by DHowett-MSFT** [comment]
This is no longer a crash, but it still represents a small compliance issue (some number of binary property lists, which we claim to support, will not act appropriately.)

**Comment by rajsesh-msft** [comment]
@DHowett-MSFT, we only don't support binary property lists created on reference platform, right? I don't think binary compatibility is required in this case.
