### ISSUE TITLE
Xib file conversion failed

### ISSUE THREAD

**Issue by Binu-Mathew** [Microsoft/WinObjC#65]
Failed to convert a project that is using interface builder (XIB) for rendering views. Please let me know the whether the WinObjC is supporting iOS projects having Xib files.

**Comment by SquaredTiki** [comment]
See #27

**Comment by Ramu-msft** [comment]
WinObjC SDK does support iOS projects with XIB files. This is done using the Xib2Nib tool. This is still under development so it may not support all types. If you encounter any problems, please send the error details.
