### ISSUE TITLE
ANNOUNCEMENT: UIKit, meet XAML. XAML, meet UIKit.

### ISSUE THREAD

**Issue by nicholasgerard-msft** [Microsoft/WinObjC#654]
[Read about our new approach to implementing UIKit on the Building Apps for Windows blog.](https://blogs.windows.com/buildingapps/2016/07/15/windows-bridge-for-ios-uikit-meet-xaml-xaml-meet-uikit/)

Have any feedback? Let us know here.

**Comment by liquidboy** [comment]
is there a roadmap or do you have an idea of how long it will take you to do this UIKit->XAML mapping ?!  I been looking through your checkins and can see the effort is well underway, just got thru the UISlider changes (quite a lot) ...

I'm guessing this will take a good while..

**Comment by antoine-haas** [comment]
Hey @liquidboy,

The migration to XAML is an ongoing effort with no end date yet. We're first migrating the controls that are already supported by the bridge, and then will proceed to add new controls. As you pointed out, those are big changes that will take a considerable amount of time.
