### ISSUE TITLE
vsimporter warns about PBXShellScriptBuildPhase?

### ISSUE THREAD

**Issue by VishalAgarW** [Microsoft/WinObjC#659]
This is what I get when trying to use vsimported against my project:
[W] Ignoring unsupported PBXShellScriptBuildPhase in "XXXX" target.

Opening the generated solution and trying to build later fails with:
Error       'FBSDKShareKit/FBSDKShareLinkContent.h' file not found

so not sure if the above warning is really legit to ignore or not?

**Comment by rhaning** [comment]
This is due to a difference in the way Xcode and Visual Studio search for headers. VS doesn't have a notion of frameworks like Xcode does. We are working on a fix for this and hope to have it ready soon.

**Comment by memontic-ms** [comment]
I could not reproduce the "Ignoring unsupported PBXShellScriptBuildPhase" warning with any of the July releases or the current implementation of vsimporter. @VishalAgarW, if this is still an issue I can take a look at it if you can provide me with a project that can reproduce the warning.

**Comment by memontic-ms** [comment]
Cannot reproduce, closing.
