### ISSUE TITLE
sys/socket.h file not found

### ISSUE THREAD

**Issue by dimio85** [Microsoft/WinObjC#66]
I'm trying to import an iOS project and it complains on socket.h not found. Am I missing something?

**Comment by greenhippie** [comment]
I am also seeing this issue in a Pods dependency project.
#import <sys/socket.h>
Error		'sys/socket.h' file not found

**Comment by s5msft** [comment]
The short answer is that the file isn't present and that use of sys/socket.h should be replaced with winsock2.h.

The longer answer is that mixing an iOS style socket.h and winsock2.h results in various type collisions -- hence the above requirement. This is something we're still looking into.

**Comment by codinggooner** [comment]
I am also seeing this issue in a Pods dependency project,and any other solution?

**Comment by rajsesh-msft** [comment]
This is in our backlog and will be considered in one of the future releases.
