### ISSUE TITLE
Build fails due to "cannot open source file .tlh" + "framework/file.h not found"

### ISSUE THREAD

**Issue by LucasTaiMacArthur** [Microsoft/WinObjC#660]
I'm attempting to build a project ported to windows through islandwood. The project includes openssl as a .framework folder with the headers for the openssl functions contained within the folder in "openssl.framework/headers/." None of the headers appear in the ProjectName-Headers solution and moving them manually to the header solution does not fix the issue.

After running vsimporter on the project and attempting to build it, the build fails due to the following error. Every location which contains an import from the framework such as  `"#import <openssl/rand.h>"` registers a failure with the following error 

`Cannot open source file "C:/........../projectName.vsimporter/...../Debug/rand.tlh"`

The compiler output is a single line stating `Fatal Error: 'openssl/rand.h` file not found.

**Comment by asimonov-msft** [comment]
@LucasTaiMacArthur  The tlh error messages are a known issue, but they do not result in compilation errors. In this case, the build failure is caused by missing openssl headers, which is tracked by Issue #928.
