### ISSUE TITLE
NSFileManager needs unit tests

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#662]
Most of the functionality does not have unit tests, also edge cases are not being handled properly (e.g nil, etc).
- File clean up for dead code and logs.

**Comment by DHowett-MSFT** [comment]
@msft-Jeyaram: Leaving this open (referenced via e9bb1b2) to track additional unit test work.

**Comment by rajsesh-msft** [comment]
NSFileManager tests should use the newly added _SCOPE (compatible with OSX)

**Comment by rajsesh-msft** [comment]
Closing this issue.  We will write tests as we add features here.
