### ISSUE TITLE
NSException details should be available in debugger

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#666]
NSExceptions often contain valuable information that can help tracking down issue. However, when an NSException is raised in the Visual Studio debugger, we currently only a boilerplate exception message like the following:

> Exception thrown at 0x743FDAE8 in MyApp.exe: Microsoft C++ exception: UNSException at memory location 0x02F5E944.
> Unhandled exception at 0x69673472 (ucrtbase.dll) in MyApp.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.

This can be reproduced e.g. with the following code:

``` objc
[[NSMutableArray new] removeObjectAtIndex:0];
```

which emits a message like the following on the reference platform:

> **\* -[__NSArrayM removeObjectAtIndex:]: index 0 beyond bounds for empty array

**Comment by weswmsft** [comment]
This is now implemented
