### ISSUE TITLE
Give effect to blendMode and alpha/opacity values in parameters

### ISSUE THREAD

**Issue by shahmeeresmail** [Microsoft/WinObjC#674]
Draws to a CG context using a draw function with no alpha or blendMode parameters, should use an alpha/opacity value of 1.0f and a blendmode of kCGBlendModeNormal as per the spec.

Similarly, draws using a function with inline alpha and blendMode parameters, should use those for the draw and restore the original state afterwards.

At least 2 functions are affected:
drawInRect(rect, blendmode, alpha) & drawAtPoint(point, blendMode, alpha) : alpha values ignored

**Comment by rajsesh-msft** [comment]
According to @shahmeeresmail #636 fixed this already.
