### ISSUE TITLE
ANNOUNCEMENT: App Analysis Tool Now Available!

### ISSUE THREAD

**Issue by nicholasgerard-msft** [Microsoft/WinObjC#679]
![IPA Analysis Tool](https://winblogs.azureedge.net/win/2016/07/image1.png)

Several months ago, we announced that we were working on an App Analysis tool to help new users get started with the bridge, and today we're happy to announce the tool is available and live on our website. [You can check it out here](https://developer.microsoft.com/en-us/windows/bridges/ios/app-analyzer-tool).

The tool will examine your compiled project (IPA) and cross-reference the frameworks and classes used with the ones currently supported by the bridge, and return the results right in your browser. The tool will also identify third-party libraries and SDK packages used in your project and let you know if they – or equivalent libraries – are available on Windows 10. The analysis is just a starting point, but it will give you a good idea of how much work will be required to bring your iOS app to Windows 10 using the bridge.

We've also published [a blog post on the Building Apps for Windows blog](https://blogs.windows.com/buildingapps/2016/07/22/windows-bridge-for-ios-app-analysis-tool-now-available/) with some more information about what the tool does and how to use it.

There are currently a handful of known issues with the tool that we're working to fix as soon as we can, including:
- IPAs larger than 2 GB will not be accepted by the tool
- IPAs with a capitalized ".IPA" extension will not work. The extension must be lower-case, as in ".ipa"
- An invalid IPA file will provide no feedback or error message

If you have any feedback on the tool, please let us know in the comments below!

**Comment by tmm1** [comment]
Everytime I try to upload an IPA, it says:

>The file you submitted is not a correctly formatted iOS app package. Please try again with a different IPA.

I generated the IPA using the instructions on the page.

**Comment by nicholasgerard-msft** [comment]
@tmm1 Try checking your Build Settings in Xcode. Under Architectures, make sure you're targeting both **arm64** and **armv7** (or use the **$(ARCHS_STANDARD)** variable). Then try rebuilding and resubmitting your IPA.

**Comment by tmm1** [comment]
I see, thanks for the pointer. My app targets 64-bit iOS devices only. Some of my dependencies are aarch64 only, so it would require considerable effort to create an armv7 ipa.

**Comment by nicholasgerard-msft** [comment]
@tmm1 In that case, your best bet is to try out the bridge itself, which you can download [here](https://github.com/Microsoft/WinObjC/releases). Once your project is up and running in Visual Studio, you'll see any unsupported methods or properties you're calling printed to the console. (This is similar to the data you'd get from the IPA Analysis Tool, but has the added benefit of being generated at runtime – rather than extracted from a compiled binary – so it should correspond even more closely to what you're actually using.)
