### ISSUE TITLE
How to remove copy and define in a document when i open with UIDocumentInteractionController?

### ISSUE THREAD

**Issue by rayalarajee** [Microsoft/WinObjC#681]
problem statement: preventing the copy (copying text) functionality in iOS app Document/PDF Viewer (.pdf, .doc, .docx, .txt & etc).

Description: Currently, We are developing an iOS app. as a part of app requirement we need to restrict the copy functionality. I am using UIDocumentInteractionController for previewing files (.pdf, .doc, .docx, .txt & etc) in my app. While previewing the file we need to restrict the copy (copying text) functionality.

![image](https://cloud.githubusercontent.com/assets/6753943/17093832/396a2a52-5269-11e6-9257-0c769c6bd794.jpg)
![image 1](https://cloud.githubusercontent.com/assets/6753943/17093853/62a3de68-5269-11e6-9723-8ee4eead65bd.jpg)

**Comment by ArnOmsft** [comment]
Sorry for the late feedback. Are you asking about how to prevent copying text on iOS or how to do that on your app after bringing it to Windows using the Bridge?

**Comment by rayalarajee** [comment]
Thank you ...I am asking about how to prevent copying text on iOS

**Comment by ArnOmsft** [comment]
Sorry, we don't know the answer to that. Closing since this is not related to the iOS bridge itself.
