### ISSUE TITLE
NSLock/NSRecursiveLockTests can be non-WindowsOnly

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#688]
Dependent on https://github.com/Microsoft/WinObjC/issues/634

NSLock/NSRecursiveLockTests currently use an internal _lockCount function as validation. The test performed can be rewritten to be nearly the same, if [NSLock tryLock] (unlock on success) were used, allowing cross-compilation.

It may possibly still be valuable to keep the _lockCount version of the tests even after the cross-plat versions are written.

**Comment by msft-Jeyaram** [comment]
When I was going through your CR for the mac port, I thought the same thing. Although we do have tryLock tests (which works fine on mac).

**Comment by msft-Jeyaram** [comment]
Actually this isn't going to give us much, i would rather leave the lock/unlock tests and since tryLock already be ported to MAC it's fine. Changing the lock test to try Lock would end up testing the same scenario in mac and missing out the actual lock/unlock scenario on windows.

**Comment by msft-Jeyaram** [comment]
Closing this out as per comment above.
