### ISSUE TITLE
EntryPoint.cpp needs a scopeguard

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#689]
tests/unittests/EntryPoint.cpp::30
// TODO: move to a scopeguard when we have one in our codebase

The initialize and uninitialize should be done in a scopeguard. This would also reduce the size of the ifdef introduced in https://github.com/Microsoft/WinObjC/pull/634

**Comment by rajsesh-msft** [comment]
Not super duper important. Won't fix.
