### ISSUE TITLE
Unable to read the project file "WOCCatalog.vcxproj"

### ISSUE THREAD

**Issue by reyesrico** [Microsoft/WinObjC#69]
Hi,

This is my first time using this SDK. I have downloaded and tried to run the "WOCCatalog" project but it appeared the following error.

Unabel to read the project file "WOCCatalog.vcxproj". C:\Program Files\...  the imported project C:\... was not found. Confirm that the path in the <Import> declaration is correct, and that the file exist on disk.

Any help?

**Comment by asimonov-msft** [comment]
@reyesrico  Could you please provide us with a few more details about the error.
Did you use a pre-built SDK or clone our git repository?
What was the full error message?

**Comment by reyesrico** [comment]
I have downloaded the winobjc and when I open the /samples/WOCCatalog-WinSotre10.sln, VS2013 is opened and start to load the projects. Then appears: Not all the projects were loaded please review the Output. The output says: WOCCatalog-WinStore10\WOCCatalog.vcxproj : error  : Unable to read the project file "WOCCatalog.vcxproj". 
The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v12.0\10.0\Microsoft.Windows.UI.Xaml.Cpp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

I think is because the installation of my VS2013. Dont you think?

**Comment by agustingandara** [comment]
To use WinObjC, there are a few requirements. You need:

Windows 10
Visual Studio 2015 with Windows developer tools. Visual Studio 2015 Community is available for free here. Select (at least) the following components during installation:

Programming Languages -> Visual C++

Universal Windows App Development Tools (all)

Windows 8.1 and Windows Phone 8.0/8.1 Tools (all)

**Comment by reyesrico** [comment]
Thanks Agustin! I have installed these requirements and now I can run the samples!
