### ISSUE TITLE
Archival.NSKeyedUnarchiver_Secure fails on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#702]
Dependent on https://github.com/Microsoft/WinObjC/pull/634

[ RUN      ] Archival.NSKeyedUnarchiver_Secure
Foundation/ArchivalTests.mm:138: Failure
Expected: secureUnarchiver.requiresSecureCoding = __objc_no throws an exception.
  Actual: it doesn't.
It should be impossible to turn off secure coding.
Foundation/ArchivalTests.mm:262: Failure
Value of: [secureUnarchiver decodeObjectOfClass:[NSDictionary class] forKey:@"dictionary"]
  Actual: 0x7ff2e1d24300
Expected: nullptr
Which is: NULL
Foundation/ArchivalTests.mm:263: Failure
Value of: [secureUnarchiver decodeObjectOfClass:[NSArray class] forKey:@"array"]
  Actual: 0x7ff2e1c415b0
Expected: nullptr
Which is: NULL
Foundation/ArchivalTests.mm:264: Failure
Value of: [secureUnarchiver decodeObjectOfClass:[NSNumber class] forKey:@"number"]
  Actual: 0x2837
Expected: nullptr
Which is: NULL
[  FAILED  ] Archival.NSKeyedUnarchiver_Secure (5 ms)

Not sure about the exception throwing, but the latter failures look like us having the encode/decode keys differently from OSX - not sure if that's fixable...

**Comment by DHowett-MSFT** [comment]
I'm not sure it's key-related -- we should be able to serialize and deserialize objects of any type with the same key.

*However*: The first failing test here tests [the API contract](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSKeyedUnarchiver_Class/#//apple_ref/occ/instm/NSKeyedUnarchiver/setRequiresSecureCoding:) laid out for `setSecureCoding:`, which specifies:

    The secure coding requirement for NSKeyedUnarchiver is designed to be set once
    at the top level and remain on. Once enabled, attempting to call setRequiresSecureCoding:
    with a value of NO will throw an exception. This is to prevent classes from selectively
    turning secure coding off. 

It looks like the reference platform doesn't follow its own rules.

What does that mean for our tests? :frown:

**Comment by DHowett-MSFT** [comment]
The other two tests match observed behaviour where an insecure object being decoded would stop all future decoding. I am uncertain as to why this behaviour has changed on the reference platform as well.
