### ISSUE TITLE
Foundation.NSCompoundPredicate_copy fails on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#704]
Dependent on https://github.com/Microsoft/WinObjC/pull/634

[ RUN      ] Foundation.NSCompoundPredicate_copy
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] Foundation.NSCompoundPredicate_copy (0 ms)

Require deeper investigation to see what the exception actually is.

**Comment by msft-Jeyaram** [comment]
closed as per commit #789
