### ISSUE TITLE
Investigate root cause for all frameworks being loaded even when not used.

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#714]

**Comment by bbowman** [comment]
This is not the case. In one example middle ware we see the following dll dependencies from WinObjC:

AUTOLAYOUT.DLL
CAIRO.DLL
COREFOUNDATION.DLL
COREGRAPHICS.DLL
CORETEXT.DLL
FBSDK.DLL
FOUNDATION.DLL
FREETYPE.DLL
ICUDT57.DLL
ICUIN57.DLL
ICUUC57.DLL
LIBDISPATCH.DLL
LIBJPEG.DLL
LIBOBJC2.DLL
LIBPNG.DLL
LIBXML2.DLL
LIBZ.DLL
LOGGING.DLL
MOBILECORESERVICES.DLL
OBJCUWP.DLL
QUARTZCORE.DLL
RTOBJCINTEROP.DLL
STARBOARD.DLL
UIKIT.DLL
WINOBJCRT.DLL

Which means many frameworks are *not* loaded even if all the libs are specified to the linker anyway.
