### ISSUE TITLE
Xcode Macros - e.g. NS_DESIGNATION_INITIALIZER

### ISSUE THREAD

**Issue by joewood** [Microsoft/WinObjC#72]
I've hit this problem where a MACRO defined in XCode 6 isn't being defined. Could these be added to the default build environment?

http://stackoverflow.com/questions/24119896/ns-designated-initializer-expected-colon

**Comment by technotrance** [comment]
yes if you built a converter in java that can convert to your file for eg xvid to bdrip on downloads

**Comment by MaddTheSane** [comment]
A simple fix is (in your own code) checking if `NS_DESIGNATION_INITIALIZER` is defined, and if it isn't, defining it to nothing:

    #ifndef NS_DESIGNATION_INITIALIZER
    #define NS_DESIGNATION_INITIALIZER
    #endif

**Comment by antoine-haas** [comment]
This is going to be fixed on the next release, please reopen the issue the problem persists by then.

**Comment by antoine-haas** [comment]
This should have been fixed with the latest release. Please reopen the issue if that's not the case.
