### ISSUE TITLE
Support CTFont and CTFontCollection with proper bridging support

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#729]
- [x] Interoperable	CTFontCopyFamilyName
- [x] Interoperable	CTFontGetAscent
- [x] Interoperable	CTFontGetDescent
- [x] Interoperable	CTFontGetSize
- [x] Caveat	CTFontCopyFullName
- [x] Caveat	CTFontCopyName
- [x] Caveat	CTFontCopyPostScriptName
- [x] Caveat	CTFontCreateWithName

**Comment by ms-jihua** [comment]
Note that CTFontCollection has no bridged equivalent.
