### ISSUE TITLE
NSOperation completionBlock not executed for NSOperation subclass.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#734]
If you implement your own concurrent NSOperation subclass, the completion block for the operation is not executed when the `isFinished` property is changed to `TRUE`.

It looks like the completion block handling is done in the private method `- (void)_finish:(BOOL)didExecute` and if your subclass overrides the `-(void)start` method, then the `_finish` method will never be called and the completion block will not be executed.

**Comment by DHowett-MSFT** [comment]
@rupertdaniel Thanks for the report. We've root-caused the issue and come up with a tentative fix. Do you have a representative sample we can include in our test burden to make sure this doesn't regress?

**Comment by DHowett-MSFT** [comment]
It appears as though we have a test for this case -- it asserts that the operation is finished when the completion block is called.
However, _it never actually asserts that the completion block was, in fact, called._

**Comment by rupertdaniel** [comment]
Great, thanks for looking at this.

Here is a simple operation subclass...

```
@interface MyOperation : NSOperation

@property (assign, getter = isExecuting) BOOL executing;
@property (assign, getter = isFinished, readonly) BOOL finished;

@end

@implementation MyOperation

@synthesize executing = _executing;
@synthesize finished = _finished;

- (void)setExecuting:(BOOL)executing
{
	[self willChangeValueForKey:@"isExecuting"];
	[self willChangeValueForKey:@"isFinished"];
	
	_executing = executing;
	_finished = !executing;
	
	[self didChangeValueForKey:@"isExecuting"];
	[self didChangeValueForKey:@"isFinished"];
}

- (BOOL)isExecuting
{
	return _executing;
}

- (BOOL)isFinished
{
	return _finished;
}

- (void)start
{	
	if (self.isCancelled)
		return;
	
	self.executing = YES;
	[self doSomething];
}

- (void)doSomething
{
	// Do some async task.
	dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
            self.executing = NO;
    });
}

@end
```

Then to run it...
```
self.op = [[MyOperation alloc] init];
self.op.completionBlock = ^{
  NSLog(@"FINISHED!!!");
};

[self.queue addOperation:self.op];
```

**Comment by DHowett-MSFT** [comment]
Thanks.

We investigated a couple more use cases for NSOperation, and identified a couple other problem areas.
* Operations should be scheduleable without a queue and run manually.
* Operations with dependencies need to perform dependency resolution if they're at the head of the queue.

We've added additional test burden in #784, but the dependency issue is still outstanding.

Right now, if you enqueue an operation BEFORE its dependencies, the queue will block forever. On the reference platform, the dependencies resolve and execute before their depending operation.

**Comment by DHowett-MSFT** [comment]
Ping! This is P0.

**Comment by rupertdaniel** [comment]
@DHowett-MSFT sorry was this a ping at me? :-)

If so...
> Operations should be scheduleable without a queue and run manually.

We don't do this at the moment so should be ok for us.
>Operations with dependencies need to perform dependency resolution if they're at the head of the queue.

We don't use dependencies at the moment so should be ok too.
