### ISSUE TITLE
'CoreMotion/CoreMotion.h' file not found

### ISSUE THREAD

**Issue by YusukeYamamoto** [Microsoft/WinObjC#74]
Does WinObjC support "CoreMotion"?

**Comment by greenhippie** [comment]
When you downloaded the [Windows Bridge for iOS SDK](https://github.com/Microsoft/WinObjC/releases/download/0.1-preview/winobjc.zip) - where ever you extracted it to, you can open the "include" folder to see everything that is currently supported.

CoreMotion is not currently supported.

**Comment by YusukeYamamoto** [comment]
OIC, I got it.

CoreMotion is not supported yet.

**Comment by rajsesh-msft** [comment]
Thanks to our partners at Intel, Coremotion is now part of the SDK.  Check it out.
