### ISSUE TITLE
NSBundle tests fail on OSX (plist issues)

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#741]
These look like the plist file might not be in the correct location for OSX:

[ RUN      ] NSBundle.Paths
[       OK ] NSBundle.Paths (3 ms)
[ RUN      ] NSBundle.Resources
Foundation/ReferenceFoundation/TestNSBundle.mm:60: Failure
Expected: (testPlist) != (nullptr), actual: NULL vs NULL
[  FAILED  ] NSBundle.Resources (4 ms)
[ RUN      ] NSBundle.InfoPlist
Foundation/ReferenceFoundation/TestNSBundle.mm:74: Failure
Value of: bundle.bundleIdentifier
  Actual: NULL
Expected: @"org.swift.TestFoundation"
Which is: org.swift.TestFoundation
[  FAILED  ] NSBundle.InfoPlist (0 ms)

**Comment by bbowman** [comment]
[ RUN      ] NSBundle.Resources
[       OK ] NSBundle.Resources (6 ms)
[ RUN      ] NSBundle.InfoPlist
[       OK ] NSBundle.InfoPlist (0 ms)

on latest. Closing issue.
