### ISSUE TITLE
NSCache.DiscardableContent_DiscardButKeepOnEvict fails on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#742]
[ RUN      ] NSCache.DiscardableContent_DiscardButKeepOnEvict
Foundation/NSCacheTests.mm:252: Failure
Expected: (nullptr) != ([cache objectForKey:@"disc"]), actual: NULL vs NULL
[  FAILED  ] NSCache.DiscardableContent_DiscardButKeepOnEvict (0 ms)

**Comment by DHowett-MSFT** [comment]
We had `evictsObjectsWithDiscardedContent` backwards; the intent appears to have been to remove discarded objects when we realize they're discarded (and signal the delegate). We interpreted it to mean "remove objects after we have discarded them in recosting".
