### ISSUE TITLE
NSFileHandle tests fail on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#750]
A lot of fh == nil - might be a test infrastructure issue.

[----------] 12 tests from NSFileHandle
[ RUN      ] NSFileHandle.Init
Foundation/NSFileHandleTests.mm:75: Failure
Value of: [[[NSFileHandle alloc] init] autorelease] != nullptr
  Actual: false
Expected: true
FAILED: alloc/init failed.
[  FAILED  ] NSFileHandle.Init (0 ms)
[ RUN      ] NSFileHandle.ReadFile
Foundation/NSFileHandleTests.mm:54: Failure
Value of: fh != nil
  Actual: false
Expected: true
Foundation/NSFileHandleTests.mm:85: Failure
Value of: fh != nil
  Actual: false
Expected: true
[  FAILED  ] NSFileHandle.ReadFile (3 ms)
[ RUN      ] NSFileHandle.UpdateAndSeeks
Foundation/NSFileHandleTests.mm:54: Failure
Value of: fh != nil
  Actual: false
Expected: true
Foundation/NSFileHandleTests.mm:103: Failure
Value of: fh != nil
  Actual: false
Expected: true
[  FAILED  ] NSFileHandle.UpdateAndSeeks (3 ms)
[ RUN      ] NSFileHandle.Offsets
Foundation/NSFileHandleTests.mm:54: Failure
Value of: fh != nil
  Actual: false
Expected: true
Foundation/NSFileHandleTests.mm:126: Failure
Value of: fh != nil
  Actual: false
Expected: true
[  FAILED  ] NSFileHandle.Offsets (3 ms)
[ RUN      ] NSFileHandle.WriteToNonExistentFileAndRead
Foundation/NSFileHandleTests.mm:54: Failure
Value of: fh != nil
  Actual: false
Expected: true
Foundation/NSFileHandleTests.mm:153: Failure
Value of: fh != nil
  Actual: false
Expected: true
[  FAILED  ] NSFileHandle.WriteToNonExistentFileAndRead (4 ms)
[ RUN      ] NSFileHandle.TruncateFileAtOffset
Foundation/NSFileHandleTests.mm:54: Failure
Value of: fh != nil
  Actual: false
Expected: true
Foundation/NSFileHandleTests.mm:174: Failure
Value of: fh != nil
  Actual: false
Expected: true
[  FAILED  ] NSFileHandle.TruncateFileAtOffset (2 ms)
[ RUN      ] NSFileHandle.FileHandleWithNullDevice
[       OK ] NSFileHandle.FileHandleWithNullDevice (0 ms)
[ RUN      ] NSFileHandle.ReadDataOfLength
Foundation/NSFileHandleTests.mm:54: Failure
Value of: fh != nil
  Actual: false
Expected: true
Foundation/NSFileHandleTests.mm:241: Failure
Value of: fh != nil
  Actual: false
Expected: true
[  FAILED  ] NSFileHandle.ReadDataOfLength (3 ms)
[ RUN      ] NSFileHandle.UpdatingURL
Foundation/NSFileHandleTests.mm:54: Failure
Value of: fh != nil
  Actual: false
Expected: true
Foundation/NSFileHandleTests.mm:271: Failure
Value of: fh != nil
  Actual: false
Expected: true
[  FAILED  ] NSFileHandle.UpdatingURL (3 ms)
[ RUN      ] NSFileHandle.ReadingFromURL
Foundation/NSFileHandleTests.mm:54: Failure
Value of: fh != nil
  Actual: false
Expected: true
Foundation/NSFileHandleTests.mm:297: Failure
Value of: fh != nil
  Actual: false
Expected: true
[  FAILED  ] NSFileHandle.ReadingFromURL (2 ms)
[ RUN      ] NSFileHandle.WritingAtPath
Foundation/NSFileHandleTests.mm:316: Failure
Value of: fh != nil
  Actual: false
Expected: true
[  FAILED  ] NSFileHandle.WritingAtPath (2 ms)
[ RUN      ] NSFileHandle.ReadingNonExistentFile
[       OK ] NSFileHandle.ReadingNonExistentFile (2 ms)
[----------] 12 tests from NSFileHandle (37 ms total)

**Comment by msft-Jeyaram** [comment]
fix in #805
