### ISSUE TITLE
NSFileManager tests fail on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#751]
Probably a test infrastructure issue?

[ RUN      ] NSFileManager.GetAttributes
[  INFO ] this test try to validate file creation date and modification date and size for /
Foundation/NSFileManagerTests.mm:76: Failure
Value of: [manager fileExistsAtPath:testFileFullPath]
  Actual: false
Expected: true
Failed: file /
[  FAILED  ] NSFileManager.GetAttributes (0 ms)
[ RUN      ] NSFileManager.EnumateDirectoryUsingURL
Foundation/NSFileManagerTests.mm:124: Failure
Value of: SetCurrentDirectoryW(startUpPath) != 0
  Actual: false
Expected: true
[  FAILED  ] NSFileManager.EnumateDirectoryUsingURL (0 ms)

**Comment by msft-Jeyaram** [comment]
Looks like it might be an infrastructure issue. we expect NSFileManagerUT.txt to be placed at a fixed path. 
Also the path to verify against is constructed via windows specific path.
Will look further.

**Comment by ms-jihua** [comment]
Reassigning this to myself - this is a somewhat general issue involving our test data files (https://github.com/Microsoft/WinObjC/issues/777 is the same root cause), so the same person should be looking at both.

**Comment by msft-Jeyaram** [comment]
Taking it back since I have some changes. Opening a new bug for supporting file staging during test runs.

**Comment by msft-Jeyaram** [comment]
Actually this is the only issue, the file staging .
I was thinking of NSFileHandler issues when I took it back.
