### ISSUE TITLE
NSKeyValueCoding tests fail on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#755]
Also if we could Aggerate -> Aggregate it'd be nice

[ RUN      ] NSKeyValueCoding.AggerateFunctionUnionOfObjectsSet
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSKeyValueCoding.AggerateFunctionUnionOfObjectsSet (0 ms)
[ RUN      ] NSKeyValueCoding.AggerateFunctionSumDict
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSKeyValueCoding.AggerateFunctionSumDict (1 ms)
[ RUN      ] NSKeyValueCoding.AggerateFunctionCountDict
[       OK ] NSKeyValueCoding.AggerateFunctionCountDict (0 ms)
[ RUN      ] NSKeyValueCoding.AggerateFunctionMaxDict
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSKeyValueCoding.AggerateFunctionMaxDict (0 ms)
[ RUN      ] NSKeyValueCoding.AggerateFunctionMinDict
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSKeyValueCoding.AggerateFunctionMinDict (0 ms)
[ RUN      ] NSKeyValueCoding.AggerateFunctionAvgDict
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSKeyValueCoding.AggerateFunctionAvgDict (0 ms)
[ RUN      ] NSKeyValueCoding.AggerateFunctionDistinctUnionOfObjectsDict
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSKeyValueCoding.AggerateFunctionDistinctUnionOfObjectsDict (0 ms)
[ RUN      ] NSKeyValueCoding.AggerateFunctionUnionOfObjectsDict
[       OK ] NSKeyValueCoding.AggerateFunctionUnionOfObjectsDict (0 ms)
[ RUN      ] NSKeyValueCoding.AggerateFunctionNullLeafArray
Foundation/NSKeyValueCodingTests.mm:228: Failure
Expected: [result valueForKeyPath:@"@unionOfArrays.testObj"] throws an exception.
  Actual: it doesn't.
[  FAILED  ] NSKeyValueCoding.AggerateFunctionNullLeafArray (0 ms)
[ RUN      ] NSKeyValueCoding.AggerateFunctionNullLeafSet
Foundation/NSKeyValueCodingTests.mm:235: Failure
Expected: [result valueForKeyPath:@"@distinctUnionOfSets.testObj"] throws an exception.
  Actual: it doesn't.
[  FAILED  ] NSKeyValueCoding.AggerateFunctionNullLeafSet (0 ms)

**Comment by DHowett-MSFT** [comment]
This reflects a design deficiency in our implementation of aggregate functions.
Where we have one global class that implements these for everybody, it looks like they're class-specific on the reference platform. This allows them to disable `unionOfSets` on `NSSet`, and `sum`, `min`, `max` on `NSDictionary`.
