### ISSUE TITLE
NSMutableOrderedSet.oneWayArray sends an unrecognized selector on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#757]
This test passes because the message is wrapped in an ASSERT_ANY_THROW - however, I'm not sure that the exception the test was looking for was an unrecognized selector.

[ RUN      ] NSMutableOrderedSet.oneWayArray
2016-08-01 10:46:03.256 Foundation.UnitTests.exe[4412:468597] -[__NSOrderedSetArrayProxy addObject:]: unrecognized selector sent to instance 0x7fae9b201910
[       OK ] NSMutableOrderedSet.oneWayArray (2 ms)

**Comment by mnithish** [comment]
Verified the behavior matches the reference platform i.e. unrecognized selector is thrown in this case.

This is not an issue.
