### ISSUE TITLE
NSPointerArray tests fail on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#761]
[ RUN      ] NSPointerArray.Equality
Foundation/NSPointerArrayTests.mm:121: Failure
Expected: (h1) != (h3), actual: 3 vs 3
Hash value of C strings arrays should not be equal
[  FAILED  ] NSPointerArray.Equality (0 ms)

[ RUN      ] NSPointerArray.RemovePointer
2016-08-01 10:46:14.099 Foundation.UnitTests.exe[4412:468597] -[NSConcretePointerArray allocatedCount]: unrecognized selector sent to instance 0x7fae98c481d0
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSPointerArray.RemovePointer (1 ms)

[ RUN      ] NSPointerArray.Weak
Foundation/NSPointerArrayTests.mm:276: Failure
Value of: 1
Expected: notify
Which is: 0
Instance should have been released
[  FAILED  ] NSPointerArray.Weak (0 ms)

[ RUN      ] NSPointerArray.Encoder
Foundation/NSPointerArrayTests.mm:313: Failure
Value of: equal
  Actual: false
Expected: true
Arrays should be equal
[  FAILED  ] NSPointerArray.Encoder (1 ms)

**Comment by mnithish** [comment]
https://github.com/Microsoft/WinObjC/pull/806
