### ISSUE TITLE
NSPredicate tests fail on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#763]
[----------] 25 tests from NSPredicate
[ RUN      ] NSPredicate.Init
[       OK ] NSPredicate.Init (0 ms)
[ RUN      ] NSPredicate.predicateWithValue
[       OK ] NSPredicate.predicateWithValue (0 ms)
[ RUN      ] NSPredicate.PredicateWithBlock
[       OK ] NSPredicate.PredicateWithBlock (0 ms)
[ RUN      ] NSPredicate.PredicateWithBlockSub
[       OK ] NSPredicate.PredicateWithBlockSub (0 ms)
[ RUN      ] NSPredicate.ArchiveAndUnarchiveObject
[       OK ] NSPredicate.ArchiveAndUnarchiveObject (0 ms)
[ RUN      ] NSPredicate.copy
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSPredicate.copy (1 ms)
[ RUN      ] NSPredicate.stringFormatTest
[       OK ] NSPredicate.stringFormatTest (0 ms)
[ RUN      ] NSPredicate.stringFormatComplexTest
[       OK ] NSPredicate.stringFormatComplexTest (0 ms)
[ RUN      ] NSPredicate.stringFormatAccessClassVarsTestAge
[       OK ] NSPredicate.stringFormatAccessClassVarsTestAge (0 ms)
[ RUN      ] NSPredicate.stringFormatAccessClassVarsTestName
[       OK ] NSPredicate.stringFormatAccessClassVarsTestName (0 ms)
[ RUN      ] NSPredicate.stringFormatBETWEEN
[       OK ] NSPredicate.stringFormatBETWEEN (1 ms)
[ RUN      ] NSPredicate.stringFormatGreater
[       OK ] NSPredicate.stringFormatGreater (0 ms)
[ RUN      ] NSPredicate.stringFormatRange
[       OK ] NSPredicate.stringFormatRange (0 ms)
[ RUN      ] NSPredicate.keyPathAccess
[       OK ] NSPredicate.keyPathAccess (0 ms)
[ RUN      ] NSPredicate.BeginsWith
[       OK ] NSPredicate.BeginsWith (0 ms)
[ RUN      ] NSPredicate.EndsWith
[       OK ] NSPredicate.EndsWith (0 ms)
[ RUN      ] NSPredicate.Contains
[       OK ] NSPredicate.Contains (0 ms)
[ RUN      ] NSPredicate.Contains2
[       OK ] NSPredicate.Contains2 (0 ms)
[ RUN      ] NSPredicate.InCollection
[       OK ] NSPredicate.InCollection (0 ms)
[ RUN      ] NSPredicate.Matches
Foundation/NSPredicateTests.m:324: Failure
Value of: [validTestAnimals count]
  Actual: 0
Expected: 1
FAILED: Unable to filter based on class property.
[  FAILED  ] NSPredicate.Matches (3 ms)
[ RUN      ] NSPredicate.Like
Foundation/NSPredicateTests.m:342: Failure
Value of: [validTestAnimals count]
  Actual: 0
Expected: 2
FAILED: Unable to filter based on class property.
[  FAILED  ] NSPredicate.Like (0 ms)
[ RUN      ] NSPredicate.SelfAccess
[       OK ] NSPredicate.SelfAccess (0 ms)
[ RUN      ] NSPredicate.SelfAccessObjectProperty
[       OK ] NSPredicate.SelfAccessObjectProperty (0 ms)
[ RUN      ] NSPredicate.SelfAccessObjectPropertyNegatives
[       OK ] NSPredicate.SelfAccessObjectPropertyNegatives (0 ms)
[ RUN      ] NSPredicate.SubPredicate
[       OK ] NSPredicate.SubPredicate (0 ms)
[----------] 25 tests from NSPredicate (24 ms total)

**Comment by msft-Jeyaram** [comment]
Looks like the copy issue has to do with the way reference platform implements the NSPredicate class.
using a static function to obtain a predicate should fix that.

**Comment by msft-Jeyaram** [comment]
Closing this as per commit #788
