### ISSUE TITLE
NSProgress tests fail on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#764]
[----------] 11 tests from NSProgress
[ RUN      ] NSProgress.UserInfo
[       OK ] NSProgress.UserInfo (0 ms)
[ RUN      ] NSProgress.FractionCompleted
[       OK ] NSProgress.FractionCompleted (0 ms)
[ RUN      ] NSProgress.IsIndeterminate
Foundation/NSProgressTests.mm:137: Failure
Value of: [progress isIndeterminate]
  Actual: '\0'
Expected: __objc_yes
Which is: '\x1' (1)
[  FAILED  ] NSProgress.IsIndeterminate (0 ms)
[ RUN      ] NSProgress.ChainImplicit
Foundation/NSProgressTests.mm:155: Failure
Value of: [prog2 fractionCompleted]
  Actual: 0.6
Expected: 0
[  FAILED  ] NSProgress.ChainImplicit (1 ms)
[ RUN      ] NSProgress.TreeImplicit
[       OK ] NSProgress.TreeImplicit (16 ms)
[ RUN      ] NSProgress.TreeExplicit
[       OK ] NSProgress.TreeExplicit (0 ms)
[ RUN      ] NSProgress.CurrentProgress_ThreadLocal
[       OK ] NSProgress.CurrentProgress_ThreadLocal (29 ms)
[ RUN      ] NSProgress.SingleParentEvenAcrossThreads
[       OK ] NSProgress.SingleParentEvenAcrossThreads (14 ms)
[ RUN      ] NSProgress.ResignCurrentAutomaticBehavior
[       OK ] NSProgress.ResignCurrentAutomaticBehavior (0 ms)
[ RUN      ] NSProgress.CancelPauseResume
Foundation/NSProgressTests.mm:333: Failure
Value of: cancelCalled
  Actual: '9' (57, 0x39)
Expected: __objc_yes
Which is: '\x1' (1)
[  FAILED  ] NSProgress.CancelPauseResume (0 ms)
[ RUN      ] NSProgress.LocalizedDescription
Foundation/NSProgressTests.mm:360: Failure
Value of: localizedAdditionalDescriptionWithKind
  Actual: Zero KB of 100 bytes
Expected: @""
Which is: 
[  FAILED  ] NSProgress.LocalizedDescription (2 ms)
[----------] 11 tests from NSProgress (75 ms total)

**Comment by msft-Jeyaram** [comment]
Closing this as per CR #788

**Comment by msft-Jeyaram** [comment]
Re-opening this as the wrong one was closed.

**Comment by rajsesh-msft** [comment]
@msft-Jeyaram is there a new PR for this?

**Comment by msft-Jeyaram** [comment]
there is a PR, not sure why it's not linked. My CI builds failed since I didn't track the Expected string case for localized Descriptor. sending and update and scheduling the build.

PR #836
