### ISSUE TITLE
NSRegularExpression.NSMatchingOptionsTest fails on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#766]
[ RUN      ] NSRegularExpression.NSMatchingOptionsTest
Foundation/NSRegularExpressionTests.m:285: Failure
Value of: expected
  Actual: 20
Expected: count
Which is: 25
[  FAILED  ] NSRegularExpression.NSMatchingOptionsTest (1 ms)

**Comment by MSFTFox** [comment]
Investigating this, I don't have the failure reproducing. This test passes for me.

One thing that might have caused this is the 1ms run time I see in the posted log. Mine is running at 0ms. I suppose it's possible for NSMatchingReportProgress to trigger more times over longer running matching operations but every test I've done has allowed the number reported to remain constant. I'll look into if I can get it to report a different value and work on a fix that way.
