### ISSUE TITLE
Many files have extraneous semicolons

### ISSUE THREAD

**Issue by lhoward** [Microsoft/WinObjC#77]
See CGColorSpace.mm for example, there are many lines at the end containing extraneous semicolons. These should be removed.

**Comment by keluo-ms** [comment]
This was fixed with https://github.com/Microsoft/WinObjC/commit/1f80ae32d7e2651ab702648f27cfa50eaf850cb8#diff-37737934391fa51165e65fbc9de45eb6

Thanks!
