### ISSUE TITLE
NSURLResponse.canBeArchived, NSHTTPURLResponse.canBeArchived fail on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#780]
[ RUN      ] NSURLResponse.canBeArchived
Foundation/ReferenceFoundation/TestNSURLResponse.mm:330: Failure
Value of: actual
  Actual: <NSURLResponse: 0x7fae98c7dbd0> { URL: test }
Expected: expected
Which is: <NSURLResponse: 0x7fae98c84a20> { URL: test }
[  FAILED  ] NSURLResponse.canBeArchived (1 ms)

[ RUN      ] NSHTTPURLResponse.canBeArchived
Foundation/ReferenceFoundation/TestNSURLResponse.mm:341: Failure
Value of: actual
  Actual: <NSHTTPURLResponse: 0x7fae9b2410a0> { URL: https://www.swift.org } { status code: 200, headers {
    "Content-Type" = "text/HTML; charset=ISO-8859-4";
} }
Expected: expected
Which is: <NSHTTPURLResponse: 0x7fae9b222d60> { URL: https://www.swift.org } { status code: 200, headers {
    "Content-Type" = "text/HTML; charset=ISO-8859-4";
} }
[  FAILED  ] NSHTTPURLResponse.canBeArchived (1 ms)

**Comment by DHowett-MSFT** [comment]
Evidence points to `NSURLResponse` using a pointer comparison only, just like @mnithish found for `NSPointerArray`!
