### ISSUE TITLE
NSHTTPURLResponse suggested filename tests fail on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#781]
[ RUN      ] NSHTTPURLResponse.SuggestedFilename_3
Foundation/ReferenceFoundation/TestNSURLResponse.mm:265: Failure
Value of: response.suggestedFilename
  Actual: ;.ext
Expected: @"_.ext"
Which is: _.ext
[  FAILED  ] NSHTTPURLResponse.SuggestedFilename_3 (0 ms)
[ RUN      ] NSHTTPURLResponse.SuggestedFilename_4
Foundation/ReferenceFoundation/TestNSURLResponse.mm:273: Failure
Value of: response.suggestedFilename
  Actual: wrong.ext
Expected: @"fname.ext"
Which is: fname.ext
[  FAILED  ] NSHTTPURLResponse.SuggestedFilename_4 (0 ms)

**Comment by DHowett-MSFT** [comment]
LOL.
```objc
ASSERT_OBJCEQ(@"_.ext", response.suggestedFilename); // Differs from reference platform
// because ; is an illegal filename character
```

Incidentally, it doesn't _look_ like `;` is an illegal filename character..
