### ISSUE TITLE
Use libobj, libdispatch, CF?

### ISSUE THREAD

**Issue by russbishop** [Microsoft/WinObjC#8]
I'm curious why the team didn't adopt any of the existing code from Apple's open source libraries? Specifically things like `libdispatch`, `libobjc`, and `CoreFoundation` are available and have Windows #ifdefs in them since that's how iTunes & co run on Windows. Then you'd have 100% compatibility at those layers.

**Comment by ckent** [comment]
Especially since libdispatch is leveraged heavily by all iOS frameworks and applications. The WinObjC implementation is completely incorrect- not just incomplete, but entirely wrong conceptually. At least use the open source libdispatch as a reference to understand the purpose of the library.

**Comment by AriX** [comment]
+1

**Comment by filipinascimento** [comment]
They took a very different approach by turning libdispatch and core foundation into something existing over the Foundation, and I'm not sure why. I think I have already seen something like that on GNUStep. Still, this seems so wrong in many ways. Anyone knows how this is done on cocotron (which is also licensed as  MIT)?

+1 for implementing libdispatch over pthreads and pure C (+blocks extension).

**Comment by colincornaby** [comment]
If they did it the reverse (the Apple) way, it would also reduce the amount of code they have to maintain in their Obj-C objects. Building CoreFoundation on Foundation is going to slow down development and make the API less in sync with Apple's work.

I remember when I looked into libDispatch a while ago on Windows it required kernel support, which Windows lacked. Obviously Apple is shipping libDispatch on Windows now, so maybe that's been resolved.

**Comment by filipinascimento** [comment]
LibDispatch can be implemented over pthread or even directly over winthreads (I'm not sure about the complications though). There is at least two open source projects that brings libdispatch to windows  (https://github.com/DrPizza/libdispatch/tree/master/libdispatch and http://opensource.mlba-team.de/xdispatch/docs/current/index.html ), all implemented in pure C and even extending the functionality to work with C++ lambda syntax.

**Comment by s5msft** [comment]
A "proper" libdispatch is high on our list of TODOs.

> WinObjC implementation is completely incorrect- not just incomplete, but entirely wrong conceptually
Yes, this "implementation" was for a very particular and very narrow use case.

**Comment by rajsesh-msft** [comment]
Thanks for all the suggestions: 

We have a new runtime (Gnustep libobjc2) for a while.  
We have the DrPizza fork of libdispatch and are evaluating other options as well to support more recent versions of libdispatch.
We are in the process of using Apple CF.

Even with all of these, we will still not have 100% compatibility.  Ex: file paths are different between iOS and UWPs.  Our goal is to have sufficient compatibility to allow apps to be easily port to UWPs and these changes will drive towards that.

I am closing this issue given that we are making traction on all of those fronts.
