### ISSUE TITLE
-[NSObject methodForSelector:] does not call doesNotRecognizeSelector

### ISSUE THREAD

**Issue by lhoward** [Microsoft/WinObjC#80]
-[NSObject methodForSelector:] should call -[NSObject doesNotRecognizeSelector:] to allow subclasses to override this. The default implementation should be fatal.

**Comment by rajsesh-msft** [comment]
fixed with new runtime.

**Comment by DHowett-MSFT** [comment]
It doesn't look like -[NSObject methodForSelector:] is supposed to call -doesNotRecognizeSelector:. It should, however, return a forwarding IMP!
