### ISSUE TITLE
+[NSMethodSignature signatureWithObjCTypes] ignores calloc return value

### ISSUE THREAD

**Issue by lhoward** [Microsoft/WinObjC#82]
+[NSMethodSignature signatureWithObjCTypes] does not check the return value of calloc()

Whilst EbrCalloc() is #defined to calloc(), it would be cleaner to use one or the other consistently. Also consider whether to use C runtime malloc or LocalAlloc().

**Comment by rajsesh-msft** [comment]
This has been fixed for a while now, closing the issue.
