### ISSUE TITLE
UIKit: Properly draw UISegment, UIDatePicker and other UI elements

### ISSUE THREAD

**Issue by shahmeeresmail** [Microsoft/WinObjC#821]
These and possibly other UI elements are not drawn correctly on WinObjC

On iOS, an app can a specify tintColor which defines the border and text color when unselected and the background color when selected. 

On WinObjC, static textures are used to draw the border and background for selected and unselected states using textured draw calls. Since there are only two textures (one for each state) and they are fixed, the colors are static as well:
- If the element is unselected, the element will always have a gray border and white background
- If the element is selected, the element will have a gray border and blue background. 

Further, when insets are specified, it is drawn using up to 9 textured draws for each segment which makes it quite inefficient. 

It could be drawn with a single vector draw for the border and a single colorFill for the background. This way we could avoid 9 textured draws (27 if drawing a segment with 3 parts) and at the same time more closely match what the developer specified and the output on iOS.

**Comment by rajsesh-msft** [comment]
This has to be reconciled with the xaml backed solution for most UIKit controls.

**Comment by shahmeeresmail** [comment]
Absolutely, ideally we should map as many UIKit items to xaml type controls. However, some are not mapped including UIDatePicker and UISegment which have custom draw calls to display their components. In those cases, we should do our best to match what the app developer is asking for.

**Comment by jaredhms** [comment]
Fixed with https://github.com/Microsoft/WinObjC/pull/822.
