### ISSUE TITLE
CFArrayReplaceValues() etc make assumptions about class layout

### ISSUE THREAD

**Issue by lhoward** [Microsoft/WinObjC#83]
CFArrayReplaceValues(), CFArrayContainsValue(), assume that the array is a NS[Mutable]ArrayConcrete. This is not how the CoreFoundation APIs work; they should work on any subclass of the abstract class in the class cluster (in this case, NSArray or NSMutableArray). Passing a custom NSArray subclass to CFArrayReplaceValues() (for example) will crash.

One must check the concrete class and dispatch to ObjC if it is not a [Core]Foundation concrete type.

**Comment by rajsesh-msft** [comment]
@lhoward, thanks for reporting these and many other issues. This issue has been fixed (fix has been in for a while).  Our CF/Foundation code is now class cluster aware.
