### ISSUE TITLE
vsimporter -- Update manifest for apps using AddressBook framework

### ISSUE THREAD

**Issue by chadimoussi** [Microsoft/WinObjC#830]
Apps that use the AddressBook framework will need to update their app's package manifest to include Contacts Capability (`<Capabilities><uap:Capability Name="contacts"/></Capabilities>`) to ensure that their app has proper permissions. In iOS, the permissions can be requested at run time, but for a Windows app using Contacts, the manifest must have the capability declared beforehand.

It would save developers the trouble of manually updating the manifest with Contacts Capabilities if vsimporter automatically did this if it detects that an app uses the AddressBook framework.

**Comment by rajsesh-msft** [comment]
@aballway since you already did something like this for the group container, you may be able to get this quickly.

**Comment by rajsesh-msft** [comment]
We'll revisit this in the future if needed.
