### ISSUE TITLE
NSHTTPURLResponse does not respect MIME type when generating filenames.

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/WinObjC#832]
Potential fix:

Get the extension from MobileCoreServices,

```
CFStringRef uti = UTTypeCreatePreferredIdentifierForTag(kUTTagClassMIMEType, mimeType, nullptr);
CFStringRef preferredExtension = UTTypeCopyPreferredTagWithClass(uti, kUTTagClassFilenameExtension);
```

and make sure the filename ends with it.

Not sure yet if Foundation can take a dependency on MobileCoreServices.

**Comment by DHowett-MSFT** [comment]
Per the [documentation](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURLResponse_Class/index.html#//apple_ref/occ/instp/NSURLResponse/suggestedFilename),
>  In most cases, this property appends the proper file extension based on the MIME type. Accessing this property always returns a valid filename regardless of whether the resource is saved to disk.

**Comment by rajsesh-msft** [comment]
Our mobilecoreservices implementation is quite limited and has a static map.  Also depends on foundation, so we have a cyclic dependency.

**Comment by DHowett-MSFT** [comment]
@rajsesh-msft It looks like the dependency on Foundation is only for NSString message dispatch, and it's only in logging codepaths. We might be able to get away without linking it, or stripping out the dependency completely.

It uses CoreFoundation everywhere else internally. It's awesome.

**Comment by DHowett-MSFT** [comment]
@mnithish might have some more insights here!

**Comment by mnithish** [comment]
Mobilecoreservices should only depend on CF and we should be able to do that now with the new CF we have. Foundation can then depend on mobilecoreservices
