### ISSUE TITLE
NSCharacterSet Initializers don't throw when passed invalid arguments like nil.

### ISSUE THREAD

**Issue by MSFTFox** [Microsoft/WinObjC#843]
[NSMutableCharacterSet characterSetWithBitmapRepresentation:nil] and [NSMutableCharacterSet characterSetWithContentsOfFile:nil] should throw an Invalid Argument Exception. Reference platform throws this exception so we should as well.

**Comment by rajsesh-msft** [comment]
@MSFTFox we should fix it as part of your OSX compat issues with these tests.

**Comment by cp2024** [comment]
I am so sorry I am new to this programming so I'm trying to get a better understanding of everything if you can find it in your heart please help me to learn and understand my telling me and explaining things thank you
