### ISSUE TITLE
The new Colorspace implementation doesn't quite support RGBA, and that breaks jpg and png rendering

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#847]
Both our JPG and PNG decoders set surface format as RGBA.  This breaks some validation apps (they use cocos2d), where the colors of the PNG and JPG images are off.

**Comment by rajsesh-msft** [comment]
@shahmeeresmail I have a potential fix, but that breaks in other circumstances.  Will submit a PR and tag you, would you be able to take a look?

**Comment by rajsesh-msft** [comment]
Also UIImage is constructed directly to hold the backing instead of a CGImage.  If the CGImageRef is then passed to other CG methods, we will create another backing (inside the backing) and be all kinds of broken.  TBD: #848

**Comment by shahmeeresmail** [comment]
Yes, I can take a look at the PR.

On another note, I have been unable to repro the issue with WOCCATALOG nor with any of the other samples.
