### ISSUE TITLE
NSInvocation ignores allocation return values

### ISSUE THREAD

**Issue by lhoward** [Microsoft/WinObjC#85]
NSInvocation - copyArgument() does not check return value from EbrMalloc(). 

invocationWithMethodSignature does not check return value from [self alloc].

**Comment by lhoward** [comment]
Also, why is pMsgFunc a string and not a boolean if it's not being used to look up a symbol at runtime?

**Comment by rajsesh-msft** [comment]
Should be covered as part of #711
