### ISSUE TITLE
cannot open source file "<path to project>/UIKit.tlh"

### ISSUE THREAD

**Issue by philnach** [Microsoft/WinObjC#861]
When code refers to methods in an interface, but the header doesn't have the methods present you'll receive build errors in the Error List, they don't appear in the build output but look like IntelliSense's errors.  I spent 15-20 minutes trying to figure out what's wrong only to realize that the error was being added because I forgot to declare the methods in the interface.

SDK: 0.1.160728
VS 2015 Update 3

Repo Steps:
1. Create a new empty interface that has a framework import reference i.e.: #import <UIKit/UIKit.h>
2. Write code that refers to non defined methods in interface
3. Build

Result:
1. Error in error list that cannot open source file *.tlh appears (see below)

Expected:
1. No errors about *.tlh not existing, only errors indicating that I need to define the methods on the interface.

![cannotopenfile](https://cloud.githubusercontent.com/assets/19275540/17565019/78b6c03e-5eea-11e6-9ed9-acad8cd0b886.PNG)

**Comment by rajsesh-msft** [comment]
Hi @philnach In order to help, could you please provide the build log by following these steps in our [FAQ](https://github.com/Microsoft/WinObjC/wiki/FAQ#how-do-i-get-my-project-log-file-to-help-determining-the-cause-of-an-issue)?

**Comment by antoine-haas** [comment]
Hey @philnach, those are indeed Intellisense errors, as explained [here in the FAQ](https://github.com/Microsoft/WinObjC/wiki/FAQ#im-getting-errors-on-my-header-files-about-tlh-files-that-cant-be-opened--and---method-modifiers-being-marked-as-expected-declaration-and-unrecognized-token-for-interface-and-property-what-should-i-do).

**Comment by rajsesh-msft** [comment]
closing this issue per @antoine-haas's comment above.
