### ISSUE TITLE
-[NSMutableURLRequest copy] should return a mutable copy

### ISSUE THREAD

**Issue by memontic-ms** [Microsoft/WinObjC#863]
Reference platform returns a mutable copy in contravention to platform standards.

**Comment by DHowett-MSFT** [comment]
It looks like we have tests to make sure that a copy of a mutable version doesn't reflect changes to the original, but we aren't testing whether the copy itself is mutable _or_ immutable.

**Comment by rajsesh-msft** [comment]
So annoying.

**Comment by rajsesh-msft** [comment]
If we had tested for mutability, we would have tested for copy being immutable.  Since there is code out there that relies on this copy being mutable, lets go ahead and make the compat argument.
