### ISSUE TITLE
CFGetTypeID() is brittle

### ISSUE THREAD

**Issue by lhoward** [Microsoft/WinObjC#88]
CFTypeID type should be defined as a typedef to a DWORD.

CFGetTypeID() is brittle; better to check if the object responds to _cfTypeID and return that.

    CFTypeID CFGetTypeID(id cfobj)
    {
        if ([cfobj respondsToSelector:@selector(_cfTypeID)])
            return [cfobj _cfTypeID];
        else
            return 0;
    }

    @implementation NSArray
    - (CFTypeID)_cfTypeID
    {
        return CFArrayGetTypeID();
    }
    @end

**Comment by MaddTheSane** [comment]
On Apple's CoreFoundation framework, `CFTypeID` is defined as a 32-bit unsigned integer on 32-bit architectures, and a 64-bit unsigned integer on 64-bit architectures (even going so far as being an `unsigned long long` on LLP64 architectures, like Windows).

After doing some digging, it seems the function implemented in CFType.mm is commented out, and doesn't match the declaration in CFBase.h. That said, how it is implemented *is* fragile. Depending on how MS decides to do Core Foundation types, passing an `id` for CF types may not be valid.

**Comment by lhoward** [comment]
Good digging. ULONG_PTR might be better then. I forgot that it was commented out, still it should be fixed before uncommenting :-)
