### ISSUE TITLE
[NSURL] URLByAppendingPathComponent fails when trying to append empty string

### ISSUE THREAD

**Issue by memontic-ms** [Microsoft/WinObjC#880]
`CFStringGetCharacterAtIndex` supports out of bound access but `CFStringGetCharacterAtIndex(NSConstantString)` throws and exception.

**Comment by rajsesh-msft** [comment]
Its quite likely that the NSConstantString implementation we have  does not have a trailing null, which probably is the reason this bombs.  We should fix this by short circuiting the function for empty path components (simply return a copy).
