### ISSUE TITLE
Addressbook - working with people

### ISSUE THREAD

**Issue by chadimoussi** [Microsoft/WinObjC#890]
Implement the following APIs:

- [ ] ABAddressBookCopyPeopleWithName
- [ ] ABPersonComparePeopleByName
- [ ] ABPersonCopyArrayOfAllLinkedPeople
- [ ] ABAddressBookRegisterExternalChangeCallback
- [ ] ABAddressBookUnregisterExternalChangeCallback

**Comment by rajsesh-msft** [comment]
postponed for the future.
