### ISSUE TITLE
Addressbook - get format information

### ISSUE THREAD

**Issue by chadimoussi** [Microsoft/WinObjC#891]
Implement the following APIs:

- [ ] ABPersonGetCompositeNameFormat
- [ ] ABPersonGetCompositeNameFormatForRecord
- [ ] ABPersonGetSortOrdering
- [ ] ABAddressBookCopyLocalizedLabel
- [ ] ABPersonCopyLocalizedPropertyName
- [ ] ABPersonGetTypeOfProperty
- [ ] ABPersonCopyCompositeNameDelimiterForRecord

**Comment by rajsesh-msft** [comment]
potentially future work.
