### ISSUE TITLE
NSCharacterSet.ExceptionTests fails on OSX

### ISSUE THREAD

**Issue by ms-jihua** [Microsoft/WinObjC#897]
This was a new test added recently.

[ RUN      ] NSCharacterSet.ExceptionTests
NSCharacterSetTests.m:228: Failure
Failed
[  FAILED  ] NSCharacterSet.ExceptionTests (0 ms)

**Comment by rajsesh-msft** [comment]
@MSFTFox, this looks like bug introduced by 0bc4993f4d52f9fa53c0fb0ea711b4a388dab4f3, please take a look.
