### ISSUE TITLE
Autolayout support

### ISSUE THREAD

**Issue by iragsdale** [Microsoft/WinObjC#9]
Wanted to go ahead and get an issue created for this. Our app is pretty much 100% auto layout based, there's about zero chance we could port any UI code without this support.

**Comment by pedrovieira7** [comment]
On the README they explicitly say that the Autolayout is still under development

**Comment by iragsdale** [comment]
Yeah, I saw that. :) Just wanted to add this here so people can +1 to help them gauge interest.

**Comment by liuxuan30** [comment]
Does Apple make the framework implementations private? Seems MS implemented their own ones. Now we can guess how Apple implement a lot of stuff, like how Apple implement UICollectionView.

**Comment by LeoNatan** [comment]
@liuxuan30 All of UIKit is closed source.

**Comment by ikkerus** [comment]
Unfortunetely you'll need Autolayout also for Universal Apps, right?

**Comment by weemundo** [comment]
+1, Any update on progress? It's super critical for a lot of iOS apps!

**Comment by davelamb** [comment]
It's well under way and will be released shortly.

**Comment by weemundo** [comment]
Great news, looking forward to it :)

**Comment by LeoNatan** [comment]
@davelamb Make sure to take layout margins into account when implementing.

**Comment by davelamb** [comment]
Autolayout should be in the next drop. It's a little rough around the edges, and I couldn't find any exceptionally good examples floating around. For the simple cases it should work as advertised, but some things have been fudged in, like layoutMargins (which required a change to Xib2Nib that I'm not 100% on), layouts relative to margins which we don't really have support for yet, and RTL languages which would need a much more thorough change. I've also added visual layout language support, but it hasn't been thoroughly tested (and doesn't have unit tests) so beware. When it drops, I'll close this issue and expect new ones to be opened for missing features and the inevitable bugs and inconsistencies that pop up. Thanks for your patience!

**Comment by davelamb** [comment]
Changes pushed to github. For missing features, please open a new issue. Thanks!
