### ISSUE TITLE
MFMailComposeViewController

### ISSUE THREAD

**Issue by GitMarJansen** [Microsoft/WinObjC#901]
Our app sends email based on the reference implementation described here: https://developer.apple.com/library/ios/documentation/MessageUI/Reference/MFMailComposeViewController_class/. 
Compiling the project with the bridge causes an error on the first line of Listing 2: MFMailComposeViewController* composeVC = [[MFMailComposeViewController alloc] init];
There error is: no known class method for selector 'alloc'.

I can see that the bridge implements a stub of the MFMailComposeViewController, but I guess it should still be able to at least compile.

**Comment by rajsesh-msft** [comment]
@GitMarJansen yes, it should build.  Could you please provide the build log by following these steps in our [FAQ](https://github.com/Microsoft/WinObjC/wiki/FAQ#how-do-i-get-my-project-log-file-to-help-determining-the-cause-of-an-issue)?

**Comment by GitMarJansen** [comment]
Hi Rajsesh,

I attacht the logfile. (I replace customer/project names with 'customer' and 'project')
[ProjectLog.zip](https://github.com/Microsoft/WinObjC/files/431877/ProjectLog.zip)

Regards,

Hilmar
