### ISSUE TITLE
Bridged class implementation of classForCoder always returns immutable class

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#902]
This can be an issue if an app tries to encode/decode mutable types

**Comment by rajsesh-msft** [comment]
This results in a crash in internal test app, we should add additional tests to cover this.

**Comment by DHowett-MSFT** [comment]
We can fix this for:

* **Dictionary**
* **Set**
* **Index Set**
* **Array**
* **Character Set**
* **Data**

*We cannot fix this for:*
* **Attributed String** - they do not support archival (stubbed)
* **String** - this is somewhat bad. Our NSKeyedArchiver implementation will emit a self-reference, stating that a mutable string's string contents is itself. When NSKeyedArchiver later deserializes this, it gets a prototype string that hasn't been initialized.

**Comment by DHowett-MSFT** [comment]
Well, we cannot TEST the fix for NSAttributedString. We can certainly fix it.
