### ISSUE TITLE
Improve performance of [NSObject valueForKeyPath:]

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#904]
When using `[NSObject valueForKeyPath:]` there seems to be a heavy performance impact. This is very noticeable for example when using an NSSortDescriptor to sort a large array.

When profiling the app it seems a lot of time in `[NSObject valueForKeyPath:]` is spent processing the actual NSString of the key path.

Attached is a screen grab of the relevant profile section.

<img width="1108" alt="screenshot 2016-08-23 13 02 02" src="https://cloud.githubusercontent.com/assets/237035/17891170/134720b6-6932-11e6-89c7-401957031c06.png">

**Comment by DHowett-MSFT** [comment]
This is fixed as of the merge of #1005.
