### ISSUE TITLE
gotcha: tableviewcell specific xibs not supported by vsimporter

### ISSUE THREAD

**Issue by ehren** [Microsoft/WinObjC#905]
I haven't tested this recently, but there is an issue where vsimporter doesn't process the UITableViewCell specific xibs (that can be created with XCode by selecting File -> New -> New File and creating a UITableViewCell subclass with the "create XIB" option checked).

The easy workaround is to just use a standard xib with the "File's Owner" set to your UITableView subclass (this is what I've done in my app).

I don't need a fix for the vsimporter issue but I'm posting this because, if you're using the above workaround (to use a standard 'UIView' style xib), you should be careful to use the "registerNib:" API to enable cell reuse (because your xib no longer defines your "reuse identifier"). This fixed some performance problems with my app (which switched to UIView style nibs, inadvertently disabling cell reuse).

**Comment by ArnOmsft** [comment]
Thanks Ehren for raising this and sharing a workaround. We're not planning to address this issue (which would require to update the Xib2Nib tool) since we're investing in a new Xib2XAML tool, although it won't be ready before several months.
