### ISSUE TITLE
Implement CTFontDrawGlyphs

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#924]

**Comment by ms-jihua** [comment]
The following APIs will probably be related and ought to be implemented:

* [ ] CTFontGetBoundingRectsForGlyphs
* [ ] CTFontGetGlyphWithName

The following API is most likely related but may be more complex:
* [ ] CTFontCreatePathForGlyph
D2D API GetGlyphRunOutline may be a good mapping.

**Comment by rajsesh-msft** [comment]
#922 explicitly covers CTFontCreatePathForGlyph.

**Comment by ms-jihua** [comment]
Oops!

**Comment by rajsesh-msft** [comment]
This is not a blocker as this is not used by any test collateral at this point.

**Comment by DHowett-MSFT** [comment]
This is the cause of the missing button text in #1445.
