### ISSUE TITLE
Clang/C2 Internal Compiler Error

### ISSUE THREAD

**Issue by wjk** [Microsoft/WinObjC#926]
Apologies if this is off-topic, but I know of no better place to ask.

I am trying to compile a build of CoreFoundation ([CF-1153.18](http://opensource.apple.com/source/CF/CF-1153.18/), to be precise) using Clang/C2 as included with Visual Studio "15" Preview 4. It works swimmingly, except for the `CFBasicHash.c` file. When I try to compile this file (on its own or with the rest of the project), it spits out [this error text](https://gist.github.com/wjk/7237f6b63e322f8afc533e116fc18f74) (copy/pasted straight from Visual Studio's Output window).

I am clueless as to what is the cause of this error, considering that it does not give me a line number like it usually does when it emits C1001 for another reason (namely, unimplemented GCC-style atomic intrinsic functions; I have had to remove usage of those throughout my project). [Here is a zipfile](https://github.com/Microsoft/WinObjC/files/438428/clang-bug.zip) containing the original source file, the preprocessed source file, and the Clang/C2 diagnostic run script. Can anyone point me to what the problem might be? Even if it is as simple as a too-large source file, this gives me headway towards solving this bug that I do not have right now.

**Comment by wjk** [comment]
I have narrowed down the cause of the error to the two functions `CFBasicHashGetCountOfValue` and `CFBasicHashesAreEqual`. If either or both are present in the source file, I get a C1001 error as described above. However, if I comment both out through `#if 0`, the file compiles successfully. The source for the functions is included below.

```c
CF_PRIVATE CFIndex CFBasicHashGetCountOfValue(CFConstBasicHashRef ht, uintptr_t stack_value) {
    if (__CFBasicHashSubABZero == stack_value) {
        return 0L;
    }
    if (0L == ht->bits.used_buckets) {
        return 0L;
    }
    if (!(ht->bits.keys_offset)) {
        return __CFBasicHashFindBucket(ht, stack_value).count;
    }
    __block CFIndex total = 0L;
    CFBasicHashApply(ht, BLOCK_DEF((CFBasicHashBucket bkt), {
            if ((stack_value == bkt.weak_value) || __CFBasicHashTestEqualValue(ht, bkt.weak_value, stack_value)) total += bkt.count;
            return (Boolean)true;
        }));
    return total;
}

CF_PRIVATE Boolean CFBasicHashesAreEqual(CFConstBasicHashRef ht1, CFConstBasicHashRef ht2) {
    CFIndex cnt1 = CFBasicHashGetCount(ht1);
    if (cnt1 != CFBasicHashGetCount(ht2)) return false;
    if (0 == cnt1) return true;
    __block Boolean equal = true;
    CFBasicHashApply(ht1, BLOCK_DEF((CFBasicHashBucket bkt1), {
            CFBasicHashBucket bkt2 = __CFBasicHashFindBucket(ht2, bkt1.weak_key);
            if (bkt1.count != bkt2.count) {
                equal = false;
                return (Boolean)false;
            }
            if ((ht1->bits.keys_offset) && (bkt1.weak_value != bkt2.weak_value) && !__CFBasicHashTestEqualValue(ht1, bkt1.weak_value, bkt2.weak_value)) {
                equal = false;
                return (Boolean)false;
            }
            return (Boolean)true;
        }));
    return equal;
}
```

**Comment by wjk** [comment]
Note: the `BLOCK_DEF` macro referenced in the code above is a compatibility shim to keep the Visual Studio editor's C++ parser from emitting spurious syntax errors. I have to do this because the editor is not aware of blocks or other Clang/C2-specific syntax features. It is defined as such:

```c
#if defined(__INTELLISENSE__)
#define BLOCK_DEF(args, ...) NULL
#else
#define BLOCK_DEF(args, ...) ^args __VA_ARGS__
#endif
```

**Comment by wjk** [comment]
I believe I have finally identified the root cause of this bug. Apparently, Clang/C2 does not appreciate the use of an `__block` variable within a block scope, and emits a C1001 error whenever I use one. For example, the following code snippet will elicit the crash:

```c
extern void _doFoo(int count, void (^block)(void));
__block int foo = 0;
_doFoo(44, BLOCK_DEF((void), { int bar = foo + 1; }));
```

However, this code block will _not_ elicit the crash:

```c
extern void _doFoo(int count, void (^block)(void));
int foo = 0;
_doFoo(44, BLOCK_DEF((void), { int bar = foo + 1; }));
```

Unfortunately, the latter code block does not allow me to modify the `foo` variable, which is necessary in the two functions referenced in the above posts. Attempting to obscure the operation through the use of pointers (e.g. `__block int *foo; int bar = *foo + 1`) does no good. Clang/C2 does not correctly handle `__block` variables, with read or write access, under any circumstances.

@PooyaZv You have been handling C1001 errors with different causes in a few other issues. Could you please take a look and either suggest a workaround or pass this on to the appropriate Microsoft team? This is completely blocking me from continuing on with my project. Many thanks!

**Comment by wjk** [comment]
BTW, here is the `clang --version` output for my version of Clang/C2:

```
clang with Microsoft CodeGen version 3.8.0
Provided as - is without support
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\Common7\IDE\VC\ClangC2\bin\x86
```

**Comment by s5msft** [comment]
@wjk it looks like you're using the build of clang that's included with VS

I (quickly) tried block semantics with the version of clang that's specific to Islandwood and they seem to work correctly. This build is located in winobjc/msvc/LLVM-3.6.0/

The version string should read:
C:\Starboard\winobjc\msvc\LLVM-3.6.0\bin>clang.exe --version
clang with Microsoft CodeGen version 3.7.0
Provided as - is without support
C:\Starboard\winobjc\msvc\LLVM-3.6.0\bin\x86\c2.dll version 19.0.23904.1
Target: i686-pc-windows-msvc
Thread model: posix

**Comment by wjk** [comment]
@s5msft That is correct. The main reason I'm not using the Islandwood build of Clang/C2 is because by using the version shipped with Visual Studio, I get out-of-the-box project-system support. This lets me get right to working on my app code instead of fighting with MSBuild.

Also note that I have managed to workaround this issue through the usage of a pointer to a struct, something like this:

```c
struct block_params {
    int value;
}
struct block_params params_struct;
struct block_params params = &params_struct;

_doFoo(44, BLOCK_DEF((void), { params->value += 3; }));
```

Using this technique, I can modify the contents of the `block_params` struct through the pointer, even though the pointer itself is immutable. This does not cause a C1001 error, because `__block` is not used.

**Comment by weswmsft** [comment]
What you're trying to do is unsupported. For many reasons it is required that you use the version of the compiler that is distributed with WinObjC. If there are issues with the version of Clang that is part of this project then please file issues and we'll have a look.
