### ISSUE TITLE
Pre-built WinObjC SDK does not provide openssl headers

### ISSUE THREAD

**Issue by asimonov-msft** [Microsoft/WinObjC#928]
The pre-built SDK ships with the openssl libraries (libeay32.dll and ssleay32.dll), but does not contain the corresponding headers.

**Comment by DHowett-MSFT** [comment]
libssl is not a public interface on iOS. I don't think it should be exposed here.

**Comment by antoine-haas** [comment]
The OpenSSL libraries included with the SDK are for internal use only. To use them in a UWP app, you need to add them to your VS solution as a static or dynamic library, and you can get them from here: https://github.com/Microsoft/openssl.
