### ISSUE TITLE
[NSProgress] fractionCompleted does not fire KVO when it changes

### ISSUE THREAD

**Issue by memontic-ms** [Microsoft/WinObjC#947]
It is missing a dependency on completedUnitCount.

**Comment by DHowett-MSFT** [comment]
Fix:

```objc
+ (NSSet<NSString*>*)keyPathsForValuesAffectingFractionCompleted {
    return [NSSet setWIthObjects:@"completedUnitCount", @"totalUnitCount', nil];
}
```

However, we may want to evaluate all of _NSProgress_'s calculated properties for KVO conformance.

**Comment by DHowett-MSFT** [comment]
The following derived properties are expected to be KVO-compliant with dependencies, but are not:

* fractionCompleted
* indeterminate
* cancelled
* paused
* localizedDescription
* localizedAdditionalDescription
