### ISSUE TITLE
CFXXXGetTypeID() should be defined in appropriate compilation unit

### ISSUE THREAD

**Issue by lhoward** [Microsoft/WinObjC#95]
The CFXXXGetTypeID() functions should be defined in the appropriate compilation units, e.g. CFArrayGetType() should be in CFArray.mm not CFType.mm.

**Comment by s5msft** [comment]
The CFXXXGetTypeID functions in CFType.mm are in an #if 0'd block.

https://github.com/Microsoft/WinObjC/blob/master/Frameworks/CoreFoundation/CFType.mm#L88
