### ISSUE TITLE
AddressBook ModifyContactsTests Crashes Visual Studio Project

### ISSUE THREAD

**Issue by MSFTFox** [Microsoft/WinObjC#955]
The ModifyContactsTests crashes Visual Studio when one of its tools tries to parse the file. The root cause still needs to be identified. Until this is fixed, the file will be disabled.

**Comment by bbowman** [comment]
Seems like the wrong fix. Commenting out tests is rarely the correct approach as it only hides issues and incorrectly gives the impression that everything is passing.

**Comment by rajsesh-msft** [comment]
@bbowman, yes. We got a proper workaround from the VS folks.  On an unrelated note, are you running out of things to do on vacation? :smile:
