### ISSUE TITLE
RTLD_DEFAULT not in dlfcn.h

### ISSUE THREAD

**Issue by saurik** [Microsoft/WinObjC#957]
dlsym is very commonly used (not just by me, I swear ;P) with RTLD_DEFAULT, which has not been implemented.

**Comment by pradipd** [comment]
Note: Even if we implement this, we will not be able to support all of the functionality in RTLD_DEFAULT.  There are no UWA API's to find the shared objects in the executable and it's dependencies.  We would only be able to support searching symbols in shared objects loaded by RTLD_GLOBAL.

**Comment by weswmsft** [comment]
We're not able to implement this at this time.
