### ISSUE TITLE
Target "_ComputeStarboardReferencedProjectRequiresObjectiveC missing when building a project with C++ static lib

### ISSUE THREAD

**Issue by antoine-haas** [Microsoft/WinObjC#973]
Projects don't build anymore when adding a C++ static lib following the [wiki page instructions](https://github.com/Microsoft/WinObjC/wiki/Creating-and-Linking-Against-C---Static-Libraries), with **error MSB4057 The target "_ComputeStarboardReferencedProjectRequiresObjectiveC" does not exist in the project**. This seems to be a regression of the August 23rd release, since it works with the July 28th release (the September 6 release still gives the error).

To repro, just add a C++ static lib to the HelloUI sample following the wiki instructions and try to build the project.

**Comment by DHowett-MSFT** [comment]
As far as I know, Artem fixed this a while ago. We'll have to investigate that fix again.
